`Development`: Remove jenkins client and access Jenkins REST API directly
ls1intum/Artemis pull request #10084
Opened 2024-12-27 10:21 UTC by krusche

also exclude a few now unused dependencies
try out RestClient instead of RestTemplate for Apollon

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [ ] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [ ] I **strictly** followed the principle of **data economy** for all database calls.
- [ ] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.

#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [ ] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [ ] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.

#### Changes affecting Programming Exercises
- [ ] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server configured with **Gitlab** and **Jenkins**.

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exam_mode/) as reference.
4. ...

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked
> Click on the badges to get to the test servers.

[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)](https://artemis-test1.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)](https://artemis-test2.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)](https://artemis-test3.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)](https://artemis-test4.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)](https://artemis-test5.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)](https://artemis-test6.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test9)](https://artemis-test9.artemis.cit.tum.de)

### Review Progress

#### Performance Review

- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2
#### Performance Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2025-01-02 09:57 UTC, b-fein commented on src/main/java/de/tum/cit/aet/artemis/programming/service/jenkins/JenkinsEndpoints.java
> +    CREATE_ADMIN("securityRealm", "createAccountByAdmin");
```suggestion
    CREATE_USER("securityRealm", "createAccountByAdmin");
```
This creates any new user via the admin API rather than creating a new admin user in Jenkins.

2025-01-02 09:57 UTC, b-fein commented on src/main/java/de/tum/cit/aet/artemis/programming/service/jenkins/JenkinsXmlFileUtils.java
> +    // TODO: should we really parse this into a document?
What would be the alternative?

I‘m not sure if parsing into a DTO is possible here, since the XML configuration of build jobs can contain the additional config of any Jenkins-plugin that has folder/job-specific settings. I.e. we do not know the schema in advance.

2025-01-02 09:57 UTC, b-fein commented on src/main/java/de/tum/cit/aet/artemis/programming/service/jenkins/jobs/JenkinsJobService.java
> +        // NOTE: this API call is unnecessary and only improves logging, we could remove it
:+1:

The `log.warn` should be moved into the `catch (NotFound)` then.

2025-01-05 22:34 UTC, HawKhiem reviewed
I tested on TS3. I encountered an odd error when trying to submit code through the online editor for programming exercises (as could be seen in the following video). 
https://github.com/user-attachments/assets/5d4b974a-6769-4a3f-9bfb-5ccb3b3d47c5

The submission for programming exercises in an exam works fine
![Screenshot 2025-01-05 233038](https://github.com/user-attachments/assets/85225bd3-ab12-4518-b281-303ac1bd72e9)

2025-01-06 13:12 UTC, vinceclifford submitted a review, later dismissed
Tested on TS5, works as expected.

2025-01-06 15:04 UTC, ole-ve requested changes
code looks good, see my inline comments.
currently, some seemingly related server tests fail

2025-01-06 15:04 UTC, ole-ve commented on src/main/java/de/tum/cit/aet/artemis/core/config/Constants.java
> +     * The name of the Spring profile used to process build jobs in a local CI setup.
I think the comment is wrong, should refer to Jenkins

2025-01-07 08:47 UTC, ole-ve commented on src/test/java/de/tum/cit/aet/artemis/core/authentication/UserJenkinsGitlabIntegrationTest.java
> +    // some race condition on the mocked API due to parallel execution?
seems reasonable. looking at the server error log, we can see:
```code
Handler dispatch failed: java.lang.AssertionError: No further requests expected: HTTP GET https://continuous-integration.fake.fake/job/SHORT624CEF590D2AD04E000A87309695326FAED9TSTEXC/api/json\n4 request(s) executed:\nGET https://continuous-integration.fake.fake/user/oetkuv7iaumejhw1haxz/api/json
```
This is interesting as the test calls only a DELETE-endpoint, no GET-endpoint. Sounds like a mock-related issue.

Similar for below test (testNotifyPush_studentCommitUpdatesSubmissionCount):
```code
Handler dispatch failed: java.lang.AssertionError: No further requests expected: HTTP POST https://continuous-integration.fake.fake/job/SHORT9B70D226067CA04563091B20826B545ABFABTSTEXC/job/SHORT9B70D226067CA04563091B20826B545ABFABTSTEXC-PROGRAMMINGSUBMISSIONSTUDENT1/build\n0 request(s) executed.
```

My guess would be that it's related to `JenkinsRequestMockProvider#enableMockingOfRequests()` or `reset()` - both are called after a lot of tests and might interfere.

2025-01-09 08:34 UTC, b-fein commented on src/test/java/de/tum/cit/aet/artemis/programming/util/ProgrammingExerciseTestService.java
> +        assertThat(programmingExerciseStudentParticipationRepository.findByIdElseThrow(participation8a.getId()).getBuildPlanId()).isNull();
I think the previously mocked behaviour was wrong. It is a successful result (100%) from 6 days ago for an exercise that finished 4 days ago. At that point the build plan clean-up should have happened (i.e. expecting `null`).

2025-01-10 14:03 UTC, krusche commented on src/test/java/de/tum/cit/aet/artemis/core/authentication/UserJenkinsGitlabIntegrationTest.java
> +    // some race condition on the mocked API due to parallel execution?
I don't think this is the case. We used this approach before as well and it worked without issues.

2025-01-10 16:32 UTC, chrisknedl submitted a review, later dismissed
Tested on my local Jenkins Setup. Creating an exercise and participating, build plan edits and resets and deleting the exercise still work as before. Didn't test in exam mode, though.

2025-01-17 12:17 UTC, b-fein approved these changes

2025-01-17 12:26 UTC, HawKhiem approved these changes
Reapprove

2025-01-17 13:23 UTC, merged

2025-01-17 14:37 UTC, vinceclifford reviewed
Re-approval