Feature/export cluster hierarchy
ls1intum/Artemis pull request #1934
Opened 2020-07-19 16:42 UTC by CanArisan

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Server: I added multiple integration tests (Spring) related to the features
- [ ] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [ ] Server: I implemented the changes with a good performance and prevented too many database calls
- [ ] Server: I documented the Java code using JavaDoc style.
- [ ] Client: I added multiple integration tests (Jest) related to the features
- [ ] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [ ] Client: I documented the TypeScript code using JSDoc style.
- [ ] Client: I added multiple screenshots/screencasts of my UI changes
- [ ] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

To offer automatic feedback to text blocks which were:
- Not assigned to any cluster in the initial clustering
- Was assigned to a cluster, but it does not have an existing feedback yet

[https://github.com/ls1intum/Artemis/issues/1782](url)

### Description

- Extended the response from TextSimilarityClusteringService to include the clusterTree and distanceMatrix of blocks
- Added corresponding entities and repositories
- Modified AutomaticTextFeedbackService

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Screenshots

2020-07-21 07:08 UTC, krusche commented
I would like to discuss the relevant database changes in https://github.com/ls1intum/Artemis/issues/1782 before we review and test this PR. Due to the current extremely high workload, I can only offer you a meeting on July 28 or afterwards.

Please make sure that all information in https://github.com/ls1intum/Artemis/issues/1782 is structured in an easy to understand way in the main post (at the top) using headlines and bullet points.

2020-08-05 16:27 UTC, jpbernius commented on src/main/java/de/tum/in/www1/artemis/domain/ClusteringResult.java
> +import javax.persistence.*;
Codacy found an issue: [Avoid unused imports such as 'javax.persistence'](https://app.codacy.com/gh/ls1intum/Artemis/pullRequest?prid=5968857)

2020-08-05 16:27 UTC, jpbernius commented on src/test/java/de/tum/in/www1/artemis/service/connectors/TextSimilarityClusteringServiceTest.java
> +import java.util.ArrayList;
Codacy found an issue: [Avoid unused imports such as 'java.util.ArrayList'](https://app.codacy.com/gh/ls1intum/Artemis/pullRequest?prid=5968857)

2020-08-05 16:27 UTC, jpbernius commented on src/main/java/de/tum/in/www1/artemis/repository/TreeNodeRepository.java
> +import static org.springframework.data.jpa.repository.EntityGraph.EntityGraphType.LOAD;
Codacy found an issue: [Avoid unused imports such as 'org.springframework.data.jpa.repository.EntityGraph.EntityGraphType.LOAD'](https://app.codacy.com/gh/ls1intum/Artemis/pullRequest?prid=5968857)

2020-08-05 16:27 UTC, jpbernius commented on src/main/java/de/tum/in/www1/artemis/service/AutomaticTextFeedbackService.java
> +                if(x.isBlockNode()) {
Codacy found an issue: [Avoid empty if statements](https://app.codacy.com/gh/ls1intum/Artemis/pullRequest?prid=5968857)

2020-08-05 16:27 UTC, jpbernius commented on src/main/java/de/tum/in/www1/artemis/domain/TreeNode.java
> +    public double getLambda_val() {
Codacy found an issue: [The instance method name 'getLambda_val' doesn't match '[a-z][a-zA-Z0-9]*'](https://app.codacy.com/gh/ls1intum/Artemis/pullRequest?prid=5968857)

2020-08-05 16:27 UTC, jpbernius commented on src/main/java/de/tum/in/www1/artemis/domain/TextExercise.java
> +    private List<PairwiseDistance> pairwiseDistances;
Codacy found an issue: [Avoid unused private fields such as 'pairwiseDistances'.](https://app.codacy.com/gh/ls1intum/Artemis/pullRequest?prid=5968857)

2020-08-05 16:27 UTC, jpbernius commented on src/main/java/de/tum/in/www1/artemis/domain/ClusteringResult.java
> +import java.util.List;
Codacy found an issue: [Avoid unused imports such as 'java.util.List'](https://app.codacy.com/gh/ls1intum/Artemis/pullRequest?prid=5968857)

2020-08-05 16:27 UTC, jpbernius commented on src/main/java/de/tum/in/www1/artemis/domain/PairwiseDistance.java
> +import javax.persistence.*;
Codacy found an issue: [Avoid unused imports such as 'javax.persistence'](https://app.codacy.com/gh/ls1intum/Artemis/pullRequest?prid=5968857)

2020-08-05 16:27 UTC, jpbernius commented on src/main/java/de/tum/in/www1/artemis/repository/TextBlockRepository.java
> +import org.springframework.data.repository.query.Param;
Codacy found an issue: [Avoid unused imports such as 'org.springframework.data.repository.query.Param'](https://app.codacy.com/gh/ls1intum/Artemis/pullRequest?prid=5968857)

2020-08-05 16:27 UTC, jpbernius commented on src/main/java/de/tum/in/www1/artemis/repository/PairwiseDistanceRepository.java
> +import org.springframework.data.jpa.repository.EntityGraph;
Codacy found an issue: [Avoid unused imports such as 'org.springframework.data.jpa.repository.EntityGraph'](https://app.codacy.com/gh/ls1intum/Artemis/pullRequest?prid=5968857)

2020-08-05 16:27 UTC, jpbernius commented on src/main/java/de/tum/in/www1/artemis/domain/ClusteringResult.java
> +import com.fasterxml.jackson.annotation.JsonIgnore;
Codacy found an issue: [Avoid unused imports such as 'com.fasterxml.jackson.annotation.JsonIgnore'](https://app.codacy.com/gh/ls1intum/Artemis/pullRequest?prid=5968857)

2020-08-05 16:27 UTC, jpbernius commented on src/main/java/de/tum/in/www1/artemis/domain/TreeNode.java
> +    public void setChild_size(long child_size) { this.child_size = child_size; }
Codacy found an issue: [The instance method name 'setChild_size' doesn't match '[a-z][a-zA-Z0-9]*'](https://app.codacy.com/gh/ls1intum/Artemis/pullRequest?prid=5968857)

2020-08-05 16:27 UTC, jpbernius commented on src/main/java/de/tum/in/www1/artemis/domain/ClusteringResult.java
> +import java.io.Serializable;
Codacy found an issue: [Avoid unused imports such as 'java.io.Serializable'](https://app.codacy.com/gh/ls1intum/Artemis/pullRequest?prid=5968857)

2020-08-05 16:27 UTC, jpbernius commented on src/main/java/de/tum/in/www1/artemis/domain/TreeNode.java
> +import javax.persistence.*;
Codacy found an issue: [Avoid unused imports such as 'javax.persistence'](https://app.codacy.com/gh/ls1intum/Artemis/pullRequest?prid=5968857)

2020-08-05 16:27 UTC, jpbernius commented on src/main/java/de/tum/in/www1/artemis/service/AutomaticTextFeedbackService.java
> +    private final PairwiseDistanceRepository pairwiseDistanceRepository;
Codacy found an issue: [Avoid unused private fields such as 'pairwiseDistanceRepository'.](https://app.codacy.com/gh/ls1intum/Artemis/pullRequest?prid=5968857)

2020-08-05 16:27 UTC, jpbernius commented on src/main/java/de/tum/in/www1/artemis/domain/PairwiseDistance.java
> +    public long getBlock_i() { return this.block_i; }
Codacy found an issue: [The instance method name 'getBlock_i' doesn't match '[a-z][a-zA-Z0-9]*'](https://app.codacy.com/gh/ls1intum/Artemis/pullRequest?prid=5968857)

2020-08-05 16:27 UTC, jpbernius commented on src/main/java/de/tum/in/www1/artemis/repository/TextBlockRepository.java
> +    List<TextBlock> findAllBySubmission_Participation_Exercise_IdAndTreeIdNotNull(Long exerciseId);
Codacy found an issue: [The instance method name 'findAllBySubmission_Participation_Exercise_IdAndTreeIdNotNull' doesn't match '[a-z][a-zA-Z0-9]*'](https://app.codacy.com/gh/ls1intum/Artemis/pullRequest?prid=5968857)

2020-08-05 16:27 UTC, jpbernius commented on src/main/java/de/tum/in/www1/artemis/domain/PairwiseDistance.java
> +import org.hibernate.annotations.NaturalId;
Codacy found an issue: [Avoid unused imports such as 'org.hibernate.annotations.NaturalId'](https://app.codacy.com/gh/ls1intum/Artemis/pullRequest?prid=5968857)

2020-08-05 16:27 UTC, jpbernius commented on src/test/java/de/tum/in/www1/artemis/service/connectors/TextSimilarityClusteringServiceTest.java
> +        List<Long> groupByChild = clusterTree.stream().map(treeNode -> treeNode.getChild()).distinct().collect(Collectors.toList());
Codacy found an issue: [Unnecessary use of fully qualified name 'Collectors.toList' due to existing static import 'java.util.stream.Collectors.toList'](https://app.codacy.com/gh/ls1intum/Artemis/pullRequest?prid=5968857)

2020-08-05 16:27 UTC, jpbernius commented on src/main/java/de/tum/in/www1/artemis/domain/TreeNode.java
> +    public void setLambda_val(double lambda_val) { this.lambda_val = lambda_val; }
Codacy found an issue: [The instance method name 'setLambda_val' doesn't match '[a-z][a-zA-Z0-9]*'](https://app.codacy.com/gh/ls1intum/Artemis/pullRequest?prid=5968857)

2020-08-05 16:27 UTC, jpbernius commented on src/main/java/de/tum/in/www1/artemis/domain/TreeNode.java
> +    public long getChild_size() { return child_size; }
Codacy found an issue: [The instance method name 'getChild_size' doesn't match '[a-z][a-zA-Z0-9]*'](https://app.codacy.com/gh/ls1intum/Artemis/pullRequest?prid=5968857)

2020-08-05 16:27 UTC, jpbernius commented on src/main/java/de/tum/in/www1/artemis/domain/PairwiseDistance.java
> +    public void setBlock_j(long block_j) { this.block_j = block_j; }
Codacy found an issue: [The instance method name 'setBlock_j' doesn't match '[a-z][a-zA-Z0-9]*'](https://app.codacy.com/gh/ls1intum/Artemis/pullRequest?prid=5968857)

2020-08-05 16:27 UTC, jpbernius commented on src/main/java/de/tum/in/www1/artemis/domain/PairwiseDistance.java
> +    public void setBlock_i(long block_i) { this.block_i = block_i; }
Codacy found an issue: [The instance method name 'setBlock_i' doesn't match '[a-z][a-zA-Z0-9]*'](https://app.codacy.com/gh/ls1intum/Artemis/pullRequest?prid=5968857)

2020-08-05 16:27 UTC, jpbernius commented on src/main/java/de/tum/in/www1/artemis/service/AutomaticTextFeedbackService.java
> +    private final PairwiseDistanceRepository pairwiseDistanceRepository;
Codacy found an issue: [Perhaps 'pairwiseDistanceRepository' could be replaced by a local variable.](https://app.codacy.com/gh/ls1intum/Artemis/pullRequest?prid=5968857)

2020-08-05 16:27 UTC, jpbernius commented on src/test/java/de/tum/in/www1/artemis/service/connectors/TextSimilarityClusteringServiceTest.java
> +        List<Long> groupByParent = clusterTree.stream().map(treeNode -> treeNode.getParent()).distinct().collect(Collectors.toList());
Codacy found an issue: [Unnecessary use of fully qualified name 'Collectors.toList' due to existing static import 'java.util.stream.Collectors.toList'](https://app.codacy.com/gh/ls1intum/Artemis/pullRequest?prid=5968857)

2020-08-12 12:18 UTC, jpbernius commented
@actions Tests are failing due to dependency to ls1intum/Athene#26.

2020-08-25 08:10 UTC, krusche requested changes
Please make sure to mock the communication to Athene in the server integration tests.
Please post the test coverage for the changed files in the PR description.
Please make sure to cover all cases for the deletion of related entities (course, exam, exercise, exercise group, participation, submission, result) so that we do not have any problems in those cases

2020-09-24 07:55 UTC, krusche commented
> Please make sure to mock the communication to Athene in the server integration tests.
> Please post the test coverage for the changed files in the PR description.
> Please make sure to cover all cases for the deletion of related entities (course, exam, exercise, exercise group, participation, submission, result) so that we do not have any problems in those cases

@CanArisan Please let us know, if you addressed those change requests. In particular, whether you have been able to mock all communication with Athene in the tests and whether the deletion is tested thoroughly

2020-09-24 10:04 UTC, CanArisan commented
> > Please make sure to mock the communication to Athene in the server integration tests.
> > Please post the test coverage for the changed files in the PR description.
> > Please make sure to cover all cases for the deletion of related entities (course, exam, exercise, exercise group, participation, submission, result) so that we do not have any problems in those cases
> 
> @CanArisan Please let us know, if you addressed those change requests. In particular, whether you have been able to mock all communication with Athene in the tests and whether the deletion is tested thoroughly

I test the deletion for the relevant cases for the new entities that I created, which are course, exam, exercise group and exercise.
I also mocked the communication to Athene in the new test that I created (TextClusteringServiceTest). There is however a test already in develop (TextSimilarityClusteringServiceTest) which communicates with Athene. I did not mock it there because it only tests the response from Athene and does not make sense when mocked. If we want absolutely no communication to Athene, I would remove that test entirely.

2020-09-29 17:30 UTC, krusche commented
> > > Please make sure to mock the communication to Athene in the server integration tests.
> > > Please post the test coverage for the changed files in the PR description.
> > > Please make sure to cover all cases for the deletion of related entities (course, exam, exercise, exercise group, participation, submission, result) so that we do not have any problems in those cases
> > 
> > 
> > @CanArisan Please let us know, if you addressed those change requests. In particular, whether you have been able to mock all communication with Athene in the tests and whether the deletion is tested thoroughly
> 
> I test the deletion for the relevant cases for the new entities that I created, which are course, exam, exercise group and exercise.
> I also mocked the communication to Athene in the new test that I created (TextClusteringServiceTest). There is however a test already in develop (TextSimilarityClusteringServiceTest) which communicates with Athene. I did not mock it there because it only tests the response from Athene and does not make sense when mocked. If we want absolutely no communication to Athene, I would remove that test entirely.

1. Can you point to the place where you test the deletion?
2. Why would it not make sense? You would still invoke the code that is responsible for sending a request and handling the response. We can still make sure that there are no exceptions in the Artemis side. Please also mock this one.

2020-09-30 18:10 UTC, CanArisan commented
> > > > Please make sure to mock the communication to Athene in the server integration tests.
> > > > Please post the test coverage for the changed files in the PR description.
> > > > Please make sure to cover all cases for the deletion of related entities (course, exam, exercise, exercise group, participation, submission, result) so that we do not have any problems in those cases
> > > 
> > > 
> > > @CanArisan Please let us know, if you addressed those change requests. In particular, whether you have been able to mock all communication with Athene in the tests and whether the deletion is tested thoroughly
> > 
> > 
> > I test the deletion for the relevant cases for the new entities that I created, which are course, exam, exercise group and exercise.
> > I also mocked the communication to Athene in the new test that I created (TextClusteringServiceTest). There is however a test already in develop (TextSimilarityClusteringServiceTest) which communicates with Athene. I did not mock it there because it only tests the response from Athene and does not make sense when mocked. If we want absolutely no communication to Athene, I would remove that test entirely.
> 
> 1. Can you point to the place where you test the deletion?
> 2. Why would it not make sense? You would still invoke the code that is responsible for sending a request and handling the response. We can still make sure that there are no exceptions in the Artemis side. Please also mock this one.

1. The following test cases in src/test/java/de/tum/in/www1/artemis/service/TextClusteringServiceTest.java are testing the deletion:
    - line 272: testExerciseRemoval
    - line 287: testCourseRemoval
    - line 307: testExamRemoval
    - line 327: testExerciseGroupRemoval
2. I also mocked the communication to Athene in the existing test class.

2020-10-21 19:34 UTC, krusche commented
@CanArisan what is the status of this PR? It is open since 3 months now and it is getting outdated.
Should we close it, or can you finish the PR in the next days? This would be really important, because our policies normally prohibit PRs that are open more than 2 weeks.

2020-10-22 11:53 UTC, bigultekin approved these changes
I tested locally and observed that all the tables mentioned in step 6 are filled. Also, automatic feedback suggestion and feedback conflicts are still working too. Good job! 👍

2020-10-22 14:05 UTC, krusche commented on src/main/java/de/tum/in/www1/artemis/domain/text/TextPairwiseDistance.java
> +@Table(name = "text_pairwise_distance")
the following annotations are missing

@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
@JsonInclude(JsonInclude.Include.NON_EMPTY)

2020-10-22 14:11 UTC, krusche commented on src/main/java/de/tum/in/www1/artemis/domain/text/TextPairwiseDistance.java
> +    public TextPairwiseDistance exercise(TextExercise exercise) {
please delete this method in case it is unused

2020-10-23 10:15 UTC, closed without merging