[Feature] Improve automated grading page (former manage test-cases)
ls1intum/Artemis pull request #2037
Opened 2020-08-18 00:46 UTC by schultek

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Client: I added multiple integration tests (Jest) related to the features
- [ ] Client: I documented the TypeScript code using JSDoc style.
- [ ] Client: I added multiple screenshots/screencasts of my UI changes
- [ ] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

Prepare grading page to incorporate static code analysis configuration.

### Description

1. Rename test-case page to configure-grading page

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration -> Programming Exercise
3. Navigate to Configure Grading

### Screenshots

2020-09-01 15:15 UTC, fde312 reviewed
When clicking into one of the edit fields, the state changes directly to 'unsaved changes' even though I did not change anything at all. The state should just switch when the value has changed.

![image](https://user-images.githubusercontent.com/41108487/91869852-a662a480-ec76-11ea-9002-fa08652717bd.png)

2020-09-01 15:37 UTC, kloessst reviewed
Looks nice. Could you hide the quality tab when static code analysis is not enabled or the programming language is not supported at the moment?

2020-09-01 15:38 UTC, fde312 commented on src/main/webapp/app/exercises/programming/manage/grading/programming-exercise-configure-grading.component.html
> +    <ng-template #loadingContainer>
You can remove this, as we have the overall loading icon in the nav bar :)

2020-09-23 16:27 UTC, kloessst approved these changes
Re-approve

2020-09-25 09:08 UTC, fde312 approved these changes
re-approve

2020-09-26 09:51 UTC, balazs-czopf approved these changes
Tested it on the testserver, worked really well for me. Good job! 🚀

2020-09-29 05:45 UTC, filip-gregurevic approved these changes

2020-09-29 11:36 UTC, krusche commented on src/main/webapp/app/exercises/programming/manage/grading/codeAnalysisMapping.ts
> +export const Mapping: StaticCodeAnalysisCategory[] = [
please mark this as a dummy object that will be replaced later by the actual default categories of the server

2020-09-29 11:36 UTC, krusche commented on src/main/webapp/app/exercises/programming/manage/grading/codeAnalysisMapping.ts
> +export const Mapping: StaticCodeAnalysisCategory[] = [
using a TODO :-)

2020-09-29 11:39 UTC, stefanwaldhauser requested changes

2020-09-29 11:39 UTC, stefanwaldhauser commented on src/main/webapp/app/entities/static-code-analysis-category.model.ts
> +    checks: { tool: string; check: string }[];
I would create an interface for the type instead of defining here anonymously.

2020-09-29 11:40 UTC, krusche approved these changes

2020-09-29 11:41 UTC, krusche approved these changes

2020-09-29 11:41 UTC, merged