[Enhancement] Result view
ls1intum/Artemis pull request #2177
Opened 2020-10-08 00:20 UTC by schultek

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [ ] Client: I documented the TypeScript code using JSDoc style.
- [ ] Client: I added multiple screenshots/screencasts of my UI changes
- [ ] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

Improve the visual presentation of feedbacks.

### Description

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Test Coverage

### Screenshots

![result1](https://user-images.githubusercontent.com/13920539/95401177-da338880-090c-11eb-89dd-03bba00351c4.PNG)
![result2](https://user-images.githubusercontent.com/13920539/95401178-db64b580-090c-11eb-8f8c-1cef3eb7b983.PNG)

2020-10-26 13:18 UTC, krusche commented
The screenshots look quite nice already! Do you also support exercises with bonus? (i.e. more than 100%)

2020-10-26 13:19 UTC, krusche commented
make sure to add some tests before setting the PR to ready for review and to include the test coverage statistics

2020-10-26 18:50 UTC, tiffca submitted a review, later dismissed
The result bar for the programming exercises displayed as described. 

Tested on test server 1 programming with/without SCA, auto, and manual, and all scenarios functioned as described. 

The points seem to add up/display as expected when SCA/bonus grading is enabled, manual feedback overrides as expected. 

I was able to view the preliminary indicator if build plan date is set. 
![image](https://user-images.githubusercontent.com/63906424/97214836-f2881c00-17c3-11eb-9aa8-52bbeb888c87.png)

tutor feedback is displayed to instructors only. scenarios make sense, for example in a scenario with auto, SCA, and manual grading. 
![image](https://user-images.githubusercontent.com/63906424/97214864-00d63800-17c4-11eb-8a6d-31d65ee01305.png)

the deductions display and make sense
![image](https://user-images.githubusercontent.com/63906424/97215019-39761180-17c4-11eb-88b3-b93f37de527b.png)

with bonus
![image](https://user-images.githubusercontent.com/63906424/97215758-29aafd00-17c5-11eb-967c-6cea892cdaf3.png)


everything worked as described. 

The feedback for text, model, and file upload seem unchanged (no result bar is shown), I think this was the reason for testing these? for example, no result bar shown to instructor or students. 
![image](https://user-images.githubusercontent.com/63906424/97214782-dc7a5b80-17c3-11eb-9473-3c5e8d0f9223.png)

2020-10-27 20:29 UTC, fde312 requested changes
I really like how you have implemented it 👍 
Just a small remark, could you change the color of the manual result with score of 0 to yellow, to keep it consistent? You can then use the grey for the SCA :)

2020-10-27 20:51 UTC, kloessst approved these changes
Looks really nice. Suggestions by @fde312 have been integrated. Code looks good too. Well done 💯

2020-10-27 20:58 UTC, MaisiKoleni approved these changes
Looks excellent and works really well. Displaying the positive test cases is a great addition.

We should have a look how more monospaced font dependent error messages look thought. But I don't have a solution for that right now without making all monospaced.

2020-10-27 20:59 UTC, fde312 commented on src/main/webapp/app/exercises/shared/result/result-detail.component.ts
> +            return 'alert-warning';
Now we have both the SCA and the manual feedback with score 0 in yellow. I think this is okay for now. If we encounter some misunderstandings from the students side, we can adjust it in a follow up  :)

2020-10-27 21:00 UTC, fde312 approved these changes
Code looks good as well. A really cool enhancement! 👍 🥇

2020-10-27 21:42 UTC, merged