Use JUnit 5 for the JVM Tests
ls1intum/Artemis pull request #2281
Opened 2020-10-27 08:19 UTC by MaisiKoleni

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context
Switch to JUnit 5 and newer Maven Surefire version to support https://github.com/ls1intum/artemis-java-test-sandbox and also resolve #2273.

The name of the test cases in Artemis will **not** change.

### Description
- Use `artemis-java-test-sandbox` already as provider for JUnit 5, AssertJ and more. Remove JUnit 4.
- Use Maven Surefire version `3.0.0-M5`
- Adjust the Java test template to JUnit 5 Jupiter using dynamic tests.

#### TODO:
- [ ] Change version and check some JavaDoc
- [ ] Also update Kotlin (and #2278 is also affected)

### Steps for Testing

TODO

### Test Coverage

_Unchanged._

2020-10-27 16:17 UTC, krusche commented on src/main/resources/templates/kotlin/test/testutils/ClassNameScanner.java
> +        if(fileName.contains(".java")) {
re-add kt

2020-10-27 16:17 UTC, krusche commented on src/main/resources/templates/kotlin/test/testutils/ClassNameScanner.java
> +            String packageName = node.getPath().substring(0, node.getPath().indexOf(".java"));
re-add kt

2020-10-27 16:18 UTC, krusche commented on src/main/resources/templates/kotlin/test/testFiles/structural/ConstructorTest.java
> +    @TestFactory
can we add some timeout?

2020-10-27 22:42 UTC, fde312 requested changes
Tested it in ts2 and somehow all tests are successful even though I only solved bubble sort:
<img width="1598" alt="image" src="https://user-images.githubusercontent.com/41108487/97369425-3571ee80-18ad-11eb-8dfb-227337fa64ee.png">

2020-10-27 23:13 UTC, schultek reviewed
This works for the bamboo setup on test server 1, but i had the same errors as @fde312 for the jenkins setup on ts2.

2020-10-29 21:04 UTC, sleiss approved these changes
LGTM

2020-10-29 21:10 UTC, schultek approved these changes
This works fine now.

2020-10-29 21:36 UTC, kloessst approved these changes
Tested multiple exercises with various configs. Works fine. Well done!

2020-10-29 21:43 UTC, krusche approved these changes
Thanks! Code looks good! Great work 👍🏻🚀

2020-10-29 21:44 UTC, merged