[Feature] Support for PMD Copy/Paste Detection
ls1intum/Artemis pull request #2292
Opened 2020-10-29 00:28 UTC by kloessst

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Server: I documented the Java code using JavaDoc style.

### Motivation and Context

Clones are a threat to the maintainability of software systems. Pieces of code which are used often should be encapsulated and made available to other components by providing well documented interfaces (Don't repeat yourself, Single responsibility principle). With this PR, code clones can be automatically detected and punished by configuring the grading for programming exercises.

### Description

- Add `PMD CPD` tool, which automatically extends the build plan if SCA is enabled
- Add Copy Paste detection category
- Add default configuration for PMD CPD. Only duplication with a minimum size of 70 tokens are reported.

### Steps for Testing

**Test on TS1 and TS2**
1. Create a programming exercise with SCA enabled
2. Participate
3. Submit code with contains duplications (must be at least 70 tokens long, this can be changed in the pom, the BubbleSort algorithm should suffice)
--> Check that the code duplication is detected

### Test Coverage

Nothing changed

### Screenshots

![image](https://user-images.githubusercontent.com/16407766/97510877-fbc0e680-1985-11eb-862f-49c2ab9887a4.png)

2020-10-29 00:48 UTC, fde312 reviewed
I added the same method for all 3 classes and got the following issues:

<img width="933" alt="image" src="https://user-images.githubusercontent.com/41108487/97511977-a20deb80-1988-11eb-88a0-c71cd9feca10.png">

I would expect just to get the 3 issues with the 3 files and not additionally 2 issues with `BubbleSort` and `Client. Is this intended @kloessst ?

2020-10-29 20:12 UTC, kloessst commented
> I added the same method for all 3 classes and got the following issues:
> 
> <img alt="image" width="933" src="https://user-images.githubusercontent.com/41108487/97511977-a20deb80-1988-11eb-88a0-c71cd9feca10.png">
> 
> I would expect just to get the 3 issues with the 3 files and not additionally 2 issues with `BubbleSort` and `Client. Is this intended @kloessst ?

I guess it finds one more duplicate token/line as in the other duplication and creates another issue for this. As the copy paste detection is a blackbox for us, we can't change this. 
The reporting of multiple feedback elements for one unique duplication is wanted and approved by @krusche. This allows us to highlight the locations in the code editor and to punish multiple clones of the same code harder.

I will set this PR to the draft state, until it can be tested on both TS1 and TS2.

2020-11-01 14:08 UTC, MaisiKoleni submitted a review, later dismissed
Code looks good to me. Tested on TS 2, works fine.

2020-11-03 23:49 UTC, fde312 requested changes

2020-11-03 23:49 UTC, fde312 commented on src/main/resources/templates/java/test/projectTemplate/pom.xml
> +                <configuration>
I think we now have two `pom.xml` files right? One for eclipse and one for maven. This change should also be done for the other right?

2020-11-04 01:54 UTC, fde312 approved these changes
CPD works for me: 
<img width="1663" alt="image" src="https://user-images.githubusercontent.com/41108487/98060073-04636200-1e49-11eb-9013-86f3ac6f8dcb.png">

2020-11-04 16:50 UTC, MaisiKoleni commented
Is there any reason for the changes in c7b25bc?

2020-11-05 15:27 UTC, kloessst commented
> 
> 
> Is there any reason for the changes in [c7b25bc](https://github.com/ls1intum/Artemis/commit/c7b25bc50c1f4cce63be52db8cb5740d34732b40)?

I did some testing, playing around with the options. If you activate `ignoreIdentifiers`, a lot of tokens e.g. variable names, method names, won't be counted any longer. In turn, the `minimumTokens` must be reduced significantly, otherwise no duplications will be found. Lowering the `minimumTokens` too much, increases the risk of false positives.

I tested this with the MergeSort implementation of the template and using `ignoreIdentifiers` with 70 `minimumTokens`, copying the whole MergeSort implementation won't be detected. Reducing `minimumTokens` to 30 detects a if block duplication within the implementation which is a false positive. For 50 `minimumTokens` nothing is detected.

I try to find a good default configuration but in the end, each instructor is able to play around with these settings as well. Let me know if you found a better solution. Then we can use this as the default.

2020-11-05 21:53 UTC, MaisiKoleni approved these changes
The CPD still works fine, also tested with Maven Java projects. It is a bit sad to lose the "ignore identifiers" option which makes it a bit easier to circumvent but it is a limitation of PMD and there are other ways to hide C&P. (This makes grading it more problematic because avoid the CPD messages can lead to worse code, especially is students are inexperienced). But I cannot think of a better way.

2020-11-05 23:18 UTC, krusche approved these changes

2020-11-05 23:19 UTC, merged