[Enhancement] Add bonus to views and rename to type
ls1intum/Artemis pull request #2304
Opened 2020-10-30 21:24 UTC by fde312

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [ ] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [ ] Server: I implemented the changes with a good performance and prevented too many database calls
- [ ] Server: I documented the Java code using JavaDoc style.
- [ ] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [ ] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [ ] Client: I documented the TypeScript code using JSDoc style.
- [ ] Client: I added multiple screenshots/screencasts of my UI changes
- [ ] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

### Description

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Test Coverage

* ExerciseService.java: 85%
* programming-exercise.component.ts 95%

### Screenshots

2020-10-30 21:56 UTC, fde312 commented
Client tests are failing because of formatting. I just runned prettier and got this back:
<img width="893" alt="image" src="https://user-images.githubusercontent.com/41108487/97760253-005ed980-1b03-11eb-81df-792a23a21f61.png">

So do not wonder why it is formatted so strangely 😅

2020-11-01 13:10 UTC, MaisiKoleni reviewed
Looks good and works well (for both German and English).

I just have some points that are unclear to me:
- Do we want to display bonus points in the "View" exercise as well? Currently, there are only the normal points.
- For exams (in this case a test run) i found "Max. Points" in the summary. Is this intended/ok?
  ![image](https://user-images.githubusercontent.com/11130248/97803801-090ef700-1c4c-11eb-9735-bd3e9147dbbb.png)

2020-11-02 09:19 UTC, FrankeLukas reviewed
Imho
![grafik](https://user-images.githubusercontent.com/72132281/97850606-8ee67d00-1cf4-11eb-9d18-717683d4ac54.png)
would look better as
![grafik](https://user-images.githubusercontent.com/72132281/97850813-d3721880-1cf4-11eb-91de-12d28a0610ad.png)
Opinions?

2020-11-02 09:19 UTC, FrankeLukas commented on src/main/webapp/app/exam/participate/exercises/modeling/modeling-exam-submission.component.html
> +        >&nbsp;[{{ exercise.maxScore }} {{ 'artemisApp.examParticipation.points' | translate }}
Can we move the closing tags onto the same line? (Here and in the files below.) Imho
```
<span
    >
```
looks very weird compared to just having `<span>` when there are no attributes.

2020-11-02 11:46 UTC, krusche commented
> Imho
> ![grafik](https://user-images.githubusercontent.com/72132281/97850606-8ee67d00-1cf4-11eb-9d18-717683d4ac54.png)
> would look better as
> ![grafik](https://user-images.githubusercontent.com/72132281/97850813-d3721880-1cf4-11eb-91de-12d28a0610ad.png)
> Opinions?

I would like to avoid a third line and rather make the header a bit smaller. I think the current display is good

2020-11-02 11:47 UTC, krusche commented
> * Do we want to display bonus points in the "View" exercise as well? Currently, there are only the normal points.
Yes, this would be good!
> * For exams (in this case a test run) i found "Max. Points" in the summary. Is this intended/ok?
Please rename to Points here as well.

Basically Max. Points should not be used any more in the whole application

2020-11-02 12:03 UTC, FuchsDominik requested changes
In my exam summary, the bonus points are not shown. (Exercise 1 should have bonus points)
![image](https://user-images.githubusercontent.com/44401560/97865755-fb6c7680-1d0a-11eb-823a-83a7d59200e9.png)
Mini remark: You could switch the white space to the second string, so without the second string, the square brackets are even:
![image](https://user-images.githubusercontent.com/44401560/97866103-8c435200-1d0b-11eb-8633-5ecc6034cb0a.png)
The rest looked very good to me!

2020-11-02 15:09 UTC, fde312 commented
> In my exam summary, the bonus points are not shown. (Exercise 1 should have bonus points)
> ![image](https://user-images.githubusercontent.com/44401560/97865755-fb6c7680-1d0a-11eb-823a-83a7d59200e9.png)
> Mini remark: You could switch the white space to the second string, so without the second string, the square brackets are even:
> ![image](https://user-images.githubusercontent.com/44401560/97866103-8c435200-1d0b-11eb-8633-5ecc6034cb0a.png)
> The rest looked very good to me!

@FuchsDominik I added this now:
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/41108487/97883584-58752600-1d25-11eb-9b52-699353b3c7fa.png">

The issue with the whitespace comes from the formatting. I tried out to use prettier-ignore to fix the issue with the styling mentioned by @FrankeLukas. 

@MaisiKoleni I added the bonus points also in the exercise view :

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/41108487/97883776-95411d00-1d25-11eb-91ef-b724db0241af.png">

Would be nice if you could recheck :)

2020-11-02 23:40 UTC, krusche approved these changes

2020-11-02 23:40 UTC, merged