[Bugfix] Stash unsubmitted changes after due date has passed
ls1intum/Artemis pull request #2314
Opened 2020-11-02 22:11 UTC by fde312

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context

We want to display only the changes that the student submitted (all changes that are on BitBucket). To ensure this, we will stash all unsubmitted changes.

### Description

- Implemented method to  stash changes after the due date has passed
- Invoke stash changes method in a scheduler, that will be executed when the due date has passed (same as for lock repo)

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Create Programming Exercise, set due date in the near future and enable manual assessment
4. Participate on exercise
4.1 Submit code and make change and just click on save (do not submit a second time!!!)
4.2 Just save your changes (do not submit at all)
4.3 Make changes and alway submit your code
5. Wait until the due date has passed
6. Check your submission in the code editor and check that the not saved changes are not displayed anymore

### Test Coverage

* ExerciseService.java: 85%
* programming-exercise.component.ts 95%

### Screenshots

During participation after clicking on save:
<img width="1665" alt="image" src="https://user-images.githubusercontent.com/41108487/97924909-b83cf280-1d60-11eb-82ef-1a4fa0ddd33a.png">

2020-11-03 22:05 UTC, MaisiKoleni commented on src/main/java/de/tum/in/www1/artemis/service/scheduled/ProgrammingExerciseScheduleService.java
> +                                    + numberOfFailedStashOperations);
Reformulate / adjust reporting logic to notify only about operations that failed (not always both).

2020-11-04 00:07 UTC, kloessst reviewed
Already tested on this on TS1. Nice feature works really well.

2020-11-05 03:06 UTC, fde312 commented
I am not quite sure why the server tests on bamboo fail. I ran the test 100 times locally and everything works fine:
<img width="1664" alt="image" src="https://user-images.githubusercontent.com/41108487/98192884-385b8780-1f1c-11eb-8d98-d8c1aea7fcf8.png">

2020-11-05 13:41 UTC, stefanwaldhauser approved these changes
Works as expected :) I am not an export in the programming exercise code but also looks fine
![image](https://user-images.githubusercontent.com/29718932/98247854-74bad200-1f74-11eb-874f-99452c41d27c.png)
![image](https://user-images.githubusercontent.com/29718932/98248213-ea26a280-1f74-11eb-858d-3f42a9535084.png)

2020-11-05 14:57 UTC, FrankeLukas commented
Is there a specific reason we stash changes instead of tagging a release once the deadline is reached and always display that release? (Which has the advantage of not 'removing' things.) Might be worth considering for the long term?

2020-11-05 18:14 UTC, kloessst requested changes
Works fine. Cool feature. Just a small note about closing the repos:

2020-11-05 18:19 UTC, kloessst commented on src/main/java/de/tum/in/www1/artemis/service/connectors/GitService.java
> +        git.close();
Nevermind the Git(repo, closeRepo) constructor is package private and can't be used. We would need to use Git.open(File dir, FS fs) the get a Git instance which closes the repo. You could still close the repo by hand if you don't need it anymore.

2020-11-05 18:21 UTC, kloessst approved these changes
Closing of repos shouldn't be an issue so I approve 😄

2020-11-05 18:29 UTC, tiffca approved these changes
Tested on test server 1 and confirmed only submitted changes are saved and actually graded. Saved changes are not available after the due date, only submitted changed. Tested the 3 scenarios described and a 4th scenario with not saving or submitting the changes.

2020-11-05 18:59 UTC, derLalla approved these changes
this is a nice feature! Approved :)

2020-11-05 22:14 UTC, MaisiKoleni approved these changes
Code still looks good as far as I can see.

2020-11-05 23:29 UTC, krusche commented
> Is there a specific reason we stash changes instead of tagging a release once the deadline is reached and always display that release? (Which has the advantage of not 'removing' things.) Might be worth considering for the long term?

We wanted to have a quick solution. Stashing the changes means they would still be available for server admins and would not be lost. For students and instructors, they would currently not be visible.

One future extension could be to commit and push them into a different branch, however this would include multiple operations (which could potentially fail) and might have other side effects (e.g. a pushed branch could lead to a build on the CI server and to a result on Artemis which would have to be ignored, etc.)

2020-11-05 23:31 UTC, krusche approved these changes

2020-11-05 23:32 UTC, merged