[Enhancement] Add tooltip for folder rename action
ls1intum/Artemis pull request #2368
Opened 2020-11-09 00:17 UTC by schultek

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

While the online code editor supports renaming folders, this is kind of hidden and might not be clear to students (See #2360).

### Description

When the renaming action is disabled, I added a tooltip to describe how to enable renaming folders.

### Steps for Testing

1. Log in to Artemis
2. Navigate to the online editor
3. Check that the tooltip for the rename action of folders is visible when the action itself is disabled.
4. Check that the tooltip is not visible when the rename action is enabled.

### Test Coverage

Nothing changed.

### Screenshots

2020-11-09 08:15 UTC, derLalla requested changes
![image](https://user-images.githubusercontent.com/33484318/98515704-bfd22f00-226b-11eb-920d-ea490254e959.png)

I have tested it on TS3, but I didn't get the tooltip message while hovering. I can edit the folder name, when I expand the folder structure though. I have tested it in several places and it was everytime the same: 
"View in Editor"-mode for templates and participating in an exercise via Online Editor

2020-11-09 10:43 UTC, tiffca approved these changes
Tooltip works as described, nice change! Tested in test server 1. 

Confirmed selecting the drop down enables/disables the menu and tooltip as expected.

2020-11-09 10:43 UTC, schultek commented
@derLalla Thats strange. Could you maybe test this again with a cleared cache? I just tested it on the same instance and it worked.

2020-11-09 12:28 UTC, derLalla approved these changes
the latest change now works fine! Good job 👍

2020-11-09 12:56 UTC, schultek commented
Because the ngb tooltip had problems in different browsers i changed it to use the default icon tooltip.

2020-11-09 14:30 UTC, sjagla27 approved these changes
Worked as expected.

2020-11-09 14:58 UTC, stefanwaldhauser approved these changes
![image](https://user-images.githubusercontent.com/29718932/98557412-73efac00-22a4-11eb-902b-025a87d3acb9.png)
Works as expected. Nice change :)

2020-11-09 15:36 UTC, kloessst approved these changes
Good usability change!

2020-11-09 15:50 UTC, FuchsDominik approved these changes
Works well!

2020-11-10 08:15 UTC, krusche approved these changes

2020-11-10 08:15 UTC, merged