Allow to set timeout for jenkins pipelines
ls1intum/Artemis pull request #2440
Opened 2020-11-20 23:37 UTC by axel1200

Fixes #2434

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [ ] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [ ] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [ ] Server: I implemented the changes with a good performance and prevented too many database calls

### Motivation and Context
Timeout out removes stale builds so i don't have to to it manually

### Description

### Steps for Testing
Set timeout to a minute via ENV variable. Submit a submission which runs forever.

I have no set up server. So I would be cool if one could help me test this or something similar.

2020-11-20 23:39 UTC, axel1200 commented on src/main/java/de/tum/in/www1/artemis/service/connectors/jenkins/DefaultJenkinsBuildPlanCreator.java
> -                REPLACE_ARTEMIS_NOTIFICATION_URL, artemisNotificationUrl, REPLACE_NOTIFICATIONS_TOKEN, ARTEMIS_AUTHENTICATION_TOKEN_KEY, REPLACE_DOCKER_IMAGE_NAME,
That code was duplicated 3 time and it was not readable with thing was replaced by what

2020-11-20 23:39 UTC, axel1200 commented on src/main/java/de/tum/in/www1/artemis/service/connectors/jenkins/JavaJenkinsBuildPlanCreator.java
> +            replacements.put(REPLACE_STATIC_CODE_ANALYSIS_SCRIPT, staticCodeAnalysisScript);
Only set what is really different here

2020-11-21 21:19 UTC, kloessst reviewed
Code looks fine to me. Still have to test this though

2020-11-22 11:56 UTC, axel1200 commented
No idea why tests are failing

2020-11-23 21:54 UTC, kloessst commented
You can run .\gradlew spotlessApply to automatically fix the style issues.

2020-11-24 15:32 UTC, kloessst requested changes
Can you quickly fix the codacy issues? I think both a valid. Double-brace initialization causes another .class file to be created.

2020-11-24 19:17 UTC, fde312 approved these changes
Tested it and the build was aborted after 30 mins:
![image](https://user-images.githubusercontent.com/41108487/100141063-19ed0a00-2e92-11eb-8e1c-d5d156b6611d.png)

As far as I can tell the code looks also good! Good job 🚀

2020-11-24 19:20 UTC, kloessst approved these changes
Worked for me. Jenkins stopped the build after 30 mins:

![image](https://user-images.githubusercontent.com/16407766/100140854-d1cde780-2e91-11eb-9a7b-c37d6f960425.png)

You have to remove the StrictTimeout annotations, otherwise AJTS will stop the endless loop (Good to know that this works 😃 )

This is the result. I'm not sure if we can improve this. I guess it is fine for now:
![image](https://user-images.githubusercontent.com/16407766/100141267-718b7580-2e92-11eb-9344-721910a2d3bb.png)

2020-11-24 20:15 UTC, axel1200 commented
Nice

2020-11-24 21:05 UTC, krusche approved these changes

2020-11-24 21:05 UTC, merged