Added tests for file-upload-assessment-dashboard component
ls1intum/Artemis pull request #2452
Opened 2020-11-23 21:47 UTC by nicolasruscher

### Checklist

- [X] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)

### Test Coverage
Get Test Coverage for client over 80%

2020-11-24 11:20 UTC, FrankeLukas reviewed
The coverage report says 100% for the .html but only 62% for the .component.ts. Am I looking at the wrong report/file here?
![grafik](https://user-images.githubusercontent.com/72132281/100087678-5cd9be00-2e4f-11eb-84ed-324a9086e2f2.png)

2020-11-24 11:20 UTC, FrankeLukas commented on src/test/javascript/spec/component/file-upload-assessment/file-upload-assessment-dashboard.component.spec.ts
> +
The new line here looks a bit weird to me, but I don't know what the style policy for this is.

2020-11-26 08:32 UTC, ivanchimeno approved these changes
The tests good!

2020-11-27 10:11 UTC, stefanwaldhauser requested changes

2020-11-27 10:11 UTC, stefanwaldhauser commented on src/test/javascript/spec/component/file-upload-assessment/file-upload-assessment-dashboard.component.spec.ts
> +        it('test cancelAssessment', fakeAsync(() => {
fakeAsync and tick not needed.

2020-11-27 10:11 UTC, stefanwaldhauser commented on src/test/javascript/spec/component/file-upload-assessment/file-upload-assessment-dashboard.component.spec.ts
> +            expect(component.submissions).toEqual([]);
I do not realy understand what you are testing here? This is the method you want to test:

![image](https://user-images.githubusercontent.com/29718932/100437367-ec29e000-30a0-11eb-80b8-48affc1c34a5.png)

You should test that exercise is set imo.

2020-12-02 23:36 UTC, krusche commented
closing for now, please reopen it when it is ready to merge

2020-12-02 23:36 UTC, closed without merging