[Enhancement] Make download repos for programming exercises more robust
ls1intum/Artemis pull request #2550
Opened 2020-12-15 15:15 UTC by derLalla

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I implemented the changes with a good performance and prevented too many database calls

### Motivation and Context

See issue #2542 

### Description

While cloning into a directory there might be a case, that the selected directory is already existent and not empty. So we delete this directory before cloning into it. 
Also in the case of an error, we delete this directory again. 

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Go to programming assessments
4. Download the students' repositories and verify that everything still works as expected

### Test Coverage

Stays the same, as only two lines of code were changed.

### Screenshots

2020-12-15 16:26 UTC, simonzilker submitted a review, later dismissed
Everything works perfectly on ts1!

2020-12-15 16:26 UTC, JohannesWeiss approved these changes
Tested with @simonzilker, works as expected.

2020-12-15 16:28 UTC, airelawaleria submitted a review, later dismissed
Tested in the testing session. Works fine

2020-12-15 16:33 UTC, marvinchimeka approved these changes
tested in a testing session. Approve

2020-12-15 19:18 UTC, DenizShabani approved these changes
Tested on TS1 and everything looks good!

2020-12-15 19:22 UTC, LudwigWeide approved these changes
Tested on TS3. Works as intended.

2020-12-16 08:30 UTC, tiffca submitted a review, later dismissed
Tested successfully on ts1, tried different options for downloading the repo

2020-12-16 09:46 UTC, valeriebucher approved these changes
Tested on ts1, everything worked as described.

2020-12-16 11:28 UTC, JannisBittlmayer submitted a review, later dismissed
Tested on TS3, works as intended

2020-12-16 12:10 UTC, FrankeLukas submitted a review, later dismissed
Code changes lgtm.

2020-12-16 12:19 UTC, FrankeLukas approved these changes
Re-approve (only comment was added).

2020-12-16 12:52 UTC, simonzilker approved these changes
re-approve

2020-12-16 12:52 UTC, JohannesWeiss approved these changes
Re-Approve.

2020-12-16 12:52 UTC, marvinchimeka approved these changes
re-approve

2020-12-16 12:53 UTC, airelawaleria submitted a review, later dismissed
Re-approve

2020-12-16 16:44 UTC, LudwigWeide requested changes
Re-approve

2020-12-16 16:45 UTC, LudwigWeide submitted a review, later dismissed
Re-approve

2020-12-16 16:53 UTC, FlorianStang submitted a review, later dismissed
Tested and everything worked as intended.

2020-12-16 20:00 UTC, philgabr submitted a review, later dismissed
Works as intended.

2020-12-16 20:26 UTC, EneaGore submitted a review, later dismissed
All seems to work as intented.

2020-12-17 09:29 UTC, airelawaleria submitted a review, later dismissed
Re-approve

2020-12-17 09:38 UTC, simonzilker approved these changes
re-approve!

2020-12-17 09:40 UTC, JohannesWeiss approved these changes
Still works as intended on ts1. Re-Approve.

2020-12-17 10:44 UTC, krusche commented on src/main/java/de/tum/in/www1/artemis/service/connectors/VersionControlService.java
> +     * @param targetPath The path where the repo is cloned into
```suggestion
     * @param targetPath The path in the local Artemis server file system where the repo is cloned into in order to copy it
```

2020-12-17 11:05 UTC, merged