fix points label for zero points with bonus exercises
ls1intum/Artemis pull request #2575
Opened 2020-12-19 10:44 UTC by fde312

### Checklist
- [x] I tested *all* changes and *all* related features locally
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

Follow-up of #2539, issue with wrong point labels.

### Description

- added `!= undefined`
- 
### Steps for Testing

Normal exercises:

1. Log in to Artemis
2. Navigate to Course Administration

**Important: test the following 3 cases in 3 different exercises for Modeling, Text, Quiz and FileUpload:**
  10 points + 0 bonus points
  10 points + 10 bonus points
  0 points + 10 bonus points
Test the following scenario: if a student e.g. has collected 30 points in a course, but the sum of normal points is 20, then the score on the start page of Artemis should show 150%. The score calculation is really critical and has to be absolutely correct!
Also make sure that the instructor page course scores includes the correct calculation based on the sum of normal points and the exported csv file is correct.

3. Check that for the exercise detail view and exercise participation view the points are displayed correctly (e.g. 10, 10 (Bonus: 10), 0 (Bonus: 10) -> see screenshots below)

Exam exercises:
1. Create exam with same exercises setup as above (you can also import them)
2. Participate and set the result release date of the exam 
3. Check Summary table that no points and no bonus points are displayed with value 0 (see screenshot below)

### Test Coverage

Nothing changed.

### Screenshots

exercise detail view:
<img width="1657" alt="image" src="https://user-images.githubusercontent.com/41108487/102687249-f9447580-41ed-11eb-93cd-2d8c1c43373b.png">

exam summary view:
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/41108487/102687265-12e5bd00-41ee-11eb-817e-07721f5f5711.png">

exercise participation view:
<img width="1662" alt="image" src="https://user-images.githubusercontent.com/41108487/102687278-33157c00-41ee-11eb-98bc-68d5abaee8b8.png">

2020-12-19 11:37 UTC, JohannesWeiss requested changes
Code for this PR looks good, but when working on assessing the text/ modelling exercises with bonus points there occurs a bug: 
Those exercises only have bonus points and no normal points. We cannot add bonus points during the assessment, therefore we gave normal points (different amounts < maximum bonus points). The assessment dashboard and the students view then shows a totally wrong percentage for the grading. This happened with different amounts of (bonus) points given and always evaluated to the same percentage value.
![Screenshot 2020-12-19 at 12 37 00](https://user-images.githubusercontent.com/37304775/102688428-e5e9d800-41f6-11eb-8b7a-afdeafd09605.png)
Programming exercises did not have this problem in our testing session with @simonzilker , @airelawaleria and @marvinchimeka .

2020-12-19 11:37 UTC, simonzilker requested changes
What @JohannesWeiss said.
Scoreboard for Modeling exercise with 0 Points and 10 Bonus Points: 
![image](https://user-images.githubusercontent.com/73840817/102688427-e4201480-41f6-11eb-97a8-67234ffe91f0.png)

2020-12-19 11:37 UTC, airelawaleria requested changes
Tested in the testing session. Confirm the issue above.
![image](https://user-images.githubusercontent.com/64631786/102688382-b044ef00-41f6-11eb-9db3-410e9ca2244d.png)

2020-12-19 11:39 UTC, marvinchimeka reviewed
tested in a testing session. The case where you have 0 points and 10 Bonus points seems to work only for programming exercises. Agreeing with the mentioned issue by @JohannesWeiss .

2020-12-19 13:05 UTC, EneaGore requested changes
Can confirm same issue.
![IssueBonus](https://user-images.githubusercontent.com/73840596/102690075-31a27e80-4203-11eb-94c8-e76738154d99.PNG)

2020-12-22 17:12 UTC, fde312 commented on src/main/java/de/tum/in/www1/artemis/service/AssessmentService.java
> +        result.setScore(totalScore, maxPoints);
```suggestion
        result.setScore(totalScore, maxPointsRespectingZeroPoints);
```

2020-12-22 17:12 UTC, fde312 commented on src/main/java/de/tum/in/www1/artemis/service/AssessmentService.java
> +        result.setResultString(totalScore, maxPoints);
```suggestion
        result.setResultString(totalScore, maxPointsRespectingZeroPoints);
```

2020-12-28 12:45 UTC, derLalla commented
> What @JohannesWeiss said.
> Scoreboard for Modeling exercise with 0 Points and 10 Bonus Points:
> ![image](https://user-images.githubusercontent.com/73840817/102688427-e4201480-41f6-11eb-97a8-67234ffe91f0.png)

this is fixed with the latest changes

2020-12-28 13:17 UTC, simonzilker requested changes
Tested in testing session with @airelawaleria @JohannesWeiss @LudwigWeide . Exercises with 0 normal Points and 0 Bonus Points don´t work for all exercise types as you can see in the picture
![image](https://user-images.githubusercontent.com/73840817/103216764-19271800-4917-11eb-98b7-c0450b6692ef.png)

2020-12-28 13:17 UTC, airelawaleria requested changes
Tested in the testing session. 0 points 0 bonus points test case fails for every exercise type.

2020-12-28 13:17 UTC, LudwigWeide requested changes
Tested with @simonzilker . Same issue.

2020-12-28 13:18 UTC, JohannesWeiss requested changes
Tested again on ts1 in testing session and con confirm the issue mentioned by @simonzilker.
Additionally, we found a discrepancy in the percentage values in the course overview and the statistics tab of the course (116% and 133% in our case) that only gets updated, if one presses "Refresh". 

![output](https://user-images.githubusercontent.com/37304775/103216821-470c5c80-4917-11eb-9a6b-1df0887215e0.gif)

2020-12-28 13:34 UTC, marvinchimeka requested changes
The Test case with 0 points 0 bonus does not work for all exercise types .
Confirming already mentioned issue.

2020-12-28 15:27 UTC, derLalla commented
> Tested in testing session with @airelawaleria @JohannesWeiss @LudwigWeide . Exercises with 0 normal Points and 0 Bonus Points don´t work for all exercise types as you can see in the picture
> ![image](https://user-images.githubusercontent.com/73840817/103216764-19271800-4917-11eb-98b7-c0450b6692ef.png)

what is the issue? Do you mean that you have " x points of 100 points"?  
This is intended, as 0 point/0 bonus point exercises have a default of 100 points. So a user can achieve up to 100% of a the score.

2020-12-28 15:34 UTC, stefanwaldhauser commented
> Tested in testing session with @airelawaleria @JohannesWeiss @LudwigWeide . Exercises with 0 normal Points and 0 Bonus Points don´t work for all exercise types as you can see in the picture
> ![image](https://user-images.githubusercontent.com/73840817/103216764-19271800-4917-11eb-98b7-c0450b6692ef.png)

I am not sure what do you mean? 

![image](https://user-images.githubusercontent.com/29718932/103225608-97d98080-492a-11eb-8c44-008ca4a75faf.png)
![image (1)](https://user-images.githubusercontent.com/29718932/103225610-99a34400-492a-11eb-98a1-b94fc25f721d.png)

2020-12-28 15:43 UTC, airelawaleria approved these changes
Since the above mentioned behavior is normal, re-approve

2020-12-28 15:49 UTC, JohannesWeiss approved these changes
Re-Approve as well.

2020-12-28 15:55 UTC, stefanwaldhauser commented
> Tested again on ts1 in testing session and con confirm the issue mentioned by @simonzilker.
> Additionally, we found a discrepancy in the percentage values in the course overview and the statistics tab of the course (116% and 133% in our case) that only gets updated, if one presses "Refresh".
> 
> ![output](https://user-images.githubusercontent.com/37304775/103216821-470c5c80-4917-11eb-9a6b-1df0887215e0.gif)

I think I fixed this. Can you check again please :) ?

2020-12-28 16:42 UTC, stefanwaldhauser commented
> > Tested again on ts1 in testing session and con confirm the issue mentioned by @simonzilker.
> > Additionally, we found a discrepancy in the percentage values in the course overview and the statistics tab of the course (116% and 133% in our case) that only gets updated, if one presses "Refresh".
> > ![output](https://user-images.githubusercontent.com/37304775/103216821-470c5c80-4917-11eb-9a6b-1df0887215e0.gif)
> 
> I think I fixed this. Can you check again please :) ?

Reverted fix and will be dealt in a follow up.

2020-12-28 17:15 UTC, airelawaleria approved these changes
Tested in the testing session @marvinchimeka @JohannesWeiss @simonzilker @LudwigWeide . Works fine

2020-12-28 17:16 UTC, JohannesWeiss approved these changes
Tested on ts1 in testing session, works as expected so far.

2020-12-28 17:16 UTC, simonzilker approved these changes
Tested in testing session. Found no bugs! Looks good!

2020-12-28 17:17 UTC, marvinchimeka approved these changes
tested in testing session. Works as intended.

2020-12-28 17:34 UTC, EneaGore approved these changes
Seems to be working fine on ts1 now.

2020-12-28 21:23 UTC, valeriebucher approved these changes
Looks fine to me. Worked as described on ts1

2020-12-29 08:58 UTC, tiffca approved these changes
Tested successfully on ts1. 

noticed one behavior on file upload where the points says out of 100 points for some reason (even though it's out of 0 points and calculated correctly), but not a big issue.
Reproduce steps: 
1. Create a file upload exercise with 0 points
2. assess and give 0 points
3. in the student view look at how many points they have. Actual: it says 0 out of 100. Expected: it should say just 0 points or 0 out of 10 or 20 (if bonus included). 

![image](https://user-images.githubusercontent.com/63906424/103272085-34982e80-49bc-11eb-9ddd-1b581b1f7b50.png)

2020-12-29 09:49 UTC, krusche requested changes
I am also confused by the result string in case of 0 points exercises with 0 bonus points.

![image](https://user-images.githubusercontent.com/744067/103274907-226dbe80-49c3-11eb-88a6-b3a1e01b4170.png)

We should not show anything about points in the result string here.
For programming exercises, please only show the percentage based on the tests
For modeling|text|fileupload exercises, please show a different type of result string, I would suggest some kind of summary about the feedback elements, the minimal solution would be "X feedback"

2020-12-29 12:44 UTC, derLalla commented
> I am also confused by the result string in case of 0 points exercises with 0 bonus points.
> 
> ![image](https://user-images.githubusercontent.com/744067/103274907-226dbe80-49c3-11eb-88a6-b3a1e01b4170.png)
> 
> We should not show anything about points in the result string here.
> For programming exercises, please only show the percentage based on the tests
> For modeling|text|fileupload exercises, please show a different type of result string, I would suggest some kind of summary about the feedback elements, the minimal solution would be "X feedback"

We have addressed the issue and we are displaying now: 

x%, 0 of 0 points.

2020-12-29 12:46 UTC, derLalla commented
> Tested again on ts1 in testing session and con confirm the issue mentioned by @simonzilker.
> Additionally, we found a discrepancy in the percentage values in the course overview and the statistics tab of the course (116% and 133% in our case) that only gets updated, if one presses "Refresh".
> 
> ![output](https://user-images.githubusercontent.com/37304775/103216821-470c5c80-4917-11eb-9a6b-1df0887215e0.gif)

this will be addressed in a follow-up PR. Where we want to use websockets to update the view.

2020-12-30 08:51 UTC, tiffca approved these changes
Tested the previously mentioned scenario and it works as expected now, hence approving!

2020-12-30 08:57 UTC, airelawaleria approved these changes
Re-tested on ts3. Re-approve

2020-12-30 09:01 UTC, simonzilker submitted a review, later dismissed
Looks good! Re-approve.

2020-12-30 09:02 UTC, JohannesWeiss submitted a review, later dismissed
Looks good to me, code as well. Re-Approve!

2020-12-30 11:31 UTC, philippbauch requested changes
Added two small suggestions. Otherwise, the code looks good to me!

2020-12-30 11:31 UTC, philippbauch commented on src/main/java/de/tum/in/www1/artemis/domain/Exercise.java
> +        return false;
```suggestion
        return !hasNormalPoints && !hasBonusPoints;
```

2020-12-30 11:31 UTC, philippbauch commented on src/main/java/de/tum/in/www1/artemis/domain/Result.java
>          }
```suggestion
        if (exercise != null && exercise.isZeroPointExercise()) {
            totalScore = 0.0;
            maxScore = 0.0;
        }
        return formatter.format(totalScore) + " of " + formatter.format(maxScore) + " points";
```

You probably don't need that `else`

2020-12-30 14:21 UTC, JannisBittlmayer requested changes
Tested on TS1, works apart from some small issues:
- For exercises with 0 normal and 0 bonus points: When you assess this exercise with >0 points (for example 14), the score is set to 14%, 0 of 0 points. This may be intended but looks weird to me
- For File Upload exercises: When assessing this exercise, you cannot give 0 points for "Add feedback" since Artemis gives the warning that "The score field must be a number and can not be empty".
- For exercises with 0 points and (for example) 10 bonus points: When you give 9 points the result is 90%, 9 of 10 points. Shouldn't it be 9 of 0 points? When you have an exercise with 10 normal and 10 bonus points, it can show 15 of 10 points, too. I can see the problem of calculating a percentage for e.g. 9/0 though. I hope it's clear what I mean.

2020-12-30 14:22 UTC, FlorianStang requested changes
Tested in TS1 with @JannisBittlmayer, i can confirm the points mentioned by Jannis.

2020-12-30 14:22 UTC, derLalla commented on src/main/java/de/tum/in/www1/artemis/domain/Result.java
>          }
👍

2020-12-30 14:38 UTC, derLalla commented
> Tested on TS1, works apart from some small issues:
> 
> * For exercises with 0 normal and 0 bonus points: When you assess this exercise with >0 points (for example 14), the score is set to 14%, 0 of 0 points. This may be intended but looks weird to me
> * For File Upload exercises: When assessing this exercise, you cannot give 0 points for "Add feedback" since Artemis gives the warning that "The score field must be a number and can not be empty".
> * For exercises with 0 points and (for example) 10 bonus points: When you give 9 points the result is 90%, 9 of 10 points. Shouldn't it be 9 of 0 points? When you have an exercise with 10 normal and 10 bonus points, it can show 15 of 10 points, too. I can see the problem of calculating a percentage for e.g. 9/0 though. I hope it's clear what I mean.

I see your concerns, but all of that is intended:  
1) for 0 point / 0 bonus point exercises we still need a way to grad and give a score. So 100 is the base for those exercises. This means the shown points are actually percentage points.  

2) You cannot give 0 points for a Feedback, this wouldn't make sense. I guess you are confused by the meaning of a zero point exercise. As mentioned in 1) this should be seen as a percentage score.  

3) We always want to show the maximum points. So for a 10/10 exercise we are showing 20 of 10 points (Bonus: 10).  
For a 0/10 exercise, it is 10 of 10 points (Bonus: 10)
For a 10/0 exercise, it is 10 of 10 points.
For a 0/0 exercise, it is 0 of 0 points.

2020-12-30 14:39 UTC, derLalla commented
> Tested in TS1 with @JannisBittlmayer, i can confirm the points mentioned by Jannis.

see my explanation above :)

2020-12-30 14:40 UTC, derLalla commented
> Added two small suggestions. Otherwise, the code looks good to me!

thanks, I have committed your changes 👍

2020-12-30 14:45 UTC, JannisBittlmayer commented
> 
> 
> > Tested on TS1, works apart from some small issues:
> > 
> > * For exercises with 0 normal and 0 bonus points: When you assess this exercise with >0 points (for example 14), the score is set to 14%, 0 of 0 points. This may be intended but looks weird to me
> > * For File Upload exercises: When assessing this exercise, you cannot give 0 points for "Add feedback" since Artemis gives the warning that "The score field must be a number and can not be empty".
> > * For exercises with 0 points and (for example) 10 bonus points: When you give 9 points the result is 90%, 9 of 10 points. Shouldn't it be 9 of 0 points? When you have an exercise with 10 normal and 10 bonus points, it can show 15 of 10 points, too. I can see the problem of calculating a percentage for e.g. 9/0 though. I hope it's clear what I mean.
> 
> I see your concerns, but all of that is intended:
> 
>     1. for 0 point / 0 bonus point exercises we still need a way to grad and give a score. So 100 is the base for those exercises. This means the shown points are actually percentage points.
> 
>     2. You cannot give 0 points for a Feedback, this wouldn't make sense. I guess you are confused by the meaning of a zero point exercise. As mentioned in 1) this should be seen as a percentage score.
> 
>     3. We always want to show the maximum points. So for a 10/10 exercise we are showing 20 of 10 points (Bonus: 10).
>        For a 0/10 exercise, it is 10 of 10 points (Bonus: 10)
>        For a 10/0 exercise, it is 10 of 10 points.
>        For a 0/0 exercise, it is 0 of 0 points.

Okay, thanks for the quick response :)

2020-12-30 14:46 UTC, derLalla commented
> > > Tested on TS1, works apart from some small issues:
> > > 
> > > * For exercises with 0 normal and 0 bonus points: When you assess this exercise with >0 points (for example 14), the score is set to 14%, 0 of 0 points. This may be intended but looks weird to me
> > > * For File Upload exercises: When assessing this exercise, you cannot give 0 points for "Add feedback" since Artemis gives the warning that "The score field must be a number and can not be empty".
> > > * For exercises with 0 points and (for example) 10 bonus points: When you give 9 points the result is 90%, 9 of 10 points. Shouldn't it be 9 of 0 points? When you have an exercise with 10 normal and 10 bonus points, it can show 15 of 10 points, too. I can see the problem of calculating a percentage for e.g. 9/0 though. I hope it's clear what I mean.
> > 
> > 
> > I see your concerns, but all of that is intended:
> > ```
> > 1. for 0 point / 0 bonus point exercises we still need a way to grad and give a score. So 100 is the base for those exercises. This means the shown points are actually percentage points.
> > 
> > 2. You cannot give 0 points for a Feedback, this wouldn't make sense. I guess you are confused by the meaning of a zero point exercise. As mentioned in 1) this should be seen as a percentage score.
> > 
> > 3. We always want to show the maximum points. So for a 10/10 exercise we are showing 20 of 10 points (Bonus: 10).
> >    For a 0/10 exercise, it is 10 of 10 points (Bonus: 10)
> >    For a 10/0 exercise, it is 10 of 10 points.
> >    For a 0/0 exercise, it is 0 of 0 points.
> > ```
> 
> Okay, thanks for the quick response :)

btw. Do not hit "Close with comment", as this will close the whole PR :D

2020-12-30 14:47 UTC, JannisBittlmayer commented
> 
> 
> > > > Tested on TS1, works apart from some small issues:
> > > > 
> > > > * For exercises with 0 normal and 0 bonus points: When you assess this exercise with >0 points (for example 14), the score is set to 14%, 0 of 0 points. This may be intended but looks weird to me
> > > > * For File Upload exercises: When assessing this exercise, you cannot give 0 points for "Add feedback" since Artemis gives the warning that "The score field must be a number and can not be empty".
> > > > * For exercises with 0 points and (for example) 10 bonus points: When you give 9 points the result is 90%, 9 of 10 points. Shouldn't it be 9 of 0 points? When you have an exercise with 10 normal and 10 bonus points, it can show 15 of 10 points, too. I can see the problem of calculating a percentage for e.g. 9/0 though. I hope it's clear what I mean.
> > > 
> > > 
> > > I see your concerns, but all of that is intended:
> > > ```
> > > 1. for 0 point / 0 bonus point exercises we still need a way to grad and give a score. So 100 is the base for those exercises. This means the shown points are actually percentage points.
> > > 
> > > 2. You cannot give 0 points for a Feedback, this wouldn't make sense. I guess you are confused by the meaning of a zero point exercise. As mentioned in 1) this should be seen as a percentage score.
> > > 
> > > 3. We always want to show the maximum points. So for a 10/10 exercise we are showing 20 of 10 points (Bonus: 10).
> > >    For a 0/10 exercise, it is 10 of 10 points (Bonus: 10)
> > >    For a 10/0 exercise, it is 10 of 10 points.
> > >    For a 0/0 exercise, it is 0 of 0 points.
> > > ```
> > 
> > 
> > Okay, thanks for the quick response :)
> 
> btw. Do not hit "Close with comment", as this will close the whole PR :D

I realized this after posting, sorry! Won't happen again!

2020-12-30 14:52 UTC, JannisBittlmayer approved these changes
Everything works as intended.

2020-12-30 14:54 UTC, JohannesWeiss approved these changes
New code changes lgtm, therefore re-approve!

2020-12-30 14:56 UTC, airelawaleria approved these changes
Re-approve

2020-12-30 14:59 UTC, simonzilker approved these changes
Re-approve

2020-12-30 15:09 UTC, marvinchimeka submitted a review, later dismissed
Looks Good. Re-approve

2020-12-30 18:25 UTC, FuchsDominik approved these changes
Code looks good to me! Really just found some questionable comments which i came across

2020-12-30 18:25 UTC, FuchsDominik commented on src/main/webapp/app/exam/manage/student-exams/student-exam-detail.component.ts
> +                // TODO: rene: is it possible to have only bonusPoint exams?
Was this forgotten or left on purpose?

2020-12-30 18:25 UTC, FuchsDominik commented on src/main/webapp/app/exercises/programming/assess/code-editor-tutor-assessment-container.component.ts
> +            // TODO: rene: change the resultString depending on bonusPoints?
Is this relevant for follow-ups?

2020-12-30 18:25 UTC, FuchsDominik commented on src/main/webapp/app/exercises/programming/assess/code-editor-tutor-assessment-container.component.ts
> +            // TODO: rene: change the resultString depending on bonusPoints?
Same here?

2020-12-30 18:25 UTC, FuchsDominik commented on src/main/webapp/app/exercises/text/manage/example-text-submission/example-text-submission.component.ts
> +        // this.totalScore = credits.reduce((a, b) => a! + b!, 0)!;
Is not needed i assume?

2020-12-31 09:16 UTC, tiffca approved these changes
Everything worked for me, except I couldn't create programming exercises - probably some weird bug I'm experiencing, hence approving.
The other exercises worked fine.

2020-12-31 10:05 UTC, airelawaleria approved these changes
Changes look good. Re-approve

2020-12-31 10:05 UTC, simonzilker submitted a review, later dismissed
looks good!

2020-12-31 10:06 UTC, marvinchimeka approved these changes
Works fine and code looks good.

2020-12-31 10:07 UTC, JohannesWeiss submitted a review, later dismissed
Looks good to me, re-approve!

2020-12-31 10:45 UTC, EneaGore submitted a review, later dismissed
Looks good, for programming exercises it still shows points out of 100 for 0+0 points if you open the Feedback. It is not caluclated into the actual points though.

2021-01-02 12:02 UTC, nicolasruscher submitted a review, later dismissed
Looking good!

2021-01-02 12:38 UTC, airelawaleria submitted a review, later dismissed
Tested with @simonzilker on ts1 again. Everything works. Now for 0-0 exercises the precentual achievement is shown together with "0 of 0 points" string.

2021-01-02 12:38 UTC, simonzilker submitted a review, later dismissed
Tested with @airelawaleria on ts1. Works as intended now!

2021-01-02 12:50 UTC, LudwigWeide approved these changes
Tested on TS with @JohannesWeiss . Works as intended. Point display a little confusing (58% while 0 out of 0 points.) as in Screenshot.
![0_0points](https://user-images.githubusercontent.com/52135815/103457664-764d1000-4d01-11eb-8d32-fc345b64d84b.PNG)

2021-01-02 12:50 UTC, JohannesWeiss approved these changes
Tested on ts1 with @LudwigWeide. Basically, everything works as intended.
With a 0 0 programming exercise a percentage is shown depending on the given points, but we assume this is not a real issue, since for those exercises no points should be given. Since zero out of zero points are displayed correctly this can still be approved.
![image](https://user-images.githubusercontent.com/37304775/103457666-7cdb8780-4d01-11eb-8683-bd88a48c366c.png)

2021-01-02 14:10 UTC, marvinchimeka approved these changes
Could not find any issue. 0 of 0 string is shown as intended.

2021-01-02 14:29 UTC, airelawaleria approved these changes
Re-approve

2021-01-02 14:29 UTC, JohannesWeiss approved these changes
Re-Approve!

2021-01-02 14:30 UTC, simonzilker approved these changes
re-approve

2021-01-02 14:30 UTC, LudwigWeide submitted a review, later dismissed
Re-Approve.

2021-01-02 14:36 UTC, tiffca approved these changes
Tested all scenarios with programming exercise and it works!

2021-01-02 15:52 UTC, derLalla commented
> Tested on ts1 with @LudwigWeide. Basically, everything works as intended.
> With a 0 0 programming exercise a percentage is shown depending on the given points, but we assume this is not a real issue, since for those exercises no points should be given. Since zero out of zero points are displayed correctly this can still be approved.
> ![image](https://user-images.githubusercontent.com/37304775/103457666-7cdb8780-4d01-11eb-8683-bd88a48c366c.png)

This is intended, and going to be addressed in a follow-up.

2021-01-02 16:40 UTC, airelawaleria approved these changes
Re-approve

2021-01-02 16:40 UTC, simonzilker approved these changes
re-approve

2021-01-02 16:40 UTC, JohannesWeiss approved these changes
Re-Approve!

2021-01-02 16:40 UTC, marvinchimeka approved these changes
re-approve

2021-01-04 04:51 UTC, EneaGore submitted a review, later dismissed
Last working release seems to work as expected.

2021-01-04 17:16 UTC, kloessst commented
**Programming Exercise Manual Assessment:**

- With points and bonus the result string only shows the points initially
![image](https://user-images.githubusercontent.com/16407766/103554985-0e88f780-4eb0-11eb-9025-e1ccc7f85faf.png)

- Without points but with bonus the same max 10 points are shown
![noPB](https://user-images.githubusercontent.com/16407766/103556614-5c9efa80-4eb2-11eb-86cc-cb8d23ddd43b.png)

Given this I would expect, that the exercise with points and bonus shows the points + bonus as the max points a tutor can give.

Tutors should be able to see, how many points and bonus points they can give for each programming exercise. This could also be realized as a tooltip.

Students should also be able to examine, how many bonus points an exercise can give here:
![image](https://user-images.githubusercontent.com/16407766/103556391-016d0800-4eb2-11eb-8277-a78f933df403.png)

**Programming Exercise Complaints:**

After the manual assessment, the dashboard shows a trigger build plan button for the exercise without points but with bonus. The automatic assessment of this submission was successful before.
![image](https://user-images.githubusercontent.com/16407766/103556090-8a377400-4eb1-11eb-9481-211abceb2363.png)

Seems like complaints are deactivated for exercises without points and bonus. This makes sense but we should explain this in the tooltip:
![image](https://user-images.githubusercontent.com/16407766/103557491-97edf900-4eb3-11eb-9450-5bd79e1aa5a7.png)

Need to verify this findings as TS1 got redeployed at some point.

2021-01-04 21:17 UTC, FrankeLukas reviewed
> See if everything works as expected

What is the expected Score for 0 point exercises? I created a new text exercise with 0 points and 0 bonus points, then assessed a submission with 1 point which results in the following:
![grafik](https://user-images.githubusercontent.com/72132281/103580193-0645b200-4eda-11eb-8d64-f3dc82239712.png)
I assume that is correct because we use a fallback of `100` as base when there are no points. However, on the course statistics for the student I still have 0 points? (When in fact I should have 1 point?)
![grafik](https://user-images.githubusercontent.com/72132281/103580489-9257d980-4eda-11eb-9e26-482b2e8257d0.png)

2021-01-04 21:47 UTC, krusche commented
> > See if everything works as expected
> 
> What is the expected Score for 0 point exercises? I created a new text exercise with 0 points and 0 bonus points, then assessed a submission with 1 point which results in the following:
> ![grafik](https://user-images.githubusercontent.com/72132281/103580193-0645b200-4eda-11eb-8d64-f3dc82239712.png)
> I assume that is correct because we use a fallback of `100` as base when there are no points. However, on the course statistics for the student I still have 0 points? (When in fact I should have 1 point?)
> ![grafik](https://user-images.githubusercontent.com/72132281/103580489-9257d980-4eda-11eb-9e26-482b2e8257d0.png)

In this case it should always state 0%. You cannot achieve any points, so a score different from 0% would not make sense at the moment. (We can think about supporting this differently in the future, but such exercises do not occur often)

2021-01-04 23:39 UTC, kloessst requested changes
Everything worked fine. I added small functional suggestions in a comment above. A few notes about the code:

2021-01-06 19:49 UTC, stefanwaldhauser commented
> We can think about supporting this differently in the future, but such exercises do not occur often)


> Seems like complaints are deactivated for exercises without points and bonus. This makes sense but we should explain this in the tooltip:

This is not related to the points it all. The code is in complaint-interactions.component.ts Please check again that this is really a problem only for  0 0 exercises..
![image](https://user-images.githubusercontent.com/29718932/103813546-8f86f100-5060-11eb-8f6b-df47012758f1.png)

2021-01-06 19:58 UTC, stefanwaldhauser commented
> > See if everything works as expected
> 
> What is the expected Score for 0 point exercises? I created a new text exercise with 0 points and 0 bonus points, then assessed a submission with 1 point which results in the following:
> ![grafik](https://user-images.githubusercontent.com/72132281/103580193-0645b200-4eda-11eb-8d64-f3dc82239712.png)
> I assume that is correct because we use a fallback of `100` as base when there are no points. However, on the course statistics for the student I still have 0 points? (When in fact I should have 1 point?)
> ![grafik](https://user-images.githubusercontent.com/72132281/103580489-9257d980-4eda-11eb-9e26-482b2e8257d0.png)



> > > See if everything works as expected
> > 
> > 
> > What is the expected Score for 0 point exercises? I created a new text exercise with 0 points and 0 bonus points, then assessed a submission with 1 point which results in the following:
> > ![grafik](https://user-images.githubusercontent.com/72132281/103580193-0645b200-4eda-11eb-8d64-f3dc82239712.png)
> > I assume that is correct because we use a fallback of `100` as base when there are no points. However, on the course statistics for the student I still have 0 points? (When in fact I should have 1 point?)
> > ![grafik](https://user-images.githubusercontent.com/72132281/103580489-9257d980-4eda-11eb-9e26-482b2e8257d0.png)
> 
> In this case it should always state 0%. You cannot achieve any points, so a score different from 0% would not make sense at the moment. (We can think about supporting this differently in the future, but such exercises do not occur often)

It is unclear to me how this is an error. As far as I understood the PR the whole point of 100 point workaround was that students still see a score even though they receive no points?

2021-01-07 21:49 UTC, krusche commented
After communication issues and after finding out that the changes in this PR include some wrong implementation, we decided to close this PR and further work on an improved solution in a new PR https://github.com/ls1intum/Artemis/pull/2651

2021-01-07 21:49 UTC, closed without merging