Bugfix/issue 2193
ls1intum/Artemis pull request #2589
Opened 2020-12-21 19:17 UTC by kriststoja

### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context
When creatin a new programming exercise (or editing it), at least one of "Allow Offline IDE" and "Allow Online Editor" must be selected

### Description
Added a validation to prevent deselecting both button "Allow Offline IDE" and "Allow Online Editor". If both of them are deselected, an info icon pops up with a message explaining the problem and both the text and the icon are in red color. Also the "generate" button will be disabled until at least one of the options is selected.

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Select a course (if none possible generate a new one) and go to exercises.
4. Press "Generate a new programming exercise"
5. At the end of the form are the two options"Allow Offline IDE" and "Allow Online Editor" . Try selecting and deselecting both of them and see if the functionality fullfills the conditions. 
6. Test the disabling and enabling of the "generate" button by filling all the mandatory fields. 

### Test Coverage

### Screenshots
![image](https://user-images.githubusercontent.com/75738365/102811171-40389380-43c5-11eb-8c2d-108fa8f3c097.png)
![image](https://user-images.githubusercontent.com/75738365/102811187-46c70b00-43c5-11eb-854f-237f4355bc6d.png)
![image](https://user-images.githubusercontent.com/75738365/102811385-8db50080-43c5-11eb-97cc-1e67617bf2e2.png)

2020-12-21 20:05 UTC, airelawaleria approved these changes
Tested in the testing session. Approve

2020-12-21 20:06 UTC, simonzilker approved these changes
Tested in testing session with @EneaGore @airelawaleria @marvinchimeka . Approve!

2020-12-21 20:06 UTC, marvinchimeka submitted a review, later dismissed
Testing in testing session on ts1. Approve

2020-12-21 20:07 UTC, EneaGore submitted a review, later dismissed
Tested in testing session on ts1, approve.

2020-12-21 20:10 UTC, JohannesWeiss approved these changes
Works, approve!

2020-12-21 20:33 UTC, valeriebucher submitted a review, later dismissed
Tested on ts3, works fine!

2020-12-22 00:40 UTC, LudwigWeide approved these changes
Tested on TS1. Works as intended.

2020-12-23 06:45 UTC, krusche commented on src/main/webapp/i18n/de/programmingExercise.json
> +                "alert": "Es muss mindestens eine zwischen Offline IDE und Online Editor ausgewählt sein"
```suggestion
                "alert": "Es muss mindestens eine Option (Offline IDE oder Online Editor) ausgewählt sein"
```

2020-12-23 06:46 UTC, krusche commented on src/main/webapp/i18n/de/programmingExercise.json
> +                "alert": "Es muss mindestens eine zwischen Offline IDE und Online Editor ausgewählt sein"
```suggestion
                "alert": "Es muss mindestens eine Option (Offline IDE oder Online Editor) ausgewählt sein"
```

2020-12-23 06:46 UTC, krusche commented on src/main/webapp/i18n/en/programmingExercise.json
> +                "alert": "At least one between Offline IDE and Online Editor must be selected"
```suggestion
                "alert": "At least one option (Offline IDE or Online Editor) must be selected"
```

2020-12-23 06:46 UTC, krusche commented on src/main/webapp/i18n/en/programmingExercise.json
> +                "alert": "At least one between Offline IDE and Online Editor must be selected"
```suggestion
                "alert": "At least one option (Offline IDE or Online Editor) must be selected"
```

2020-12-23 06:46 UTC, krusche requested changes
Changes look good, please adapt the translations

2020-12-23 10:21 UTC, kriststoja commented
> Changes look good, please adapt the translations

Done

2020-12-23 11:24 UTC, FuchsDominik approved these changes
Code changes looks good :)

2020-12-23 11:29 UTC, airelawaleria approved these changes
Re-approve

2020-12-23 11:29 UTC, JohannesWeiss approved these changes
Code looks good to me, re-approve.

2020-12-23 11:31 UTC, simonzilker approved these changes
re-approve!

2020-12-23 11:32 UTC, LudwigWeide approved these changes
Re-approve.

2020-12-23 11:36 UTC, marvinchimeka approved these changes

2020-12-23 14:33 UTC, JannisBittlmayer approved these changes
Tested on TS2, everything works as intended

2020-12-23 14:35 UTC, EneaGore approved these changes
Re-approve

2020-12-23 22:02 UTC, valeriebucher approved these changes
Reapprove.

2020-12-24 09:39 UTC, tiffca approved these changes
Works as expected, nice change!

2020-12-25 10:49 UTC, MaisiKoleni approved these changes
Code looks good to me.

2020-12-27 10:55 UTC, nicolasruscher approved these changes

2020-12-29 10:21 UTC, krusche approved these changes

2020-12-29 10:23 UTC, merged