Added documentation for alternative docker build agent setup
ls1intum/Artemis pull request #2639
Opened 2021-01-04 21:08 UTC by daniels98it

### Motivation and Context

After some difficulties getting jenkins working with the new pipeline builds, I came up with an alternative way of setting up a local build agent able to use the docker pipeline builds.

### Description

Added the documentation for an additional way of setting up a build agent using docker. The documentation describes how to set up an ssh build agent (similar to the remote build agents solution) using [jenkins/ssh-agent](https://hub.docker.com/r/jenkins/ssh-agent/) locally.

2021-01-08 09:58 UTC, FuchsDominik approved these changes
Text itself sounds good and couldn't find any errors :)

2021-01-09 17:45 UTC, FrankeLukas requested changes
Can't comment much on the technical side since I don't use this setup, but there are some minor visual issues we should have another look at.

2021-01-09 17:45 UTC, FrankeLukas commented on docs/dev/setup/jenkins-gitlab.rst
> +1. Make sure to have Docker installed: https://docs.docker.com/engine/install/ubuntu/
Can we link to the more generic `https://docs.docker.com/engine/install/` here?

2021-01-09 17:45 UTC, FrankeLukas commented on docs/dev/setup/jenkins-gitlab.rst
> +1. Make sure to have Docker installed: https://docs.docker.com/engine/install/ubuntu/
We also don't usually use plain links, I suggest the following:
```suggestion
1. Make sure to have Docker `installed <https://docs.docker.com/engine/install/ubuntu/>`__
```

2021-01-09 17:45 UTC, FrankeLukas commented on docs/dev/setup/jenkins-gitlab.rst
> +locally, can be done using the jenkins/ssh-agent docker image (https://hub.docker.com/r/jenkins/ssh-agent).
Same here:
```suggestion
locally, can be done using the jenkins/ssh-agent `docker image <https://hub.docker.com/r/jenkins/ssh-agent>`__.
```

2021-01-09 17:45 UTC, FrankeLukas commented on docs/dev/setup/jenkins-gitlab.rst
> +3. Run ``docker run -d --name jenkins_agent -v /var/run/docker.sock:/var/run/docker.sock jenkins/ssh-agent:latest "<copied_public_key>"``
This command appears to be too long and doesn't render correctly:
![grafik](https://user-images.githubusercontent.com/72132281/104104749-4e821d00-52aa-11eb-98e3-32af7a09fb74.png)

2021-01-09 17:45 UTC, FrankeLukas commented on docs/dev/setup/jenkins-gitlab.rst
> +    Passphrase: <the previous entered passphrase> (you can leave it blank if none has been specified)
This list as is looks odd to me:
![grafik](https://user-images.githubusercontent.com/72132281/104104778-71143600-52aa-11eb-95a3-a56d7ca48fd7.png)
Could we have a screenshot instead? (With the example values filled in.) Or perhaps a bullet point list/"code block"?

2021-01-12 08:28 UTC, daniels98it commented
Thanks @FrankeLukas for the suggestions. :rocket: 
These have been added with f46fefe and 98e51fd

2021-01-12 10:30 UTC, FrankeLukas approved these changes
Lgtm now. Also, I hope the RSA key you put in the screenshot is invalid by now. :sweat_smile:

2021-01-12 10:40 UTC, daniels98it commented
> Lgtm now. Also, I hope the RSA key you put in the screenshot is invalid.

I copied it from [http://phpseclib.sourceforge.net/rsa/examples.html](http://phpseclib.sourceforge.net/rsa/examples.html) just to have an example for it.
So no worries :sweat_smile:

2021-01-13 09:19 UTC, krusche approved these changes

2021-01-13 09:19 UTC, merged