Fix issue with missing result for programming exercises in exam mode after refreshing the browser
ls1intum/Artemis pull request #2793
Opened 2021-02-01 11:37 UTC by krusche

Fixes #2779
Also improve REST URLs to follow the standard and to distinguish those better

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).

### Steps for Testing
1. Create an exam and change the exercise group order
2. Participate as student in an exam and double check that everything is still working (some REST Urls were changed)
3. Submit code for one programming exercise and wait until the results appears
4. Reload the page
5. Double check that the result is displayed correctly
6. Also try out a test run and make sure nothing is broken here

2021-02-01 12:27 UTC, airelawaleria reviewed
Tested on ts1 with multiple exams and test users, but the issue was the opposite for me now. 
After the first submit I always got "No graded result" and after refreshing, the tests were triggered for the fisrt time to run ("Building and testing") and then the actual result appeared. (Second reload still displayed the results correctly)

2021-02-01 12:48 UTC, JohannesWeiss reviewed
Tested with multiple exams and users on ts1 as well and observed the same behaviour as @airelawaleria. After reloading the results did show up as expected.
Test Runs seemed to work fine, no issues were apparent with those.

2021-02-01 14:12 UTC, derLalla requested changes
The code looks good. I have just found one unused code reference.

2021-02-01 14:12 UTC, derLalla commented on src/main/java/de/tum/in/www1/artemis/web/rest/StudentExamResource.java
> -            if (forConduction) {
`forConduction` needs to be removed from the function parameters, as it is not used anymore.

2021-02-01 15:26 UTC, simonzilker reviewed
Tested with @marvinchimeka . Noticed the same behavior as mentioned from @airelawaleria.

2021-02-01 15:27 UTC, marvinchimeka reviewed
Tested in testing session. Have nothing to add to @simonzilker statement.

2021-02-01 17:12 UTC, philgabr reviewed
Submission couldn't be graded for me (artemis_test_user_2, ts3):
![image](https://user-images.githubusercontent.com/73602874/106493106-01fcbc80-64b9-11eb-8695-c705b5192901.png)

2021-02-01 17:35 UTC, sebastiantpeter reviewed
For me the correct submission result was available on ts2.

2021-02-01 22:50 UTC, kloessst requested changes
Code looks fine and the result is correctly displayed after a browser reload now.

I also experienced the weird problems with receiving the new result over websocket, especially with the first submission after starting the exam. I don't see any changes regarding websockets on client or server side in this PR so this might be unrelated. I will still reject the PR for now until we get more tests and/or find the root cause of this problem.

2021-02-02 19:13 UTC, philgabr reviewed
I deployed build 6 on ts3 and although deployment was successful, it continously displays "Artemis is starting up" & a 502 is thrown 
![image](https://user-images.githubusercontent.com/73602874/106650345-17461980-6593-11eb-8f98-5ae02b98e3f4.png)

2021-02-02 19:59 UTC, airelawaleria approved these changes
tested on ts1. worked as expected now

2021-02-02 20:00 UTC, tiffca reviewed
*edit* I think I had to refresh my browser, testing again
--
I couldn't participate in the exam at all. On TS1 after registering students and generating exam/prepare exercise start, the students receive this message when trying to participate "You are not registered for the exam . Please contact your instructor." Even though I can see the prepared exam for the students from the instructor side.

2021-02-02 20:01 UTC, JohannesWeiss approved these changes
Retested on ts1, worked as expected. The previous issue occurred only after logging out as creator of the exam and logging in as student/ test-user without a refresh of the page in between. After such a page reload, everything worked for me.

2021-02-02 21:34 UTC, merged

2021-02-02 21:35 UTC, fde312 approved these changes
Tested it and it works fine. Code looks good as well 👍