[Bugfix] scores csv broken with duplicate title
ls1intum/Artemis pull request #2819
Opened 2021-02-03 20:07 UTC by stefanwaldhauser

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [ ] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [ ] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [ ] Server: I implemented the changes with a good performance and prevented too many database calls
- [ ] Server: I documented the Java code using JavaDoc style.
- [ ] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [ ] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [ ] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [ ] Client: I documented the TypeScript code using JSDoc style.
- [ ] Client: I added multiple screenshots/screencasts of my UI changes
- [ ] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

### Description

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Test Coverage

### Screenshots

2021-02-04 09:56 UTC, ivanchimeno approved these changes
It works for me on TS1!

2021-02-05 14:45 UTC, FrankeLukas submitted a review, later dismissed
Works as advertised.

2021-02-05 14:46 UTC, FuchsDominik submitted a review, later dismissed
Testing worked well :)

2021-02-05 15:00 UTC, krusche commented on src/main/webapp/app/course/course-scores/course-scores.component.ts
> +                const titleMap = new Map();
can you add the type annotations <string, number> for key+value for the map?

2021-02-05 15:00 UTC, krusche commented on src/main/webapp/app/exam/exam-scores/exam-scores.component.ts
> +                        const titleMap = new Map();
can you add the type annotations <string, number> for key+value for the map?

2021-02-05 15:01 UTC, krusche requested changes
the code looks good, even if I am not a big fan of the code duplication and the missing tests ;-)

I still would like though that we add type annotations for the map datatypes so that we get more compiler safety

2021-02-05 15:50 UTC, JohannesWeiss approved these changes
Tested on ts1 and works as expected now, id is included for duplicates.

2021-02-05 15:51 UTC, airelawaleria approved these changes

2021-02-05 15:55 UTC, EneaGore submitted a review, later dismissed

2021-02-05 15:59 UTC, simonzilker reviewed
looks good on ts1

2021-02-05 16:00 UTC, JohannesWeiss approved these changes
Re-Approve

2021-02-05 16:00 UTC, airelawaleria approved these changes

2021-02-05 16:21 UTC, nicolasruscher submitted a review, later dismissed
Code lgtm 👍

2021-02-05 16:22 UTC, marvinchimeka submitted a review, later dismissed
Works as intended. Tested on ts1

2021-02-05 16:36 UTC, FrankeLukas submitted a review, later dismissed
Re-approve

2021-02-05 16:40 UTC, simonzilker submitted a review, later dismissed

2021-02-05 17:39 UTC, valeriebucher submitted a review, later dismissed

2021-02-05 18:31 UTC, philgabr submitted a review, later dismissed
works as described :+1:

2021-02-05 18:41 UTC, krusche submitted a review, later dismissed

2021-02-05 19:30 UTC, krusche approved these changes

2021-02-05 19:31 UTC, merged