Handle time-outs and other errors when submitting exams
ls1intum/Artemis pull request #2849
Opened 2021-02-09 17:11 UTC by FrankeLukas

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [ ] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

To the user it is currently not visible that Artemis is doing work in the background. Additionally we need to make sure it is possible to submit again when a time-out or different error occurs.

### Description

Introduces a client-side time-out (20s) and re-enables submission if that or an error occurs. Adds support for properly displaying 409 errors and introduces a spinner for when the REST call in the background loads.

### Steps for Testing

Create an Exam and test handing in both in a test run and in a "normal" run. Make sure you can submit again in case the call doesn't reach the server. (TODO: Provide testcase branch for testers.)

### Screenshots

While (up)loading the submission a spinner indicates something is happening:
![grafik](https://user-images.githubusercontent.com/72132281/107400504-27657800-6b02-11eb-9c8e-c4422ea7866c.png)

An error is displayed for time-outs:
![grafik](https://user-images.githubusercontent.com/72132281/107400482-23d1f100-6b02-11eb-8405-a7acffe6a5ee.png)

2021-02-09 17:12 UTC, FrankeLukas commented on src/main/webapp/app/exam/participate/exam-participation.service.ts
> +            .delay(30000);
This is a dummy testcase that needs to be removed before merging.

2021-02-10 10:56 UTC, marvinchimeka approved these changes
Tested in testing session. Everything works fine. We turned off our internet connection to simulate the situation

2021-02-10 10:56 UTC, simonzilker submitted a review, later dismissed
Tested in testing session. What  @marvinchimeka said

2021-02-10 10:57 UTC, philgabr approved these changes
Same as @marvinchimeka

2021-02-10 10:57 UTC, valeriebucher approved these changes
Same as @marvinchimeka.

2021-02-10 11:22 UTC, airelawaleria requested changes
Tested the client-timeout test brach with @JohannesWeiss 
We've noticed some issues.

After resubmitting the exam after timeout, the user didn't get a summary of the exam (only after the re-loading of the page, the summary was displayed)
![image](https://user-images.githubusercontent.com/64631786/107503682-88408f00-6b9a-11eb-8378-2ff80de3a7ab.png)

If the user didn't submit the exam, the summary appears on the screen and disappers after re-loading the page

2021-02-10 11:22 UTC, JohannesWeiss reviewed
Tested with @airelawaleria on ts1. Can confirm the mentioned issues.

2021-02-10 11:22 UTC, derLalla submitted a review, later dismissed
I have only looked through the code and am approving

2021-02-10 11:26 UTC, FrankeLukas commented
> After resubmitting the exam after timeout, the user didn't get a summary of the exam

Yes, that expected behaviour as long as it always displays the correct error message. (Since the client will always forcefully run into a timeout on that branch.)

2021-02-10 11:27 UTC, airelawaleria approved these changes
approving since the behavior is expected

2021-02-10 11:28 UTC, JohannesWeiss submitted a review, later dismissed

2021-02-10 12:14 UTC, krusche approved these changes

2021-02-10 12:14 UTC, FuchsDominik submitted a review, later dismissed
Code looks good to me :)

2021-02-10 12:28 UTC, FrankeLukas commented
Added a comment as requested on Slack.

2021-02-10 12:43 UTC, krusche approved these changes

2021-02-10 12:44 UTC, merged