[Feature] Do not allow 0 points for a quiz
ls1intum/Artemis pull request #2916
Opened 2021-02-22 19:05 UTC by derLalla

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [ ] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [ ] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [ ] Server: I implemented the changes with a good performance and prevented too many database calls
- [ ] Server: I documented the Java code using JavaDoc style.
- [ ] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [ ] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [ ] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [ ] Client: I documented the TypeScript code using JSDoc style.
- [ ] Client: I added multiple screenshots/screencasts of my UI changes
- [ ] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

### Description

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Test Coverage

### Screenshots

2021-02-22 19:43 UTC, airelawaleria reviewed
![image](https://user-images.githubusercontent.com/64631786/108760864-7d004280-754e-11eb-9409-3c205b03e26d.png)
![image](https://user-images.githubusercontent.com/64631786/108761138-c6509200-754e-11eb-8c35-ed25fb4ee8f4.png)

I get this when saving a quiz with 1 exercise with 1 point and second exercise woth 0 points. But the save button in this case is still enabled and no errors are detected.

2021-02-22 19:52 UTC, JohannesWeiss reviewed
I observed the same behaviour as @airelawaleria. Additionally, only the first two questions get marked red with the error, but a third one (with 0 points) does not get that error. When using -1 instead of 0, the save button was disabled correctly.

2021-02-22 19:56 UTC, derLalla commented
> ![image](https://user-images.githubusercontent.com/64631786/108760864-7d004280-754e-11eb-9409-3c205b03e26d.png)
> ![image](https://user-images.githubusercontent.com/64631786/108761138-c6509200-754e-11eb-8c35-ed25fb4ee8f4.png)
> 
> I get this when saving a quiz with 1 exercise with 1 point and second exercise woth 0 points. But the save button in this case is still enabled and no errors are detected.

oh thanks! I have fixed that in the latest commit.

2021-02-22 20:28 UTC, FuchsDominik requested changes
Code looks good. Found a console log which was probably forgotten

2021-02-22 20:28 UTC, FuchsDominik commented on src/main/webapp/app/exercises/quiz/manage/quiz-exercise-detail.component.ts
> +            console.log('question.points', question.points);
Was this for debug purposes?

2021-02-22 21:09 UTC, stefanwaldhauser submitted a review, later dismissed
Looks Good except for the above-mentioned console log statement

2021-02-22 21:09 UTC, stefanwaldhauser commented on src/main/webapp/i18n/en/quizExercise.json
>                  "questionScore": "Question {{index}}: The points are invalid.",
```suggestion
                "questionScore": "Question {{index}}: At least one point per question required.",
```

2021-02-22 21:09 UTC, stefanwaldhauser commented on src/main/webapp/i18n/de/quizExercise.json
>                  "questionScore": "Frage {{index}}: Ungültige Punktzahl.",
```suggestion
                "questionScore": "Frage {{index}}: Mindestens einen Punkt pro Aufgabe erforderlich.",
```

2021-02-23 08:43 UTC, derLalla commented on src/main/webapp/app/exercises/quiz/manage/quiz-exercise-detail.component.ts
> +            console.log('question.points', question.points);
😅 thanks!

2021-02-23 09:06 UTC, FuchsDominik approved these changes
Approve regarding the code after Log got removed

2021-02-23 12:41 UTC, tiffca approved these changes
Tested successfully, can't set points < 0 and can only save if all points sum up to > 0 

Am I supposed to receive an error if I try to save the following: 
1 quiz 
- 1 MC quiz question with 2 points 
- 1 SA quiz question with 0 points 
throws error on save -> POST https://artemistest.ase.in.tum.de/api/quiz-exercises 400

![image](https://user-images.githubusercontent.com/63906424/108845029-33ab0400-75dd-11eb-9e2d-ddaf874c9768.png)

2021-02-23 12:44 UTC, airelawaleria approved these changes

2021-02-23 13:18 UTC, marvinchimeka approved these changes
works as expected

2021-02-23 13:22 UTC, simonzilker approved these changes

2021-02-23 13:39 UTC, stefanwaldhauser approved these changes
Reapprove

2021-02-23 13:43 UTC, JohannesWeiss approved these changes
Re-Approve as well.

2021-02-23 14:29 UTC, krusche approved these changes

2021-02-23 14:30 UTC, merged