[Chore] Improve Bamboo Bitbucket Jira Setup documentation
ls1intum/Artemis pull request #3048
Opened 2021-03-18 11:44 UTC by derLalla

### Description

This improves the documentation of setting up Jira in the Bamboo/Bitbucket local setup. Jira Core has become outdated and license keys for it are not available any more.

2021-03-18 12:04 UTC, nicolasruscher approved these changes
I have not tested it, but the text itself looks good to me, apart from the one GitHub annotation, but I do not think its a big problem :D

2021-03-22 21:37 UTC, SimonEntholzer requested changes
Looks good, found one possible improvement. :)

2021-03-22 21:37 UTC, SimonEntholzer commented on docs/dev/setup/bamboo-bitbucket-jira.rst
> +
Maybe add a step that makes sure that `xdg-utils` are installed. We found an issue that occured when the `xdg-open` command was not found.
```suggestion
3. Make sure that `xdg-utils` is installed before running the script. `xdg-utils <https://www.howtoinstall.me/ubuntu/18-04/xdg-utils/>`
```

2021-03-23 09:05 UTC, derLalla commented on docs/dev/setup/bamboo-bitbucket-jira.rst
> +   YET) and disabled application links between the 3 applications
```suggestion
   YET) and disabled application links between the 3 applications. Make sure that ``xdg-utils`` is installed before running the script. `xdg-utils <https://www.howtoinstall.me/ubuntu/18-04/xdg-utils/>`__
```

2021-03-23 09:07 UTC, derLalla commented on docs/dev/setup/bamboo-bitbucket-jira.rst
> +   YET) and disabled application links between the 3 applications. Make sure that ``xdg-utils`` is installed before running the script. `xdg-utils <https://www.howtoinstall.me/ubuntu/18-04/xdg-utils/
```suggestion
   YET) and disabled application links between the 3 applications. Make sure that `xdg-utils <https://www.howtoinstall.me/ubuntu/18-04/xdg-utils/>`__ is installed before running the script.
```

2021-03-23 10:26 UTC, nicolasruscher approved these changes
approving the new changes 👍

2021-03-23 10:27 UTC, SimonEntholzer approved these changes
Looks good now :+1:

2021-03-23 11:41 UTC, merged