[Follow-Up] to #2815: Hidden/private tests
ls1intum/Artemis pull request #3096
Opened 2021-03-29 18:57 UTC by b-fein

### Checklist
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Description
Follow-up to #2815

- SQL queries are now uppercase (I also reformatted the remaining ones in `ProgrammingExerciseRepository` for consistency and readability)
- Restrain width of dropdowns on ‘Configure Grading’ page (Is there a way to actually wrap the text content?)
![Screenshot_20210329_201834](https://user-images.githubusercontent.com/64250573/112883457-9c026f00-90ce-11eb-85d4-b8b14c1c1551.png)

### Steps for Testing
1. Open the ‘Configure Grading’ page and check that dropdowns are no longer cut off.

### Test Coverage
unchanged

2021-03-29 20:37 UTC, stefanwaldhauser submitted a review, later dismissed
Looks good :) Was initially confused by the XXX.id IS NULL but this seems to be the case because of the left join

2021-03-30 09:38 UTC, derLalla requested changes
it was working fine in the testing session. I have left some remarks in the code.

2021-03-30 09:38 UTC, derLalla commented on src/main/java/de/tum/in/www1/artemis/repository/ProgrammingExerciseRepository.java
> +            """)
to further increase the readability we often put each join into a new line

```suggestion
    @Query("""
            SELECT pe FROM ProgrammingExercise pe
            LEFT JOIN FETCH pe.templateParticipation tp
            LEFT JOIN FETCH pe.solutionParticipation sp
            LEFT JOIN FETCH tp.results tpr
            LEFT JOIN FETCH sp.results spr
            WHERE pe.course.id = :#{#courseId}
                AND (tpr.id = (SELECT MAX(id) FROM tp.results) OR tpr.id IS NULL)
                AND (spr.id = (SELECT MAX(id) FROM sp.results) OR spr.id IS NULL)
            """)
```

2021-03-30 09:38 UTC, derLalla commented on src/main/java/de/tum/in/www1/artemis/repository/ProgrammingExerciseRepository.java
> +            """)
```suggestion
    @Query("""
            SELECT pe FROM ProgrammingExercise pe
            WHERE pe.shortName IS NOT NULL AND (
                pe.id IN (
                    SELECT coursePe.id
                    FROM ProgrammingExercise coursePe
                    WHERE coursePe.course.instructorGroupName IN :groups
                        AND (coursePe.title LIKE %:partialTitle% OR coursePe.course.title LIKE %:partialCourseTitle%)
                ) OR pe.id IN (
                    SELECT examPe.id
                    FROM ProgrammingExercise examPe
                    WHERE examPe.exerciseGroup.exam.course.instructorGroupName IN :groups
                        AND (examPe.title LIKE %:partialTitle% OR examPe.exerciseGroup.exam.course.title LIKE %:partialCourseTitle%)
                )
            )
            """)
```

2021-03-31 13:27 UTC, krusche approved these changes

2021-03-31 13:27 UTC, merged