[markdown][pdf] drag/drop and copy/paste support for PDF files
ls1intum/Artemis pull request #3236
Opened 2021-04-18 12:52 UTC by Olimbia23

### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

Feature request: #2509

### Description
- added pdf into the accepted file extension.
- link generation for pdf with the corresponding file name.

### Steps for Testing

1. Log in to Artemis
2. Drag & Drop in any markdown editor component

### Screenshots

![demo](https://user-images.githubusercontent.com/51077603/115145846-00707880-a054-11eb-9ce4-365bd8be9e7d.gif)

### Issue
Issue with copy/paste of pdf files. 
The clipboard sees any file copy/pasted as `image.png` (instead of `file.pdf`) as reported [here](https://stackoverflow.com/questions/34508763/why-chrome-convert-the-image-data-to-image-png-mime-type-when-paste) and [here](https://ourcodeworld.com/articles/read/491/how-to-retrieve-images-from-the-clipboard-with-javascript-in-the-browser) and [here](https://stackoverflow.com/questions/58924013/javascript-paste-event-getting-file-name)
After my research I believe there is no way to fix this problem. However, I am very pleased for suggestions.

Ps. this issue occurs in Github Markdown editor as well.

2021-04-18 13:25 UTC, Strohgelaender commented on src/main/webapp/app/shared/markdown-editor/markdown-editor.component.ts
> +
```suggestion
                        let textToAdd = `[${file.name}](${res.path})\n`;
                        if (extension !== 'pdf') {
                            textToAdd = '!' + textToAdd ;
                        }

```

2021-04-18 15:00 UTC, Olimbia23 commented
@joschahenningsen sorry that I sneaked in for this task 🙈 I would like you to review it :)

2021-04-18 15:12 UTC, joschahenningsen approved these changes
Agree with @Strohgelaender s suggestion. Looks good other than that.

> The clipboard sees any file copy/pasted as image.png (instead of file.pdf)

You probably could get the mimetype somewhat hacky from the api but I wouldn't worry about it that much.

2021-04-18 16:18 UTC, joschahenningsen requested changes
Since this PR is from an external branch it's kind of hard to test.
Locally it seems like the markdown file API always sends the content type text/html which makes downloading/viewing the uploaded file impossible.
The endpoint `GET /files/markdown/{filename:.+}` might need to be updated.

Using `buildFileResponse` instead of `responseEntityForFilePath` could do the trick.

2021-04-18 17:15 UTC, Olimbia23 commented
@joschahenningsen thank you for pointing this out and for helping to fix the issue. Just pushed the fix.

2021-04-18 17:19 UTC, joschahenningsen approved these changes
Seems fine to me.

2021-04-23 08:11 UTC, Strohgelaender approved these changes
Tested locally, works as expected.

2021-04-25 23:47 UTC, closed without merging

2021-04-26 04:12 UTC, joschahenningsen commented
Hi @Olimbia23, any reason you closed this?/ Do you want me to reopen it from a internal branch?

2021-04-26 05:55 UTC, Olimbia23 commented
> Hi @Olimbia23, any reason you closed this?/ Do you want me to reopen it from a internal branch?

Hi @joschahenningsen, I closed it so I can reopen from an internal branch and see in bamboo why client-test fails.