Update Privacy Statement and Imprint
ls1intum/Artemis pull request #3253
Opened 2021-04-19 21:48 UTC by krusche

* According to data privacy experts, we should improve the privacy statement and describe the legal basis of data collection in Artemis better based on DSGVO.
* The imprint statement is now part of Artemis. Linking to an external source is not necessary any more. It can be changed by providing a custom html file in the public folder (like the privacy statement)
* The `Accept terms` option is now deactivate by default because acceptance is not necessary in terms of education and examination (as this is the duty of the corresponding university and it does not really makes senes that students can decline to it): Artemis admins who absolute want their users to accept terms can still opt-in in the yml files.

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Steps for Testing
1. Read the privacy statement
2. Read the imprint
3. Try to adapt both files in the public folder
4. Log in to Artemis

Code reviews are highly appreciated as well.

2021-04-20 07:38 UTC, maximilianbergmann requested changes
There is a typo in the privacy statement "Die Rechtsgrundlage für die Verarbeitun".

In the "Zweck" part were grammatic faults - in my opinion it should be:
"Die Rechtsgrundlage für die Verarbeitung Ihrer Daten ergibt sich, soweit nichts anderes angegeben ist, aus Art. 6 Abs. 1 Lit. c (Rechtliche Verpflichtung) der Datenschutz Grundverordnung (DSGVO). Darüberhinaus gelten Art. 61 Bayerisches Hochschulgesetz (BayHschG) sowie die Allgemeine Prüfungs- und Studienordnung (APSO) der TUM und die Bayerische Fernprüfungserprobungsverordnung (BayFEV). Demnach ist es uns erlaubt, die zur Erfüllung einer uns obliegenden Aufgabe erforderlichen Daten zu verarbeiten."

The rest looks good :-)

2021-04-20 08:17 UTC, willergeorg requested changes
A sentence @maximilianbergmann mentioned is in the privacy statement as well and needs to be adapted:

> **Darüber hinaus** gelten Art. 61 Bayerisches Hochschulgesetz (BayHschG) sowie die **die** Allgemeine Prüfungs- und Studienordnung (APSO) der TUM und **die** Bayerische Fernprüfungserprobungsverordnung (BayFEV).

2021-04-20 09:09 UTC, krusche commented
Thanks, I fixed the issues and also removed a paragraph that was not necessary and was found in the review of the data privacy expert. If there are no more issues, I think we are good to go 👍

2021-04-20 10:32 UTC, FrankeLukas approved these changes
Lgtm.

2021-04-20 11:29 UTC, KiraNickel requested changes
A few more typos in the privacy statement:
In the first paragraph it's still Verarbeitun instead of Verarbeitung.
Privatssphäre -> Privatsphäre. im Rahme -> im Rahmen. im universitäten Umfeld -> im universitären Umfeld.

The rest looks good to me 👍

2021-04-20 13:49 UTC, katjanakosic requested changes
Looked over it with @ArtemTsurikov. Requested changes: Paragraph 1 Line 3 "im Rahmen", P1L3 "Verarbeitun -> Verarbeitung", P2L1 "universitäten -> universitären". Rest looks fine

2021-04-20 13:49 UTC, ArtemTsurikov requested changes
Looked trough it with @katjanakosic. See her change requests

2021-04-20 14:02 UTC, krusche commented
Thanks, I fixed the mention typos.

2021-04-20 14:42 UTC, KiraNickel requested changes
Found one last typo 😬 
sowie die dem Allgemeine Prüfungs- ...
"dem" needs to go, everything else looks good now

2021-04-20 15:19 UTC, MDK5 requested changes

2021-04-20 15:19 UTC, MDK5 commented on src/main/resources/public/content/privacy_statement.html
> +    (HTTPS mit sicherem Zeritifkat der TUM, TLS 1.3, Strict Transport Security, Forward Secrecy, Same Site Cookie Schutz, etc.) um die Privatsphäre der Nutzer von Artemis bestmöglich zu
typo here: etc. should not be preceeded by a ,

2021-04-20 15:19 UTC, MDK5 commented on src/main/resources/public/content/privacy_statement.html
> +    Die von Ihnen im Rahmen des Besuchs unseres Webauftritts übermittelten personenbezogenen Daten werden daher in unserem Auftrag durch das LRZ verarbeitet:
An uninformed reader might not understand what LRZ stands for, a link or explaination would be helpful

2021-04-20 17:20 UTC, NicolasUllmann requested changes
Found 2 typos in the privacy statement as well:
"HTTPS mit sicherem Zeritifkat der TUM" -> "HTTPS mit sicherem Zertifikat der TUM"
"Darüberhinaus" -> "Darüber hinaus"

2021-04-20 18:43 UTC, krusche commented
Thanks again, I fixed the remaining typos. Let me know if you find even more 👍

2021-04-20 19:41 UTC, KiraNickel requested changes
... und das Bayerische Fernprüfungserprobungsverordnung (BayFEV).
das -> die 
This really is the last one I found 😅 🙈

2021-04-20 20:41 UTC, krusche commented
> ... und das Bayerische Fernprüfungserprobungsverordnung (BayFEV).
> das -> die
> This really is the last one I found 😅 🙈

thanks, fixed.

2021-04-20 20:50 UTC, MDK5 approved these changes
Tested locally, works as expected; code and text also look good to me.

2021-04-20 22:04 UTC, KiraNickel approved these changes

2021-04-21 09:11 UTC, cremertim approved these changes

2021-04-21 14:23 UTC, merged