Bugfix/programming exercise update/checkout repository of sample solution
ls1intum/Artemis pull request #3272
Opened 2021-04-22 18:27 UTC by tobiasjungmann

### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context
When using the Haskell template for generating a programming exercise, the option "Checkout repository of sample solution" should be checked automatically since the Haskell testing framework relies on it. Issue: #3094

### Steps for Testing
1.	Generate a new programming exercise
2.	Select Haskell as a programming language
3.	The option "Checkout repository of sample solution" is checked.

### Screenshots
![image](https://user-images.githubusercontent.com/32565407/115766648-7eac8200-a3a8-11eb-81f6-89acee7f6b58.png)

2021-04-22 19:29 UTC, willergeorg approved these changes
Tested on TS1. Option was checked.

2021-04-22 20:17 UTC, NicolasUllmann approved these changes
Tested on Server 1. Worked as expected.

2021-04-22 20:21 UTC, canyelten approved these changes
Tested on ts1. The option was checked as expected.

2021-04-22 20:35 UTC, katjanakosic approved these changes
Worked as expected :)

2021-04-22 20:57 UTC, sinangunduz requested changes
tested on ts3, the option was not checked.

2021-04-23 08:41 UTC, real-dmy approved these changes
Tested on TS1. Option was checked.

2021-04-23 08:51 UTC, lschlesinger requested changes
**EDIT:** I think, what I describe below is intended behavior, as one should not change the selection on `checkoutSolutionRepository` after having created the exam - It cannot be reverted anyways, I guess... 
But I would find it useful, to see the checked option in a read-only mode on the edit-page...(otherwise the information is lost, that this option was checked during exercise creation, if I am correct). But that could be out of scope for the PR :) So I guess, the PR can be approved.

Original Comment:

Tested on TS3: When generating the programming exercise for the first time with haskell as selected language, it works as expected and the option is checked. Although, after saving and reenter the edit mode (by click on edit), these selection is not present? The option does not exist and is not checked, as can be seen in the screenshot.
<img width="986" alt="Bildschirmfoto 2021-04-23 um 10 47 56" src="https://user-images.githubusercontent.com/41366522/115846008-c28f9d80-a421-11eb-878f-bdb007155582.png">

2021-04-23 09:32 UTC, lschlesinger approved these changes
**EDIT:** I think, what I describe below is intended behavior, as one should not change the selection on `checkoutSolutionRepository` after having created the exam - It cannot be reverted anyways, I guess... 
But I would find it useful, to see the checked option in a read-only mode on the edit-page...(otherwise the information is lost, that this option was checked during exercise creation, if I am correct). But that could be out of scope for the PR :) So I guess, the PR can be approved.

Original Comment:

Tested on TS3: When generating the programming exercise for the first time with haskell as selected language, it works as expected and the option is checked. Although, after saving and reenter the edit mode (by click on edit), these selection is not present? The option does not exist and is not checked, as can be seen in the screenshot.
<img width="986" alt="Bildschirmfoto 2021-04-23 um 10 47 56" src="https://user-images.githubusercontent.com/41366522/115846008-c28f9d80-a421-11eb-878f-bdb007155582.png">

2021-04-23 12:21 UTC, cremertim approved these changes
Tested on ts1. Works as expected

2021-04-23 13:42 UTC, joschahenningsen approved these changes
Worked nicely for me

2021-04-23 14:42 UTC, merged

2021-04-23 14:43 UTC, ArtemTsurikov reviewed
Works as expected on TS1

2021-04-24 09:15 UTC, derLalla commented on src/main/webapp/app/entities/programming-exercise.model.ts
> +        this.checkoutSolutionRepository = true; // default value
This breaks the creation of all other programming language templates.