Show Build success if no tests are executed
ls1intum/Artemis pull request #3293
Opened 2021-04-25 15:51 UTC by JohannesStoehr

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [ ] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [ ] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [ ] Server: I implemented the changes with a good performance and prevented too many database calls
- [ ] Server: I documented the Java code using JavaDoc style.
- [ ] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [ ] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [ ] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [ ] Client: I documented the TypeScript code using JSDoc style.
- [ ] Client: I added multiple screenshots/screencasts of my UI changes
- [ ] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

During an exam often no tests are executed. "0 of 0 tests passed" id not a helpful message in an exam. This should have a better message.

### Description

If no tests are present, but the build succeeded, a new message is shown, that explains this.

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Test Coverage

### Screenshots

2021-04-26 05:58 UTC, ivanchimeno commented on src/main/webapp/app/exercises/shared/result/result.component.ts
> +            this.result!.resultString === '0 of 0 passed'
```suggestion
            this.result?.resultString? === '0 of 0 passed'
```

2021-04-26 05:59 UTC, ivanchimeno approved these changes
Code looks good, I just added a small optional comment to simplify the code

2021-04-26 09:07 UTC, FuchsDominik approved these changes
Code looks good :)

2021-04-26 17:53 UTC, KiraNickel submitted a review, later dismissed
Tested on ts3. Old and new functionality work as expected 👍🏼

2021-04-26 17:55 UTC, NicolasUllmann approved these changes
Tested on server 3. Worked as expected.

2021-04-26 19:01 UTC, maximilianbergmann approved these changes
Tested. Works

2021-04-26 20:16 UTC, niclasschuemann submitted a review, later dismissed

2021-04-27 01:44 UTC, iozbeyli approved these changes

2021-04-27 01:44 UTC, iozbeyli submitted a review, later dismissed
Code looks good.

2021-04-27 07:05 UTC, nicolasruscher submitted a review, later dismissed

2021-04-27 08:18 UTC, katjanakosic submitted a review, later dismissed
Tested on TS1. Works as expected :)

2021-04-27 09:39 UTC, cremertim approved these changes
works on ts3

2021-04-27 15:22 UTC, FrankeLukas reviewed
Code changes lgtm otherwise.

2021-04-27 15:22 UTC, FrankeLukas commented on src/main/webapp/i18n/en/editor.json
> +            "buildSuccessful": "Build Successful, no Tests Executed",
We should probably be consistent with capitalization here, so either `No` or perhaps
```suggestion
            "buildSuccessful": "Build Successful, no tests executed",
```
?

2021-04-27 15:22 UTC, FrankeLukas commented on src/main/webapp/app/exercises/shared/result/result.component.html
> +                    {{ round(result.score) }} %,
```suggestion
                    {{ round(result.score) }}%,
```

2021-04-27 16:28 UTC, KiraNickel requested changes
Tested on ts3. Old functionality works ~~but for exercises without tests run before the due date, 0 of 0 tests passed with red X is shown again for compiling submissions. 
Also it seems that when you submit in the Online Editor, Building and Testing... is shown indefinitely unless you go back to the overview of the exercise. (Not sure if this is connected to this PR but it didn't happen for the last version of this PR I tested)~~

2021-04-27 16:55 UTC, KiraNickel submitted a review, later dismissed
Tested on ts3. Works as expected.
(Previously there seems to have been something wrong with the deploy)

2021-04-28 07:44 UTC, ivanchimeno submitted a review, later dismissed
Re-approving

2021-04-28 08:59 UTC, NicolasUllmann approved these changes
Tested on Server 1. Re-approving.

2021-04-28 09:04 UTC, willergeorg approved these changes
Tested on TS1. Worked for me.

2021-04-28 21:11 UTC, cremertim submitted a review, later dismissed
reaproving after another working test on ts3

2021-04-29 17:52 UTC, merged