Don't mind me
ls1intum/Artemis pull request #3313
Opened 2021-04-28 11:49 UTC by ivanchimeno

I need to use a draft PR to test something out with the GitHub actions

2021-04-29 10:12 UTC, lschlesinger approved these changes
I did not manage to also include students participation in the exam. But exercises of all types.
Archiving and downloading of zip folder worked as expected and all the material was inlcuded! 👍

2021-04-29 11:16 UTC, florian-glombik requested changes
In general, the export worked for me, the generated zip file looked fine to me.
[florianGlombikTestkurs-FlorianGlombikTestkurs-20210429-124634.zip](https://github.com/ls1intum/Artemis/files/6398144/florianGlombikTestkurs-FlorianGlombikTestkurs-20210429-124634.zip)


Codewise I am not quite happy with the usage of var. I might have missed something - as far as I know, var should primarily be used to hide long declarations by wrapper classes, but, in my opinion, if we know that we have a String we should also declare it as a String to increase the readability of the code.

(https://github.com/ls1intum/Artemis/files/6398036/florianGlombikTestkurs-FlorianGlombikTestkurs-20210429-124634.zip)

The bug described in https://github.com/ls1intum/Artemis/pull/3257 is not fixed, deleting a student repo during archiving the course didn't cause trouble, but deleting template/solution repositories did.
![image](https://user-images.githubusercontent.com/63976129/116539890-bc019a00-a8e9-11eb-9ae2-a13e22ea83bd.png)

2021-04-29 11:18 UTC, florian-glombik commented on src/main/java/de/tum/in/www1/artemis/service/CourseExamExportService.java
> +        var cleanCourseDirName = fileService.removeIllegalCharacters(courseDirName);
```suggestion
        String cleanCourseDirName = fileService.removeIllegalCharacters(courseDirName);
```

2021-04-29 11:18 UTC, florian-glombik commented on src/main/java/de/tum/in/www1/artemis/service/CourseExamExportService.java
> +        var courseDirPath = Path.of("./exports", cleanCourseDirName, cleanCourseDirName);
```suggestion
        Path courseDirPath = Path.of("./exports", cleanCourseDirName, cleanCourseDirName);
```

2021-04-29 11:22 UTC, ivanchimeno commented
> In general, the export worked for me, the generated zip file looked fine to me.
> [florianGlombikTestkurs-FlorianGlombikTestkurs-20210429-124634.zip]
> 
> Codewise I am not quite happy with the usage of var. I might have missed something - as far as I know, var should primarily be used to hide long declarations by wrapper classes, but, in my opinion, if we know that we have a String we should also declare it as a String to increase the readability of the code.
> 
> (https://github.com/ls1intum/Artemis/files/6398036/florianGlombikTestkurs-FlorianGlombikTestkurs-20210429-124634.zip)
> 
> The bug described in #3257 is not fixed, deleting a student repo during archiving the course didn't cause trouble, but deleting template/solution repositories did.
> ![image](https://user-images.githubusercontent.com/63976129/116539890-bc019a00-a8e9-11eb-9ae2-a13e22ea83bd.png)

What is posted is expected behavior: When you archive a course or an exam, it can happen that repositories are not available. In your case, the template repository is missing from the VCS. This is not an error and archiving should still continue. In this case be simply notify the user just in case he/she missed it.

In regard to `var`, it's been used quite extensively in Artemis. I'm also not sure why but since it's used everywhere, I also use it to shorten the lines.

2021-04-29 11:23 UTC, florian-glombik commented on src/test/java/de/tum/in/www1/artemis/programmingexercise/ProgrammingExerciseTestService.java
> +        var repository = gitService.getExistingCheckedOutRepositoryByLocalPath(localRepository.localRepoFile.toPath(), null);
```suggestion
        Repository repository = gitService.getExistingCheckedOutRepositoryByLocalPath(localRepository.localRepoFile.toPath(), null);
```

2021-04-29 12:20 UTC, lschlesinger submitted a review, later dismissed
https://github.com/ls1intum/Artemis/pull/3313#pullrequestreview-648032546

2021-04-29 13:57 UTC, florian-glombik commented on src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java
> +            var pathToZippedExercise = Path.of(pathToStoreZipFile, cleanFilename);
```suggestion
            String cleanFilename = fileService.removeIllegalCharacters(filename);
            Path pathToZippedExercise = Path.of(pathToStoreZipFile, cleanFilename);
```

2021-04-29 13:58 UTC, florian-glombik commented on src/test/java/de/tum/in/www1/artemis/programmingexercise/ProgrammingExerciseTestService.java
> +        var zip = exportInstructorRepository("TEMPLATE", exerciseRepo, HttpStatus.OK);
```suggestion
        String zip = exportInstructorRepository("TEMPLATE", exerciseRepo, HttpStatus.OK);
```

2021-04-29 13:59 UTC, florian-glombik commented on src/test/java/de/tum/in/www1/artemis/programmingexercise/ProgrammingExerciseTestService.java
> +        // Createa a programming exercise with solution, template, and tests participations
```suggestion
        // Create a a programming exercise with solution, template, and tests participations
```

2021-04-29 14:00 UTC, florian-glombik commented on src/test/java/de/tum/in/www1/artemis/programmingexercise/ProgrammingExerciseTestService.java
> +        var templateRepository = gitService.getExistingCheckedOutRepositoryByLocalPath(exerciseRepo.localRepoFile.toPath(), null);
```suggestion
        Repository templateRepository = gitService.getExistingCheckedOutRepositoryByLocalPath(exerciseRepo.localRepoFile.toPath(), null);
```

2021-04-29 14:00 UTC, florian-glombik commented on src/test/java/de/tum/in/www1/artemis/programmingexercise/ProgrammingExerciseTestService.java
> +        var solutionRepository = gitService.getExistingCheckedOutRepositoryByLocalPath(solutionRepo.localRepoFile.toPath(), null);
```suggestion
        Repository solutionRepository = gitService.getExistingCheckedOutRepositoryByLocalPath(solutionRepo.localRepoFile.toPath(), null);
```

2021-04-29 14:00 UTC, florian-glombik commented on src/test/java/de/tum/in/www1/artemis/programmingexercise/ProgrammingExerciseTestService.java
> +        var testsRepository = gitService.getExistingCheckedOutRepositoryByLocalPath(testRepo.localRepoFile.toPath(), null);
```suggestion
        Repository testsRepository = gitService.getExistingCheckedOutRepositoryByLocalPath(testRepo.localRepoFile.toPath(), null);
```

2021-04-29 14:57 UTC, lschlesinger approved these changes
https://github.com/ls1intum/Artemis/pull/3313#pullrequestreview-648032546

2021-04-29 16:33 UTC, florian-glombik approved these changes
Tested on ts1 https://github.com/ls1intum/Artemis/pull/3313#pullrequestreview-648082406 and works as expected https://github.com/ls1intum/Artemis/pull/3313#issuecomment-829147898 

After using the actual types instead of var the code does also look good to me

2021-04-30 08:00 UTC, krusche approved these changes
Code looks good 👍

2021-04-30 08:04 UTC, merged