[Feature] Grading System create/edit page
ls1intum/Artemis pull request #3342
Opened 2021-05-02 15:25 UTC by ivohashamov

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [ ] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [ ] Client: I documented the TypeScript code using JSDoc style.
- [ ] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

The instructors wishing to use the grading system in their courses/exams need to have a page where they could create and edit it.

### Description

I've created the grading system create/edit page and made it accessible via a 'Grading System' button on the course-detail and exam-detail pages.

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Test Coverage

### Screenshots

2021-05-03 15:49 UTC, rs-maker submitted a review, later dismissed
Tested on TS2. I tested a bunch of different grading scales and could not break anything so it looks good to me. The only thing i would note is that adding the Grading Scale Button to the Exam Management Page could be handy. 
![rview](https://user-images.githubusercontent.com/56715566/116899310-b2549b00-ac37-11eb-8fee-a5461fa93f25.png)

2021-05-03 16:10 UTC, willergeorg requested changes
Tested on TS2. Worked good in general. The only things I noticed is that sometimes if I generate a default grading scale, an error occurs at the top of the page saying "Not found" while the default setting is loaded (see screenshot below) . Additionally, if I delete the grading scale and confirm the deletion, the scale is still displayed, even though it has been deleted. This is fixed by reloading the page, but generates some confusion in the first moment.

![image5](https://user-images.githubusercontent.com/80622272/116901947-d4035180-ac3a-11eb-81f5-84c60020dd2f.PNG)

2021-05-03 16:22 UTC, NicolasUllmann requested changes
Tested on Server 3. I ran into the same problem as mentioned above by Georg, but I don't know if this is something in connection with this PR or something new. Other than that everything worked as expected.

2021-05-03 19:24 UTC, PatZintel submitted a review, later dismissed
changes look as described on ts1, didnt manage to break anything even though i tried

2021-05-03 20:21 UTC, lschlesinger requested changes
Tested on TS1. When I entered the grading system detail page for an exam, the `?` icon was not present, but the place where it should be was still clickable (see picture). Once I've clicked on `Default Grading Scale` the icon appeared and worked as expected. I am not sure what the intended behaviour should be, but I would assume the button to be always be there.

The "plausibility check" before saving a grading scale works as described 👍 ! Maybe, you could add the link to open the "help-modal" in the error message as well or refer to the icon in the text as this would immediately hint towards the next steps when getting this error, i.e., checking the rules again - but that would be a nice to have I guess :).

For the icon bug I screenshot and my inline code comment at the line which caused unlimited console error (in my case), I would request changes.
<img width="1264" alt="Bildschirmfoto 2021-05-03 um 21 58 43" src="https://user-images.githubusercontent.com/41366522/116928385-47b65600-ac5d-11eb-8ccf-b51d668881de.png">

2021-05-04 01:53 UTC, iozbeyli requested changes

2021-05-04 01:53 UTC, iozbeyli commented on src/main/webapp/app/grading-system/grading-system.component.html
> +        <div style="display: flex">
Prefer classes over inline styles like d-flex here instead of style

2021-05-04 01:53 UTC, iozbeyli commented on src/main/webapp/app/grading-system/grading-system.component.ts
> +        };
This function looks a bit strange with many objects inside, a function that generates them from an array of values and rules might be better. But this is just an opinion.

2021-05-04 01:53 UTC, iozbeyli commented on src/test/javascript/spec/component/grading-system/grading-system.component.spec.ts
> +        const gradingSystemUpdateForExabStub = sinon.stub(gradingSystemService, 'updateGradingScaleForExam').returns(
It says exab instead of exam

2021-05-04 01:53 UTC, iozbeyli commented on src/test/javascript/spec/component/grading-system/grading-system.component.spec.ts
> +        expect(comp.existingGradingScale).to.equal(true);
How about the effects of data that is coming from the gradingSystemService what happens to it?

2021-05-04 01:53 UTC, iozbeyli commented on src/test/javascript/spec/service/grading-system.service.spec.ts
> +    });
Please follow the new client documentation for service tests

2021-05-04 01:53 UTC, iozbeyli commented on src/test/javascript/spec/service/grading-system.service.spec.ts
> +        service.findGradingScaleForExam(123, 456).pipe(take(1)).subscribe();
If service method is returning something you should test it, also again please follow the client documentation for all of these service tests.

2021-05-04 13:12 UTC, ArtemTsurikov submitted a review, later dismissed
I tested it on TS1. Everything worked fine!

2021-05-05 06:35 UTC, maximilianbergmann submitted a review, later dismissed
Tested on TS3. Works as expected

2021-05-05 08:39 UTC, cremertim approved these changes
tested on ts 1, worked out fine for me

2021-05-05 14:29 UTC, canyelten submitted a review, later dismissed
Tested on TS1. Works as expected.

2021-05-05 16:30 UTC, lschlesinger requested changes
I would say that if you add grading steps without entering the "grade name", the list of which one would choose the "First Passing Grade" should not append with empty entries, as seen in the screenshot. I am not sure if this is very realistic, but when someone is checking out the page, making him/herself familiar with the controls without understanding the concept yet, one would stumble upon the the "ghost list" when trying to select a first passing grade without providing names to the steps first - so I guess it's better to not append it with empty entries?
![image](https://user-images.githubusercontent.com/41366522/117175923-a13e9200-adcf-11eb-88c2-2474f1928fd2.png)

2021-05-05 16:37 UTC, ivohashamov commented
@lschlesinger The list is initially empty because the added grade steps have no name yet. If you were to add a name inside the bonus points/grade name column it will appear in the list for the passing grade. I could add a default name for all grade steps, but I don't think that makes much of a difference. The instructors will most likely create the entire grading scale with all the grade steps before selecting the passing grade anyway. The opposite doesn't make much sense to me.

2021-05-05 16:54 UTC, lschlesinger commented
> The list is initially empty because the added grade steps have no name yet. If you were to add a name inside the bonus points/grade name column it will appear in the list for the passing grade. I could add a default name for all grade steps, but I don't think that makes much of a difference. The instructors will most likely create the entire grading scale with all the grade steps before selecting the passing grade anyway. The opposite doesn't make much sense to me.

Yes I see and I agree that default names would not make sense. As I said, it is maybe not too realistic to create steps without names and then check the drop down - but I just did when try to familiarize myself with the concept. So assume one would do that, it is irritating that you see the list with empty entries. In my option, a solution to avoid this would be to filter the list used in the dropdown for non-empty entires. In the scenario described, the instructor would then just simply _not_ see _any_ entry in the dropdown as there is nothing to choose from without providing names in the first place.

2021-05-05 17:04 UTC, lschlesinger commented
A question: Is there a reason why "Bonus Points" as third column name is chosen as default when entering the page (first picture)? The Grade Type dropdown did not have any default selection, so when I wanted to change the type I ended up in this situation (second picture): "Grade" seemed to be selected (with the check, but was not prefilled when I entered), but the table column name indicates, that the bonus type is selected.
I would either pre-select type "Grade" (as is lower bound inclusive) and adapt the default column name accordingly to "Grade Name" or hide the name of the third column when the initial grade type is not prefilled.
On Enter:
![image](https://user-images.githubusercontent.com/41366522/117179919-f2508500-add3-11eb-83ef-5c83cb37a168.png)
When I click on the grade type drop down the first time:
![image](https://user-images.githubusercontent.com/41366522/117179598-938b0b80-add3-11eb-89cf-8d7b0ddff99e.png)

2021-05-05 21:31 UTC, ivohashamov commented
@lschlesinger I've integrated the feedback. As for the general questions: The first passing grade was mostly for the "Grade" grading scale, the differentiation was added later, so I agree that it doesn't make much sense to have it displayed when "Bonus" is selected. I shouldn't be displayed anymore after 9030a08. I guess I left initially because there would almost always exist a grade step where the bonus points are 0, so perhaps the first passing grade there would have been the first that grants bonus points.

Regarding the second question "Grade" grading scale means that the course or the exam will be given a normal grade. There are 2 cases - if the course is only graded on weekly assignments, it makes sense to have such a scale for the course. The exam case for this grade type is straightforward (you get your typical grading as in any written exam). For the "Bonus" type of a course grading scale, the idea would be to grant bonus points for the final exam if a student fulfills assignments throughout the semester. As for the exam "Bonus" grading scale, it's not a very common use case, but if you have a midterm that contributes to the final grade, it could grant bonus points as well.

2021-05-06 11:37 UTC, lschlesinger commented
> @lschlesinger I've integrated the feedback.

Nice, I tested your changes! I think it's much better the way you do it now 👍 
Final remark (sorry for that): when entering grade names (third column) for the type "Grade" and then changing to the type "Bonus", the column name changes as expected to "Bonus Points", but the values I've entered before, such as "A" and "B" (as grade names) were carried over. I think when changing the type, the values in the third column should be reset as the values "Grade Name" and "Bonus Points" do not depend one each other and "A" as Bonus Points" entry does not make sense. As of now, I have to delete all values that were carried over before I can enter what I intended to enter, e.g. "5" bonus points (instead of "A") and the other way around.

2021-05-06 16:57 UTC, ArtemTsurikov approved these changes
Everything works as expected on TS1.

2021-05-06 17:16 UTC, iozbeyli requested changes
I added a comment about the service tests. I added for one but it is valid for each of them.

2021-05-06 17:16 UTC, iozbeyli commented on src/test/javascript/spec/service/grading-system.service.spec.ts
> +    });
Please follow client documentation for service tests. async here does nothing for example.

2021-05-07 07:04 UTC, lschlesinger requested changes
I have a problem now: Grade steps are reordered after saving (see video)

https://user-images.githubusercontent.com/41366522/117409721-ca673b80-af11-11eb-886b-5648b2a7baf0.mov

Additionally, I now that I only remarked that grade step and bonus points should not be taken over when changing the type but in fact, bonus and grade are should not be coupled at all in my opinion -> also MIN and MAX steps will most probably not depend on each other. 
From an instructor point of view, I would find it most user friendly and intuitive if the entered values are preserved in a way that when I switch back and forth between types, I only see those values that I've entered (and saved) for that exact type. 
As of now, when I save a valid grading scale (for type grade) switch to bonus grade (do nothing, or anything), go back to grade scale, I do _not_ see my previously saved scale, but I would expect to do so. As far as I see, you can only see the saved scale when reentering the page.

2021-05-07 07:48 UTC, ivohashamov commented
> I have a problem now: Grade steps are reordered after saving (see video)
> 
>  grading.mov 
> Additionally, I now that I only remarked that grade step and bonus points should not be taken over when changing the type but in fact, bonus and grade are should not be coupled at all in my opinion -> also MIN and MAX steps will most probably not depend on each other.
> From an instructor point of view, I would find it most user friendly and intuitive if the entered values are preserved in a way that when I switch back and forth between types, I only see those values that I've entered (and saved) for that exact type.
> As of now, when I save a valid grading scale (for type grade) switch to bonus grade (do nothing, or anything), go back to grade scale, I do _not_ see my previously saved scale, but I would expect to do so. As far as I see, you can only see the saved scale when reentering the page.

Yes, reordering the grade steps is the intended functionality. When saved, they are always ordered by the min %, and I think that makes the most sense since you always have a good overview of the entire grading scale in a sequence. I don't think the changes you're proposing are necessary. There is always only one grading scale for the course or the exam. Meaning, if you intend on saving a grading scale for a course it will always either be of "Grade" type or "Bonus" type. In order to save 2 (or more) of them for a single course/exam, that would require quite significant changes on the server-side, which is definitely out of the scope for this PR. Also, I really don't believe, that if an instructor wishes to change a grading scale (the reason why he is on this page in the first place), and he switches to a bonus type, switching back would mean that the saved grading scale would be set once again. What if the instructor already adjusted some grade steps? Does that mean he would get all of his changes overridden? I agreed that deleting the names made sense since they are clearly different between the 2 grade types, but I feel like introducing any further functionality related to the changes in the grade steps, based on changes in the grade type would likely lead to more issues, because what should be persisted when changing the grade type, and what not is debatable and highly dependant on the specific scenario.

So, unless there are issues in the code quality, or the functionality is not working properly, I would address any further suggestions in a follow-up PR.

2021-05-07 08:05 UTC, lschlesinger reviewed
> So, unless there are issues in the code quality, or the functionality is not working properly, I would address any further suggestions in a follow-up PR.

Ok, thanks for clarification. The reordering is reasonable! I am not quite familiar with the gradings scale procedure obviously, I just tried to put myself in the position of an instructor and pointed out the things I found not intuitive. I did not know that is in intended to only have one type, as the possibility to switch between the types, create/edit and save them does not indicate the mentioned exclusiveness of grade types in my opinion. You are right, that this more related to the UI not to functionality and code quality, so you can dismiss my requested changes.

2021-05-07 11:06 UTC, willergeorg approved these changes
Tested on TS1. Worked for me, issues I mentioned me are fixed. Re-approve.

2021-05-07 14:21 UTC, krusche commented on src/main/webapp/app/app.module.ts
> +import { GradingSystemModule } from 'app/grading-system/grading-system.module';
I would suggest to lazy load this module

2021-05-07 14:23 UTC, krusche commented on src/main/webapp/app/entities/grade-step.model.ts
> +export class GradeStep {
please follow the implementation of other entity classes:
* implement BaseEntity
* make all attributes public
* if you cannot guarantee that the attributes are set, then please use the ? operator to make them optional

2021-05-07 15:35 UTC, cremertim approved these changes
Reaproved. Tested  on ts1, still works as intended

2021-05-07 15:38 UTC, lschlesinger approved these changes
Also tested described functionality on TS1, did not encounter any problems!

2021-05-07 16:38 UTC, nicolasruscher requested changes
Found a small mistake: 
If you go to the page and: 
- select a first passing grade
- switch from grade to bonus
- > know you can not select a first passing grade 
Should be a rather simple fix. Sadly I could not find any error message so I can't help with the origin of the error here :)

2021-05-07 16:40 UTC, ivohashamov commented
> Found a small mistake:
> If you go to the page and:
> 
> * select a first passing grade
> * switch from grade to bonus
> * > know you can not select a first passing grade
>   > Should be a rather simple fix. Sadly I could not find any error message so I can't help with the origin of the error here :)

That's the intended functionality. First passing grades are not relevant for the bonus grade type. That's why the menu gets hidden

2021-05-07 17:31 UTC, jamalxo approved these changes
Tested on TS1, everything works as expected and client side validation should be added in a later PR 👍

2021-05-07 17:35 UTC, merged