[Chore] Client test coverage improvement exercise scores
ls1intum/Artemis pull request #3382
Opened 2021-05-09 10:29 UTC by ivohashamov

### Checklist
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)

### Motivation and Context

[Client test coverage improvment](https://confluence.ase.in.tum.de/display/ArTEMiS/Client+Test+Coverage+Improvements)
### Description

I created a test class for the exercise-scores.component

### Test Coverage

2021-05-09 19:03 UTC, krusche commented on .idea/runConfigurations/Artemis__Server_.xml
> +    <option name="SHORTEN_COMMAND_LINE" value="ARGS_FILE" />
please revert this change!

2021-05-09 19:03 UTC, krusche commented on src/main/resources/config/application-dev.yml
> +        show-sql: true
please revert this change!

2021-05-09 19:04 UTC, krusche requested changes
revert the unrelated changes and have a look at the GitHub warnings on unused variables

2021-05-10 10:04 UTC, imstreetspirit submitted a review, later dismissed
tests looks good. there are complaints for unused variables, it could be removed

2021-05-10 12:43 UTC, FrankeLukas approved these changes
Lgtm otherwise. (Just remove the lines with unused variables.)

2021-05-10 12:43 UTC, FrankeLukas commented on src/test/javascript/spec/component/exercises/shared/exercise-scores.component.spec.ts
> +                exerciseService = TestBed.inject(ExerciseService);
Unused variable.

2021-05-10 12:43 UTC, FrankeLukas commented on src/test/javascript/spec/component/exercises/shared/exercise-scores.component.spec.ts
> +                accountService = TestBed.inject(AccountService);
Unused variable.

2021-05-10 12:43 UTC, FrankeLukas commented on src/test/javascript/spec/component/exercises/shared/exercise-scores.component.spec.ts
> +                profileService = TestBed.inject(ProfileService);
Unused variable.

2021-05-10 13:46 UTC, nicolasruscher submitted a review, later dismissed
Inspected the code, looks good! 👍

2021-05-11 17:34 UTC, merged