[Feature] Grading System - Student Exam Summary
ls1intum/Artemis pull request #3482
Opened 2021-05-24 20:31 UTC by ivohashamov

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [ ] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I documented the TypeScript code using JSDoc style.
- [ ] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

This PR integrates the grading system in the student exam summary page. Students are now able to see the grade they've achieved on the exam (respectively the bonus points they've gained if the exam grades are of type bonus). The bonus points information is also now hidden, as long as there are no exercises that give bonus points (which is almost always the case). 

### Description

I've added some conditions to already present columns in the exam points summary component.
Also, I've added an additional section that displays the grade/bonus points of the student.
In a follow-up, a link will be created to the grade key, so a student can see the scale and where he/she fits into it.

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Test Coverage

### Screenshots

2021-05-26 23:16 UTC, imstreetspirit submitted a review, later dismissed
tested on ts3, seems working as described. code looks good to me.

2021-05-27 22:18 UTC, KiraNickel approved these changes
Tested on ts3, everything works as described 👍🏼

2021-05-28 15:14 UTC, SimonEntholzer requested changes
Tested on TS3 and everything worked as intended, The code looks good as well. Just found two small things:

2021-05-28 15:14 UTC, SimonEntholzer commented on src/main/webapp/i18n/de/exam.json
> +                    "youAchievedWithBonus": "Du hast {{achievedPoints}} Punkte von möglichen {{normalPoints}} normalen Punkten und {{bonusPoints}} Bonuspunkten erreicht",
I would reformulate this: 
```suggestion
                    "youAchievedWithBonus": "Du hast {{achievedPoints}} Punkte von {{normalPoints}} möglichen Punkten, und {{bonusPoints}} Bonuspunkten erreicht.",
```

2021-05-28 15:14 UTC, SimonEntholzer commented on src/main/webapp/i18n/de/exam.json
> +                    "youAchieved": "Du hast {{achievedPoints}} Punkte von möglichen {{normalPoints}} normalen Punkten",
I would leave out the 'normal'
```suggestion
                    "youAchieved": "Du hast {{achievedPoints}} von möglichen {{normalPoints}} Punkten",
```

2021-05-28 15:20 UTC, KiraNickel submitted a review, later dismissed
Re-approve, tested again on ts3 :)

2021-05-28 15:25 UTC, SimonEntholzer approved these changes

2021-05-28 15:56 UTC, argertboja reviewed
Tested on TS3, everything works as expected 👍🏼

2021-05-28 16:52 UTC, merged