[Chore + Mini-Features] Metis exercise/lecture discussion section improvements
ls1intum/Artemis pull request #3565
Opened 2021-06-13 19:58 UTC by lschlesinger

### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [ ] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

The discussion section on exercise and lecture pages had some improper translations, such as "Postings" (in German and English), which I wanted to change. Thereby, I realized that many other styling issues should be resolved, the structure in general could be improved to a cleaner version and some mini-features missed. I decided to go for a "Chore+Mini-Features PR" 😄 

### Description

**Styling and Appearance**
- Change of colors, sizes
- as well as re-structuring of answers and posts

**Translation and labels**
- remove labels and tooltips where not necessary
- section name is changed to `Discussion`
- German translation for Post is `Beitrag`
- All Metis related translations were factored out in dedicated translation files

**Mini-Features**
- Input validation: it should not be possible to created or save (after edit) posts or answers without content
- Loading feedback: the save-button was changed to a button with spinner indication during loading time (It happened to me sometimes, that I got impatient when I did not receive any feedback of the loading process and clicked on save two times, which led to duplicated posts)

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Test Coverage

### Screenshots

2021-06-14 11:29 UTC, FuchsDominik reviewed
Code looks good, could not test yet since the build does not seem to start. I personally liked the color-wise distinction of the post and the background but new one is fine too :) Rest looks really good for what i saw in the screenshots

2021-06-14 19:02 UTC, MDK5 requested changes
Tested in testing session on ts1. The styling is a bit broken, if the problem statement is rather wide, the posting section gets moved to the bottom.
![grafik](https://user-images.githubusercontent.com/61357727/121928104-1b075b00-cd40-11eb-90c1-6bdbc19321a2.png)

2021-06-15 10:18 UTC, lschlesinger commented
> Tested in testing session on ts1. The styling is a bit broken, if the problem statement is rather wide, the posting section gets moved to the bottom.

Should be fixed with a4ce7a3

2021-06-15 10:20 UTC, lschlesinger commented on src/main/webapp/app/overview/postings/postings.component.ts
>          });
I updated the logic in 846b040, `isLoading` is now always set to false on completion (no matter if failed or succeeded)

2021-06-15 10:21 UTC, lschlesinger commented on src/main/webapp/app/overview/postings/postings.component.ts
>          });
and btw. the load-buttons that looked a bit odd (with too much space to the left) are fixed as well :)

2021-06-15 15:29 UTC, willergeorg approved these changes
Tested on TS2. Worked for me.

2021-06-15 15:48 UTC, NicolasUllmann submitted a review, later dismissed
Tested on TS1. Everything worked as expected.

2021-06-15 16:09 UTC, lschlesinger commented
I had to commit a fix for the overflow problem. If a UML diagram was rendered in the problem statement of a programming exercise and the screen size was decreased, the behavior of the discussion section was not as intended.
@Reviwers, please check out this scenario and report, if the section is moved below the problem statement as spans over the full page width.

2021-06-15 16:26 UTC, lschlesinger commented on src/main/webapp/app/exercises/programming/shared/instructions-render/extensions/programming-exercise-plant-uml.extension.ts
> +                        plantUmlSvg = plantUmlSvg.replace(`style="width`, `style="max-width:100%;width`);
@FrankeLukas hope this is an allowed fixed for the overflow problem on an exercise page with rendered uml model (as svg). It was not possibly for me to solve the problem without restricting the svg width to max of 100%.

2021-06-15 19:32 UTC, KiraNickel requested changes
Tested on ts3. For me, in both languages and both as student and instructor the text for most options is not displayed correctly (see screenshots)

English and German Section with no posts:
![grafik](https://user-images.githubusercontent.com/69356806/122111946-95a7a780-ce20-11eb-9481-c0e1ffc0e66b.png)

All other boxes in both languages, like answering/editing/deleting/adding new post.
![grafik](https://user-images.githubusercontent.com/69356806/122112321-f931d500-ce20-11eb-93bc-9233cbd72793.png)

2021-06-15 22:23 UTC, lschlesinger commented
> Tested on ts3. For me, in both languages and both as student and instructor the text for most options is not displayed correctly (see screenshots)
@KiraNickel that's most probably a caching issue. Could you please try to empty your browser cache and reload the page before testing it once again?

2021-06-16 13:51 UTC, ivanchimeno commented on src/main/webapp/i18n/en/instructorCourseDashboard.json
> +            "discussion": "Disucssions",
```suggestion
            "discussion": "Discussions",
```

2021-06-16 14:03 UTC, lschlesinger commented on src/main/webapp/i18n/en/instructorCourseDashboard.json
> +            "discussion": "Disucssions",
damn! solved 6627496

2021-06-16 14:04 UTC, MDK5 approved these changes
Tested in testing session on ts5, worked well

2021-06-16 15:26 UTC, FuchsDominik approved these changes
Couldn't find any missing translations or other problems during testing

2021-06-16 21:07 UTC, canyelten submitted a review, later dismissed
Tested on TS2, works as expected.

2021-06-16 22:48 UTC, KiraNickel submitted a review, later dismissed
Tested on ts3, works as expected 👍🏼  (sorry I forgot to clear the cache before)

2021-06-17 06:16 UTC, ivanchimeno submitted a review, later dismissed
Tested and works!

2021-06-17 08:43 UTC, ArtemTsurikov submitted a review, later dismissed
Tested on TS1, everything works.

2021-06-17 12:05 UTC, merged