[Refactor] Refactoring of the saving process in exercise-update-component
ls1intum/Artemis pull request #3574
Opened 2021-06-14 23:30 UTC by Olimbia23

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [ ] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [ ] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [ ] Server: I implemented the changes with a good performance and prevented too many database calls
- [ ] Server: I documented the Java code using JavaDoc style.
- [ ] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [ ] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [ ] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [ ] Client: I documented the TypeScript code using JSDoc style.
- [ ] Client: I added multiple screenshots/screencasts of my UI changes
- [ ] Client: I translated all the newly inserted strings into English and German using neutral, gender-inclusive language

### Motivation and Context

### Description

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Test Coverage

### Screenshots

2021-06-21 06:50 UTC, argertboja reviewed
I faced no issues while testing on TS1 👍🏼

2021-06-21 08:12 UTC, maximilianbergmann submitted a review, later dismissed
Tested on TS3. Works normal

2021-06-21 10:00 UTC, real-dmy approved these changes
Tested on TS1. No issues.

2021-06-21 10:42 UTC, joschahenningsen approved these changes
Changes look good, had no issues either :)

2021-06-21 20:56 UTC, coolchock approved these changes
tested on ts3, works as expected :+1:

2021-06-21 23:27 UTC, jhainzlschmid submitted a review, later dismissed
Tested on ts1

2021-06-22 08:03 UTC, jpbernius submitted a review, later dismissed

2021-06-23 05:11 UTC, sinangunduz approved these changes
tested on ts1, had no issues

2021-06-23 10:14 UTC, krusche commented
@Olimbia23 there is a merge conflict. Could you please resolve it and ask for re-approvals?

2021-06-23 10:42 UTC, ArtemTsurikov submitted a review, later dismissed
Tested on TS1, looks good!

2021-06-23 18:39 UTC, canyelten approved these changes
Tested on TS1, works as expected.

2021-06-23 19:10 UTC, katjanakosic submitted a review, later dismissed
Everything worked fine on ts2

2021-06-24 13:38 UTC, FrankeLukas commented on src/main/webapp/app/exercises/file-upload/manage/file-upload-exercise-update.component.ts
> +        return this.fileUploadExercise.id === undefined ? EditType.CREATE : EditType.UPDATE;
```suggestion
        return this.fileUploadExercise.id == undefined ? EditType.CREATE : EditType.UPDATE;
```

2021-06-24 13:38 UTC, FrankeLukas commented on src/test/javascript/spec/component/modeling-exercise/modeling-exercise-update.component.spec.ts
> -        expect(exampleSubmissionService.delete).toHaveBeenCalledWith(2);
This deletes the last usage of `exampleSubmissionService`, so the variable (and import) itself should also be removed I suppose?

2021-06-25 07:10 UTC, ivanchimeno submitted a review, later dismissed

2021-06-26 10:49 UTC, NicolasUllmann submitted a review, later dismissed
Tested on TS2. Everything worked as expected.

2021-06-27 00:41 UTC, imstreetspirit requested changes
tested on ts2. I created new modeling/text/file exercises and updated. it works. But I also tested for re-evaluation. So I submitted student solutions and assessed them. During the assessment I used grading instructions for feedback. After that I go back the exercise edit view, I change credit/maxCountUsage and delete one of them grading instruction in there, then I clicked save button. In this case, there should be exercise-update-warning popup, but it did not open the popup. Instead of, it automatically updated the exercise with grading instructions. This happens for each type of exercise. I can help if this explanation is not enough to describe the problem

2021-06-27 00:51 UTC, imstreetspirit commented on src/main/webapp/app/exercises/shared/exercise/exercise-utils.ts
> +        if (exercise.gradingInstructionFeedbackUsed && this.modalService.hasOpenModals()) {
maybe the problem is related with this check. In the current version, first I check `exercise.gradingInstructionFeedbackUsed` is true or not after that, invoke `this.popupService.checkExerciseBeforeUpdate`... this one decides whether the popup can be opened or not.. So, `this.modalService.hasOpenModals()` check should come after that... I will try on my local, and let you know...

2021-06-27 01:11 UTC, imstreetspirit commented on src/main/webapp/app/exercises/shared/exercise/exercise-utils.ts
> +        }
```suggestion
        if (exercise.gradingInstructionFeedbackUsed) {
            const popupRefObs = from(this.popupService.checkExerciseBeforeUpdate(exercise, this.backupExercise));
            
            if (this.modalService.hasOpenModals()) {
                const confirmedCase = popupRefObs.pipe(
                    mergeMap((ref) => (ref.componentInstance as ExerciseUpdateWarningComponent).confirmed.pipe(map(() => [false, prepareRequestOptions()]))),
                );
                const reEvaluatedCase = popupRefObs.pipe(
                    mergeMap((ref) =>
                        (ref.componentInstance as ExerciseUpdateWarningComponent).reEvaluated.pipe(map(() => [true, { deleteFeedback: ref.componentInstance.deleteFeedback }])),
                    ),
                );
                const canceledCase = popupRefObs.pipe(mergeMap((ref) => (ref.componentInstance as ExerciseUpdateWarningComponent).canceled));

                saveObservable = confirmedCase.pipe(mergeWith(reEvaluatedCase), takeUntil(canceledCase));
            }
        }
```

2021-06-27 01:12 UTC, imstreetspirit commented on src/main/webapp/app/exercises/shared/exercise/exercise-utils.ts
> +        }
tried it locally, it works

2021-06-27 09:00 UTC, cremertim submitted a review, later dismissed
worked on ts 1 as expected :) //despite the error mentioned by Merve

2021-06-27 12:37 UTC, Olimbia23 commented
Thank you @imstreetspirit. Now should work as expected.

2021-06-27 13:47 UTC, imstreetspirit approved these changes
tested on ts2 again. great job!! thanks for quick fix! reevaluation works properly again.

2021-06-27 15:33 UTC, willergeorg approved these changes
Tested on TS2. Worked good for me.

2021-06-27 17:13 UTC, NicolasUllmann approved these changes
Tested on TS3. Re-approve.

2021-06-27 19:44 UTC, merged