Feature/compass/enable all diagram types
ls1intum/Artemis pull request #3589
Opened 2021-06-17 19:15 UTC by iozbeyli

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [ ] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [ ] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [ ] Server: I implemented the changes with a good performance and prevented too many database calls
- [ ] Server: I documented the Java code using JavaDoc style.
- [ ] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [ ] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [ ] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [ ] Client: I documented the TypeScript code using JSDoc style.
- [ ] Client: I added multiple screenshots/screencasts of my UI changes
- [ ] Client: I translated all the newly inserted strings into English and German using neutral, gender-inclusive language

### Motivation and Context

### Description

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Test Coverage

### Screenshots

2021-06-18 22:14 UTC, SimonEntholzer requested changes
Just tested on TS3, and I don't think it works properly (maybe I made a mistake somewhere though, but I don't think so). When I assess submissions I do not get any automatic assessment suggestions. 
A second thing I noticed: When creating (or editing) a modeling exercise, and clicking the save button on the bottom, the page navigates to this example submission creation page. I'm not sure if that is intended. Or maybe it is? 
![image](https://user-images.githubusercontent.com/33342534/122619802-89765100-d091-11eb-8db8-54daae0ca926.png)

2021-06-18 23:42 UTC, iozbeyli commented
> Just tested on TS3, and I don't think it works properly (maybe I made a mistake somewhere though, but I don't think so). When I assess submissions I do not get any automatic assessment suggestions.
> A second thing I noticed: When creating (or editing) a modeling exercise, and clicking the save button on the bottom, the page navigates to this example submission creation page. I'm not sure if that is intended. Or maybe it is?
> ![image](https://user-images.githubusercontent.com/33342534/122619802-89765100-d091-11eb-8db8-54daae0ca926.png)

I checked it again it should be working. Example submission part is not part of this PR, it is already on develop.

2021-06-19 14:07 UTC, SimonEntholzer submitted a review, later dismissed
Tested again, now on TS1, it seems to work correctly now. (For all the modeling types I tried at least, which is 4, so it should be fine).
No idea what the issue was yesterday

2021-06-19 14:59 UTC, ga62suz reviewed
I assume the efficacy of the grading suggestions are out of the question, only the fact that auto-grading was suggested.

Tested on TS1, on all types of diagrams.

Results: All diagrams function correctly **if first grading was after due date.**
https://ibb.co/album/FgyNrM

If first submission was graded before due date, I couldn't find a way to get the auto grading to work.

Conclusion: Behavior as described.

2021-06-19 15:26 UTC, lschlesinger requested changes
-> first of all, great feature and good explanation of the testing process!

I tested on TS1 for all the different types.
I encountered this situation: for deployment diagrams
It exactly the same submission, but the feedback on the association (line between node 1 and component) was not suggested...

<img width="515" alt="Bildschirmfoto 2021-06-19 um 17 19 12" src="https://user-images.githubusercontent.com/41366522/122647057-a4dd6c80-d122-11eb-8641-4f4ba2b438d3.png">

<img width="621" alt="Bildschirmfoto 2021-06-19 um 17 19 25" src="https://user-images.githubusercontent.com/41366522/122647056-a3ac3f80-d122-11eb-9983-f9c241efadc4.png">


For the Flowchart Model, I had a similar situation where the feedback was not transferred correctly:
<img width="599" alt="Bildschirmfoto 2021-06-19 um 17 23 25" src="https://user-images.githubusercontent.com/41366522/122647185-3a78fc00-d123-11eb-88a4-d8bcb365446d.png">

<img width="555" alt="Bildschirmfoto 2021-06-19 um 17 23 15" src="https://user-images.githubusercontent.com/41366522/122647179-351bb180-d123-11eb-8565-f1469ab12498.png">

You can find all the exercises here: https://artemistest.ase.in.tum.de/course-management/477/exercises

2021-06-20 15:45 UTC, iozbeyli commented
> -> first of all, great feature and good explanation of the testing process!
> 
> I tested on TS1 for all the different types.
> I encountered this situation: for deployment diagrams
> It exactly the same submission, but the feedback on the association (line between node 1 and component) was not suggested...
> 
> <img alt="Bildschirmfoto 2021-06-19 um 17 19 12" width="515" src="https://user-images.githubusercontent.com/41366522/122647057-a4dd6c80-d122-11eb-8641-4f4ba2b438d3.png">
> 
> <img alt="Bildschirmfoto 2021-06-19 um 17 19 25" width="621" src="https://user-images.githubusercontent.com/41366522/122647056-a3ac3f80-d122-11eb-9983-f9c241efadc4.png">
> 
> For the Flowchart Model, I had a similar situation where the feedback was not transferred correctly:
> <img alt="Bildschirmfoto 2021-06-19 um 17 23 25" width="599" src="https://user-images.githubusercontent.com/41366522/122647185-3a78fc00-d123-11eb-88a4-d8bcb365446d.png">
> 
> <img alt="Bildschirmfoto 2021-06-19 um 17 23 15" width="555" src="https://user-images.githubusercontent.com/41366522/122647179-351bb180-d123-11eb-8565-f1469ab12498.png">
> 
> You can find all the exercises here: https://artemistest.ase.in.tum.de/course-management/477/exercises

@lschlesinger The flowchart issue happens because of something called confidence threshold in Compass. The two lines that are coming out of input output and going into decision are considered equal in Compass. If you give different scores to them in your first assessment, Compass cannot select one and does not give a suggestion.

2021-06-20 18:48 UTC, canyelten submitted a review, later dismissed
Tested on TS1, for all modelling types. Couldn't find any error.

2021-06-21 06:40 UTC, ivanchimeno commented on src/main/webapp/app/exercises/modeling/manage/modeling-exercise-update.component.ts
>          const semiAutomaticSupportPossible =
I think you missed the Codacy warning here

2021-06-21 06:42 UTC, ivanchimeno commented on src/main/java/de/tum/in/www1/artemis/service/compass/utils/SimilarityFunctions.java
> +public class SimilarityFunctions {
There's a codacy warning here. Would it be better to rename is to `SimilarityUtils` since the file is located in the utilities folder?

2021-06-21 06:44 UTC, ivanchimeno commented on src/main/java/de/tum/in/www1/artemis/service/compass/umlmodel/parsers/UMLModelParser.java
> +    // TODO: why is this done more than once?
Is this todo intentional?

2021-06-21 06:47 UTC, ivanchimeno commented on src/main/java/de/tum/in/www1/artemis/service/compass/umlmodel/parsers/DeploymentDiagramParser.java
> +        // TODO: try to further reduce code duplication from buildComponentDiagramFromJSON
Is this intentional?

2021-06-21 06:48 UTC, ivanchimeno commented on src/main/java/de/tum/in/www1/artemis/service/compass/umlmodel/parsers/ClassDiagramParser.java
> +    private static UMLMethod parseMethod(JsonObject methodJson) {
I think that this method is defined multiple times? Would it be possible to make it  static and define it in some utility class?

2021-06-21 09:54 UTC, real-dmy reviewed
Tested on TS1.  There are some remarks:
Use case diagram: 
1. Assessment
![image](https://user-images.githubusercontent.com/80687511/122741001-cfdfd180-d284-11eb-8ea0-c38d0e20d01f.png)
2. Assessment. No Suggestion
![image](https://user-images.githubusercontent.com/80687511/122741066-e0904780-d284-11eb-8dc0-d0b6149a003a.png)

Object Diagram:
1.st Assesment
![image](https://user-images.githubusercontent.com/80687511/122741244-0d445f00-d285-11eb-9b15-47db536f56c3.png)
2. Assessment. No Suggestion
![image](https://user-images.githubusercontent.com/80687511/122741333-251be300-d285-11eb-90b7-74d0a4c35718.png)

Communication Diagram:
1. Assessment
![image](https://user-images.githubusercontent.com/80687511/122741795-9bb8e080-d285-11eb-86e6-bb61cd6673f8.png)

2. Assessment. No suggestion.
![image](https://user-images.githubusercontent.com/80687511/122741830-a5dadf00-d285-11eb-9b73-46800933d0dc.png)

Component Diagram:
1. Assessment
![image](https://user-images.githubusercontent.com/80687511/122742181-fa7e5a00-d285-11eb-8971-4ec74029b0ce.png)

2. Assessment
![image](https://user-images.githubusercontent.com/80687511/122742212-01a56800-d286-11eb-9050-35a89853284d.png)

Deployment Diagram:

1. Assessment
![image](https://user-images.githubusercontent.com/80687511/122742550-5943d380-d286-11eb-97df-4759f313d8fd.png)

2. Assesment. No suggestion 
![image](https://user-images.githubusercontent.com/80687511/122742590-6496ff00-d286-11eb-9e17-9a8428864315.png)

Petri Net:
1. Assessment
![image](https://user-images.githubusercontent.com/80687511/122742778-990abb00-d286-11eb-8dbd-0da16b8cf054.png)

2. Assessment. No Suggestion.
![image](https://user-images.githubusercontent.com/80687511/122742828-a627aa00-d286-11eb-8a55-cb706a7f00cc.png)

Syntax Tree:
1. Assessment
![image](https://user-images.githubusercontent.com/80687511/122742927-c2c3e200-d286-11eb-9c84-e2b75e5d948f.png)

2.Assesment. No Suggestion.
![image](https://user-images.githubusercontent.com/80687511/122742978-d1aa9480-d286-11eb-99bf-fb8594e7bcb0.png)

These are all the ones that I did not get a suggestion for. I am not sure whether this has something to do with not changing the name of the classes from the default names but I do not think so since the same logic worked with Activity Diagram and I got a suggestion. Due dates were also over as I did the assessments.

2021-06-21 10:38 UTC, iozbeyli commented
> Tested on TS1. There are some remarks:
> Use case diagram:
> 
>     1. Assessment
>        ![image](https://user-images.githubusercontent.com/80687511/122741001-cfdfd180-d284-11eb-8ea0-c38d0e20d01f.png)
> 
>     2. Assessment. No Suggestion
>        ![image](https://user-images.githubusercontent.com/80687511/122741066-e0904780-d284-11eb-8dc0-d0b6149a003a.png)
> 
> 
> Object Diagram:
> 1.st Assesment
> ![image](https://user-images.githubusercontent.com/80687511/122741244-0d445f00-d285-11eb-9b15-47db536f56c3.png)
> 2. Assessment. No Suggestion
> ![image](https://user-images.githubusercontent.com/80687511/122741333-251be300-d285-11eb-90b7-74d0a4c35718.png)
> 
> Communication Diagram:
> 
>     1. Assessment
>        ![image](https://user-images.githubusercontent.com/80687511/122741795-9bb8e080-d285-11eb-86e6-bb61cd6673f8.png)
> 
>     2. Assessment. No suggestion.
>        ![image](https://user-images.githubusercontent.com/80687511/122741830-a5dadf00-d285-11eb-9b73-46800933d0dc.png)
> 
> 
> Component Diagram:
> 
>     1. Assessment
>        ![image](https://user-images.githubusercontent.com/80687511/122742181-fa7e5a00-d285-11eb-8971-4ec74029b0ce.png)
> 
>     2. Assessment
>        ![image](https://user-images.githubusercontent.com/80687511/122742212-01a56800-d286-11eb-9050-35a89853284d.png)
> 
> 
> Deployment Diagram:
> 
>     1. Assessment
>        ![image](https://user-images.githubusercontent.com/80687511/122742550-5943d380-d286-11eb-97df-4759f313d8fd.png)
> 
>     2. Assesment. No suggestion
>        ![image](https://user-images.githubusercontent.com/80687511/122742590-6496ff00-d286-11eb-9e17-9a8428864315.png)
> 
> 
> Petri Net:
> 
>     1. Assessment
>        ![image](https://user-images.githubusercontent.com/80687511/122742778-990abb00-d286-11eb-8dbd-0da16b8cf054.png)
> 
>     2. Assessment. No Suggestion.
>        ![image](https://user-images.githubusercontent.com/80687511/122742828-a627aa00-d286-11eb-8a55-cb706a7f00cc.png)
> 
> 
> Syntax Tree:
> 
>     1. Assessment
>        ![image](https://user-images.githubusercontent.com/80687511/122742927-c2c3e200-d286-11eb-9c84-e2b75e5d948f.png)
> 
> 
> 2.Assesment. No Suggestion.
> ![image](https://user-images.githubusercontent.com/80687511/122742978-d1aa9480-d286-11eb-99bf-fb8594e7bcb0.png)
> 
> These are all the ones that I did not get a suggestion for. I am not sure whether this has something to do with not changing the name of the classes from the default names but I do not think so since the same logic worked with Activity Diagram and I got a suggestion. Due dates were also over as I did the assessments.

Are you sure you waited for the due date to pass because I am getting suggestions for the same diagrams?

2021-06-21 14:46 UTC, imstreetspirit commented
tested for all diagram types on ts1. just found two weird case for me. 

For this scenario, I do not understand why the relation between Actor1 and UseCase2 is graded automatically.

Assessed Submission
<img src="https://user-images.githubusercontent.com/23650630/122780968-a5efd480-d2af-11eb-818f-9e8618bc8a65.png" width="400" />
Suggestion by Compass
<img src="https://user-images.githubusercontent.com/23650630/122781088-c455d000-d2af-11eb-8128-b9fce6a8da63.png" width="400" />

For this one, I think the relation between Node1 and Component1 should be graded automatically as well.

Assessed Submission
<img src="https://user-images.githubusercontent.com/23650630/122781313-f8c98c00-d2af-11eb-8199-e7487cf50e68.png" width="400" />
Suggestion by Compass
<img src="https://user-images.githubusercontent.com/23650630/122781379-07b03e80-d2b0-11eb-9c67-2c1fc7d0aeb2.png" width="400" />

2021-06-21 21:12 UTC, imstreetspirit approved these changes
tested the deployment diagram on ts1 again. works as intended.

2021-06-23 11:32 UTC, ArtemTsurikov submitted a review, later dismissed
Tested on TS1 with all diagrams, very nice feature!

2021-06-23 19:15 UTC, canyelten approved these changes
Tested on TS1, works as expected. Re-approve

2021-06-24 06:42 UTC, sinangunduz submitted a review, later dismissed
tested on ts1, works as expected

2021-06-24 15:37 UTC, merged