[Bugfix] Sentry Issue Type Error in programming submission service
ls1intum/Artemis pull request #3625
Opened 2021-06-24 15:35 UTC by lschlesinger

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Server: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [ ] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [ ] Server: I implemented the changes with a good performance and prevented too many database calls
- [ ] Server: I documented the Java code using JavaDoc style.
- [ ] Client: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [ ] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [ ] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [ ] Client: I documented the TypeScript code using JSDoc style.
- [ ] Client: I added multiple screenshots/screencasts of my UI changes
- [ ] Client: I translated all newly inserted strings into English and German.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).

### Motivation and Context

This PR solves the [Sentry Issue ARTMIS-26](https://sentry.ase.in.tum.de/organizations/artemis/issues/71/?project=2)

### Description

Error: TypeError call(src/main/webapp/app/exercises/programming/participate/programming-submission.service)
Cannot read property 'next' of undefined.
I inspected the use of `.next()` at other places in the respective service and adapted two occurrences of `.next()` without prior null check.

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

2021-06-25 12:59 UTC, jpbernius requested changes
Could this also work with optional chaining?

2021-06-25 12:59 UTC, jpbernius commented on src/main/webapp/app/exercises/programming/participate/programming-submission.service.ts
> +        }
```suggestion
        this.resultEtaSubject?.next(this.currentExpectedResultETA);
```

2021-06-25 12:59 UTC, jpbernius commented on src/main/webapp/app/exercises/programming/participate/programming-submission.service.ts
> +                }
```suggestion
                this.exerciseBuildStateSubjects.get(exerciseId)?.next(exerciseBuildState);
```

2021-06-25 19:40 UTC, ga62suz requested changes
Tested on TS2.

With manual assessment enabled + no due date, students don't get an immediate build + test when they submit after editing submission with online editor.
Compared to TS1 (deployed with another branch at the time) where build trigger was instant.

2021-06-26 23:05 UTC, Olimbia23 approved these changes
Looks good 👍

2021-06-27 13:53 UTC, rs-maker approved these changes
Good fix.

2021-06-28 18:52 UTC, SimonEntholzer approved these changes
Changes look good and fix the issue :+1:

2021-06-28 21:00 UTC, ivohashamov approved these changes
Changes look good

2021-06-29 08:18 UTC, FrankeLukas approved these changes
Lgtm. @ga62suz TS2 uses a different setup compared TS1, so I don't think delays in the builds are caused by this PR.

2021-06-29 12:31 UTC, merged