[Feature] Exercise dashboard button in exercise details pages
ls1intum/Artemis pull request #3628
Opened 2021-06-25 12:46 UTC by SimonEntholzer

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Client: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [ ] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [ ] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [ ] Client: I documented the TypeScript code using JSDoc style.
- [ ] Client: I added multiple screenshots/screencasts of my UI changes
- [ ] Client: I translated all newly inserted strings into English and German.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).

### Motivation and Context

In the exercise details pages I added a button to directly access the exercise-assessment dashboard.
Furthermore I cleaned up the button layout a bit. There is still some room for further improvements.

### Description

### Steps for Testing

1. Navigate to the course oveview -> exercises
2. Click on an exercise of every type (directly on the name), and check out the exercise detail page (Text, Modeling, Programming, File-Upload)
3. Test every button on those pages
4. Now, in an exam with a programming exercise, check the exercise details page too.

### Screenshots

File-Upload-exercise details page:
![image](https://user-images.githubusercontent.com/33342534/123426577-dee7bc00-d5c3-11eb-8b4f-7f9520bf3570.png)
Programming exercise details page:
![image](https://user-images.githubusercontent.com/33342534/123426651-f3c44f80-d5c3-11eb-9a95-5da08c68d4c5.png)
Modeling & text exercise details page: (they are identical)
![image](https://user-images.githubusercontent.com/33342534/123426707-076fb600-d5c4-11eb-8204-11cb107279a4.png)

2021-06-25 14:14 UTC, willergeorg approved these changes
Tested on TS1. Worked for me.

2021-06-25 15:01 UTC, ga62suz requested changes
Tested on TS2, with instructor account.
Everything works fine except the following:

Programming exercise:

Manage Hints doesn't seem to do anything

Newly created programming exercises doesn't have a dashboard button
![image](https://user-images.githubusercontent.com/50523655/123444158-e19fdc80-d5d6-11eb-9099-ac03ef38df4c.png)

Some old programming exercises also doesn't have a dashboard button, even though they have multiple graded submissions
![image](https://user-images.githubusercontent.com/50523655/123444186-e82e5400-d5d6-11eb-9062-93aa8b575808.png)

Recreate Build Plans does not seem to trigger a rebuild of Template Result (reset the timer)
![image](https://user-images.githubusercontent.com/50523655/123444199-ec5a7180-d5d6-11eb-9e23-4c6bbf57259d.png)

there is a programming exercise with no Update Structure Test Oracle button (KotlinExercise)
![image](https://user-images.githubusercontent.com/50523655/123444221-f2505280-d5d6-11eb-9de0-7b77cc5a56a4.png)

2021-06-25 18:39 UTC, argertboja reviewed
Tested on TS1, everything looks good!

2021-06-25 20:35 UTC, canyelten approved these changes
Tested on TS1, works as expected.

2021-06-26 10:04 UTC, SimonEntholzer commented
> Tested on TS2, with artemis_test_user_11.
> Everything works fine except the following:
> 
> Programming exercise:
> 
> Manage Hints doesn't seem to do anything

Are you sure? For me it works. Which exercise did you use, specifically?

> Newly created programming exercises doesn't have a dashboard button
> <img src=https://user-images.githubusercontent.com/50523655/123444158-e19fdc80-d5d6-11eb-9099-ac03ef38df4c.png width=150>

This is intended, as the button is only shown when the manual assessment for the exercise is enabled. This is option comes available as soon as you set a due date.

> Some old programming exercises also doesn't have a dashboard button, even though they have multiple graded submissions
> <img src=https://user-images.githubusercontent.com/50523655/123444186-e82e5400-d5d6-11eb-9062-93aa8b575808.png width=150>
Again, probably manual assessment is not enabled.

> Recreate Build Plans does not seem to trigger a rebuild of Template Result (reset the timer)
> <img src=https://user-images.githubusercontent.com/50523655/123444199-ec5a7180-d5d6-11eb-9e23-4c6bbf57259d.png width=150>
I have to look into that, I'm not sure in this case tbh.

> there is a programming exercise with no Update Structure Test Oracle button (KotlinExercise)
> <img src=https://user-images.githubusercontent.com/50523655/123444221-f2505280-d5d6-11eb-9de0-7b77cc5a56a4.png width=150>
This is intended, the button is only shown for Java exercises.

2021-06-26 10:40 UTC, ga62suz commented
> > Tested on TS2, with artemis_test_user_11.
> > Everything works fine except the following:
> > Programming exercise:
> > Manage Hints doesn't seem to do anything
> 
> Are you sure? For me it works. Which exercise did you use, specifically?
All of the exercises I tested was like that, but it could be because artemis_test_user_11 was not granted Instructor permission, which I did not realize until later (artemis_test_user_11 is noted as Instructor in the test credentials page)
 
> > Recreate Build Plans does not seem to trigger a rebuild of Template Result (reset the timer)
> > <img alt="" width="150" src="https://user-images.githubusercontent.com/50523655/123444199-ec5a7180-d5d6-11eb-9e23-4c6bbf57259d.png">
> > I have to look into that, I'm not sure in this case tbh.
Perhaps the problem lies with the triggering account's permission too.

2021-06-26 10:42 UTC, NicolasUllmann submitted a review, later dismissed
Tested on TS2. Everything worked as expected.

2021-06-26 21:28 UTC, Olimbia23 reviewed
Solid work @SimonEntholzer. Left some minor comments.

2021-06-26 21:28 UTC, Olimbia23 commented on src/main/webapp/app/overview/exercise-details/course-exercise-details.component.ts
> +    }
Nice change but can we remove it hahah 😄

2021-06-26 21:28 UTC, Olimbia23 commented on src/main/webapp/app/exercises/programming/manage/programming-exercise-detail.component.ts
> +                this.baseResource =  `/course-management/${this.courseId}/programming-exercises/${programmingExercise.id}/`;
Please don't forget to address the `client-style` issues.

2021-06-27 07:46 UTC, katjanakosic submitted a review, later dismissed
Tested on TS1, worked fine 👍

2021-06-27 08:12 UTC, cremertim submitted a review, later dismissed
tested on ts1.. works as expected

2021-06-28 10:55 UTC, sinangunduz submitted a review, later dismissed
tested on ts1, works as expected

2021-06-28 18:44 UTC, imstreetspirit commented
tested on ts2 works as expected. code seem good in general, there are only minor client-style issues need to be fixed.... 👍

2021-06-28 21:02 UTC, ivohashamov submitted a review, later dismissed
Code is looking good 👍

2021-06-29 13:50 UTC, ArtemTsurikov approved these changes
Tested on ts1, worked fine.

2021-07-03 05:55 UTC, merged