[Followup] increase Test Coverage in TextAssessment- and ResultResource
ls1intum/Artemis pull request #3632
Opened 2021-06-26 08:08 UTC by PatZintel

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Server: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [ ] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [ ] Server: I implemented the changes with a good performance and prevented too many database calls
- [ ] Server: I documented the Java code using JavaDoc style.
- [ ] Client: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [ ] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [ ] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [ ] Client: I documented the TypeScript code using JSDoc style.
- [ ] Client: I added multiple screenshots/screencasts of my UI changes
- [ ] Client: I translated all newly inserted strings into English and German.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).

### Motivation and Context

### Description

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Test Coverage

### Screenshots

2021-06-28 07:31 UTC, MerlinMehmed requested changes
Additionally, it would also be good if you can fix the Codacy issues. 

I couldn't test the integration of the client with all of the endpoints because of the problem in participations/{participationId}/submissions/{submissionId}/for-text-assessment so I will test them after this is fixed.

2021-06-28 07:31 UTC, MerlinMehmed commented on src/test/java/de/tum/in/www1/artemis/ExampleSubmissionIntegrationTest.java
> +        feedbacks.add(new Feedback().credits(80.00).type(FeedbackType.MANUAL).detailText("nice submission 1").reference(textBlockIterator.next().getId()));
Maybe you can use the ModelFactory (i.e. generateManualFeedback()) here and in the next test to generate feedbacks in order to remove duplicates.

2021-06-30 20:20 UTC, krusche commented on src/main/webapp/app/exercises/text/assess/text-submission-assessment.route.ts
> +        path: 'participations/:participationId/submissions/:submissionId/for-text-assessment',
if you change those paths, you probably also need to change the component that load the corresponding pages

2021-07-05 08:42 UTC, Olimbia23 reviewed
Creation of text and modelling- example submissions seems to be working. 
The creation of Example Assessment also works. @PatZintel

2021-07-05 16:01 UTC, Olimbia23 submitted a review, later dismissed
re-tested on TS1 the creation of Text-/Model Example Submissions. 
As well as for exams. 
It works as it should. 👍 @PatZintel

2021-07-05 19:16 UTC, imstreetspirit requested changes
tested on ts3, seems good for normal exercise/exam mode. Only thing, this Save button did not work for me while assessing the text submissions. tried for two submissions, it throws the same error. Submit works as expected.

<img src="https://user-images.githubusercontent.com/23650630/124511284-0ca7de80-ddd6-11eb-9237-d94e94c51ad3.png" width="500" />

2021-07-05 21:26 UTC, argertboja reviewed
Works as expected on TS1!

2021-07-05 21:30 UTC, imstreetspirit approved these changes
saving works now.. tested on ts3 again.

2021-07-06 11:14 UTC, merged