[Sentry-issue] Fix property of undefined in text-submission-viewer.component
ls1intum/Artemis pull request #3638
Opened 2021-06-27 22:31 UTC by Olimbia23

### Checklist

- [x] Client: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).

### Motivation and Context
This PR solved this Sentry Issue: [ARTEMIS-39F](https://sentry.ase.in.tum.de/organizations/artemis/issues/3399/?project=2)

### Description

Error: "Cannot read property 'slice' of undefined"
Now we check if the row variable is defined before calling the insertToken method

### Steps for Testing

I didn't manage to reproduce this problem. It would be great if someone who has touched the Plagiarism part of the codebase can test it. 
Maybe @joschahenningsen you know how to reproduce it?  

### Test Coverage
Didn't change.

2021-06-28 05:39 UTC, joschahenningsen approved these changes
LGTM

2021-06-28 10:38 UTC, joschahenningsen approved these changes
Ultimately the actual line calculation might be off by one for matches on the first line, but I think your solution should fix the issue :+1:

2021-06-28 12:16 UTC, FrankeLukas commented on src/main/webapp/app/exercises/shared/plagiarism/plagiarism-split-view/text-submission-viewer/text-submission-viewer.component.ts
>              offsets[idxLineFrom] += this.tokenStart.length;
We probably shouldn't increase the offset if we don't insert anything, or should we? (I'm not sure.)

2021-06-28 12:16 UTC, FrankeLukas commented on src/main/webapp/app/exercises/shared/plagiarism/plagiarism-split-view/text-submission-viewer/text-submission-viewer.component.ts
>              offsets[idxLineTo] += this.tokenEnd.length;
Same here.

2021-06-29 12:19 UTC, FuchsDominik reviewed
Changes look good, agree an Lukas' comment

2021-06-30 06:37 UTC, krusche requested changes
I agree: please move the corresponding calls inside the if statement

2021-07-01 14:34 UTC, Olimbia23 commented
> I agree: please move the corresponding calls inside the if statement

I did it @krusche

2021-07-01 16:38 UTC, FrankeLukas approved these changes

2021-07-01 20:04 UTC, DanielKainz approved these changes
Code changes look good :-)

2021-07-02 21:52 UTC, coolchock approved these changes

2021-07-03 04:56 UTC, merged