Fix broken links on setup docs page
ls1intum/Artemis pull request #3643
Opened 2021-06-28 18:08 UTC by joschahenningsen

Also I removed a link to `package.json`. Didn't think it's needed.

2021-06-28 20:09 UTC, ndricimrr requested changes
I tried these locally. Doesn't seem to work for me 🤔. The forwarding link is still broken.
![1](https://user-images.githubusercontent.com/18335489/123697266-fc838280-d85c-11eb-8f62-f4a27a444770.PNG)
![2](https://user-images.githubusercontent.com/18335489/123697269-fd1c1900-d85c-11eb-9209-9fb2875c0142.PNG)


I can assume you also test the links on the current deployed docs. Just check the links below refactored from .rst to ~.rst~.That should be the same as what you are doing in the PR. Those also don't seem to work for me.
https://docs.artemis.ase.in.tum.de/dev/setup/setup#athene-service 

and this link:
https://docs.artemis.ase.in.tum.de/dev/setup/setup#client-setup

2021-06-29 21:43 UTC, FrankeLukas approved these changes

2021-06-29 21:58 UTC, coolchock approved these changes

2021-06-30 06:35 UTC, krusche approved these changes

2021-06-30 06:35 UTC, merged