[Bugfix] fix deletion of results
ls1intum/Artemis pull request #3654
Opened 2021-06-29 16:16 UTC by SimonEntholzer

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Server: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] Client: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [ ] Client: I documented the TypeScript code using JSDoc style.
- [ ] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

For some reason the endpoints in the client didn't match the endpoints in the server anymore, 
which made deletion of results impossible. This is fixed now.
![image](https://user-images.githubusercontent.com/33342534/123832718-ef6e9e00-d905-11eb-92ad-1cac563d8cdf.png)

### Testing steps
1. course overview -> exercises page
2. for each exercise type click on the submissions button. From this page, navigate to the page for individual submissions. (Click the number in the submissions column)
3. If there is result for the submission it should be visible now, and a 'delete' button should be visible. Using this button should work for all exercise types
![image](https://user-images.githubusercontent.com/33342534/123832659-dcf46480-d905-11eb-9a69-ee5645b378bb.png)

### Screenshots

2021-06-29 20:31 UTC, krusche commented on src/main/java/de/tum/in/www1/artemis/web/rest/TextAssessmentResource.java
> +    @DeleteMapping("participations/{participationId}/text-submissions/{submissionId}/delete/{resultId}")
```suggestion
    @DeleteMapping("participations/{participationId}/text-submissions/{submissionId}/results/{resultId}")
```

2021-06-29 20:31 UTC, krusche commented on src/main/java/de/tum/in/www1/artemis/web/rest/TextAssessmentResource.java
> +    @DeleteMapping("participations/{participationId}/text-submissions/{submissionId}/delete/{resultId}")
I don't think we should use `delete` here as part of the URL.
This should also be changed in the other cases

2021-06-29 20:32 UTC, krusche commented on src/main/webapp/app/exercises/file-upload/assess/file-upload-assessment.service.ts
> +        return this.http.delete<void>(`${this.resourceUrl}/participations/${participationId}/file-upload-submissions/${submissionId}/delete/${resultId}`);
I don't see those changes reflected on the server

2021-06-29 20:32 UTC, krusche commented on src/main/webapp/app/exercises/file-upload/assess/file-upload-assessment.service.ts
> +        return this.http.delete<void>(`${this.resourceUrl}/participations/${participationId}/file-upload-submissions/${submissionId}/delete/${resultId}`);
```suggestion
        return this.http.delete<void>(`${this.resourceUrl}/participations/${participationId}/file-upload-submissions/${submissionId}/results/${resultId}`);
```

2021-06-29 20:32 UTC, krusche commented on src/main/webapp/app/exercises/modeling/assess/modeling-assessment.service.ts
> +        return this.http.delete<void>(`${this.resourceUrl}/participations/${participationId}/modeling-submissions/${submissionId}/delete/${resultId}`);
```suggestion
        return this.http.delete<void>(`${this.resourceUrl}/participations/${participationId}/modeling-submissions/${submissionId}/results/${resultId}`);
```

2021-06-29 20:32 UTC, krusche commented on src/main/webapp/app/exercises/modeling/assess/modeling-assessment.service.ts
> +        return this.http.delete<void>(`${this.resourceUrl}/participations/${participationId}/modeling-submissions/${submissionId}/delete/${resultId}`);
I don't see those changes reflected on the server

2021-06-29 20:32 UTC, krusche commented on src/main/webapp/app/exercises/programming/assess/manual-result/programming-assessment-manual-result.service.ts
> +        return this.http.delete<void>(`${this.resourceUrl}/participations/${participationId}/programming-submissions/${submissionId}/delete/${resultId}`);
```suggestion
        return this.http.delete<void>(`${this.resourceUrl}/participations/${participationId}/programming-submissions/${submissionId}/results/${resultId}`);
```

2021-06-29 20:33 UTC, krusche commented on src/main/webapp/app/exercises/programming/assess/manual-result/programming-assessment-manual-result.service.ts
> +        return this.http.delete<void>(`${this.resourceUrl}/participations/${participationId}/programming-submissions/${submissionId}/delete/${resultId}`);
I don't see those changes reflected on the server and in the server integration tests (they fail at the moment)

2021-06-29 20:33 UTC, krusche commented on src/main/webapp/app/exercises/text/assess/text-assessment.service.ts
> +        return this.http.delete<void>(`${this.resourceUrl}/participations/${participationId}/text-submissions/${submissionId}/delete/${resultId}`);
```suggestion
        return this.http.delete<void>(`${this.resourceUrl}/participations/${participationId}/text-submissions/${submissionId}/results/${resultId}`);
```

2021-06-29 20:33 UTC, krusche commented on src/main/webapp/app/exercises/text/assess/text-assessment.service.ts
> +        return this.http.delete<void>(`${this.resourceUrl}/participations/${participationId}/text-submissions/${submissionId}/delete/${resultId}`);
I don't see those changes reflected on the server and in the server integration tests (they fail at the moment)

2021-06-29 20:34 UTC, krusche commented on src/main/java/de/tum/in/www1/artemis/web/rest/TextAssessmentResource.java
> +    @DeleteMapping("participations/{participationId}/text-submissions/{submissionId}/delete/{resultId}")
I don't see those changes reflected in the server integration tests (they fail at the moment)

2021-06-29 20:34 UTC, krusche requested changes
see my inline comments

2021-06-30 12:03 UTC, FuchsDominik submitted a review, later dismissed
worked while testing 👍

2021-06-30 14:02 UTC, jhainzlschmid approved these changes
Tested in testing session and worked

2021-06-30 17:57 UTC, canyelten approved these changes
Tested on TS1, the delete button is visible and works as expected.

2021-06-30 19:39 UTC, krusche approved these changes
code looks good now 👍

2021-06-30 19:40 UTC, merged