[Feature] Grading System - Participant Scores
ls1intum/Artemis pull request #3715
Opened 2021-07-09 11:17 UTC by ivohashamov

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Client: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [ ] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [ ] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [ ] Client: I documented the TypeScript code using JSDoc style.
- [ ] Client: I added multiple screenshots/screencasts of my UI changes
- [ ] Client: I translated all newly inserted strings into English and German.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).

### Motivation and Context

This PR integrates the grading system with the participant scores pages for courses and exams

### Description

I've added an average grade and average rated grade on top of the participant scores pages.
In addition, the average scores table now also has an average grade and average rated grade columns.

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Test Coverage

unchanged (100% for both participant scores components)

### Screenshots

2021-07-10 09:23 UTC, willergeorg requested changes
Tested on TS1. Might not be associated with this PR, but somehow the grading key is not stored after generation (see Screencast below), therefore of course the average grades cannot be displayed as well. I faced this problem for both the course and an exam.

https://user-images.githubusercontent.com/80622272/125158399-30ba4580-e171-11eb-9d69-1c57b4bf255a.mp4

2021-07-10 10:22 UTC, ivohashamov commented
> Tested on TS1. Might not be associated with this PR, but somehow the grading key is not stored after generation (see Screencast below), therefore of course the average grades cannot be displayed as well. I faced this problem for both the course and an exam.
> 
>  2021-07-10.11-16-51.mp4

That's odd, I would have to check that out on a test server. I can't reproduce the issue locally. I would have to check it out on a test server. Was the save button constantly disabled and did you test only in your course?

2021-07-11 09:00 UTC, NicolasUllmann approved these changes
Tested on TS1. Everything worked for me, wasn't able to reproduce the error mentioned above.

2021-07-11 14:35 UTC, willergeorg submitted a review, later dismissed
Tested again on TS1. This time works perfectly fine for me.

2021-07-12 11:43 UTC, niclasschuemann requested changes
It seems like there are still translation issues: 
![translationIssue](https://user-images.githubusercontent.com/45300855/125281371-6ea49e80-e316-11eb-8252-770b9aadf81e.PNG)
Also, currently, there are no german translations for both labels (German translation is still the English text)

I don't think this is in scope for this PR, but I want to mention it anyway:
The **Participant Scores** Button is present in the course management detail view of a course, but not in the course-management view that lists all courses. Also, while testing I was not quite sure how the average grade is calculated:
![gradeweird](https://user-images.githubusercontent.com/45300855/125281783-ee326d80-e316-11eb-8193-86bd5d69b3ab.PNG)
I would expect something between 4.7 and 5.0, is it rounded to the next possible grade?

2021-07-12 11:47 UTC, niclasschuemann requested changes

2021-07-12 11:47 UTC, niclasschuemann commented on src/main/webapp/i18n/de/participantScores.json
> +            "averageRatedBonus": "Average Rated Bonus",
```suggestion
            "averageGrade": "Notendurchschnitt",
            "averageRatedGrade": "Gewerteter Notendurchschnitt",
            "averageBonus": "Durchschnittlicher Bonus",
            "averageRatedBonus": "Gewerteter durchschnittlicher Bonus",
```

2021-07-12 12:40 UTC, ivohashamov commented
> It seems like there are still translation issues:
> ![translationIssue](https://user-images.githubusercontent.com/45300855/125281371-6ea49e80-e316-11eb-8252-770b9aadf81e.PNG)
> Also, currently, there are no german translations for both labels (German translation is still the English text)
> 
> I don't think this is in scope for this PR, but I want to mention it anyway:
> The **Participant Scores** Button is present in the course management detail view of a course, but not in the course-management view that lists all courses. Also, while testing I was not quite sure how the average grade is calculated:
> ![gradeweird](https://user-images.githubusercontent.com/45300855/125281783-ee326d80-e316-11eb-8193-86bd5d69b3ab.PNG)
> I would expect something between 4.7 and 5.0, is it rounded to the next possible grade?

@niclasschuemann The translation issue is what Lorena mentioned a few weeks ago in the team meeting. You have to refresh your browser cache and it should work.

Regarding your other comments, I think the Participant Scores button is not on the "overview" pages, but only on the detail ones because it's mainly used for debugging and is not as important.

The average grade is calculated entirely based on the average score -> whatever grade that average score would map to, is the average grade. This is similar to the calculation on the scores pages as well. The reason for that is simple, grades don't necessarily have to be a numeric value -> they could be A,B,C,D,E,F, if that is the type of grading key set. Such grades can't reasonably be averaged. In general, the grading key is discrete in terms of its values, so this gets propagated to the average grade as well.

2021-07-12 18:08 UTC, canyelten approved these changes
Tested on TS1, works perfectly fine.

2021-07-13 18:31 UTC, ArtemTsurikov approved these changes
Works fine on TS1

2021-07-17 14:27 UTC, katjanakosic approved these changes
Works on ts2

2021-07-19 09:17 UTC, sinangunduz approved these changes
tested on ts2, works as expected

2021-07-19 09:40 UTC, argertboja approved these changes
Works fine on TS1!

2021-07-19 14:56 UTC, imstreetspirit approved these changes
tested on ts2, works fine. 

guess, you refactored the code which comes from 404 not found error bugfixing. I also tested as a student. The error is not shown in the console at the end of the exam. Maybe you can also add this into testing steps.

I have one question regarding this new information in the participant scores. So, if do not have a grading key, I can not see the  `average grade` and `average rated grade`. How can I know that to see this results, I should have a grading key as a new user? hope, I expressed myself correctly.

2021-07-19 16:55 UTC, merged