[Bugfix] Fix export routing for quiz exercises
ls1intum/Artemis pull request #3727
Opened 2021-07-11 19:27 UTC by imstreetspirit

### Motivation and Context

PR aims to fix #3433 and #3317 . 

### Description

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Test Coverage

nothings changes

### Screenshots

2021-07-11 20:03 UTC, ndricimrr approved these changes
Tested on TS1 . Export button leads to export page 👍

2021-07-12 08:22 UTC, ivanchimeno submitted a review, later dismissed
Tested on TS2 :+1:

2021-07-12 10:06 UTC, niclasschuemann requested changes
The changes work as expected on TS1, but I have added a few comments regarding the authorities. If you think this is out of scope for this PR, feel free to dismiss this review 😄

2021-07-12 10:06 UTC, niclasschuemann commented on src/main/webapp/app/exercises/quiz/manage/quiz-management.route.ts
> +            authorities: [Authority.TA, Authority.EDITOR, Authority.INSTRUCTOR, Authority.ADMIN],
The TA is not supposed to be able to export quiz exercises, so I guess we should remove the respective authority

2021-07-12 10:06 UTC, niclasschuemann commented on src/main/webapp/app/exercises/quiz/manage/quiz-management.route.ts
>              authorities: [Authority.TA, Authority.EDITOR, Authority.INSTRUCTOR, Authority.ADMIN],
The TA is not supposed to access the quiz exercise creation view, so we should remove the respective authority

2021-07-12 10:24 UTC, imstreetspirit commented on src/main/webapp/app/exercises/quiz/manage/quiz-management.route.ts
>              authorities: [Authority.TA, Authority.EDITOR, Authority.INSTRUCTOR, Authority.ADMIN],
hmm, okay I did not check the other routes permissions. Thanks for capturing, I think I can handle this in this PR :)

2021-07-12 10:40 UTC, argertboja reviewed
Tested on TS2 and everything works fine. 👍🏼 

 Something I would suggest is to disable the export button in case there are no quizzes selected to export. See image below:
 
![image](https://user-images.githubusercontent.com/17032718/125274527-5761b300-e30e-11eb-8a85-d4f1091218e0.png)

2021-07-12 12:56 UTC, imstreetspirit commented
> Tested on TS2 and everything works fine. 👍🏼
> 
> Something I would suggest is to disable the export button in case there are no quizzes selected to export. See image below:
> 
> ![image](https://user-images.githubusercontent.com/17032718/125274527-5761b300-e30e-11eb-8a85-d4f1091218e0.png)

hmm, could be part of ui improvement, but I think that it is not relevant with the problem we have now. I just took noted this.

2021-07-12 14:13 UTC, lschlesinger approved these changes
Tested on TS3, worked as described 👍

2021-07-12 15:33 UTC, real-dmy approved these changes
Tested on TS1. Works as expected.

2021-07-12 15:36 UTC, FrankeLukas approved these changes

2021-07-12 17:57 UTC, rs-maker approved these changes
Works on local too :+1:

2021-07-12 18:09 UTC, katjanakosic approved these changes
Worked as expected on TS2

2021-07-12 18:42 UTC, canyelten approved these changes
Tested on TS1, works as expected.

2021-07-12 19:05 UTC, merged