test change A
ls1intum/Artemis pull request #3740
Opened 2021-07-13 09:35 UTC by Malyuk-A

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Server: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [ ] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [ ] Server: I implemented the changes with a good performance and prevented too many database calls
- [ ] Server: I documented the Java code using JavaDoc style.
- [ ] Client: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [ ] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [ ] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [ ] Client: I documented the TypeScript code using JSDoc style.
- [ ] Client: I added multiple screenshots/screencasts of my UI changes
- [ ] Client: I translated all newly inserted strings into English and German.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).

### Motivation and Context

### Description

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Test Coverage

### Screenshots

2021-07-18 12:35 UTC, SimonEntholzer commented on src/main/webapp/app/exercises/programming/shared/code-editor/container/code-editor-container.component.html
> +
```suggestion
```

2021-07-18 12:35 UTC, SimonEntholzer commented on src/main/webapp/app/exercises/programming/shared/code-editor/container/code-editor-container.component.html
> +
```suggestion
```

2021-07-18 12:35 UTC, SimonEntholzer commented on src/main/webapp/app/exercises/programming/shared/code-editor/layout/code-editor-grid.scss
> +            border-left: 3px solid;
```suggestion
            border-left: 1px solid rgba(0, 0, 0, 0.125);
```

2021-07-18 14:52 UTC, rs-maker submitted a review, later dismissed
Tested on ts3 works great.

2021-07-18 19:22 UTC, FrankeLukas submitted a review, later dismissed
Lgtm.

2021-07-18 19:59 UTC, MDK5 requested changes
Tested on ts1, style for exams is unified now.

However the style for assessment is now different:
Other (e.g. text):
![grafik](https://user-images.githubusercontent.com/61357727/126080585-06fb4d22-059c-46fb-88b2-bf703d503c74.png)
Other (e.g. modeling):
![grafik](https://user-images.githubusercontent.com/61357727/126080571-696c647d-ea31-4394-bbd9-cf428f76a1ee.png)
Programming:
![grafik](https://user-images.githubusercontent.com/61357727/126080545-74d027e1-cf75-4626-95d5-525e841fb8f3.png)

I'm afraid the code editor has to use different texts for each usage.

Also, but maybe out of scope: modeling exercises have the text in bold and with different capitalization for some reason:
Other:
![grafik](https://user-images.githubusercontent.com/61357727/126080428-cce17038-4d8d-4378-aef5-4a1e722cdac6.png)
Modeling:
![grafik](https://user-images.githubusercontent.com/61357727/126080435-71df541f-363f-4ee7-adcd-2f2552e5bd5b.png)

2021-07-19 10:20 UTC, argertboja submitted a review, later dismissed
Tested on TS1 and LGTM 👍🏼

2021-07-19 14:11 UTC, canyelten submitted a review, later dismissed
Tested on TS1, works as expected.

2021-07-19 16:41 UTC, krusche commented
> Tested on ts1, style for exams is unified now.
> 
> However the style for assessment is now different:
> Other (e.g. text):
> ![grafik](https://user-images.githubusercontent.com/61357727/126080585-06fb4d22-059c-46fb-88b2-bf703d503c74.png)
> Other (e.g. modeling):
> ![grafik](https://user-images.githubusercontent.com/61357727/126080571-696c647d-ea31-4394-bbd9-cf428f76a1ee.png)
> Programming:
> ![grafik](https://user-images.githubusercontent.com/61357727/126080545-74d027e1-cf75-4626-95d5-525e841fb8f3.png)
> 
> I'm afraid the code editor has to use different texts for each usage.
> 
> Also, but maybe out of scope: modeling exercises have the text in bold and with different capitalization for some reason:
> Other:
> ![grafik](https://user-images.githubusercontent.com/61357727/126080428-cce17038-4d8d-4378-aef5-4a1e722cdac6.png)
> Modeling:
> ![grafik](https://user-images.githubusercontent.com/61357727/126080435-71df541f-363f-4ee7-adcd-2f2552e5bd5b.png)

I think we can fix this issue in a follow-up PR

2021-07-19 22:09 UTC, Olimbia23 approved these changes
Tested it on TS2.
The result looks as in the screenshots. Nice work @Malyuk-A

2021-07-20 07:00 UTC, ArtemTsurikov approved these changes
Tested on TS1, looks good

2021-07-20 17:48 UTC, FrankeLukas approved these changes
Re-approve (only style & test fixes).

2021-07-24 18:12 UTC, maximilianbergmann approved these changes
Tested on TS3

2021-07-25 16:01 UTC, real-dmy approved these changes
Tested on TS1, works as expected.

2021-07-26 07:17 UTC, katjanakosic approved these changes
Looks good on ts1

2021-07-26 15:56 UTC, sinangunduz approved these changes
tested on ts2, works as expected

2021-07-27 14:30 UTC, willergeorg approved these changes
Tested on TS1. Looks good to me!

2021-07-27 16:38 UTC, NicolasUllmann approved these changes
Tested on TS1. Everything worked as expected.

2021-07-27 19:30 UTC, Malyuk-A commented
This PR is part of https://github.com/ls1intum/Artemis/pull/3832
therefore the code was already merged.
I will close this PR

2021-07-27 19:30 UTC, Malyuk-A commented
This PR is part of https://github.com/ls1intum/Artemis/pull/3832
therefore the code was already merged.
I will close this PR

2021-07-27 19:30 UTC, closed without merging