Fix hint and explanation flickering on drag and drop exercises
ls1intum/Artemis pull request #3746
Opened 2021-07-13 11:42 UTC by joschahenningsen

### Checklist
- [X] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [X] Client: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [X] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

fixes #3743 

### Steps for Testing

1. Create a drag and drop quiz with a hint and an explanation
2. preview quiz
3. verify that you are able to see the hints/explanations on hover.

### Test Coverage
unchanged

### Screencast

https://user-images.githubusercontent.com/44805696/125445904-1895db4c-23d4-491c-9eb5-7dba184ed123.mp4

2021-07-13 11:48 UTC, SimonEntholzer requested changes
some minor sytle issue with spaces, but otherwise looks good

2021-07-13 11:48 UTC, SimonEntholzer commented on src/main/webapp/app/exercises/quiz/shared/questions/drag-and-drop-question/drag-and-drop-question.component.html
> +            <br />
```suggestion
            <br/>
```
I guess here you missed a whitespace

2021-07-13 11:52 UTC, SimonEntholzer approved these changes
looks good to me.

2021-07-13 18:20 UTC, ArtemTsurikov requested changes
I still had the flickering issue on TS1. Maybe it was due to the background picture dimension size (1200 × 630). 

https://user-images.githubusercontent.com/64026687/125504829-c1d025c3-e587-4981-a5b9-f5d2cea51d53.mov

2021-07-14 09:17 UTC, joschahenningsen commented
https://github.com/ls1intum/Artemis/pull/3746#pullrequestreview-705510883 
Thanks! I can't reproduce this with any image. Which browser did you use?

2021-07-14 19:24 UTC, willergeorg approved these changes
Tested on TS1. I wasn't able to reproduce the issue of @ArtemTsurikov, it worked good for me.

2021-07-14 19:33 UTC, merged