[Refactor] improved ParticipationResource
ls1intum/Artemis pull request #3869
Opened 2021-08-02 14:38 UTC by PatZintel

### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context

adapt ParticipationResource to adhere to new guidelines of REST Resources

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Test Coverage

2021-08-16 13:19 UTC, FrankeLukas requested changes

2021-08-16 13:19 UTC, FrankeLukas commented on src/main/java/de/tum/in/www1/artemis/repository/TeamRepository.java
> +                .orElseThrow(() -> new EntityNotFoundException("Couldn't an active team for exercise " + exerciseId + " with user " + userId + "!"));
```suggestion
                .orElseThrow(() -> new EntityNotFoundException("Couldn't find an active team for exercise " + exerciseId + " with user " + userId + "!"));
```

2021-08-16 13:19 UTC, FrankeLukas commented on src/main/webapp/app/exercises/shared/participation/participation.service.ts
> +        this.convertDateFromClient(participation);
If we don't send this via the network, we also don't need to convert anything, right?

2021-08-16 13:19 UTC, FrankeLukas commented on src/test/java/de/tum/in/www1/artemis/programmingexercise/ProgrammingExerciseTestService.java
> +        final var path = ParticipationResource.Endpoints.ROOT + '/' + ParticipationResource.Endpoints.START_PARTICIPATION.replace("{exerciseId}", String.valueOf(exercise.getId()));
What is the difference between `ParticipationResource.Endpoints.ROOT` and just `ROOT`? Can we use `ROOT` for consistency?

2021-08-16 21:58 UTC, imstreetspirit reviewed
just left very small comment, and agree with the suggestions mentioned by Lukas above.

2021-08-16 21:58 UTC, imstreetspirit commented on src/main/java/de/tum/in/www1/artemis/web/rest/ParticipationResource.java
> +     * GET participations/:participationId : get the participation for the given "participationId" including its latest result.
```suggestion
     * GET participations/:participationId/withLatestResult : get the participation for the given "participationId" including its latest result.
```

2021-08-24 16:56 UTC, MaisiKoleni requested changes
Changes look good to me in general, the renaming and de-duplication is great, I'm just not sure about the failed team participation start response.

This also needs extensive manual testing of all connected functionality, as a pure code review to check the matching client-server REST services is too hard. Maybe we find a better automatic way to check that as well.

2021-08-24 16:56 UTC, MaisiKoleni commented on src/main/java/de/tum/in/www1/artemis/web/rest/ParticipationResource.java
> -        }
I would recommend keeping this (make it not instantiable).

2021-08-24 16:56 UTC, MaisiKoleni commented on src/main/java/de/tum/in/www1/artemis/web/rest/ParticipationResource.java
> -                    .orElseThrow(() -> new BadRequestAlertException("Team exercise cannot be started without assigned team.", "participation", "cannotStart"));
Are we certain this alert is still displayed properly? I'm also not sure whether `Not Found` is better in this context than `Bad Request`. We require a team to be assigned, which does not exist then, but the problem does not seem to me like a "classic" missing entity, the exercise is found and a prerequisite not fulfilled. The opinion of other's would be useful here as well.

2021-08-24 16:56 UTC, MaisiKoleni commented on src/main/java/de/tum/in/www1/artemis/web/rest/ParticipationResource.java
> +     * PUT exercises/{exerciseId}/participations : Updates an existing participation.
Are the braces intentional here? Or do we use `:`?

2021-11-13 09:46 UTC, krusche commented
This PR has too many merge conflicts!

2021-11-13 09:46 UTC, closed without merging