[Test] Cypress Quiz Exercise Management tests
ls1intum/Artemis pull request #3939
Opened 2021-08-23 13:16 UTC by rs-maker

### Motivation and Context
 Like all other exercise types Quiz Exercises will be covered with automated UI tests. The management aspect of that will be done in this PR.

### Description
 Checks creation/Deletion of different Quiz exercise types via the UI.

### Steps for Testing

I have created a tutorial for how to test cypress PRs <a href="https://confluence.ase.in.tum.de/display/ArTEMiS/Cypress+Tests">on this confluence page</a> 
Please test all .spec files that were changed in this PR or ideally all of the existing ones.

### Review Progress

- Code Review
  - [ ] Review 1
  - [ ] Review 2
- Manual Tests
  - [ ] Test 1
  - [ ] Test 2

2021-08-26 20:49 UTC, jhainzlschmid submitted a review, later dismissed
I suggested some changes

2021-08-27 15:30 UTC, MerlinMehmed submitted a review, later dismissed
I ran the tests against TS3 and all of them passed

2021-08-28 14:17 UTC, rs-maker commented on src/test/cypress/integration/quiz-exercise/QuizExercise.spec.ts
> +                quizExercise = quizResponse?.response?.body;
I removed the first ones since as you say they do nothing but removing the ? behind response gives me a type error so those will have to stay.

2021-08-28 14:17 UTC, rs-maker commented on src/test/cypress/integration/quiz-exercise/QuizExercise.spec.ts
> +                quizExercise = quizResponse?.body;
Agreed.

2021-08-28 15:18 UTC, rs-maker commented on src/test/cypress/support/pageobjects/QuizExerciseCreationPage.ts
> +        cy.contains('Save').click();
Done

2021-08-28 15:19 UTC, rs-maker commented on src/test/cypress/integration/quiz-exercise/QuizExercise.spec.ts
> +                expect(deleteResponse?.response?.statusCode).to.eq(200);
Done

2021-08-28 15:20 UTC, rs-maker commented on src/test/cypress/integration/quiz-exercise/QuizExercise.spec.ts
> +            cy.wait('@createQuizExercise').then((quizResponse) => {
Done

2021-08-28 15:20 UTC, rs-maker commented on src/test/cypress/integration/quiz-exercise/QuizExercise.spec.ts
> +        cy.intercept(POST, '/api/quiz-exercises').as('createQuizExercise');
Done

2021-08-28 15:24 UTC, rs-maker commented on src/test/cypress/integration/quiz-exercise/QuizExercise.spec.ts
> +            mcQuestion.title = 'Cypress MC' + uid;
This has already been addressed for completion i will change it here as well.

2021-08-28 15:28 UTC, rs-maker commented on src/test/cypress/integration/quiz-exercise/QuizExercise.spec.ts
> +            cy.intercept('DELETE', '/api/quiz-exercises/*').as('deleteQuizQuery');
Done

2021-08-28 15:35 UTC, rs-maker commented on src/test/cypress/integration/quiz-exercise/QuizExercise.spec.ts
> +            cy.get('.modal-footer').contains('Delete').click();
Done

2021-08-28 15:36 UTC, rs-maker commented on src/test/cypress/integration/quiz-exercise/QuizExercise.spec.ts
> +    cy.get('#create-quiz-button').should('be.visible').click();
Removed

2021-08-28 15:41 UTC, rs-maker commented on src/test/cypress/support/pageobjects/QuizExerciseCreationPage.ts
> +            cy.get('.ace_text-input').focus().clear({ force: true }).type(fileContent, { force: true });
They make the tests significantly more stable but i knew you would want me to change them :)

2021-08-28 15:41 UTC, rs-maker commented on src/test/cypress/support/pageobjects/QuizExerciseCreationPage.ts
> +            cy.get('.ace_text-input').focus().clear({ force: true }).type(fileContent, { force: true });
Done

2021-08-28 15:42 UTC, rs-maker commented on src/test/cypress/support/requests/CourseManagementRequests.ts
> +            method: 'POST',
DOne

2021-08-28 15:45 UTC, rs-maker commented on src/test/cypress/support/requests/CourseManagementRequests.ts
> +            url: `/api/quiz-exercises/${exerciseId}`,
Done

2021-08-28 15:46 UTC, rs-maker commented on src/test/cypress/support/requests/CourseManagementRequests.ts
> +        quizExercise.quizQuestions = quizQuestions;
Done

2021-09-06 22:13 UTC, ndricimrr submitted a review, later dismissed
Tested locally & using TS3. The test is passing with no failures

2021-09-12 16:00 UTC, jhainzlschmid requested changes
Added some suggestions

2021-09-12 16:00 UTC, jhainzlschmid commented on src/test/cypress/integration/quiz-exercise/QuizExercise.spec.ts
> +            cy.intercept(DELETE, '/api/quiz-exercises/*').as('deleteQuizQuery');
```suggestion
            cy.intercept(DELETE, BASE_API + 'quiz-exercises/*').as('deleteQuizQuery');
```

2021-09-12 16:00 UTC, jhainzlschmid commented on src/test/cypress/integration/quiz-exercise/QuizExercise.spec.ts
> +            courseManagement.openExercisesOfCourse(courseName, courseShortName);
```suggestion
            courseManagement.openExercisesOfCourse(course.title, course.shortName);
```

2021-09-13 15:44 UTC, jhainzlschmid submitted a review, later dismissed
Since this PR has been open for quite some time already we decided to fix the still open refactorings in a future PR. I reran the tests in their current state and the [tests still pass in the buildplan](https://bamboo.ase.in.tum.de/browse/ARTEMIS-AETBBT-247), so I approve

2021-09-15 16:49 UTC, jhainzlschmid approved these changes
Merge conflict has been resolved and the [tests still pass on bamboo](https://bamboo.ase.in.tum.de/browse/ARTEMIS-AETBBT-267)

2021-09-15 19:07 UTC, merged