`General`: Fix issues with tutor performance in assessment dashboard
ls1intum/Artemis pull request #4169
Opened 2021-10-20 20:29 UTC by Olimbia23

### Checklist
#### General

- [X] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] *This is a small issue that I tested locally and was confirmed by another developer on a test server
- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
#### Server
- [ ] *I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] *I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] *I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [ ] *I implemented the changes with a good performance and prevented too many database calls.
- [ ] *I documented the Java code using JavaDoc style.
#### Client
- [X] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [X] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] *I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [X] I documented the TypeScript code using JSDoc style.
- [X] I added multiple screenshots/screencasts of my UI changes.
- [X] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] *I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] *I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

Instructor is interested in cases when a particular tutor performs worse than the average of the group. It would be nice to see which tutors have issues with performance and what exactly is wrong: bad scoring, bad rating or a lot of complaints? This PR solves this by computing the issues with tutor performance and showing it as a list in course assessment dashboard as well as marking the tutors with bad performance in the tutor leaderboard with ⚠️ near their name.

### Description

Issues with tutor performance are computed on the fly the client side. `TutorIssueRatingChecker`, `TutorIssueScoreChecker`, `TutorIssueComplaintsChecker` check if tutor has a performance issue with rating, score or complaints.
When it comes to complaints, complaints per submission ratio is computed, this way the performance issue is computed fairly.

Tutor performance issue is computed by computing the course average +/- 20%. This is the threshold value. If the tutor surpasses it, then he/she has a performance issue, which will be shown in the list.

### Steps for Testing

1. Log in to Artemis as Instructor
2. Navigate to Course Administration
3. Navigate to Course Assessment Dashboard
4. You should see the list with issues with tutor performance

### Review Progress

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

#### Before
<img width="1840" alt="before" src="https://user-images.githubusercontent.com/51077603/138154662-06284d8e-bb38-4438-b07f-e7bfba92ef74.png">

#### After - logged in as Instructor
<img width="1223" alt="Screenshot 2021-10-22 at 3 49 47 PM" src="https://user-images.githubusercontent.com/51077603/138465343-ac415bbb-7b6d-4c2f-8cc6-3dfbb73e7907.png">

2021-10-26 21:25 UTC, julian-christl submitted a review, later dismissed
Code looks good so far, let's monitor the values and see how they behave in production 👍

2021-10-29 23:40 UTC, Olimbia23 reviewed
Thank you for your review @lschlesinger.
I applied all your suggestions 😇

2021-10-30 08:55 UTC, lschlesinger requested changes
There is  a failing client test suite for `TutorLeaderboardComponent`
https://github.com/ls1intum/Artemis/runs/4052298509?check_suite_focus=true

Once this is fixed, I can manually test again :)

2021-10-30 08:55 UTC, lschlesinger commented on src/main/webapp/app/course/dashboards/assessment-dashboard/tutor-issue.ts
> + * Represents the an inclusive range with a lower and upper bound
the + an, one could be removed

2021-10-30 20:14 UTC, lschlesinger submitted a review, later dismissed
I tested again on TS1. issues were shown as expected 👍

2021-10-30 23:49 UTC, julian-christl requested changes
Found some test guideline issues, sorry :/ 😅

2021-10-30 23:49 UTC, julian-christl commented on src/test/javascript/spec/component/assessment-dashboard/assessment-dashboard.component.spec.ts
> +        expect(comp.examId).toEqual(20);
```suggestion
        expect(comp.courseId).toBe(10);
        expect(comp.examId).toBe(20);
```

2021-10-30 23:49 UTC, julian-christl commented on src/test/javascript/spec/component/assessment-dashboard/assessment-dashboard.component.spec.ts
> +        expect(getStatsForExamAssessmentDashboardStub).toHaveBeenCalledOnce();
```suggestion
        expect(getExamWithInterestingExercisesForAssessmentDashboardStub).toHaveBeenCalledTimes(1);
        expect(getStatsForExamAssessmentDashboardStub).toHaveBeenCalledTimes(1);
```

2021-10-30 23:49 UTC, julian-christl commented on src/test/javascript/spec/component/assessment-dashboard/assessment-dashboard.component.spec.ts
> +        expect(comp.courseId).toEqual(10);
```suggestion
        expect(comp.courseId).toBe(10);
```

2021-10-30 23:49 UTC, julian-christl commented on src/test/javascript/spec/component/assessment-dashboard/assessment-dashboard.component.spec.ts
> +        expect(getStatsForTutorsStub).toHaveBeenCalledOnce();
```suggestion
        expect(getCourseWithInterestingExercisesForTutorsStub).toHaveBeenCalledTimes(1);
        expect(getStatsForTutorsStub).toHaveBeenCalledTimes(1);
```

2021-10-30 23:49 UTC, julian-christl commented on src/test/javascript/spec/component/assessment-dashboard/assessment-dashboard.component.spec.ts
> +        expect(updateExercisesSpy).toHaveBeenCalledOnce();
```suggestion
        expect(updateExercisesSpy).toHaveBeenCalledTimes(1);
```

2021-10-30 23:49 UTC, julian-christl commented on src/test/javascript/spec/component/assessment-dashboard/assessment-dashboard.component.spec.ts
> +        expect(sortServiceSpy).toHaveBeenCalledOnce();
```suggestion
        expect(sortServiceSpy).toHaveBeenCalledTimes(1);
```

2021-10-31 10:14 UTC, Olimbia23 commented
I addressed your suggestions @julian-christl, even though these changes were not introduced by me and were already in develop.

2021-10-31 11:50 UTC, julian-christl approved these changes
Thank you @Olimbia23, appreciate it.

2021-10-31 19:49 UTC, lschlesinger submitted a review, later dismissed
Re-approve, changes to the test files look good!

2021-11-03 08:14 UTC, MerlinMehmed approved these changes
Retested on TS1, still works as expected!

2021-11-03 13:30 UTC, julian-christl approved these changes
Reapprove Code

2021-11-03 14:08 UTC, lschlesinger approved these changes
Re-approve! Did not see 17 successful github checks for a long time 😄

2021-11-04 08:58 UTC, merged