`General`: Add CSV file team import and provide better error messages
ls1intum/Artemis pull request #4327
Opened 2021-11-17 22:03 UTC by Hialus

Imrpove error messages

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2021-11-30 17:05 UTC, mallgaier approved these changes
Tested together with @lBruchmann and @Strohgelaender.  Import tested using JSON. Users with incorrect usernames are ignored and not imported.
If a team name does not start with a letter, a corresponding browser error message is displayed.

2021-11-30 17:07 UTC, lBruchmann submitted a review, later dismissed
Tested together with @Strohgelaender and @mallgaier. Tested on ts1. I followed the test steps. Importing valid and invalid (both .json and .csv files) works as expected. We have one small comment, see @Strohgelaender .

2021-11-30 17:08 UTC, Strohgelaender submitted a review, later dismissed
Tested in testing session with @lBruchmann @mallgaier on ts1. The import worked for both csv and json files and the enhanced error messaged were shown if invalid input was provided. But directly pasting the example provided in #1994 did not work, since it uses both `;` and `,` as a separator. We might have to recheck whether or not this is indeed the format that is provided by moodle, if yes the import stil won't work.

2021-12-01 00:07 UTC, Hialus commented
> Tested in testing session with @lBruchmann @mallgaier on ts1. The import worked for both csv and json files and the enhanced error messaged were shown if invalid input was provided. But directly pasting the example provided in #1994 did not work, since it uses both `;` and `,` as a separator. We might have to recheck whether or not this is indeed the format that is provided by moodle, if yes the import stil won't work.

If this is actually the format that Moodle uses the user will have to fix this before importing it.
While the tool used for parsing the CSV file (Papa Parse) tries to automatically detect the used separator, it does not support different separators in one file.

2021-12-02 09:03 UTC, Garfield96 requested changes
Nice PR. Thanks for fixing my issues. Please update the UI and documentation to show the user which input formats are supported now.

2021-12-03 15:51 UTC, Hialus commented
I have removed the code duplication in the test cases and added the supported file types to the import dialog.
However, I could not find any documentation about the teams import feature, so I cannot update it. And it would be out of scope for this PR to add an entire documentation page about the teams feature.

2021-12-06 13:38 UTC, Malyuk-A reviewed
small type, else approve

2021-12-06 13:38 UTC, Malyuk-A commented on src/main/webapp/i18n/de/team.json
> +                "missingTeamName": "Studierende:r {{ studentName }} in Eintrag {{ entryNr }} ist kein Teamname zuordnet.",
```suggestion
                "missingTeamName": "Studierende:r {{ studentName }} in Eintrag {{ entryNr }} ist kein Teamname zugeordnet.",
```

2021-12-06 13:41 UTC, julian-christl commented on src/test/javascript/spec/component/team/teams-import-from-file-form.component.spec.ts
> +        let control: any;
Please avoid `any`.

2021-12-06 13:41 UTC, julian-christl commented on src/main/webapp/app/exercises/shared/team/teams-import-dialog/teams-import-from-file-form.component.ts
>          importTeam.forEach((student) => {
```suggestion
        importTeam.forEach((student, index) => {
```
You can the remove `entryNr` and use `index + 1`

2021-12-06 13:56 UTC, julian-christl approved these changes
Code looks good now

2021-12-06 13:56 UTC, Malyuk-A approved these changes
Code looks good

2021-12-06 14:04 UTC, daniels98it approved these changes
No complaint on code 👍

2021-12-06 14:05 UTC, Garfield96 approved these changes

2021-12-07 22:41 UTC, merged