`Development`: Refactor routing mocks
ls1intum/Artemis pull request #4343
Opened 2021-11-20 22:32 UTC by MDK5

### Checklist
#### General
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).

### Motivation, Context and Description
Previously, Artemis contained two definitions of a MockRouter, two definitions of MockActivatedRoute and about five definitions of the MockRouterLinkDirective, which were then imported to various unrealted places. This PR unifies this into one definition for each and adapts all affected imports.

Also converts two test to jest which was needed to deal with the jest mocks in the new MockRouter.

I recommend to review with whitespace changes disabled.

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2

### Test Coverage

2021-11-22 15:57 UTC, lschlesinger approved these changes
Nice, this makes the dependencies among tests way cleaner for the future use of `npm run test-diff`, thanks for refactoring and providing a mock that is consistently shared by all tests.

2021-11-22 15:57 UTC, lschlesinger commented on src/test/javascript/spec/component/admin/audits.component.spec.ts
> +        TestBed.configureTestingModule({
you could change the order according to our guidelines here

2021-11-23 00:35 UTC, julian-christl requested changes

2021-11-23 00:35 UTC, julian-christl commented on src/test/javascript/spec/service/navigation-util.service.spec.ts
>      });
```suggestion
    });
    
```

2021-11-23 00:35 UTC, julian-christl commented on src/test/javascript/spec/service/navigation-util.service.spec.ts
>      });
```suggestion
    });
    
```

2021-11-23 13:29 UTC, MDK5 commented on src/test/javascript/spec/component/admin/audits.component.spec.ts
> +            expect(comp.toDate).toBe(getDate());
Probably. If the tests happen to be executed exactly at 0:00 and the onInit gets the old date, but the expecrt the new, the tests will probably fail. I think this is out of scope for this PR, though.

2021-11-23 13:57 UTC, julian-christl approved these changes
Thanks for the changes.

2021-11-23 13:58 UTC, lschlesinger approved these changes
Looks good, let's merge :)

2021-11-23 15:04 UTC, merged