`Assessment`: Show logic for assessment training
ls1intum/Artemis pull request #4388
Opened 2021-11-27 15:30 UTC by Olimbia23

### Checklist
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] *This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [ ] *I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] *I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] *I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [ ] *I implemented the changes with a good performance and prevented too many database calls.
- [ ] *I documented the Java code using JavaDoc style.
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [ ] *I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] *I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] *I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] *I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] *I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

[ ] * - not needed

### Motivation and Context

In order to add clarity to the tutors on how exactly is their assessment evaluated, a new section in the instructions view is added. This section should only be shown when tutor is assessing example submissions.
Extra heading is also added in example submissions screen (as shown in the screenshot below)

### Description

I added a new section in the `assessment-instructions.component` as well as the new heading in the `example-text-submissions` and exaple-modeling-submissions` components.

### Steps for Testing

Prerequisites:
- 1 Tutor

1. Log in to Artemis
2. Navigate to Course Administration
3. Navigate to Assessment Dashboard of the Exercise that has Example Submissions to *assess*
4. Click on Assess example submission
5. In the instructions panel on the right you should see the "Assessment Training Evaluation Criteria" section

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots

<img width="1297" alt="Screen Shot 2021-11-27 at 15 53 35" src="https://user-images.githubusercontent.com/51077603/143686368-9db35556-b34a-423f-8c1d-3182229c5ce5.png">
<img width="664" alt="Screen Shot 2021-11-27 at 15 25 09" src="https://user-images.githubusercontent.com/51077603/143685749-f22ab071-f966-41af-bd21-518e80719f00.png">

2021-11-27 19:06 UTC, Malyuk-A requested changes
Tested on TS1. It is showed just as described 👍
I have found some minimal translation issues and a few nitpicks in the code

2021-11-27 19:30 UTC, Olimbia23 reviewed
Thanks a lot for testing and reviewing it @Malyuk-A 
I applied your suggestions 😀

2021-11-27 19:30 UTC, Olimbia23 commented on src/main/webapp/app/exercises/text/manage/example-text-submission/example-text-submission.component.html
> +<h5 *ngIf="toComplete" class="mt-3" style="font-weight: 300">{{ 'artemisApp.exampleSubmission.home.assessmentTraining' | artemisTranslate }}</h5>
You are right. Applied the `fw-light` class.

2021-11-27 19:30 UTC, Olimbia23 commented on src/main/webapp/i18n/en/assessmentInstructions.json
> +            "description": "In order to successfully complete the training, your assessment should match all of the following criteria:<br>&nbsp;1. Number of feedback that you provide should be the s
Couldn't commit your translation suggestions as `feedback` is the terminology we agreed on using in Artemis for plural. But I have incorporated the rest.

2021-11-27 19:30 UTC, Olimbia23 commented on src/main/webapp/i18n/de/assessmentInstructions.json
> +            "description": "Um das Assessment-Training erfolgreich abzuschließen, sollte Ihre Bewertung alle folgenden Kriterien erfüllen:<br>&nbsp;1. Die Anzahl der Feedbacks, die Sie geben, sollte
Adjusted the german translation.

2021-11-27 19:55 UTC, MerlinMehmed submitted a review, later dismissed
Tested on TS1, works as expected. Code changes also look good.

2021-11-27 21:33 UTC, filip-gregurevic approved these changes
Code changes look good to me

2021-11-27 21:46 UTC, filip-gregurevic approved these changes
Code changes look good to me

2021-11-28 07:14 UTC, argertboja submitted a review, later dismissed
Tested on TS1 and works as expected 😃 

Well done @Olimbia23 👍🏼

2021-11-28 09:25 UTC, Malyuk-A approved these changes
Thank you for addressing my change requests. Approved 👍

2021-12-01 21:55 UTC, merged