`Programming exercises`: Fix an issue when creating external submissions
ls1intum/Artemis pull request #4414
Opened 2021-12-01 10:26 UTC by krusche

Prevent a LazyInitializationException by using the correct exercise object

see #4411 

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.

### Steps for Testing

Prerequisites:
1. Create a programming exercise
2. Add an external submission
3. Make sure everything works correctly (check the participation, submission and scores page)

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

2021-12-01 15:07 UTC, dfuchss approved these changes
Tested on our test systems. Commit resolved issue!

2021-12-03 09:03 UTC, fh314 requested changes
(deleted) wrong branch used, review in progress
edit: tested on ts1 and works fine

2021-12-03 09:17 UTC, fh314 approved these changes

2021-12-03 15:43 UTC, VinnavanSembian approved these changes
tested on ts1. This works correctly

2021-12-04 16:22 UTC, dfuchss commented
@krusche I've added an IT. Feel free to modify the test.

2021-12-04 16:24 UTC, dfuchss approved these changes
Simply added an IT to prevent similar issues in the future.

2021-12-05 20:17 UTC, baranimo7 submitted a review, later dismissed
Tested on ts1, everything works correct

2021-12-05 21:12 UTC, krusche commented
@dfuchss thanks, unfortunately the test fails. I'll try to have a look as soon as possible. If you find the time to review the failure before, even better

2021-12-05 21:25 UTC, dfuchss commented
Mmh locally it worked yesterday.

2021-12-05 21:26 UTC, MertAksehirlioglu reviewed
Tested on ts1. After adding an external submission (with full points) Average Score in the Exercise Page is not updated (Participation rate gets updated):
![Screen Shot 2021-12-05 at 22 22 11](https://user-images.githubusercontent.com/23525970/144764406-e357a760-dac0-442f-9128-a5a8a78ef7c1.png)
Other views such as:
Submissions
Participation
Scores are updated but the in the Statistics page Average Score is also not updated.

2021-12-05 22:37 UTC, dfuchss commented
@krusche maybe it works now. Nevertheless, locally it has passed.

2021-12-06 08:49 UTC, krusche commented
> @krusche maybe it works now. Nevertheless, locally it has passed.

Thank you, now it passes.

2021-12-06 11:04 UTC, dfuchss approved these changes
Re-Approve

2021-12-06 15:12 UTC, krusche commented
There are still some necessary improvements for the server integration test:
1. We actually don't want to mock methods in `versionControlService` (see comment in superclass), it's better to mock communication with Gitlab and Jenkins so that all our code is actually executed, there could theoretically still be exceptions in GitlabService because database objects have not been loaded or configured correctly. For mocking the communication with Gitlab and Jenkins there are some examples in the code, you can probably even use methods that already do that.
2. We should also call the test in the context of Bitbucket/Bamboo. To avoid code duplication, we then create a TestService with the test logic and call that from two actual tests. There are a few examples in the code for this, e.g. `ProgrammingExerciseTestService`.
3. it would be even better if the test calls the REST call in the `ResultResource`, then the complete server code would be tested (and not "only" the service).


We decided to work on those improvements in a follow-up so that the bugfix can be merged and deployed

2021-12-06 15:19 UTC, merged