`Assessment`: Display subsequent feedback in the assessment review when the usage limit of assessment instruction is exceed
ls1intum/Artemis pull request #4500
Opened 2021-12-14 02:39 UTC by imstreetspirit

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [ ] I implemented the changes with a good performance and prevented too many database calls.
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

Fixes #4442 

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2021-12-21 14:07 UTC, Strohgelaender requested changes
Tested on TS1 with @cremertim @VinnavanSembian @lBruchmann @willergeorg @Bofan-Zhu. For Programming, Modeling, and File Upload Exercises everything works as expected. The overused grading instructions are displayed gray for the student and reevaluating after changing the maximum usage correctly updates the score and the changes are reflected in the students view.

But for text exercises, the reevaluation does not work. The re-evaluate endpoints returns an internal server error due to a null pointer exception: "Cannot invoke "de.tum.in.www1.artemis.domain.Result.getId()" because the return value of "de.tum.in.www1.artemis.domain.Submission.getLatestResult()" is null".

Additionally, it would be nice to directly show the gray background while assessing the submission. When the tutor uses a grading instruction more than the defined limit, every usage still has a green background. I think we could prevent assessment mistakes when the tutor already sees the instruction gray here.

2021-12-21 14:08 UTC, VinnavanSembian reviewed
Tested on ts1 with @Strohgelaender @lBruchmann @cremertim @willergeorg @Bofan-Zhu. See @Strohgelaender for remarks!

2021-12-21 14:09 UTC, willergeorg reviewed
See @Strohgelaender s remarks

2021-12-21 14:10 UTC, lBruchmann reviewed
Tested on ts1. I followed the testing steps. Everything works as described. See @Strohgelaender  for some remarks.

2021-12-21 14:11 UTC, Bofan-Zhu reviewed
Tested on ts1 with @Strohgelaender @VinnavanSembian @cremertim @lBruchmann and
@willergeorg. Works fine for every exercise type except text exercises -> see @Strohgelaender's request for changes.

2021-12-21 14:24 UTC, cremertim reviewed
see remarks from @Strohgelaender

2021-12-29 14:45 UTC, Strohgelaender approved these changes
Retested on TS1, the re-evaluation is fixed and the subsequent feedback is shown correctly.

2022-01-11 15:05 UTC, Strohgelaender requested changes
Tested on TS1 with @lBruchmann @willergeorg @VinnavanSembian. The feedback was shown correctly in the feedback popup, but there are some smaller inconsistencies when viewing the own submission. There is also a huge problem with complaints and the grading instructions:

For programming exercises, the code editor still showed every feedback with a green color, even if its subsequent feedback.

![grafik](https://user-images.githubusercontent.com/26540346/148964881-a7cd0ed3-1b0c-4499-a01b-22516d48e485.png)

For modeling exercises, the table shows the feedback in gray, but the corresponding element stil has a green tick. 

![grafik](https://user-images.githubusercontent.com/26540346/148964986-11721f35-ba42-4b41-9aa9-a86d31d9c97f.png)
(ignore the "Limit: 2"-text here, we re-evaluated it to 1 afterwards, this behavior is correct)

After accepting a complaint, the connection with the instruction apparently gets removed. There is no more gray feedback visible for the students and the points are counted towards the score, leaving the student with a higher score than expected.

2022-01-11 15:05 UTC, willergeorg reviewed
Tested during testing session with a programming exercise and a modeling exercise. We observed some issues. See @Strohgelaender s remarks.

2022-01-11 15:07 UTC, VinnavanSembian reviewed
tested during testing session with @Strohgelaender @lBruchmann @willergeorg on ts1. See @Strohgelaender for remarks.

2022-01-11 15:08 UTC, lBruchmann approved these changes
Tested on ts1. Tested together with @Strohgelaender, @VinnavanSembian and @willergeorg. See @Strohgelaender for some remarks .

2022-01-11 15:41 UTC, imstreetspirit commented
Thanks for your review again.

> For programming exercises, the code editor still showed every feedback with a green color, even if its subsequent feedback.

I think it can be resolved in the scope of this PR.

> For modeling exercises, the table shows the feedback in gray, but the corresponding element still has a green tick.

the model is shown in the Apollon editor, so if we want to change it requires some changes/additional logic on the Apollon side. I am not sure if we want this logic in the Apollon editor, I can ask. However, I do not think that it affects what this PR wants to achieve. 

> After accepting a complaint, the connection with the instruction apparently gets removed. There is no more gray feedback visible for the students and the points are counted towards the score, leaving the student with a higher score than expected.

well, I am not familiar with the newly changed complaint handling process in Artemis and I did not touch any part related to complain logic, it seems like an issue with result calculation after accepting a complaint. It does not relate to this PR, feel free to open a ticket for this issue.

2022-01-15 23:46 UTC, imstreetspirit commented
Now the code editor displays the subsequent feedback for students. The PR is ready to review/test again.

2022-01-17 16:13 UTC, willergeorg reviewed
I tested on TS1 the case that the assessment was not shown correctly in the programming exercise editor (subsequent feedback was not colored grey). This worked for me now. Good job!
I also had a look at your code. My comments regarding the translations are only preferences as I found that the enumeration was not clearly separated. But let me know your opinion on this.
Regarding the test code I marked you some small things.

2022-01-17 16:13 UTC, willergeorg commented on src/main/webapp/i18n/de/exercise.json
> +            "gradingScaleHint": "Die Skala beschreibt das Leistungsniveau für den Anweisung. Einige Beispiele sind ausgezeichnet, gut, durchschnittlich, schlecht.",
```suggestion
            "gradingScaleHint": "Die Skala beschreibt das Leistungsniveau für den Anweisung. Einige Beispiele hierfür sind: ausgezeichnet, gut, durchschnittlich, schlecht.",
```

2022-01-17 16:13 UTC, willergeorg commented on src/main/webapp/i18n/en/exercise.json
> +            "gradingScaleHint": "The scale describes the performance level for the instruction. Some examples are excellent, good, average, poor.",
```suggestion
            "gradingScaleHint": "The scale describes the performance level for the instruction. Some examples are: excellent, good, average, poor.",
```

2022-01-17 16:13 UTC, willergeorg commented on src/test/javascript/spec/component/modeling-submission/modeling-submission.component.spec.ts
> +        expect(unreferencedFeedback!.length).toBe(1);
```suggestion
        expect(unreferencedFeedback!).toHaveLength(1);
```

2022-01-17 16:13 UTC, willergeorg commented on src/test/javascript/spec/component/modeling-submission/modeling-submission.component.spec.ts
> +        expect(referencedFeedback!.length).toBe(1);
```suggestion
        expect(referencedFeedback!).toHaveLength(1);
```

2022-01-17 16:13 UTC, willergeorg commented on src/test/javascript/spec/component/file-upload-submission/file-upload-submission.component.spec.ts
> +        expect(unreferencedFeedback!.length).toBe(2);
```suggestion
        expect(unreferencedFeedback!).toHaveLength(2);
```

2022-01-17 16:13 UTC, willergeorg commented on src/test/javascript/spec/component/text-result/text-result.component.spec.ts
> +        expect(component.textResults.length).toBe(2);
```suggestion
        expect(component.textResults).toHaveLength(2);
```

2022-01-17 16:51 UTC, imstreetspirit commented on src/main/webapp/i18n/en/exercise.json
> +            "gradingScaleHint": "The scale describes the performance level for the instruction. Some examples are excellent, good, average, poor.",
it makes sense 👍

2022-01-18 13:56 UTC, willergeorg approved these changes
Code lgtm now. Functionality worked for me as well.

2022-01-18 13:56 UTC, mallgaier approved these changes
Tested together with @lBruchmann , @Strohgelaender , @VinnavanSembian and @willergeorg .
The functionality was implemented as expected.

2022-01-18 13:56 UTC, VinnavanSembian approved these changes
tested on ts1 with @lBruchmann @Strohgelaender @mallgaier @willergeorg. Everything works as expected now! Thank you!

2022-01-18 13:57 UTC, lBruchmann approved these changes
Tested on ts1. Tested together with @Strohgelaender, @mallgaier, @willergeorg, and @VinnavanSembian. We followed the testing steps. Everything works as expected.

2022-01-18 13:58 UTC, Strohgelaender approved these changes
Tested with @lBruchmann @VinnavanSembian @mallgaier @willergeorg on TS1. Everything worked as expected, thanks for implementing my request.

2022-01-19 17:30 UTC, MerlinMehmed approved these changes
Code changes look good to me!

2022-01-19 19:25 UTC, merged