`Assessment`: Improve the comprehensibility
ls1intum/Artemis pull request #4503
Opened 2021-12-14 12:05 UTC by valeriebucher

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

### Description

Reducing confusion for displaying '0' as the value for unlimited applicable grading instructions by exchanging it with infinity symbol '∞'.

### Steps for Testing

Prerequisites:
- 1 Editor/Instructor
- 1 Programming/Modeling/Text/File-Upload Exercise with Structured Grading Criteria

1. Create an Exercise 
2. Create grading criteria with `Limit` greater than 0
3. Create grading criteria with `Limit` equal to 0 or undefined `Limit`
4. See that the value for undefined or equal to 0 `Limit` is now an infinity symbol '∞', otherwise the `Limit` is displayed as the defined number

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots

Updated version:

<img width="279" alt="Bildschirmfoto 2021-12-14 um 12 55 21" src="https://user-images.githubusercontent.com/73841445/145993756-47aab91d-525d-4158-82b2-9dde4d16d9f0.png">

Old version:

<img width="392" alt="Components of structured assessment" src="https://user-images.githubusercontent.com/73841445/145994284-77d3ce9d-8553-4b96-9fb0-95833c67cef2.png">

2021-12-14 12:45 UTC, FlorianGlombik approved these changes
Tested on ts1, works as described for 0/undefined and defined values such as 2 and should be easier understandable than the current solution.
The code changes look good to me.

<details>
<summary>Screenshot of updated grading criteria</summary>

![image](https://user-images.githubusercontent.com/63976129/146000486-47afd462-1609-4638-8956-7f04911120ea.png)
</details>

2021-12-14 13:12 UTC, cremertim approved these changes
tested on ts2, the infinite symbol is displayed as expected. 👍 
tested @lBruchmann @Strohgelaender @Bofan-Zhu @VinnavanSembian

2021-12-14 13:22 UTC, Bofan-Zhu submitted a review, later dismissed
Looks good. Infinity symbol is displayed for Limit 0 and undefined.

2021-12-14 13:24 UTC, VinnavanSembian submitted a review, later dismissed
tested in testing session on ts2. Looks good to me!

2021-12-14 13:26 UTC, willergeorg submitted a review, later dismissed
Tested on TS1. Worked fine. I have a small suggestion. Whenever possible, try to avoid explicit styling within the html template. I marked two affected spots. Reuse or declare CSS classes for this or use bootstrap classes.

2021-12-14 13:26 UTC, lBruchmann approved these changes
Tested on ts2. I followed the testing steps. Everything works and is displayed as expected. "0" is switched with the "∞" character.

2021-12-14 13:26 UTC, willergeorg commented on src/main/webapp/app/assessment/structured-grading-instructions-assessment-layout/structured-grading-instructions-assessment-layout.component.html
> +                        <td [innerHTML]="setScore(instruction.credits)" style="width: 4%"></td>
Here

2021-12-14 13:26 UTC, willergeorg commented on src/main/webapp/app/assessment/structured-grading-instructions-assessment-layout/structured-grading-instructions-assessment-layout.component.html
> +                        <td style="width: 4%; position: relative; white-space: nowrap">
Here

2021-12-14 13:28 UTC, Strohgelaender requested changes
Tested on TS2, worked as expected. I agree with the requested changes by @willergeorg.

2021-12-14 13:45 UTC, FlorianGlombik commented
@Strohgelaender @willergeorg Are you sure that a class with 4% width exist from bootstrap? I can not find one that would fit in the [documentation](https://getbootstrap.com/docs/5.0/utilities/sizing/)

2021-12-14 14:15 UTC, Strohgelaender submitted a review, later dismissed
After discussion with @FlorianGlombik I agree that this is one possible exception for the general "style should be separated from html" rule.

2021-12-14 14:26 UTC, baranimo7 approved these changes
Tested on TS1. ∞ is shown correctly.

2021-12-15 12:38 UTC, MertAksehirlioglu approved these changes
Tested on TS2, worked as expected.

2021-12-15 16:33 UTC, coaxial1 commented
I'd vote for moving the inline styles to scss. We have 3 (!) inline styles in this file.
I've prepared this here real quick if you want to use it: https://github.com/ls1intum/Artemis/commit/e07bd820d0c640271569431762e63805157a1a8f

2021-12-15 17:40 UTC, valeriebucher commented
thank you @coaxial1 ! Makes sense and looks good to me. I added your commit.

2021-12-15 19:17 UTC, ole-ve approved these changes
Tested on TS1, works as described. 👍

2021-12-16 15:09 UTC, willergeorg approved these changes
Code changes since last review look good.

2021-12-17 11:04 UTC, mallgaier approved these changes
Tested on ts3. 
The functionality was implemented as described. If no limit is defined, infinity is now displayed instead of 0.

2021-12-17 22:56 UTC, jpbernius approved these changes
:shipit:

2021-12-18 11:40 UTC, merged