`Development`: Refactor server exam access permission checks
ls1intum/Artemis pull request #4568
Opened 2022-01-01 09:24 UTC by b-fein

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
In `ExamAccessService` the permission checks returned an optional failure instead of directly throwing an `EntityNotFound`/`Conflict`/`AccessForbidden`/…-exception.

### Description
This PR refactors this service to follow the access check style for exercises and courses.

### Steps for Testing
Prerequisites:
- 1 Exam with Instructor, Tutor, Student

This PR affects all server endpoints related to exams. Therefore, please check that you can access the various pages/parts for an exam as before.
No functional changes should have been made.

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage
| Unit | Branch | Line |
| --- | --- | --- |
| `ExamAccessService` | TODO | TODO |

2022-01-08 19:53 UTC, krusche requested changes
Thanks a lot for the great work. This makes the code much more readable and easier to understand! 

In a recent commit, I changed how the `ConflictException` works. It is now closer to the `BadRequestAlertException` and needs some parameters such as an error message. Could you please adapt the places in which you use it. You should receive compile errors.

Thanks again!

2022-01-21 19:45 UTC, krusche commented on src/main/java/de/tum/in/www1/artemis/service/exam/ExamAccessService.java
> +    private static final String ENTITY_NAME = "exam";
```suggestion
    private static final String ENTITY_NAME = "Exam";
```

2022-01-21 19:48 UTC, krusche commented on src/main/java/de/tum/in/www1/artemis/web/rest/StudentExamResource.java
> +            throw new AccessForbiddenException("exam", examId);
```suggestion
            throw new AccessForbiddenException("Exam", examId);
```

2022-01-21 19:48 UTC, krusche commented on src/main/java/de/tum/in/www1/artemis/web/rest/StudentExamResource.java
> +            throw new AccessForbiddenException("exam", examId);
```suggestion
            throw new AccessForbiddenException("Exam", examId);
```

2022-01-22 10:43 UTC, MerlinMehmed submitted a review, later dismissed
Code changes look good to me. I also tested exam functionality on TS1. I created an exam with two exercise groups and participated as a student. It all worked fine. Exam assessment and deletion is also okay.
However, I found an issue but it was not introduced by this PR as I reproduced it on TS3 as well. As this is not introduced here, I approve the PR. The issue I faced is described below:
As a student who reviews the exam, I cannot properly do this action. See the screenshot: 
![Screenshot from 2022-01-22 12-19-14](https://user-images.githubusercontent.com/20031592/150634963-efc6ef47-2acc-4008-92e5-6de75b6b1b4f.png)
The first exercise is ok but the second one (the second box including only ] ) is not properly shown.

2022-01-22 11:30 UTC, MerlinMehmed approved these changes
Reapprove after entity name change.

2022-01-23 10:14 UTC, merged