`Development`: Fix charts on course management and course detail page
ls1intum/Artemis pull request #4575
Opened 2022-01-03 17:29 UTC by willergeorg

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I implemented the changes with a good performance and prevented too many database calls.
### Motivation and Context

This PR fixes #4574 
### Description

So far, the aggregation of active users for different weeks did not take into account the following edge case appropriately:
The displayed timespan includes two different years and the most recent week has active users > 0.
The current implementation handles this case somehow by applying an offset to the most recent week in order to allocate the correct array position. The problem is, that the offset is hardcoded to 53 calendar weeks which does not necessarily hold for every year (if you are interested, read more about this on e.g. [Wikipedia](https://de.wikipedia.org/wiki/Woche#:~:text=Z%C3%A4hlweise%20nach%20ISO%208601%5BBearbeiten%20%7C%20Quelltext%20bearbeiten%5D)).
This leads currently to internal server errors as the server tries to access an array position that is out of bounds.
I changed the implementation so that it identifies the amount of calendar weeks for the prior year and applies the appropriate offset in case of such a situation as described above.
### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course with activity in the most recent week

1. Log in to Artemis
2. Navigate to Course Administration
3. Make sure no internal server error is thrown and the charts are filled with data
4. Click on the course card and check the same for the chart on the course detail page.

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2022-01-03 19:46 UTC, b-fein requested changes
Is there a difference between the new calculation and using the provided standard library functionality instead?
```java
int weeksDifference = (int) ChronoUnit.WEEKS.between(startDate, date);
```

In any case, `StatisticsRepository::mergeResultsIntoArrayForQuarter` needs the exact same fix. Can you apply it there as well (ideally without duplicating code if the standard library cannot be used)?

2022-01-03 19:46 UTC, b-fein commented on src/main/java/de/tum/in/www1/artemis/service/CourseService.java
>              int weeksDifference;
```suggestion
```

2022-01-03 19:46 UTC, b-fein commented on src/main/java/de/tum/in/www1/artemis/service/CourseService.java
> +            weeksDifference = dateWeek < startDateWeek ? dateWeek == startDateWeek - 1 ? 0 : dateWeek + lastCalendarWeek - startDateWeek : dateWeek - startDateWeek;
```suggestion
            int weeksDifference = dateWeek < startDateWeek ? dateWeek == startDateWeek - 1 ? 0 : dateWeek + lastCalendarWeek - startDateWeek : dateWeek - startDateWeek;
```
With the double ternary operator it is also quite hard to understand what is going on in this line. Can you change it into a nested if-else, please?

2022-01-04 00:13 UTC, akesfeden commented
First of all, thanks for spotting and working on this bug, I also have failing tests because of it.

I agree with @b-fein on using `ChronoUnit.WEEKS.between(startDate, date)` (or equivalent `startDate.until(date, ChronoUnit.WEEKS)`) if it is applicable.

2022-01-04 10:07 UTC, willergeorg commented
First of all, thanks @b-fein and @akesfeden for taking the time and reviewing my changes. Unfortunately, there were some devs that worked on this problem in parallel without knowing someone else already has a look on it. As @krusche already fixes this problem in #4571 and additionally reduces the code duplication there, this PR is obsolete.

2022-01-04 10:07 UTC, closed without merging