`Development`: Remove use of deprecated methods
ls1intum/Artemis pull request #4637
Opened 2022-01-24 21:56 UTC by krusche

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [ ] I implemented the changes with a good performance and prevented too many database calls.
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2022-01-25 09:24 UTC, Strohgelaender submitted a review, later dismissed
I went through all files and did not spot any mistakes, the changes look good. I only added a small suggestion:

2022-01-25 09:24 UTC, Strohgelaender commented on src/main/java/de/tum/in/www1/artemis/service/SubmissionService.java
> +            optionalSubmission.ifPresent(submissions::add);
I think we can replace this whole loop:
```
List<Submission> submissions = studentParticipationPage.getContent().stream()
    .map(Participation::findLatestSubmission())
    .filter(Optional::isPresent)
    .toList();
```

2022-01-25 15:05 UTC, coaxial1 approved these changes
Besides the comment above (which I second), I did not spot any mistakes. LGTM.

2022-01-25 18:19 UTC, b-fein requested changes

2022-01-29 10:37 UTC, b-fein requested changes
I think there are a few more methods which should get the `ElseThrow` suffix. And I found a typo. Looks good otherwise.

2022-01-29 10:37 UTC, b-fein commented on src/main/java/de/tum/in/www1/artemis/service/exam/StudentExamAccessService.java
> +    public void checkCourseAndExamAccess(Long courseId, Long examId, User currentUser, boolean isTestRun) {
```suggestion
    public void checkCourseAndExamAccessElseThrow(Long courseId, Long examId, User currentUser, boolean isTestRun) {
```

2022-01-29 10:37 UTC, b-fein commented on src/main/java/de/tum/in/www1/artemis/service/exam/StudentExamAccessService.java
> +    public void checkStudentExamAccess(Long courseId, Long examId, Long studentExamId, User currentUser, boolean isTestRun) {
```suggestion
    public void checkStudentExamAccessElseThrow(Long courseId, Long examId, Long studentExamId, User currentUser, boolean isTestRun) {
```

2022-01-29 10:37 UTC, b-fein commented on src/main/java/de/tum/in/www1/artemis/service/exam/StudentExamAccessService.java
> +    public void checkStudentExamAccess(Long courseId, Long examId, Long studentExamId, boolean isTestRun) {
```suggestion
    public void checkStudentExamAccessElseThrow(Long courseId, Long examId, Long studentExamId, boolean isTestRun) {
```

2022-01-29 10:37 UTC, b-fein commented on src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingSubmissionResource.java
> +            throw new EntityNotFoundException("Cannot trigger failed build. There is a submission after exercise duet date");
```suggestion
            throw new EntityNotFoundException("Cannot trigger failed build. There is a submission after the exercise due date");
```

2022-01-29 11:07 UTC, b-fein approved these changes
The changes since the last review look good. I did not see anything else during the re-review. :+1:

2022-01-29 13:26 UTC, merged