`Assessments`: Fix filter for finished exercises with complaints for automatic assessment
ls1intum/Artemis pull request #4641
Opened 2022-01-25 18:17 UTC by JohannesStoehr

### Checklist
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).

### Motivation, Context and Description

Fix a bug where exercises with complaints on automated assessments would still be shown in the tutor assessment dashboard even though they were finished.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 Programming Exercise with Complaints on automatic assessments enabled

1. Create the exercise, participate as a student and complain after the deadline on the automatic assessment
2. Check that the exercise appears correctly on the assessment dashboard
3. Respond to the complaint
4. Check that the finished exercise is correctly filtered

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

2022-01-25 19:02 UTC, b-fein requested changes
Code change makes sense. :+1: 

Is it somewhat easily possible to add a unit-test to make sure this bug doesn’t happen again?

2022-01-25 19:07 UTC, JohannesStoehr commented on src/main/webapp/app/course/dashboards/assessment-dashboard/assessment-dashboard.component.ts
> +                        exercise.totalNumberOfAssessments?.inTime !== exercise.numberOfSubmissions?.inTime)) ||
On it 👍

2022-01-25 19:48 UTC, b-fein approved these changes
Thanks for addressing the comments, looks good now with only one small nitpick remaining. :+1:

2022-01-25 19:48 UTC, b-fein commented on src/main/webapp/app/course/dashboards/assessment-dashboard/assessment-dashboard.component.ts
> +    private hasUnfinishedAssessments(exercise: Exercise) {
```suggestion
    private hasUnfinishedAssessments(exercise: Exercise): boolean {
```

2022-01-25 19:50 UTC, b-fein approved these changes

2022-01-26 10:31 UTC, willergeorg approved these changes
Tested on TS1 and worked as expected

2022-01-26 19:54 UTC, ole-ve approved these changes
Tested on TS1, works as described.
Code changes also look good to me 👍

2022-01-26 21:53 UTC, valeriebucher approved these changes
Exercise was correctly filtered, worked as expected.

2022-01-27 06:37 UTC, merged