`Documentation`: Add a note about the usage of custom SQL queries in the Java Migration Tool
ls1intum/Artemis pull request #4690
Opened 2022-02-10 20:43 UTC by ole-ve

### Checklist
#### General
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context
I encountered an issue when using a custom SQL query inside of a changeset with the Java Migration Tool from @julian-christl.

### Description
There seems to be a problem with the tool connecting to the database when using some custom SQL queries from a Spring repository. I encountered the following error:
`java.lang.IllegalArgumentException: Authentication object cannot be null`

I agreed with @julian-christl to add a note into the documentation that the usage of custom SQL queries is not suggested.

2022-02-10 21:02 UTC, julian-christl commented on docs/dev/migration/data.rst
> +- It is suggested to not use repository methods that execute custom SQL queries as this may lead to problems with the authentication to the database.
```suggestion
- Do not use repository methods that execute custom SQL/JPQL queries as this leads to problems.
```

I think we can keep this short.

2022-02-10 21:06 UTC, julian-christl approved these changes

2022-02-11 16:15 UTC, krusche commented
There is a simple solution to this problem. Simply invoke SecurityUtils.setAuthorizationObject(); if there is no user context (e.g. based on a REST Call) before

2022-02-11 16:16 UTC, krusche requested changes
such queries are possible, please change the docs accordingly

2022-02-11 16:21 UTC, julian-christl commented on docs/dev/migration/data.rst
> +- Do not use repository methods that execute custom SQL/JPQL queries as this leads to problems.
```suggestion
- If queries fail due to the authorization object being null, call `SecurityUtils.setAuthorizationObject()` beforehand to set a dummy object.
```

2022-02-11 22:41 UTC, krusche approved these changes

2022-02-11 22:42 UTC, merged