`General`: Open routing via chart in new tab
ls1intum/Artemis pull request #4839
Opened 2022-03-22 13:33 UTC by willergeorg

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Currently, the access of other pages via charts is implemented in that way, that the page changes in the same browser tab. Since the click event is handled by the charting framework, we cannot implement the delegation as link without rebuilding the whole chart from scratch. Especially for charts that provide an overview of different aspects, this might be a suboptimal solution. The user would need to navigate back via browser navigation or breadcrumbs. Instead, I changed the navigation of selected charts in that way, that the new page opens in a separate tab. Then, the user can simply switch tabs to return to the overview.

### Description

I implemented a chart-routing.service.ts that handles the new routing behavior. I replaced the angular router with the auxiliary service within the components.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

2022-04-04 18:33 UTC, filip-gregurevic submitted a review, later dismissed
Changes look good to me, nice work 👍🏼

2022-04-05 09:02 UTC, Dominik-Weinzierl approved these changes
Works as described - Code looks good :+1:

2022-04-06 15:13 UTC, canberkanar approved these changes
Tested on ts2. Tabs open on clicking the bars as described.

2022-04-24 15:09 UTC, filip-gregurevic requested changes
This is probably due to resolving some conflicts, I guess this should also fix the build and tests

2022-04-24 15:09 UTC, filip-gregurevic commented on src/main/webapp/app/course/course-scores/course-scores.component.ts
> +import { CsvExportOptions } from 'app/shared/export/csv-export-modal.component';
```suggestion

```
Should probably fix this

2022-04-25 18:38 UTC, Dominik-Weinzierl approved these changes
Re-approve :+1: Changes looks good since last approve and tested again on Ts1

2022-04-26 15:23 UTC, Dominik-Weinzierl approved these changes
Re-approve - changes looks good :+1:

2022-04-27 01:23 UTC, akesfeden reviewed
Code changes look good, I just have some minor suggestions.

2022-04-27 01:23 UTC, akesfeden commented on src/test/javascript/spec/component/assessment-dashboard/exercise-assessment-dashboard.component.spec.ts
> +                routingStub = jest.spyOn(navigationUitlService, 'routeInNewTab').mockImplementation();
```suggestion
                const navigationUtilService = TestBed.inject(ArtemisNavigationUtilService);

                routingStub = jest.spyOn(navigationUtilService, 'routeInNewTab');
```

As far as I know, `mockImplementation` shouldn't be needed when `MockProvider` is used.

2022-04-27 01:23 UTC, akesfeden commented on src/test/javascript/spec/component/statistics/statistics-average-score-graph.component.spec.ts
> +                routingStub = jest.spyOn(routingService, 'routeInNewTab').mockImplementation();
```suggestion
                routingStub = jest.spyOn(routingService, 'routeInNewTab');
```

Same here.

2022-04-27 07:00 UTC, cremertim approved these changes
Tested on ts3, everything works as expected. Followed the testing steps

2022-04-27 11:33 UTC, cremertim approved these changes
reapporve after local testing

2022-04-27 11:55 UTC, bassner approved these changes
Thanks for adding the changes. LGTM 👍

2022-04-27 13:26 UTC, Dominik-Weinzierl approved these changes
Re-approve after local testing :+1:

2022-04-29 17:54 UTC, akesfeden approved these changes
Thank you for adding the suggested changes, looks good to me!

2022-04-29 18:43 UTC, filip-gregurevic approved these changes
Re-approve 👍🏼

2022-05-02 21:25 UTC, merged