``General``: Replace websocket connection alerts with connection lost indicator
ls1intum/Artemis pull request #4878
Opened 2022-03-29 19:35 UTC by bassner

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

If the websocket connection fails, the client currently displays a permanent alert, blocking access to the underlying components of the navbar.

<img width="1890" alt="image" src="https://user-images.githubusercontent.com/23171488/160689595-12486ef5-52c4-413a-963f-691b8edf7589.png">

### Description

This PR introduces a red indicator (wifi symbol) and a popover that belongs to it to notify the user about the connection interruption. The old notification alerts have been removed. This does not cover anything anymore, and shows the warning (in form of the animated symbol) even if the popover is clicked away.

As the new component needs access to the connection state, this PR additionally reworks how the websocket connection state is distributed in the application. Currently, the websocket service maintained arrays of connect and disconnect listeners, which are populated by calls to the ``bind()`` method of the service. This is not the best approach to this problem, and ignores the fact that we generally encourage the use of RxJs for usecases like this.

Therefore, the state of the websocket is now distributed using a RxJs behavior subject and comes with additional state information: connected, hasEverBeenConnected, intendedDisconnect.
All code that previously relied on connection events have been updated accordingly.

Lastly, I've updated the breakpoints and responsive mechanism of the navbar a bit as the new icon takes a bit more space (if it's rendered) and in general, currently, the navbar does not behave very well when it's scaled down (e.g. "Course Management" gets a line break etc). It will just switch to the collapsed navbar earlier than before. 

### Steps for Testing

New functionality:
1. Start the web application
2. Disable your internet connection
--> Verify that the warning symbol in the top left pops up and that the popover is displayed.
You should be able to dismiss the popover and bring it back by clicking on the button again.

Affected features:
The update of the websocket state distribution affects a few existing components, most notably the exam participation component and the quiz participation component.

Therefore, please verify that these components still deal with websocket connection drops like they used to do.
For example, check that the connection indicator on the bottom when doing an exam as a student still shows up and updates if you disable your internet connection.

Navbar: Please scale down your viewport horizontally and observe that the navbar is responsive and looks good on smaller screen sizes, and that the hamburger menu still works.

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

2022-03-30 11:55 UTC, b-fein requested changes
Code looks good.

During testing the status got updated when disconnecting and reconnecting in the navbar, during quizzes, and during exams.
⟹ Everything worked flawlessly regarding the changes to the websocket connection. :+1:

Personal opinion: I’m not a fan of the pulsating icon and would rather like to have it without animation. I think that the red icon and the notification are noticeable enough.

### Requested Changes
The notifications now overflow the page to the right:
![Screenshot 2022-03-30 at 13-42-05 Courses](https://user-images.githubusercontent.com/64250573/160827393-7ea65a25-00c9-4874-803d-b74fa402b647.png)

The menu when clicking on the username is shown in the wrong location:
![Screenshot 2022-03-30 at 13-42-36 Courses](https://user-images.githubusercontent.com/64250573/160827400-30fe4b71-2fb8-46b3-bedf-b62334659df4.png)
The one for ‘Server Administration’ is shown correctly.

2022-03-30 11:55 UTC, b-fein commented on src/test/javascript/spec/component/exercises/quiz/quiz-participation.component.spec.ts
> +import { ConnectionState, JhiWebsocketService } from 'app/core/websocket/websocket.service';
```suggestion
import { JhiWebsocketService } from 'app/core/websocket/websocket.service';
```
unused import

2022-03-30 11:55 UTC, b-fein commented on src/main/webapp/app/core/websocket/websocket.service.ts
>       * Close the connection to the websocket and unsubscribe als listeners.
```suggestion
     * Close the connection to the websocket and unsubscribe all listeners.
```

2022-03-30 13:11 UTC, bassner commented on src/test/javascript/spec/component/exercises/quiz/quiz-participation.component.spec.ts
> +import { ConnectionState, JhiWebsocketService } from 'app/core/websocket/websocket.service';
👍

2022-03-30 13:15 UTC, bassner commented
@b-fein Thank you for testing! :)
The notification overflow should be fixed in 66b886c.
The dropdown location actually doesn't show up correctly on develop either, but with c68c4d0, it now works.

Regarding the animation topic: I've got the current appearance approved by @krusche, but I think wether or not we animate it is something we can quickly vote on in tomorrow's meeting. :)

2022-03-30 13:33 UTC, b-fein approved these changes
Thanks, all comments and issues I had before are now resolved.

2022-03-31 12:09 UTC, bassner commented
Latest changes after today's dev meeting:
We keep the animation, but try to make it less distractive, especially if:
- The student is filling out an exam. The pulse animation should not be distracting from the exam.
- The websocket keeps disconnected for a longer period of time. The pulse doesn't need to keep blinking for a very long time, therefore we disable it after 1 minute.

All changes added in fd90d0a.

@b-fein I'd be super happy if you could verify these new changes again! :)

2022-03-31 12:31 UTC, b-fein submitted a review, later dismissed
The icon stops the animation after a minute. On the exams page the icon does not play the animation at all. Code changes make sense. :+1: 

I like that the animation is disabled completely during an exam to avoid unnecessary distraction.

2022-03-31 13:19 UTC, Santia-go approved these changes
Tested on TS1. 
Working as expected in the general mode and the exam mode. 
<img width="433" alt="Screenshot 2022-03-31 at 15 10 04" src="https://user-images.githubusercontent.com/88991954/161064046-ed33c510-4cf8-4cf7-ad12-90c0441abb37.png">

Additionally, the icon is responsive to the change of the scale in the window
<img width="174" alt="Screenshot 2022-03-31 at 15 18 05" src="https://user-images.githubusercontent.com/88991954/161064100-d7c11162-80cc-44c8-b1ac-dee5547371d4.png">

2022-04-02 17:14 UTC, b-fein approved these changes

2022-04-02 17:14 UTC, bassner commented
@b-fein @Santia-go Just merged develop, nothing changed. :)

2022-04-03 20:11 UTC, ole-ve submitted a review, later dismissed
Followed all testing steps on TS2, and worked as expected. 👍
Unfortunately, I cannot really comment on the (client) code.

2022-04-04 10:03 UTC, Santia-go approved these changes
Tested for a second time on TS1.
Working as expected on the two modes (general and exam).
The icon is adapted to the change of the scale in the window also.

2022-04-05 08:47 UTC, mallgaier submitted a review, later dismissed
Good job, works as expected

2022-04-06 06:54 UTC, merged