`Bugfix`: Display warning when using Grading Criterion without feedback
ls1intum/Artemis pull request #4899
Opened 2022-04-05 18:35 UTC by mallgaier

### Checklist
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
The additional Feedback component requires textual feedback to submit the assessment. While a visual warning is shown to the TA when the textual feedback is missing, when using a grading criterion without feedback the warning is currently missing. Because of this, the TA cannot submit the assessment, but also has no indication about the reason for this.

### Description
The additional Feedback component now also displays a visual warning when the TA used a Grading Criterion without Feedback. 

### Steps for Testing
Prerequisites:
- 1 Instructor
- 1 Exercise with 1 Grading Criterion without Feedback to the students

1. Participate and submit the exercise as student
2. Assess the exercise
3. Drag & Drop the Grading Criterion without Feedback into the additional feedback
4. Make sure the red warning is shown
5. (Add some textual description and submit the assessment)

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots
https://user-images.githubusercontent.com/94070506/161821774-d0fd099b-2614-4850-95f9-b1869861beba.mp4

2022-04-05 20:16 UTC, bassner requested changes
The usage of the non-null assertion operator ``!`` is wrong here in my opinion (and it was before your changes, too). I'd suggest to change it according to my inline comments! :)

Other occurrences in this file, mostly of ``assessment.gradingInstruction!`` in ``*ngIf``, could and should be changed to omit the ``!``, too, but it's up to you if you want to include it in this PR or not. :)

2022-04-05 20:16 UTC, bassner commented on src/main/webapp/app/assessment/assessment-detail/assessment-detail.component.html
> +                        assessment.gradingInstruction! && assessment.gradingInstruction!.feedback!
```suggestion
                        assessment.gradingInstruction?.feedback
```

2022-04-05 20:16 UTC, bassner commented on src/main/webapp/app/assessment/assessment-detail/assessment-detail.component.html
> +                    [required]="!assessment.gradingInstruction || !assessment.gradingInstruction!.feedback"
```suggestion
                    [required]="!assessment.gradingInstruction?.feedback"
```

2022-04-06 11:35 UTC, bassner approved these changes
Thanks for adding the changes. LGTM 👍

2022-04-06 13:23 UTC, maximiliansoelch approved these changes
Tested on TS3, works as described.
Code changes look good 👍

2022-04-07 19:25 UTC, merged