`Lectures`: Allow instructors to import existing lectures into courses
ls1intum/Artemis pull request #4931
Opened 2022-04-13 22:14 UTC by ge65cer

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [ ] I implemented the changes with a good performance and prevented too many database calls.
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

2022-04-18 19:05 UTC, bassner requested changes
I've tested this on TS1 and it works perfectly fine. 👍 

The client code you added looks good. However, you didn't provide any tests for the new client components and services you added. I suggest to add some tests for them!

2022-04-19 13:00 UTC, Hialus requested changes
Reviewed the code.
Client code looks good tp me, but I left some comments for the server code.
You also did not add an integration test for your new endpoints. Please add them for both the search and the import lecture endpoint.

2022-04-19 13:01 UTC, Hialus commented on src/main/webapp/app/lecture/lecture.service.ts
> +    import(courseId: number, lectureId: number): Observable<EntityResponseType> {
Please add a JSDoc here.

2022-04-20 13:59 UTC, Hialus approved these changes
Thanks for applying my feedback.
Server, Client, and Test code look good to me now.
Well done 👍🏻

2022-04-20 15:00 UTC, Hialus submitted a review, later dismissed
New test changes look good.
Reapprove Code.

2022-04-20 18:18 UTC, bassner requested changes
Two minor nitpicks :)

2022-04-20 18:18 UTC, bassner commented on src/test/javascript/spec/component/lecture/lecture-import.component.spec.ts
> +            schemas: [],
```suggestion
```

2022-04-20 18:18 UTC, bassner commented on src/test/javascript/spec/component/lecture/lecture-import.component.spec.ts
> +    });
Tests like this are, altough some of them exist in our codebase, useless. Please remove it :)

2022-04-20 19:18 UTC, Strohgelaender commented on src/test/javascript/spec/component/lecture/lecture-import.component.spec.ts
> +import { MockComponent, MockDirective, MockPipe } from 'ng-mocks';
unused import (code warning)
```suggestion
import { MockComponent, MockDirective } from 'ng-mocks';
```

2022-04-20 20:04 UTC, ge65cer commented on src/test/javascript/spec/component/lecture/lecture-import.component.spec.ts
> +import { MockComponent, MockDirective, MockPipe } from 'ng-mocks';
Great to see my IDE doing its job… 🤖

2022-04-21 07:50 UTC, bassner submitted a review, later dismissed
Thanks for adding the changes.
Looks good to me now! 👍 
Good work :)

2022-04-21 09:13 UTC, maximiliansoelch submitted a review, later dismissed
Tested on TS1, works as expected 👍

2022-04-21 09:24 UTC, Hialus submitted a review, later dismissed
Re-approve Code 👍🏻

2022-04-21 15:15 UTC, Strohgelaender commented on src/main/java/de/tum/in/www1/artemis/service/LectureImportService.java
> +            Files.copy(new FileInputStream(oldPath.toFile()), tempPath, StandardCopyOption.REPLACE_EXISTING);
```suggestion
            Files.copy(oldPath, tempPath, StandardCopyOption.REPLACE_EXISTING);
```

2022-04-21 16:30 UTC, Strohgelaender approved these changes
Code aproval

2022-04-21 18:35 UTC, ge65cer commented
Another iteration, here we go… 🎡

2022-04-21 20:07 UTC, bassner approved these changes
Only minor things changed since my last review.
Reapprove 👍

2022-04-21 20:42 UTC, Hialus approved these changes
Code still looks good.
Re-approve 👍🏻

2022-04-22 08:27 UTC, maximiliansoelch approved these changes
Reapprove 👍

2022-04-22 09:14 UTC, merged