`Assessment`: Allow instructors to export course scores to an Excel file
ls1intum/Artemis pull request #4941
Opened 2022-04-20 18:39 UTC by maximiliansoelch

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

Currently Artemis only allows to export course scores to a CSV file. When a user specifies another decimal separator than their system's setting and then imports the CSV file into Excel, values are interpreted differently (e.g. Custom Decimal Separator: '.', User system set to german: ',' -> Generated csv contains numbers in the format 1.4 -> Excel interprets this as a date (1. April)).
In addition, allowing to export directly to an Excel file improves the usability for technical inexperienced users.

### Description

The introduced changes now allow an instructor to download course scores directly as an Excel file.

### Steps for Testing

Prerequisites:

- 1 Course
- 1 Student
- 1 Exercise, on which the student participated

1. Log in to Artemis
2. Navigate to Course Administration, select the course, then Scores
3. Click the `Export` button
4. A modal opens, where you can select the file type used for the export (Excel<default> or CSV).
5. Select Excel (which should be selected initially) and click `Export as Excel`
6. Open the downloaded Excel file and make sure the rows and their values are equivalent to the ones displayed in Artemis
7. In addition, also verify that the export to a CSV file still works as expected.

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

2022-04-27 13:13 UTC, bassner requested changes
I've tested this on TS1 and was unable to export an Excel file due to this error in the console:
![grafik](https://user-images.githubusercontent.com/23171488/165525971-43a64a61-1c7f-4a06-9d2a-e9cdd23cdadf.png)
(Tried on https://artemis-test1.artemis.in.tum.de/course-management/7/scores)

Additionally, please see my few code remarks below.

2022-04-27 13:13 UTC, bassner commented on src/main/webapp/app/course/course-scores/course-scores.component.ts
> +        if (!!customCsvOptions) {
```suggestion
        if (customCsvOptions) {
```

2022-04-27 13:13 UTC, bassner commented on src/main/webapp/app/course/course-scores/course-scores.component.ts
> +            Author: `Artemis ${VERSION ? VERSION : ''}`,
```suggestion
            Author: `Artemis ${VERSION ?? ''}`,
```

2022-04-27 13:18 UTC, maximiliansoelch commented
@bassner Thanks for testing. I will look into the error ...

2022-04-27 13:33 UTC, maximiliansoelch commented
@bassner The error you observed should be fixed now. I also implemented your code suggestions.

2022-04-27 14:22 UTC, ge65cer reviewed
Great work on the functionality, tested on TS2 and worked correctly.
I've left some small remarks.

2022-04-27 14:22 UTC, ge65cer commented on src/main/webapp/app/shared/export/export-modal.component.ts
> +    active = 1;
I'd rename this `activeTab` or similar to give better context

2022-04-27 14:22 UTC, ge65cer commented on src/main/webapp/app/course/course-scores/course-scores-excel-row-builder.ts
> +export interface CommonSpreadsheetCellObject {
Maybe you could add the description for the attributes as comments directly here?

2022-04-29 13:29 UTC, maximiliansoelch commented
@bassner Yes, for now that is intended as Artemis stores grades as strings.

2022-04-29 13:33 UTC, ge65cer approved these changes
Thanks for the small changes, looks good to me now!

2022-05-02 07:54 UTC, joaquinmurcia requested changes
Tested with test_user_2 on TS2. The columns in the exported (both Excel and CSV) files don't match the columns shown in Artemis. Is this supposed to happen?
![image](https://user-images.githubusercontent.com/47792433/166202248-b3287154-b8f2-43c9-bea5-69266eef33e9.png)
![image](https://user-images.githubusercontent.com/47792433/166202284-88a66ef8-3ac0-498a-98d2-8651eb42e619.png)

2022-05-02 08:52 UTC, maximiliansoelch commented
@joaquinmurcia Thanks for testing.
Yeah, it is intended that the order of the columns is not the same (e.g. in Artemis the _avg_ and _max_ column are located at the top, in the export files they are located at the bottom).

What is important is that the exported points and scores of the students match the data in Artemis as well as the values for _avg_ and _max_ (what they do in your posted case).

2022-05-02 14:37 UTC, max-bergmann submitted a review, later dismissed
Tested on TS3. Works as expected.

2022-05-02 18:59 UTC, jschmautzer approved these changes
Tested on ts1, followed the described testing steps, works as expected :)

2022-05-03 09:43 UTC, ge65cer approved these changes
Re-approve

2022-05-03 12:48 UTC, willergeorg approved these changes
Tested on TS3. The scores in the Excel file match the values displayed by Artemis.

2022-05-03 18:24 UTC, jschmautzer approved these changes
re-approve, tested on ts1

2022-05-04 14:22 UTC, merged