`General`: Improve CSV header parsing when importing users into course groups
ls1intum/Artemis pull request #4956
Opened 2022-04-22 20:40 UTC by maximiliansoelch

### Checklist
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

This is a follow-up PR to the fix [b054013](https://github.com/ls1intum/Artemis/commit/b054013ff172ee355d41e1fe6c11e474cffaa62e), which closed #4939.
The changes introduced in this PR simplify the code and also make it clearer where new header fields need to be added in the future.
In addition, this PR addresses an additional improvement mentioned in a comment in [#4939](https://github.com/ls1intum/Artemis/issues/4939#issuecomment-1106570075): 
> All "not found" lines should be red, not only every second one
This refers to the text color.

### Description

This PR transitions from a single object, which previously stored the possible csv header fields in the object's parameters, to several arrays.

### Steps for Testing

Prerequisites:
- 1 Course

1. Log in to Artemis as Admin
2. Navigate to Course Administration
3. Select a course and go to the student overview
4. Click Import Users
5. Select the CSV file

- [invalid_rows_2_and_6.csv](https://github.com/ls1intum/Artemis/files/8543832/invalid_rows_2_and_6.csv)
- [valid_test_3_of_5_users_imported.csv](https://github.com/ls1intum/Artemis/files/8543825/valid_test_3_of_5_users_imported.csv)

7. Click on Import
- for the invalid file an error message should be shown, indicating errors in row 2 and 6:
![Bildschirmfoto 2022-04-22 um 22 26 55](https://user-images.githubusercontent.com/9954674/164789012-419daeb5-35ab-4fe1-8501-0911642fc150.png)

- for the valid file 3 out of 5 users should get imported

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| users-import-dialog.component.ts | 78.3% | 89.52% |

### Screenshots

Before the changes, only every second line the import status was applied:
![Bildschirmfoto 2022-04-22 um 22 15 08](https://user-images.githubusercontent.com/9954674/164788397-b9d61223-fb7c-497d-87b5-fe58529b44c3.png)

After the changes the text color corresponding to the import status is applied correctly regardless of the row position:
![Bildschirmfoto 2022-04-22 um 22 18 43](https://user-images.githubusercontent.com/9954674/164788380-529bea3f-9583-4b5c-a901-0d69c27dd3b1.png)

2022-04-25 15:57 UTC, ge65cer approved these changes
Tested with various valid/invalid CSV files and worked correctly. 👍

2022-04-26 10:00 UTC, Santia-go submitted a review, later dismissed
Tested in TS1. 
Working as expected. It is possible to import the groups from the CSV.

2022-04-27 12:58 UTC, bassner requested changes
Tested this on TS1 and it works as described 👍 

Just one remark :)

2022-04-27 12:58 UTC, bassner commented on src/main/webapp/app/shared/import/users-import-dialog.component.ts
> +        return false;
```suggestion
        return keys.some((key) => entry[key] && entry[key] !== '');
```

2022-04-27 13:27 UTC, bassner approved these changes
Thanks for applying the feedback. LGTM! 👍

2022-04-27 14:05 UTC, ge65cer approved these changes

2022-04-29 07:52 UTC, max-bergmann approved these changes
Tested on TS3. Works as expected.

2022-04-29 09:27 UTC, Santia-go approved these changes
Tested on TS1
Re-approved!

2022-04-29 13:51 UTC, merged