`Development`: Fix typos in code comments
ls1intum/Artemis pull request #5007
Opened 2022-05-03 07:59 UTC by Strohgelaender

#### General
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context
This PR fixes a multitude of typos or grammar mistakes around the whole code base. I used the integrated IntelliJ-Inspection to spot theses issues. 

### Description
These are a few noteworthy changes:
- Use the offical spelling for brand names (`Github` -> `GitHub`, `MacOS` -> `macOS`)
- Add hyphens where needed (`logged in` -> `logged-in`, `semi automatic` -> `semi-automatic`)
- Fix a / an and its / it's mistakes

### Steps for Testing
Code Review

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2

2022-05-03 15:02 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/7a56396dabe78c790261ae5dcd93b6880ba514d4/src/test/java/de/tum/in/www1/artemis/AssessmentTeamComplaintIntegrationTest.java#L206

Result, but this would require a bit of refactoring as this is a variable name

2022-05-03 16:13 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/b3d021b6d9bb45fd00845fed00fe7e8144554684/artemis-server-cli#L6
Common

https://github.com/ls1intum/Artemis/blob/b3d021b6d9bb45fd00845fed00fe7e8144554684/artemis-server-cli#L7
assumes

2022-05-03 16:18 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/b3d021b6d9bb45fd00845fed00fe7e8144554684/LICENSE#L17
Non infringement (2 words, not 1)

2022-05-03 16:26 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/b3d021b6d9bb45fd00845fed00fe7e8144554684/docs/dev/setup/common-problems.rst#L51

Retrieve

2022-05-03 16:31 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/b3d021b6d9bb45fd00845fed00fe7e8144554684/.github/workflows/build-deploy.yml#L175

Download

2022-05-03 16:36 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/b3d021b6d9bb45fd00845fed00fe7e8144554684/src/main/webapp/app/shared/chart/chart-exercise-type-filter.directive.ts#L34

exerciseScores

2022-05-03 16:39 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/b3d021b6d9bb45fd00845fed00fe7e8144554684/src/main/webapp/app/shared/markdown-editor/commands/colorPicker.command.ts#L14
Color change occurs? Not sure what was initially meant

2022-05-04 09:49 UTC, Strohgelaender commented
Thank you for the review @babyygemperor. I changed everything except one:

> NONINFRINGEMENT

I won't change this since it is part of the licence (and I expect it to be copied from somewhere)

2022-05-04 12:08 UTC, Marvin-Vitcu requested changes
TIP FOR REVIEWERS: USE UNIFIED VIEW

reviewed all of the changes. Found one spelling mistake:

bee --> be
![image](https://user-images.githubusercontent.com/36523308/166677065-9a67128f-f189-4e7e-a155-f4d7f2ef94a5.png)
![image](https://user-images.githubusercontent.com/36523308/166677112-25b72575-a8be-43d1-91f3-f03e74fa98d1.png)
![image](https://user-images.githubusercontent.com/36523308/166677125-51a86636-4a8c-4126-a75f-cef0408415b5.png)

2022-05-04 12:12 UTC, Marvin-Vitcu requested changes

2022-05-04 12:12 UTC, Marvin-Vitcu commented on src/main/webapp/app/exam/exam-scores/exam-scores.component.ts
> +                    // This should never bee thrown. Indicates that the information in the ExamScoresDTO is inconsistent
```suggestion
                    // This should never be thrown. Indicates that the information in the ExamScoresDTO is inconsistent
```

2022-05-04 12:12 UTC, Marvin-Vitcu commented on src/main/webapp/app/exam/exam-scores/exam-scores.component.ts
> +                    // This should never bee thrown. Indicates that the information in the ExamScoresDTO is inconsistent
```suggestion
                    // This should never be thrown. Indicates that the information in the ExamScoresDTO is inconsistent
```

2022-05-04 14:35 UTC, Strohgelaender commented on src/main/webapp/app/exam/exam-scores/exam-scores.component.ts
> +                    // This should never bee thrown. Indicates that the information in the ExamScoresDTO is inconsistent
🐝

2022-05-04 14:39 UTC, bassner approved these changes
Looks good to me, didn't find any more mistakes 👍

2022-05-04 21:10 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/docs/user/exercises/programming-exercise-setup.inc#L386

repository is authoritative

2022-05-04 21:26 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/shared/markdown-editor/commands/orderedListCommand.ts#L56

format

2022-05-04 21:27 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/shared/markdown-editor/commands/underline.command.ts#L15

underline

2022-05-04 21:30 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/shared/markdown-editor/commands/unorderedListCommand.ts#L50

format

2022-05-04 21:38 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/overview/course-exams/course-exams.component.ts#L45

unsubscribe from all subscriptions? I suppose, I didn't quite understand what was meant by that

2022-05-04 21:39 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/overview/course-statistics/course-statistics.component.ts#L577

corresponding

2022-05-04 21:47 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/domain/FileUploadSubmission.java#L36

Past tense of split is split

2022-05-04 21:50 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/domain/enumeration/ParticipationLifecycle.java#L6

participations

2022-05-04 21:58 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/repository/ModelAssesmentKnowledgeRepository.java#L12

Assessment (will require a lot of refactoring because it's a name of a class)

2022-05-04 21:59 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/repository/ProgrammingExerciseTestCaseRepository.java#L42

https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/repository/ProgrammingExerciseTestCaseRepository.java#L55

Associated

2022-05-04 22:00 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/repository/TextAssesmentKnowledgeRepository.java#L12

Assessment

2022-05-04 22:02 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/MailService.java#L77

Resource

2022-05-04 22:03 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/SubmissionExportService.java#L61
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/SubmissionExportService.java#L74

Zipped

2022-05-04 22:04 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/TextBlockService.java#L76
Submitted
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/TextBlockService.java#L116
Submission

2022-05-04 22:05 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/TextExerciseImportService.java#L53
Assessment

2022-05-04 22:09 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/connectors/GitService.java#L542
Default

https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/connectors/GitService.java#L910
Separate

2022-05-04 22:17 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/connectors/gitlab/GitLabService.java#L236
Regularly
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/connectors/gitlab/GitLabService.java#L252
Regularly
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/connectors/gitlab/GitLabService.java#L282
existent
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/connectors/gitlab/GitLabService.java#L297
existent

2022-05-04 22:18 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/connectors/gitlab/GitLabService.java#L507
liveliness
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/connectors/gitlab/GitLabService.java#L459
access

2022-05-04 22:19 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/connectors/jenkins/JenkinsUserManagementService.java#L307

Assistant

2022-05-04 22:22 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/connectors/jenkins/jobs/JenkinsJobPermissionsUtils.java#L114

Permission

2022-05-04 22:23 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/exam/ExamService.java#L694
course

2022-05-04 22:24 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/exam/ExamSessionService.java#L38

Added

2022-05-04 22:25 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/exam/StudentExamService.java#L253

Submissions

2022-05-04 22:28 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/metis/PostService.java#L695

lowercase

2022-05-04 22:29 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/plagiarism/PlagiarismService.java#L30
Anonymised
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/plagiarism/PlagiarismService.java#L55
Anonymised

2022-05-04 22:33 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/plagiarism/ProgrammingPlagiarismDetectionService.java#L211
Plagiarism
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/plagiarism/ProgrammingPlagiarismDetectionService.java#L238
Directories

2022-05-04 22:36 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java#L552
Anonymise/Anonymisation

https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java#L429
Occurred

2022-05-04 22:38 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingSubmissionResultSimulationService.java#L65
participate

2022-05-04 22:40 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingSubmissionService.java#L648
correction round (2 words)

https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingSubmissionService.java#L652
submissions

https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingSubmissionService.java#L653
submissions

https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingSubmissionService.java#L722
submissions

2022-05-04 22:41 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/scheduled/AtheneScheduleService.java#L127

processing

2022-05-04 22:47 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/service/scheduled/quiz/QuizScheduleService.java#L288
Registered???

2022-05-04 22:51 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/web/rest/ComplaintResource.java#L479

submitterName

2022-05-04 22:53 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/web/rest/FileResource.java#L433

uploaded

2022-05-04 22:54 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/web/rest/FileUploadSubmissionResource.java#L118

split

2022-05-04 22:55 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/web/rest/ParticipationResource.java#L417

Participations

2022-05-04 22:57 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/web/rest/StaticCodeAnalysisResource.java#L99

Past tense of reset is reset

2022-05-04 22:59 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/java/de/tum/in/www1/artemis/web/rest/UserJWTController.java#L108

Caught

2022-05-04 23:02 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/course/manage/detail/course-detail-doughnut-chart.component.ts#L101
Assigns

2022-05-04 23:03 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/overview/discussion-section/discussion-section.component.html#L1

expanded

2022-05-04 23:06 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/i18n/en/health.json#L23

Liveliness (liveness is not a word)

2022-05-04 23:07 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/i18n/en/lecture.json#L46

Title (I suppose it ought to be in English because it is under the "en" folder)

2022-05-04 23:09 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/entities/course.model.ts#L92
typecast
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/entities/course.model.ts#L94
typecast
past tense of typecast is typecast

2022-05-04 23:11 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/exam/exam-scores/exam-scores.component.html#L10
weight

2022-05-04 23:11 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/exam/exam-scores/exam-scores.component.ts#L856
recalculating

2022-05-04 23:13 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/exercises/text/manage/example-text-submission/example-text-submission.component.ts#L143

everything

2022-05-04 23:14 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/exercises/shared/exercise/exercise.service.ts#L20
Serviceable

https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/exercises/shared/exercise/exercise.service.ts#L134
reset

2022-05-04 23:16 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/exercises/quiz/manage/apollon-diagrams/exercise-generation/quiz-exercise-generator.ts#L238
absolute
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/exercises/quiz/manage/apollon-diagrams/exercise-generation/quiz-exercise-generator.ts#L239
percentage

2022-05-04 23:18 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/overview/visualizations/exercise-scores-chart/exercise-scores-chart.component.ts#L117
Exercise
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/overview/visualizations/exercise-scores-chart/exercise-scores-chart.component.ts#L159
Exercise

2022-05-04 23:19 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/exam/participate/exercises/file-upload/file-upload-exam-submission.component.ts#L83

handled

2022-05-04 23:21 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/exercises/shared/structured-grading-criterion/grading-instructions-details/grading-instructions-details.component.ts#L327
Tuple
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/exercises/shared/structured-grading-criterion/grading-instructions-details/grading-instructions-details.component.ts#L356
Tuple
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/exercises/shared/structured-grading-criterion/grading-instructions-details/grading-instructions-details.component.ts#L369
Tuple

2022-05-04 23:21 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/admin/health/health.model.ts#L3

Liveliness

2022-05-04 23:23 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/core/interceptor/errorhandler.interceptor.ts#L13
broadcast (past tense of broadcast is broadcast)

2022-05-04 23:24 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/core/interceptor/notification.interceptor.ts#L13
broadcast (past tense of broadcast is broadcast)

2022-05-04 23:25 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/exercises/programming/shared/code-editor/layout/code-editor-repository-is-locked.component.ts#L10
label
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/exercises/programming/shared/code-editor/layout/code-editor-repository-is-locked.component.ts#L18
label

2022-05-04 23:26 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/lecture/lecture-import.component.ts#L140
delay

2022-05-04 23:26 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/lecture/lecture.service.ts#L159
as well

2022-05-05 07:00 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/course/manage/course-group.component.ts#L91

course

2022-05-05 07:01 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/course/manage/course-management.component.ts#L117
expanded
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/course/manage/course-management.component.ts#L124
expanded

2022-05-05 07:04 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/exercises/file-upload/manage/file-upload-exercise-update.component.ts#L120
exercise

2022-05-05 07:06 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/exercises/modeling/manage/modeling-exercise-import.component.html#L8
exercise

2022-05-05 07:07 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/exercises/programming/manage/programming-exercise-import.component.html#L8
exercise

2022-05-05 07:08 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/exercises/programming/manage/programming-exercise-import.component.ts#L111
element

2022-05-05 07:09 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/exercises/text/manage/text-exercise-import.component.html#L8
exercise

2022-05-05 07:09 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/exercises/text/manage/text-exercise-import.component.ts#L54
delay
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/exercises/text/manage/text-exercise-import.component.ts#L85
element

2022-05-05 07:12 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/shared/markdown-editor/markdown-editor.component.ts#L113

default

https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/shared/markdown-editor/markdown-editor.component.ts#L293

split

https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/shared/markdown-editor/markdown-editor.component.ts#L328

whitespace

2022-05-05 07:13 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/shared/markdown-editor/markdown-editor.component.ts#L89

colour picker (2 words)

2022-05-05 07:15 UTC, babyygemperor commented
https://github.com/ls1intum/Artemis/blob/fbc2f20a433d0d16daf00b606a952df3d24bc75d/src/main/webapp/app/exam/participate/exercises/modeling/modeling-exam-submission.component.ts#L96

submission

2022-05-05 08:57 UTC, babyygemperor commented
Okay I'll make my own pull request for the rest of the typos, pointing out all the other typos outside your code changes doesn't make sense.

2022-05-05 16:48 UTC, SimonPaul02 approved these changes
Reviewed code together with @yuling-sun . Mostly all corrections were correct, but we found some additional changes:
In our opinion, there should by a hyphen after "non" -> non-instructors
![image](https://user-images.githubusercontent.com/68793520/166972585-29cffd82-c70d-4e5a-b299-52d09d6d824c.png)
Also, sometimes "ID", "Id" and "id" are used, there is no strict convention. 
Furthermore, we aren't sure what that comment wants to say:
![image](https://user-images.githubusercontent.com/68793520/166974237-6fc0355d-3100-41fa-94aa-a7d5a99d97a8.png)
Additionally, we think that the following change is incorrect: (should be changes occur or a change occurs)
![image](https://user-images.githubusercontent.com/68793520/166974636-83bd08ec-085f-40fa-96e4-f9533a1092ff.png)
And we found an error in this change: ("is" should be deleted)
![image](https://user-images.githubusercontent.com/68793520/166975448-c32f0053-ea3b-4fd2-a845-d6120432f269.png)

2022-05-07 08:08 UTC, babyygemperor approved these changes
Looks good

2022-05-09 14:12 UTC, Strohgelaender commented
Thank you for the review @SimonPaul02 and @yuling-sun, I fixed most of the points meantioned.

> Also, sometimes "ID", "Id" and "id" are used, there is no strict convention.

I noticed that, but since I also don't know what version should be prefered here, I just oped to keep it.

> we found a couple of comma-mistakes

I also found a few of them, but decided to fix them only in the documentation. I feel like it's almost cosistently not used in comments, so I just opted to keep that.

2022-05-11 13:57 UTC, Dominik-Weinzierl submitted a review, later dismissed
I scrolled through your changes and it looks good to me :tada:

2022-05-15 06:30 UTC, ge65cer submitted a review, later dismissed

2022-05-16 13:17 UTC, nadinesamyy approved these changes
checked commit changes, look good

2022-05-21 07:59 UTC, ge65cer approved these changes

2022-05-27 13:05 UTC, maximiliansoelch submitted a review, later dismissed

2022-06-01 16:07 UTC, ge65cer approved these changes
Let's get this merged, so you don't have to update it all the time.

2022-06-04 21:33 UTC, merged