`Quiz exercises`: Disable navigation to quiz exercise detail page when the quiz is active
ls1intum/Artemis pull request #5034
Opened 2022-05-06 16:07 UTC by akesfeden

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [ ] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Users should not be able to open the details page after the quiz has started. Instructors should be able to navigate to Re-evaluate page after the quiz ends. Closes #5022. 
### Description

There are already server-side checks disallowing quiz editing requests after the quiz has started. Also, the Edit button at the Course Management > Exercises page and the one at the Instructor actions bar at the Exercise details behaves correctly and get disabled when the quiz is active. Only the link on the id of the quiz exercise (see screenshot below) seems to be misbehaving so it is fixed in this PR to behave like other navigation buttons.
### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Active Quiz
- 1 Visible Quiz
- 1 Closed Quiz
- 1 Open for Practice Quiz
- 1 Hidden Quiz

1. Log in to Artemis
2. Navigate to Course Administration
3. Go to Exercises page
4. Check for quizzes in each status:
    - Hidden, Visible: Editing link/buttons should be enabled.
    - Closed, Open for Practice: Re-evaluate link/buttons should be enabled.
    - Active: Editing and Re-evaluate link/buttons should be disabled.
5. Ensure there are no other buttons or links in the application (apart from typing the url directly) should navigate the user to the re-evaluate and edit pages of Quiz Exercises which does not obey the status rules above.

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots

![image](https://user-images.githubusercontent.com/18427209/167166285-867a84e7-6256-4927-b0b9-2eabc5f241ac.png)

The `Visible` quiz's id has the navigation link to the edit page while the `Active` quiz's id does not have it.

2022-05-06 17:28 UTC, joaquinmurcia approved these changes
Works as expected
![image](https://user-images.githubusercontent.com/47792433/167182480-5b4fc81a-7e1f-4f3d-9802-477b270f45a0.png)

2022-05-06 18:01 UTC, b-fein requested changes
As far as I know, the only way to change the quiz from ‘Released for Practice’ to ‘Closed’ is on the quiz edit page (or it should at least be possible from there, #5003). This is now no longer reachable by clicking on the quiz exercise ID in the exercise list.
How can I close a quiz now? The quiz lifecycle table column has no button to go to the next state like it did for the other steps before.

2022-05-07 07:12 UTC, krusche commented
> As far as I know, the only way to change the quiz from ‘Released for Practice’ to ‘Closed’ is on the quiz edit page (or it should at least be possible from there, #5003). This is now no longer reachable by clicking on the quiz exercise ID in the exercise list.
> How can I close a quiz now? The quiz lifecycle table column has no button to go to the next state like it did for the other steps before.

Closing a quiz was never a use case for us, we always kept them `open for practice`.
We can add a button to the quiz lifecycle column, or we can make it part of the re-evaluation screen which might not be very obvious to users though. It would make sense to rename "Re-evaluate" to "Edit" in the future, but still opening the "re-evaluate" page. Here, we could allow to change the status of the quiz then

2022-05-09 08:46 UTC, jbllhff approved these changes
<img width="1348" alt="Bildschirmfoto 2022-05-09 um 10 40 35" src="https://user-images.githubusercontent.com/67310526/167373719-3a6ee951-4079-46fa-89dc-70dcddd52e82.png">
Tested on ts2, works as expected. One comment though: When I want to change the status, when editing the quiz, the dropdown status-menu on the bottom left does not work. This is probably intended?

2022-05-09 09:23 UTC, canberkanar commented
> <img alt="Bildschirmfoto 2022-05-09 um 10 40 35" width="1348" src="https://user-images.githubusercontent.com/67310526/167373719-3a6ee951-4079-46fa-89dc-70dcddd52e82.png">
> 
> Tested on ts2, works as expected. One comment though: When I want to change the status, when editing the quiz, the dropdown status-menu on the bottom left does not work. This is probably intended?

Thank you for your review. Yes , the condition of the drop-down menu is intended and it will even be removed in a follow-up PR since it is not needed anymore.

2022-05-09 10:43 UTC, nadinesamyy approved these changes
Works as described, tested on ts3

2022-05-12 19:08 UTC, merged