`Assessment`: Improve the manual text selection for tutors
ls1intum/Artemis pull request #5035
Opened 2022-05-06 16:45 UTC by valeriebucher

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

During the assessment of text exercises, tutors can create custom text blocks by pressing `alt/option`, selecting a piece of text, and then clicking the `Assess` button. This functionality often leads to problems because the `Assess` button appears at a random position or not at all. (see screencast below)
The changes within this PR allow tutors to manually select text easier by clicking on the first and last word of the text they want to assess. 

### Description

There are multiple text block groups within a text submission; by iterating over these groups and splitting the text by spaces, we get the submission words that can be clicked on.
First, the word index within the whole submission needs to be calculated for each selected word. The selected word and its index are saved in an array. Once two words are selected, the array is emitted to the `manual-textblock-selection.component` where the corresponding text block is created.

### Steps for Testing

Prerequisites:
- 1 Tutor
- 1 Text Exercise with a submission

1. Go to the `Exercise Dashboard` of the text exercise.
2. Start the assessment on a text submission.
3. Press `alt/option` to select a custom text block.
4. Click on the first and last word of the text block you want to assess. The corresponding textblock should be created.
5. Change the order: Click the ending word first and then the starting word. The corresponding textblock should be created.
6. Check that it works if the submission contains whitespaces (linebreaks, tabs, spaces).
7. Check that nothing should happen if the tutor clicks on two words but an already created text block is inbetween (see screenshot example).

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots

**Old version:**

https://user-images.githubusercontent.com/73841445/167175066-62983f94-cae5-4247-86dd-fe3029b29f92.mov

**New version:**

https://user-images.githubusercontent.com/73841445/167175100-a3042868-d62d-4def-acf0-853f2b58db0c.mov

**Example for testing step 6:**

<img width="379" alt="Bildschirmfoto 2022-05-06 um 17 29 50" src="https://user-images.githubusercontent.com/73841445/167175192-23a2465c-61ab-498e-9c60-3dd40fe65767.png">

2022-05-06 17:19 UTC, joaquinmurcia approved these changes
Works as expected, even when in step 7 you click a word that is inside the selected block.
Good work, needed feature :smile:

2022-05-06 19:00 UTC, bassner requested changes
Please see my inline comment :)

2022-05-07 16:23 UTC, alaraozdenler submitted a review, later dismissed
Tested on ts3, works as described

2022-05-07 18:17 UTC, xlieA submitted a review, later dismissed
Tested on ts3. Everything worked as described in the testing steps. Very useful :)

2022-05-08 10:48 UTC, valeriebucher commented on src/main/webapp/app/exercises/text/shared/manual-text-selection/manual-text-selection.component.scss
> +
Thank you for the detailed description! I adapted it.

2022-05-08 13:44 UTC, nadinesamyy approved these changes
Tested on TS3, all reported enhancements work as expected

2022-05-08 13:46 UTC, nadinesamyy submitted a review, later dismissed

2022-05-08 20:15 UTC, bassner approved these changes
Thanks for the updates! Code looks good to me now.
Tested the feature on TS5, works as intended.
Good job 👍

2022-05-09 07:35 UTC, ge65cer submitted a review, later dismissed
Everything works alright. I get a bit of a weird behavior when the submission has multiple subsequent spaces, but nothing breaks.

<img width="500" alt="Screenshot" src="https://user-images.githubusercontent.com/102237363/167361839-e476bbbc-266a-49d4-bac0-dcc5e45c2d90.png">

2022-05-09 07:52 UTC, joaquinmurcia approved these changes

2022-05-09 13:59 UTC, Santia-go submitted a review, later dismissed
Tested on TS1
Working as expected!
The corresponding textblock is created even with whitespaces.

2022-05-09 17:53 UTC, jschmautzer approved these changes
tested on ts1, worked as expected, great feature!

2022-05-10 08:44 UTC, jbllhff approved these changes
tested on ts2, thanks!

2022-05-10 10:42 UTC, mallgaier submitted a review, later dismissed
Tested, genuinely nice enhancement
Excellent work 👍

2022-05-11 11:25 UTC, max-bergmann approved these changes
Tested on TS3. Works as expected

2022-05-11 12:25 UTC, maximiliansoelch requested changes
Tested on TS1, feature works as expected 👍
But there is a small typo in your German translation string.

2022-05-11 12:25 UTC, maximiliansoelch commented on src/main/webapp/i18n/de/textAssessment.json
> +            "assessmentInstruction": "Bitte bewege die Maus über den zu bewertenden Textblock und klicke diesen an, um ihn zu bewerten.<br>Um eigene Textblöcke zu bewerten, drücke <code>alt</code>/<c
```suggestion
            "assessmentInstruction": "Bitte bewege die Maus über den zu bewertenden Textblock und klicke diesen an, um ihn zu bewerten.<br>Um eigene Textblöcke zu bewerten, drücke <code>alt</code>/<code>option</code> und klicke in beliebiger Reihenfolge auf das erste und letzte Wort eines Textabschnitts.",
```

2022-05-13 08:08 UTC, maximiliansoelch approved these changes

2022-05-15 06:25 UTC, ge65cer approved these changes

2022-05-16 06:49 UTC, mallgaier approved these changes
Re-approve after typo fixing

2022-05-16 10:15 UTC, rhubinger approved these changes
Tested on TS2. Worked as described.

2022-05-16 14:20 UTC, bassner approved these changes
Reapprove (typo)

2022-05-17 06:18 UTC, Santia-go approved these changes
Tested on TS1
Working as expected!
The corresponding text block is created even with whitespaces.

2022-05-17 14:08 UTC, merged