`Programming exercises`: Store Default Branch in Database
ls1intum/Artemis pull request #5086
Opened 2022-05-13 19:22 UTC by JohannesStoehr

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [ ] I implemented the changes with a good performance and prevented too many database calls.
- [ ] I documented the Java code using JavaDoc style.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

Retrieving the default branch for many git operations is not performant and can slow down the system.

### Description

This PR stores the default Branch for the used repositories in the database of Artemis and only retrieves them from the VCS if necessary.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

2022-05-17 21:12 UTC, dfuchss commented
@JohannesStoehr do you think we could try to add that to the next mile stone? This feature would help us a lot :)

2022-05-19 10:05 UTC, nairaarnez reviewed
While trying to use the online editor I couldn't submit the exercise. It Builded and tested for around 15 minutes now when I pressed the submit button.
![image](https://user-images.githubusercontent.com/104493356/169268183-623e34b2-2bbd-4642-8ff1-0e9f1ed2cc9a.png)

2022-05-19 13:07 UTC, Dominik-Weinzierl reviewed
The online editor works on TS2 with this PR - could you please test it again @nairaarnez :thinking:

2022-05-19 13:09 UTC, willergeorg approved these changes
Tested on TS2. Working with online editor worked fine. I could not reproduce the issues reported by @nairaarnez.

2022-05-19 13:10 UTC, JohannesStoehr commented
> While trying to use the online editor I couldn't submit the exercise. It Builded and tested for around 15 minutes now when I pressed the submit button.
> ![image](https://user-images.githubusercontent.com/104493356/169268183-623e34b2-2bbd-4642-8ff1-0e9f1ed2cc9a.png)

There were some problems with the Buildagents on TS1. This is probably related.

2022-05-19 13:14 UTC, cremertim submitted a review, later dismissed
Tested on ts2, worked as expected. Was not able to reproduce the bug either

2022-05-19 14:23 UTC, nairaarnez reviewed
I just deployed another PR and I become the same message, it is not because of your PR Johannes! Does someone happend to know why do I get this message?

2022-05-20 08:32 UTC, krusche commented on src/main/java/de/tum/in/www1/artemis/service/connectors/VersionControlService.java
> +    String getOrRetrieveDefaultBranchOfParticipation(ProgrammingExerciseParticipation participation);
Can we rename this to `getOrRetrieveBranchOfParticipation`
(same for the methods below)

2022-05-20 09:12 UTC, dfuchss commented
I've created a project with old "master" branch. 
Afterwards, I've stopped artemis and delted the repos on the local clone of artemis.

Afterwards, I've changed the default branch to "main" and updated to this PR.

Now I get internal server errors (gitlab/jenkins setup) while opening the "Edit in Editor" view as instructor:

```
2022-05-20 09:12:11.114 ERROR 1 --- [nio-8080-exec-9] o.z.problem.spring.common.AdviceTraits   : Internal Server Error

java.lang.IllegalArgumentException: null
        at de.tum.in.www1.artemis.web.rest.repository.RepositoryProgrammingExerciseParticipationResource.getOrRetrieveDefaultBranchOfDomainObject(RepositoryProgrammingExerciseParticipationResource.java:165)
        at de.tum.in.www1.artemis.web.rest.repository.RepositoryResource.getStatus(RepositoryResource.java:294)
        at de.tum.in.www1.artemis.web.rest.repository.RepositoryProgrammingExerciseParticipationResource.getStatus(RepositoryProgrammingExerciseParticipationResource.java:348)
        at de.tum.in.www1.artemis.web.rest.repository.RepositoryProgrammingExerciseParticipationResource$$FastClassBySpringCGLIB$$9ebf5bf.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
```

2022-05-20 09:12 UTC, dfuchss requested changes
See comment

2022-05-20 10:18 UTC, dfuchss approved these changes
Code works on our Test System

2022-05-20 11:01 UTC, merged