`Development`: Add test case for REST API endpoint which gets all editors in a course
ls1intum/Artemis pull request #5112
Opened 2022-05-16 22:16 UTC by sunsetcoder

### Checklist
#### General
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).

### Motivation and Context

Added test case to CourseTestService.java to improve coverage for CourseResource.java (REST endpoint) which gets all editors in a course.

### Description

CourseTestService.java (lines 1062-1070): testGetAllEditorsInCourse() 

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

2022-05-18 14:57 UTC, Strohgelaender requested changes
Currently, this test will never be executed. You need to additionally call these methods in `CourseGitlabJenkinsIntegrationTest` and `CourseBitbucketBambooJiraIntegrationTest`.

2022-05-18 23:03 UTC, sunsetcoder commented
> Currently, this test will never be executed. You need to additionally call these methods in `CourseGitlabJenkinsIntegrationTest` and `CourseBitbucketBambooJiraIntegrationTest`.

Thanks for your feedback, I commited the changes.

2022-05-20 19:17 UTC, Strohgelaender approved these changes
Small test but it gets the job done.

2022-05-29 17:03 UTC, b-fein approved these changes

2022-06-05 19:52 UTC, merged