`Discussion`: Improve design of Post and AnswerPost components
ls1intum/Artemis pull request #5134
Opened 2022-05-21 14:30 UTC by canberkanar

### Checklist
#### General

- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

2022-05-21 15:35 UTC, nadinesamyy submitted a review, later dismissed
tested on ts3, everything works as described and expected

2022-05-21 16:29 UTC, alaraozdenler approved these changes
Tested on TS1, works as described

2022-05-21 18:50 UTC, SimonPaul02 submitted a review, later dismissed
Tested on TS1, everything works!!
But I found a different issue: You can edit and delete comments from other people, even as a student

2022-05-21 18:51 UTC, yuling-sun submitted a review, later dismissed
Tested on TS1. Changes worked as described.

2022-05-22 00:44 UTC, babyygemperor approved these changes
Tested on TS1, works exactly like described

2022-05-22 01:40 UTC, canberkanar commented
> Tested on TS1, everything works!! But I found a different issue: You can edit and delete comments from other people, even as a student

Thank you for your feedback. The issue is probably related to a configuration problem on the test server, as mentioned here.
https://ls1tum.slack.com/archives/C012NFRM76F/p1653160446025809

2022-05-22 19:05 UTC, max-bergmann submitted a review, later dismissed
Tested on TS1. Works as expected

2022-05-23 09:23 UTC, ole-ve approved these changes
Tested in the testing session on TS1, works as described.

2022-05-23 09:31 UTC, Lugitan submitted a review, later dismissed
Tested in the testing session on TS1, works as described.

2022-05-23 10:05 UTC, akesfeden approved these changes
Tested on TS1 during testing session as an Instructor, works as expected and looks good 👍

2022-05-23 10:54 UTC, manuelmanso approved these changes
Tested on TS1 during testing session, looks good!

2022-05-23 10:59 UTC, minrows submitted a review, later dismissed
Tested in the testing session on TS1, works as described.

2022-05-23 14:42 UTC, bassner requested changes
Reviewed the code, looks good! Just have two minor remarks

2022-05-23 14:42 UTC, bassner commented on src/main/webapp/app/shared/metis/posting-reactions-bar/post-reactions-bar/post-reactions-bar.component.html
> +            (click)="currentUserIsAtLeastTutor && togglePin()"
Is this required? 🤔 
Seems like the button is disabled already, is there a reason for this check?
```suggestion
            (click)="togglePin()"
```

2022-05-23 17:21 UTC, canberkanar commented on src/main/webapp/app/shared/metis/posting-reactions-bar/answer-post-reactions-bar/answer-post-reactions-bar.component.html
> +        <button id="answerNowButton" class="reaction-button clickable" (click)="openPostingCreateEditModal.emit()">
Yes, it is possible, but they would be in different components. Is it a convention error here to have the same ID for these elements, can it cause severe problems?

2022-05-23 20:01 UTC, bassner commented on src/main/webapp/app/shared/metis/posting-reactions-bar/answer-post-reactions-bar/answer-post-reactions-bar.component.html
> +        <button id="answerNowButton" class="reaction-button clickable" (click)="openPostingCreateEditModal.emit()">
It doesn't matter if it's in different components - the browser and the DOM are not aware of components, they just see a big tree of HTML. I think in practice it's tolerated by the browser (and prints a warning iirc), but for example any calls to ``document.getElementById()`` would only return the first element. Nevertheless, it's still a bad practice that should be avoided

2022-05-24 08:54 UTC, canberkanar commented
There was a minor change for testing convention. For this I don't think that another manual testing is necessary.

2022-05-24 09:34 UTC, bassner approved these changes
Thank you for the fixes. LGTM! 👍 
Can approve that manual retesting is not necessary. The PR had like 8 tester confirmations before the last small change.

2022-05-25 22:34 UTC, merged