`Development`: Reduce number of server log messages for modeling submission updates
ls1intum/Artemis pull request #5146
Opened 2022-05-24 14:19 UTC by b-fein

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
~- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).~
~- [ ] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).~
- [x] I implemented the changes with a good performance and prevented too many database calls.
~- [ ] I documented the Java code using JavaDoc style.~

### Motivation and Context
The endpoint to update modelling submissions is called on a timer (30sec) in the client. Every call produced a message in the server log with a time measurement. This leads to a lot of messages in the server log when many students work on modelling exercises.

### Description
The log call has been removed to avoid spamming the log with unnecessary messages. The time measurement can be obtained from the `/admin/metrics` page in the client as well.

### Steps for Testing
n/a

### Review Progress

#### Code Review
- [x] Review 1
- [x] Review 2

### Test Coverage
unchanged

2022-05-25 14:59 UTC, SimonPaul02 approved these changes
Looks good! Thank you for keeping the log messages clean

2022-05-25 14:59 UTC, yuling-sun approved these changes
Reviewed code changes. LGTM.

2022-05-25 15:48 UTC, Strohgelaender requested changes
The fact that such messages exist indicates that the corresponding server call was / is way too slow; these messages were added to help with debuggng. As long as we don't have a confirmation that the underlying issue is fixed (cc @krusche) I would opt to not remove them.

To keep the logs clean, I think changing the level from info to debug would be possible directly.

2022-05-26 17:22 UTC, Strohgelaender approved these changes

2022-05-26 22:51 UTC, merged