`Programming Exercises`: Update Ares to 1.10.0
ls1intum/Artemis pull request #5173
Opened 2022-05-29 09:33 UTC by b-fein

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context
A new version of Ares has been released: https://github.com/ls1intum/Ares/releases/tag/1.10.0

This new release can be used in Artemis once https://github.com/ls1intum/artemis-maven-docker/pull/87 has been merged and a new release of the Docker image the tests run in has been released.

### Description
Updates Ares as used in the Java and Kotlin templates to the new version.

### Steps for Testing
Prerequisites:
- 1 Instructor

1. Create a new Java programming exercise with the Maven project template.
2. The solution repo should still pass all tests.
3. Repeat the steps with the Gradle project template.
4. Repeat the steps with a Kotlin exercise.

### Review Progress

#### Manual Tests
- [ ] Test 1 on a test server connected to Bamboo
- [ ] Test 2 on a test server connected to Jenkins

2022-05-29 09:48 UTC, Strohgelaender submitted a review, later dismissed

2022-05-29 12:12 UTC, ole-ve approved these changes

2022-06-01 06:16 UTC, MaisiKoleni commented
Note that there is now a newer version `1.10.1`

2022-06-02 11:09 UTC, Strohgelaender submitted a review, later dismissed

2022-06-04 22:25 UTC, ole-ve approved these changes

2022-06-05 09:08 UTC, krusche approved these changes

2022-06-05 10:30 UTC, ole-ve requested changes
Tested manually on TS0 (Bamboo), TS1 (Bamboo), and TS2 (Jenkins). When executing the build plan on TS1, I encountered a weird error. The memory for the JVM seems to be exceeded resulting in a build error:

```
05-Jun-2022 11:57:51 | 88ffd43f9125308f2be7ac4aefbe4b4ea6a4ad07fec9e1b3326ab1d8260581f1
05-Jun-2022 11:57:54 | [0.008s][warning][os,thread] Failed to start thread - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
05-Jun-2022 11:57:54 | #
05-Jun-2022 11:57:54 | # There is insufficient memory for the Java Runtime Environment to continue.
05-Jun-2022 11:57:54 | # Cannot create worker GC thread. Out of system resources.
05-Jun-2022 11:57:54 | # An error report file with more information is saved as:
05-Jun-2022 11:57:54 | # /opt/bambooagent/bamboo-agent-home/xml-data/build-dir/OLETESTJAVAMAVENSCA-SOLUTION-JOB1/hs_err_pid57.log
05-Jun-2022 11:57:54 | [0.007s][warning][os,thread] Failed to start thread - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
05-Jun-2022 11:57:54 | #
05-Jun-2022 11:57:54 | # There is insufficient memory for the Java Runtime Environment to continue.
05-Jun-2022 11:57:54 | # Cannot create worker GC thread. Out of system resources.
```

This issue seems to be related to the updated docker image as the build execution works fine with the newest Ares but the previous docker image.

I have encountered this issue on all build execution on TS1, only some build execution on TS0, and for no build executions on TS2. This indicates a problem with the build agents, maybe due to being junked by multiple docker images.

2022-06-05 17:07 UTC, Strohgelaender approved these changes

2022-06-05 17:08 UTC, ole-ve approved these changes

2022-06-05 19:47 UTC, krusche approved these changes

2022-06-05 19:48 UTC, merged