`Discussion`: Self-host emoji set and replace some important dark emojis in the dark mode
ls1intum/Artemis pull request #5186
Opened 2022-06-01 13:22 UTC by bassner

### Checklist
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Some heavy emojis shown as reactions and in the emoji picker are currently hard to see on the dark background of the dark mode, especially the heavy plus icon that is used for up-voting.

Moreover, the emoji and emoji-picker components currently fetch the emoji sheet from unpkg, which is a privacy / GDPR problem.

Fixes #5118.

### Description

- Self-host the emoji sheet on the Artemis server to prevent requests to external CDNs.
- Provide inverted versions of some heavy icons for the dark mode
- Created new wrapper components for emojis and the emoji picker to hide the dark mode handling details, and to make them reusable elsewhere in the application in the future (outside of metis).

The sheet will be downloaded from the Artemis server as soon as the data is needed. The full sheet is currently a bit less than 4MB large, which is unproblematic. We do not use the native / system-provided sheet to ensure a consistent look of emojis across platforms.

For dark mode, some icons will be individually replaced. We do not replace the full emoji sheet, but only a few certain emojis using individual PNGs to minimize traffic / loading times. Each of the replaced images is just a few KB at most. 
This will make upgrading the emoji set easy in the future, as the emoji sheet can simply be replaced with a new one without the need to edit anything - the replaced icons should still work after an upgrade if their position in the unicode didn't change, which is unlikely to ever happen.

Fixes caching of static resources; the previous config did not have any effect due to wrong paths being used.
Replaced it with a new, selective caching config for about us images and emoji assets.

### Steps for Testing

Prerequisites:
- 1 Student

1. Log in to Artemis, open Network Tab in Dev Tools
2. Navigate to the discussion page of a course
3. Add / remove reactions; play around:
    - Make sure that all emojis still work
    - make sure that the emoji picker still works
4. Switch the theme. Verify that reactions with the replaced heavy icons do change their color accordingly. Verify that they change their color in the emoji picker as well
5. Using Chrome, please verify that the emojis do not visually reload if you change the category in the picker or add a new reaction to a post
6. Reload the page (no force reload!). Verify that emoji assets are served from the cache. 
7. Verify that requests to fetch emoji assets (either the full sheet or single images) have a caching header with ``max-age=126230400, public``
8. Verify that other requests still have a no-cache value in the same header field
9. Visit the About us page using the link in the footer. Verify that the images have a long duration in the caching header just like the emoji assets, but the "about-us.json" does have a no-cache header

### Review Progress

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| emoji-picker.component.ts | 83% | 100% |
| emoji.component.ts | 75% | 100% |
| emoji.utils.ts | 100% | 100% |

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

https://user-images.githubusercontent.com/23171488/171414432-daf17367-bbcb-4481-adaa-1f4757f244b1.mov

![Screenshot 2022-06-01 at 15 02 50](https://user-images.githubusercontent.com/23171488/171414448-e5eded44-56cf-4ed9-9c93-4d7515124815.png)
![Screenshot 2022-06-01 at 15 02 35](https://user-images.githubusercontent.com/23171488/171414449-093dd81c-220e-4708-b1f9-470849ec8367.png)

2022-06-01 16:20 UTC, jbllhff approved these changes
Tested on ts2, works fine. Yet, when adding an emoji all other existing emojis reload again as well.

2022-06-01 16:57 UTC, bassner commented on src/main/webapp/app/shared/metis/emoji/emoji.utils.ts
> +    '1F519', // back
Yeah, why not :D

2022-06-01 16:57 UTC, bassner commented on src/main/webapp/app/shared/metis/emoji/emoji-picker.component.ts
> +        <emoji-mart
Mainly avoiding file spam 🤷‍♂️ 
But you're right that we should follow the style guide :)

2022-06-01 16:59 UTC, bassner commented
> when adding an emoji all other existing emojis reload again as well
Could you explain that bit more in detail? I can't observe any similar behavior

2022-06-01 17:05 UTC, bassner commented on src/main/webapp/app/shared/metis/emoji/emoji-picker.component.ts
> +    onEmojiSelect(event: any) {
Actually, no. The type definitions of ``emoji-mart`` specify the event emitter to be of type ``any``, see https://github.com/scttcper/ngx-emoji-mart/blob/5e5dd914834e0c24f99d8b5a403f76caf8bf71fe/src/lib/picker/picker.component.ts#L111

2022-06-01 19:52 UTC, nadinesamyy approved these changes
tested on ts2, works well

2022-06-01 20:31 UTC, TheTrueVester submitted a review, later dismissed
Tested on ts3. Encountered one slight/weird issue. At 100% resolution (of 2560 x 1440) and only in light mode, one emoji (the white heart) gets a random line. The line disappears if I zoom in, but stays if I zoom further out. It however is just a very minor and weird issue. 
![image](https://user-images.githubusercontent.com/47668936/171495917-943719aa-b104-4190-b02c-9c6cb2092c05.png)

2022-06-01 20:38 UTC, TheTrueVester commented
> > when adding an emoji all other existing emojis reload again as well
> 
> Could you explain that bit more in detail? I can't observe any similar behavior @jbllhff

I encountered the same situation. Whenever a new emoji is added, all others disappear and need to reload (which takes a few seconds). When switching between emoji tabs, the pages start off blank (see screenshot) and need to load for a few seconds. Even switching back to a previously loaded tab requires waiting a few seconds for the emojis to reload.

![image](https://user-images.githubusercontent.com/47668936/171496988-0fc69f23-1d86-44b3-88c2-e631d5c94853.png)
![image](https://user-images.githubusercontent.com/47668936/171497078-b92ed673-1ec5-45fb-ab06-b17c3cdcf28e.png)

2022-06-02 06:31 UTC, cremertim submitted a review, later dismissed
tested on ts1, emojis work in both themes

2022-06-02 08:12 UTC, ge65cer requested changes
Tested on TS1, Firefox and Safari look fine. 👍 
There is some flickering in Chrome as it reloads the emoji set every time one opens the picker.

2022-06-02 08:14 UTC, bassner commented
The reloading issue reported above seems to only happen in Chrome. Need to investigate that

2022-06-02 11:57 UTC, bassner commented
@jbllhff @TheTrueVester @ge65cer Could you please re-test this PR with my new fix on Chrome? Caching should now work properly and no flickering be visible anymore after the emoji assets were loaded initially

2022-06-02 13:48 UTC, Hialus submitted a review, later dismissed
Code looks good to me now. 
Also tested it in the developer meeting using Firefox and it worked as expected.
Well done 👍🏻

2022-06-04 22:31 UTC, TheTrueVester approved these changes
Re-tested on ts1 using Chrome. Everything now works properly. There is no more extended waiting time. The previously mentioned white heart having a random line issue still occurs, but isn't important.

2022-06-05 19:56 UTC, krusche commented
Some additional client code was introduced in this PR which seems to be untested. Could you please add some client tests and also mention the coverage in the description? Thanks

2022-06-05 23:53 UTC, babyygemperor submitted a review, later dismissed
Tested on ts1, works as described

2022-06-06 16:47 UTC, bassner commented
Added some client tests for the new components

2022-06-07 17:02 UTC, Hialus approved these changes
The new client tests look good.
Re-approve code 👍🏻

2022-06-08 10:17 UTC, merged