`Development`: Use artemisApp as consistent prefix for translation keys
ls1intum/Artemis pull request #5189
Opened 2022-06-01 20:09 UTC by Strohgelaender

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [ ] I implemented the changes with a good performance and prevented too many database calls.
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

2022-06-13 20:13 UTC, Dominik-Weinzierl reviewed
The changes looks good to me :thinking: but instead of adding all the prefixes, we could also just remove them :thinking: are they really required?

2022-06-14 09:09 UTC, rhubinger approved these changes
Tested on TS2. Everyting works and translations look good.

2022-06-14 12:03 UTC, SimonPaul02 submitted a review, later dismissed
Tested on TS2. Everything works as expected

2022-06-14 12:04 UTC, yuling-sun approved these changes
Tested on TS2. Strings look fine to me.

2022-06-18 07:31 UTC, Santia-go approved these changes
Tested on TS1
I have tested the functionality of course, exam, exercises, and shared files. 
They are working correctly. The corresponding tests look good.

2022-06-21 08:37 UTC, Santia-go submitted a review, later dismissed
ReTested on TS1
User and Organisation Management works fine
All around the Modeling Exercises works well also
No errors in Quiz-Statistics

2022-07-02 14:40 UTC, Marvin-Vitcu requested changes
When using the filter in User Management. Some translations are not found:

englisch version:
![image](https://user-images.githubusercontent.com/36523308/177005244-6525aad8-6dab-4105-aa9b-29245b4d91c8.png)

german version:
![image](https://user-images.githubusercontent.com/36523308/177005270-4311cb15-252a-4979-8447-7b4502e88721.png)

2022-07-02 16:50 UTC, Marvin-Vitcu approved these changes
Tested on TS1. The User Management Filter now displays the correct translation.

2022-07-09 15:37 UTC, max-bergmann approved these changes
Tested on TS2. Works as expected

2022-07-10 16:22 UTC, SimonPaul02 submitted a review, later dismissed
Retested on TS1👍

2022-07-10 16:22 UTC, yuling-sun submitted a review, later dismissed
Re-tested on TS1. Translations look good.

2022-07-28 00:08 UTC, nairaarnez requested changes
Tested in TS1, there are some small details:
![image](https://user-images.githubusercontent.com/104493356/181392403-90579445-8eeb-4ac7-9033-8ce75d521a59.png)
Ich würde es zu "erweiterte Suche (an?)zeigen" umschreiben
![image](https://user-images.githubusercontent.com/104493356/181392454-1fcb08f4-752e-433e-a311-788e40a718d7.png)
"Code Hinweise generieren", "Unterschied zwischen Template und Lösung zeigen" und " strukturelle Solution Entries erstellen"
![image](https://user-images.githubusercontent.com/104493356/181392746-826019e9-83d3-4988-abeb-2aeb15eca0e4.png)
"Hinweise Verwalten"
![image](https://user-images.githubusercontent.com/104493356/181392688-3110cdbd-abd5-43f6-bb70-b090e6957357.png)
to increase consistency in the writing. All verbs in the end (I would suggest this) or at the beginning (imperative)

2022-07-28 17:21 UTC, Strohgelaender commented
@nairaarnez Thanks for the review. This PR is only about refactoring the translation keys. I don't want to change the values as well since this PR is already quite big and should not get even bigger.

2022-07-29 10:12 UTC, JohannesStoehr approved these changes
Code looks good after the merge 👍

2022-07-29 10:20 UTC, nairaarnez approved these changes
Tested in ts1, looks good, approved!

2022-07-30 07:06 UTC, ge65cer reviewed
We should probably merge https://github.com/ls1intum/Artemis/pull/5296/ before this, so error messages also have a consistent `artemisApp` prefix?

2022-07-30 12:47 UTC, Strohgelaender commented
@ge65cer I did not touch error.json in the other PR, they should not conflict each other. We also cannot add the prefix to error.json because it contains translations for non-Artemis error keys.

2022-08-02 13:02 UTC, JohannesStoehr submitted a review, later dismissed
Checked the latest merge commit. Changes still look good

2022-08-25 07:50 UTC, jpbernius commented on src/main/webapp/app/core/about-us/about-us.component.html
> +                            <a href="{{ pm.website }}" target="_blank">{{ 'artemisApp.aboutUsOverview.website' | artemisTranslate }}</a>
This is a valid comment, however, this is not related to the changes here and should be addressed in a follow-up.

2022-08-25 07:53 UTC, merged

2022-08-25 10:33 UTC, jpbernius commented
Unfortunately, this PR broke two quiz-related test cases. Fixed in a4ed66d.