`General`: Don't show "No description available" in course header
ls1intum/Artemis pull request #5229
Opened 2022-06-10 13:35 UTC by JohannesStoehr

### Checklist
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

The header of exercises and courses should be small and don't take up unnecessary screen space. Therefore unavailable and not completely necessary information should be left out.

### Description

If a course has no description, it's not shown in the course header any more instead of "No description available".

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Go to a course with no description
3. Check that there is no unnecessary string
4. Add a description to the course
5. Check that it's correctly displayed

### Review Progress

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Old:
![Bildschirmfoto 2022-06-10 um 16 18 25](https://user-images.githubusercontent.com/38322605/173085682-0222e7c3-231a-4c03-956b-9fa01a219c0e.png)
New:
![Bildschirmfoto 2022-06-10 um 16 21 56](https://user-images.githubusercontent.com/38322605/173086306-56530127-0bfb-47d3-9043-3de38206c927.png)

2022-06-10 15:07 UTC, ge65cer requested changes
Please remove the extra margin on the bottom when no description is shown.

<img width="400" alt="Screenshot 2022-06-10 at 17 06 11" src="https://user-images.githubusercontent.com/102237363/173095115-20b8b36f-8d91-4cbc-9a1e-ee90619d26b8.png">

2022-06-10 15:28 UTC, nadinesamyy reviewed
"translation-not-found[descriptionTest]" was displayed instead of the text, not sure if this is an error from the ts or if it is related to the PR but I tested on ts1/ts3

2022-06-10 16:03 UTC, ge65cer commented
Thanks for fixing the margin. If the course description is an empty string, the description should also be hidden, shouldn't it?

2022-06-10 16:07 UTC, ge65cer commented
Thanks for fixing the margin. If the course description is an empty string (whitespace), the description should also be hidden, shouldn't it?

2022-06-10 20:16 UTC, JohannesStoehr commented
>  If the course description is an empty string (whitespace), the description should also be hidden, shouldn't it?

Currently it is not possible set the description to an empty string. And multiple whitespaces should rather get filtered out when saving the changed course than in the exercise header. So I would handle this in this PR

2022-06-11 10:41 UTC, willergeorg submitted a review, later dismissed
Tested on TS5. I agree with @ge65cer, that invalid descriptions (e.g. only spaces), should also be omitted. If this is out of scope of this PR, please provide a follow-up as soon as possible. Code lgtm as well. :)

2022-06-11 13:15 UTC, Dominik-Weinzierl reviewed
Some minor suggestions

2022-06-11 13:15 UTC, Dominik-Weinzierl commented on src/main/webapp/app/course/manage/detail/course-detail.component.html
> +                    <h3 class="fw-medium" [ngStyle]="courseDescription ? {} : { 'margin-bottom': 0 }">{{ course.title }}</h3>
```suggestion
                    <h3 class="fw-medium" [class.mb-0]="!courseDescription">{{ course.title }}</h3>
```
Should also work (please test this first :D) ->  https://angular.io/guide/class-binding

2022-06-11 13:15 UTC, Dominik-Weinzierl commented on src/main/webapp/app/overview/course-overview.component.html
> +                    <h3 class="fw-medium" [ngStyle]="courseDescription ? {} : { 'margin-bottom': 0 }">{{ course.title }}</h3>
same as above :)

2022-06-12 08:24 UTC, jschmautzer approved these changes
tested on ts1, works as described

2022-06-12 20:29 UTC, TheTrueVester submitted a review, later dismissed
Tested on ts1. Everything worked as expected.

2022-06-13 07:58 UTC, alaraozdenler submitted a review, later dismissed
Tested on ts2, works as described

2022-06-13 08:23 UTC, babyygemperor submitted a review, later dismissed
Tested on ts1, works as described

2022-06-13 10:30 UTC, jbllhff submitted a review, later dismissed
Tested on ts2, works great!

2022-06-13 15:15 UTC, Dominik-Weinzierl approved these changes
code 👍

2022-06-13 19:44 UTC, mallgaier approved these changes
Tested, works as expected. Good job 👍

2022-06-14 07:42 UTC, ge65cer approved these changes
Approved, please keep the follow-up PR in mind.

2022-06-15 10:01 UTC, merged