`General`: Responsive length of course header description
ls1intum/Artemis pull request #5276
Opened 2022-06-22 19:09 UTC by JohannesStoehr

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [ ] I implemented the changes with a good performance and prevented too many database calls.
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [ ] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

2022-06-23 02:45 UTC, akesfeden reviewed
Tested on TS2, works as described. I have the questions/suggestions below, I can approve according to whether they are going to be addressed in this PR or another one.
1. Can we use the space for the logo as well (even for bigger windows) if it is not set? (See the space at the right-side of the screenshot below)
2. Since the description can be long, what do you think about converting Description text input to a `textarea` where the user can also add new lines?

![image](https://user-images.githubusercontent.com/18427209/175196087-d3c8dea6-2c49-4269-ab8c-9f66682f2c31.png)

2022-06-23 08:36 UTC, jbllhff approved these changes
Tested on ts2, looks good, thanks!

2022-06-23 10:08 UTC, yuling-sun submitted a review, later dismissed
Tested on TS2. Course description works as expected.

2022-06-23 10:08 UTC, SimonPaul02 approved these changes
Tested on Ts2, works as expected

2022-06-23 12:28 UTC, rhubinger submitted a review, later dismissed
Tested on TS2. Works as described

2022-06-23 18:38 UTC, alaraozdenler submitted a review, later dismissed
Tested on ts1, works as described

2022-06-23 19:51 UTC, ge65cer commented
> 1. Can we use the space for the logo as well (even for bigger windows) if it is not set? (See the space at the right-side of the screenshot below)

That's a nice idea. Probably not too hard to implement, just remove the column if no logo is set.

2022-06-23 19:54 UTC, ge65cer submitted a review, later dismissed
Tested on TS2, works! Code also approved.

2022-06-23 22:23 UTC, julian-christl requested changes
Very small remarks

2022-06-24 00:07 UTC, babyygemperor submitted a review, later dismissed
Tested on ts2, works as described

2022-06-24 08:35 UTC, JohannesStoehr commented on src/test/javascript/spec/component/course/header-course.component.spec.ts
> +                component = TestBed.createComponent(HeaderCourseComponent).componentInstance;
I looked through the code. inject is used for services and controllers, createComponent for Components

2022-06-24 11:16 UTC, Dominik-Weinzierl approved these changes
Thanks for implementing our suggestions :+1: we talked about the text area during the testing session and i think its a good choice :+1: Code looks good to me!

2022-06-24 11:42 UTC, ge65cer approved these changes
Re-approve

2022-06-24 11:55 UTC, julian-christl commented on src/test/javascript/spec/component/course/header-course.component.spec.ts
> +                component = TestBed.createComponent(HeaderCourseComponent).componentInstance;
Ah, alright. Then I remembered this wrongly!

2022-06-24 11:55 UTC, julian-christl approved these changes
Thanks for the fix, code approved.

2022-06-25 11:14 UTC, willergeorg approved these changes
Tested it on TS1. Looks good on different screen sizes. 👍

2022-06-25 14:17 UTC, babyygemperor approved these changes
Tested on ts2 again, works as described 👍🏼

2022-06-26 19:35 UTC, max-bergmann approved these changes
Tested on TS1. Works as expected

2022-06-27 09:48 UTC, merged