`Development`: Handle simultaneous plagiarism checks
ls1intum/Artemis pull request #5288
Opened 2022-06-25 15:22 UTC by Dominik-Weinzierl

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [ ] I implemented the changes with a good performance and prevented too many database calls.
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [ ] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

2022-06-26 06:27 UTC, krusche commented on src/main/java/de/tum/in/www1/artemis/service/plagiarism/ModelingPlagiarismDetectionService.java
> +            return null;
we should throw an exception here

2022-06-26 06:28 UTC, krusche commented on src/main/java/de/tum/in/www1/artemis/service/plagiarism/ModelingPlagiarismDetectionService.java
> +        plagiarismCacheService.disablePlagiarismCheck(courseId);
we need to make sure that this is always invoked, even if an exception occurs, so please put the code above in a try catch statement, re-throw the exception and invoked `disablePlagiarismCheck` in the final clause

2022-06-26 06:30 UTC, krusche commented on src/main/java/de/tum/in/www1/artemis/service/plagiarism/cache/PlagiarismCache.java
> +    private final IMap<Long, Boolean> activePlagiarismChecksPerCourse;
add documentation that Long means `courseId` here

2022-06-26 06:30 UTC, krusche commented on src/main/java/de/tum/in/www1/artemis/service/plagiarism/cache/PlagiarismCacheService.java
> +    public void enablePlagiarismCheck(Long courseId) {
```suggestion
    public void setActivePlagiarismCheck(Long courseId) {
```

2022-06-26 06:30 UTC, krusche commented on src/main/java/de/tum/in/www1/artemis/service/plagiarism/cache/PlagiarismCacheService.java
> +    public void disablePlagiarismCheck(Long courseId) {
```suggestion
    public void setInactivePlagiarismCheck(Long courseId) {
```

2022-06-26 06:31 UTC, krusche commented on src/main/java/de/tum/in/www1/artemis/web/rest/ModelingExerciseResource.java
> +            throw new BadRequestAlertException("Only one active plagiarism check per course allowed", "PlagiarismCheck", "oneActivePlagiarismCheck");
please throw this exception directly in the `checkPlagiarism` method

2022-06-26 06:31 UTC, krusche commented on src/main/java/de/tum/in/www1/artemis/service/plagiarism/cache/PlagiarismCacheService.java
> +    public void enablePlagiarismCheck(Long courseId) {
enable does not sound good in my opinion, same below for disable

2022-06-26 06:32 UTC, krusche commented on src/main/webapp/i18n/de/error.json
> +        "oneActivePlagiarismCheck": "Es wird bereits eine Plagiatskontrolle in diesem Kurs durchgeführt!"
Add something like "Bitte warte bis die aktuelle Plagiatskontrolle abgeschlossen ist, bevor du eine weitere startest"

2022-06-26 06:32 UTC, krusche commented on src/main/webapp/i18n/en/error.json
> +        "oneActivePlagiarismCheck": "There is already a plagiarism check in this course!"
Add something like "Please wait until the current plagiarism check has finished until you start another one"

2022-06-26 06:33 UTC, krusche requested changes
see my inline feedback

2022-06-26 09:08 UTC, ge65cer submitted a review, later dismissed
Tested on TS2. Could not start another plagiarism check under any circumstances when one is running. 👍

2022-06-26 09:11 UTC, ge65cer commented on src/main/webapp/i18n/en/error.json
> +        "oneActivePlagiarismCheck": "Please wait until the current plagiarism check has finished until you start another one."
Scenario: Two users want to start a plagiarism check for different exercises in the same course. Then this error message would be a bit more descriptive I'd say.
```suggestion
        "oneActivePlagiarismCheck": "Please wait until a plagiarism check in this course has finished until you start another one."
```

2022-06-26 09:11 UTC, ge65cer commented on src/main/webapp/i18n/de/error.json
> +        "oneActivePlagiarismCheck": "Bitte warte bis die aktuelle Plagiatskontrolle abgeschlossen ist, bevor du eine weitere startest."
```suggestion
        "oneActivePlagiarismCheck": "Bitte warte bis eine Plagiatskontrolle in diesem Kurs abgeschlossen ist, bevor du eine weitere startest."
```

2022-06-26 09:21 UTC, ge65cer submitted a review, later dismissed

2022-06-26 12:27 UTC, Dominik-Weinzierl commented
Tested on ts1 after refactoring - works still as expected :+1:

2022-06-26 17:15 UTC, Strohgelaender approved these changes
Code looks good, only one comment that could be resolved in a followup refactoring.

2022-06-26 17:15 UTC, Strohgelaender commented on src/main/java/de/tum/in/www1/artemis/config/Constants.java
> +    public static final String HAZELCAST_PLAGIARISM_PREFIX = "plagiarism-";
I guess we should stay consistent in this PR, but in the future / follow-up I think these are another set of constants that should rather be located in their own classes (PlagiarismCacheService, etc).

2022-06-26 19:49 UTC, max-bergmann approved these changes
Tested on TS1. Works as expected

2022-06-27 07:56 UTC, krusche approved these changes
Code looks good to me now 👍

2022-06-27 07:59 UTC, merged