`Learning Goals`: Allow instructors to define relations between learning goals
ls1intum/Artemis pull request #5311
Opened 2022-06-30 06:16 UTC by ge65cer

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [ ] I implemented the changes with a good performance and prevented too many database calls.
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [ ] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

2022-08-01 07:33 UTC, krusche commented
there is no feature for Learning goals (yet), so I renamed it to lectures as it currently is mostly related to lecture units. I know we change this in the future, but let's stick (for now) to the features defined in the README on Github and about page on Artemis.

I am happy to add a new feature such as "Competency-based learning" in the future, but we should first add it to the README on Github and the about page (with a minimal documentation) before using it.

2022-08-23 17:22 UTC, JohannesStoehr requested changes

2022-08-23 17:22 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/domain/LearningGoalRelation.java
> +                return null;
Codacy

2022-08-23 17:22 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/web/rest/LearningGoalResource.java
> +            @PathVariable Long headLearningGoalId, @RequestParam(defaultValue = "") String type) {
Codacy

2022-08-23 17:22 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/web/rest/LearningGoalResource.java
> +        var learningGoal = findLearningGoal(Role.INSTRUCTOR, learningGoalId, courseId, false, false);
Codacy

2022-08-23 17:22 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/web/rest/LearningGoalResource.java
> +    public ResponseEntity<Void> removeLearningGoalRelation(@PathVariable Long learningGoalId, @PathVariable Long courseId, @PathVariable Long learningGoalRelationId) {
Codacy

2022-08-23 17:22 UTC, JohannesStoehr commented on src/main/webapp/i18n/de/learningGoal.json
> +            "taxonomy": "Taxonomy",
```suggestion
            "taxonomy": "Taxonomie",
```
Is there no better German word?

2022-08-30 16:38 UTC, maximiliansoelch submitted a review, later dismissed
Tested locally, works as expected 👍

2022-08-31 17:39 UTC, akesfeden reviewed
Tested locally, overall works as described, nice feature! I noticed that in this configuration the diagram is not fit to view properly on first load, so addressing may be nice. But since it is draggable it is not very critical or a blocking issue, what do you think?

Also, it may be better in terms of usability if the diagram is updated in-place when a change is made so that the user does not need to expand it everytime, but again, this is not very urgent.

![image](https://user-images.githubusercontent.com/18427209/187743592-b6a93b1d-8873-4b0b-9263-6c27404a0f03.png)

2022-09-08 09:28 UTC, stefanwaldhauser approved these changes
Tested locally! Works great and code looks good too!

2022-09-14 09:10 UTC, stefanwaldhauser approved these changes
Reapprove! :)

2022-09-14 12:09 UTC, JohannesStoehr requested changes
You have some Codacy issues in [learning-goal-management.component.spec.ts](https://github.com/ls1intum/Artemis/pull/5311/files#diff-abe6e1859ae3e9f533cfd13bd67f3795cc615cac00bf54ec9b1f08e7977e03ce)

2022-09-15 13:27 UTC, JohannesStoehr approved these changes
Code looks good to me

2022-09-16 06:38 UTC, sleiss commented on src/test/java/de/tum/in/www1/artemis/LearningGoalIntegrationTest.java
> +    public void gLearningGoalRelations() throws Exception {
```suggestion
    public void getLearningGoalRelations() throws Exception {
```

I assume it should be like this

2022-09-16 06:40 UTC, sleiss commented on src/test/java/de/tum/in/www1/artemis/LearningGoalIntegrationTest.java
> +    public void deleteLearningGoal_witRelatedGoals_shouldReturnBadRequest() throws Exception {
Optional request: Maybe add a comment, why this test case returns a bad request (what condition was not fulfilled)

2022-09-16 06:44 UTC, sleiss submitted a review, later dismissed
Tested it in the testing session, code also looks good to me :+1:

2022-09-16 07:00 UTC, Dominik-Weinzierl approved these changes
Code looks good to me - clean structure 👍 in addition, i like the usage of the converter 🚀

2022-09-20 13:31 UTC, dangcosta approved these changes
Tested locally and works as expected.

2022-09-20 22:10 UTC, akesfeden approved these changes
Tested again locally, works as described. My points in the previous comment https://github.com/ls1intum/Artemis/pull/5311#pullrequestreview-1092269870 still hold, maybe they can be done in follow-ups, what do you think?

2022-09-21 07:17 UTC, ge65cer commented
@akesfeden Yes, I've noted it down. 🙂

2022-09-21 16:01 UTC, Dominik-Weinzierl approved these changes
Reapprove - looks still good

2022-09-21 18:51 UTC, manuelmanso approved these changes
Re-approve - thanks for considering the feedback

2022-09-21 19:31 UTC, stefanwaldhauser submitted a review, later dismissed
Reapprove!

2022-09-22 04:45 UTC, sleiss submitted a review, later dismissed
Re-approve

2022-09-25 10:00 UTC, merged