`Communication`: Integration Tests for Plagiarism Case Posts
ls1intum/Artemis pull request #5321
Opened 2022-07-01 14:10 UTC by canberkanar

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [ ] I implemented the changes with a good performance and prevented too many database calls.
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [ ] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

2022-07-04 10:53 UTC, manuelmanso approved these changes
Nice tests 👍

2022-07-06 09:22 UTC, Strohgelaender commented on src/test/java/de/tum/in/www1/artemis/metis/AnswerPostIntegrationTest.java
> +                .filter(coursePost -> (coursePost.getAnswers() != null && coursePost.getPlagiarismCase() == null)).toList();
```suggestion
                .filter(coursePost -> coursePost.getAnswers() != null && coursePost.getPlagiarismCase() == null).toList();
```

2022-07-06 09:22 UTC, Strohgelaender commented on src/test/java/de/tum/in/www1/artemis/metis/PostIntegrationTest.java
>          // posts in total
```suggestion
        // initialize test setup and get all existing posts (there are 4 posts with lecture context, 4 with exercise context, 1 plagiarism case and 3 with course-wide context -
        // initialized): 12 posts in total
```

2022-07-06 09:22 UTC, Strohgelaender commented on src/test/java/de/tum/in/www1/artemis/metis/PostIntegrationTest.java
> +        existingCoursePosts = existingPosts.stream().filter(post -> post.getPlagiarismCase() == null).collect(Collectors.toList());
Use .toList() here and below, see #5312
```suggestion
        existingCoursePosts = existingPosts.stream().filter(post -> post.getPlagiarismCase() == null).toList();
```

2022-07-06 14:25 UTC, ole-ve requested changes
Reviewed the content and left two inline comments.

2022-07-06 14:25 UTC, ole-ve commented on src/test/java/de/tum/in/www1/artemis/metis/PostIntegrationTest.java
> +    public void testGetPostsForCourse_WithPlagiarismCaseIdRequestParam_asStudent_Forbidden() throws Exception {
Should be forbidden because the notification is not related to `student2`, right?

2022-07-06 14:45 UTC, canberkanar commented on src/test/java/de/tum/in/www1/artemis/metis/PostIntegrationTest.java
>          // posts in total
Thanks!

2022-07-06 15:49 UTC, ole-ve approved these changes
Test code looks good now 👍

2022-07-08 10:42 UTC, Strohgelaender approved these changes
code looks good

2022-07-08 10:53 UTC, manuelmanso approved these changes
Re-approved!

2022-07-08 13:46 UTC, ole-ve approved these changes
Re-approve

2022-07-08 16:36 UTC, merged