`Development:` Add bamboo build agent container to atlassian compose file
ls1intum/Artemis pull request #5332
Opened 2022-07-05 14:36 UTC by TheZoker

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

There is a new bamboo build agent docker image available, that is build from this file:
https://github.com/ls1intum/Artemis-Local-Setup-Docker/blob/main/bamboo-build-agent/Dockerfile

This will replace the custom bamboo build for C and swift in the future. 
The PR adds the needed parts to the `atlassian.yml` docker compose file, so the build agent service is created a long site the bamboo server.

### Description

Adds the custom bamboo build image compose definition to the `atlassian.yml` file.

### Steps for Testing
1. Use the docker compose file to run the atlassian services. 
2. Go to this path, to approve the build agent `/admin/agent/configureAgents!doDefault.action` under `Remote agents` and then `Agent authorisation`
3. Approve the request
4. Wait some minutes until the build agent has finished its setup
5. Look for this line under the build agents executables (it should be automatically be detected):
![image](https://user-images.githubusercontent.com/1368405/177352640-331f2be5-70cb-4035-9b81-8d8c9deabf03.png)
6. Now bamboo can use this agent to run docker tasks (like build, publish images etc.)

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

2022-08-24 09:04 UTC, Mtze commented
Please change the merge destination to the deployment develop branch. Other than that - it is looking good to me

2022-08-25 11:14 UTC, TheZoker commented
@Mtze Done!

2022-09-01 11:10 UTC, Mtze approved these changes

2022-09-01 19:00 UTC, krusche requested changes
Should we not use 8.2.5 now?

2022-09-01 19:00 UTC, krusche commented on src/main/docker/atlassian.yml
> +        image: ghcr.io/ls1intum/artemis-bamboo-build-agent:8.1.3
8.2.5?

2022-09-02 11:50 UTC, Mtze commented on src/main/docker/atlassian.yml
> +        image: ghcr.io/ls1intum/artemis-bamboo-build-agent:8.1.3
you're right!

2022-09-02 11:51 UTC, Mtze requested changes

2022-09-02 11:51 UTC, Mtze commented on src/main/docker/atlassian.yml
> +        image: ghcr.io/ls1intum/artemis-bamboo-build-agent:8.1.3
```suggestion
        image: ghcr.io/ls1intum/artemis-bamboo-build-agent:8.2.5
```

2022-09-20 13:34 UTC, dangcosta approved these changes
Considering that the change of version requested by Stephan was done, the rest looks good to me

2022-10-20 12:05 UTC, closed without merging