`Development:` Add sphinx gradle plugin
ls1intum/Artemis pull request #5334
Opened 2022-07-05 21:42 UTC by manuelmanso

### Checklist
#### General
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

Adds a sphinx plugin for gradle that generates the docs without having to install/run anything (python/pip) locally. Simply run `./gradlew site` to generate the docs locally.

### Description
Adds the plugin to build.gradle, points to the source directory (/docs) and adds a comment on how to run it.

####  Review
- [ ] Review 1
- [ ] Review 2

2022-07-06 06:13 UTC, Strohgelaender approved these changes
Tested locally, works.

2022-07-06 06:13 UTC, Strohgelaender commented on build.gradle
> +// 11) Generate docs:                               ./gradlew site
```suggestion
// 12) Generate docs:                               ./gradlew site
```

2022-07-06 13:54 UTC, Marvin-Vitcu submitted a review, later dismissed
tested locally, worked as intended

2022-07-08 10:08 UTC, Strohgelaender approved these changes

2022-07-09 09:29 UTC, dfuchss commented
I have to ask, because I'm not sure: How stable/mature is the Plugin? It hasn't been updated for a while and afaik some new major release of sphinx has been released some weeks ago.

2022-07-09 10:17 UTC, Hialus requested changes
> I have to ask, because I'm not sure: How stable/mature is the Plugin? It hasn't been updated for a while and afaik some new major release of sphinx has been released some weeks ago.

Thats a good remark. I just took a deeper look into it:
- Artemis currently uses Sphinx 4.2.0 (we might want to look into updating this)
- The newest Sphinx version is 5.0.2
- The sphinx-binary project (which is the basis for this plugin) is in version 0.8.2 (released 11.02.2021) and uses Sphinx version 3.4.3!

So even now the plugin is on an outdated major version of Sphinx. If we update to Sphinx 5 in the future the plugin would be 2 major versions behind. Considering that there has not been an update to the plugin in over a year for Sphinx 4/5, it is safe to say that the plugin has been abandoned before it even reached version 1.0.0.

My conclusion is therefore that this PR should not get merged.

2022-07-10 09:45 UTC, manuelmanso commented
Thanks for the input and research, I'll close it, indeed there's not much point if it's supporting only outdated version  👍

2022-07-10 09:45 UTC, closed without merging