`General`: Add Documentation for Learning Analytics
ls1intum/Artemis pull request #5364
Opened 2022-07-11 13:13 UTC by maximiliansoelch

### Checklist
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

Documentation about Artemis' learning analytics features are missing.

### Description

Add documentation about all available learning analytics for students and instructors.

### Steps for Testing

1. Look at the new documentation about learning analytics: link

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2

2022-07-12 11:53 UTC, ge65cer approved these changes
Sounds good to me. 🙂

2022-07-12 12:03 UTC, MetinLamby submitted a review, later dismissed
really nice documentation! Concise and clear!

2022-07-12 13:00 UTC, jschmautzer reviewed
Regarding the "Exercise Statistics" Section: Maybe add a little description how someone can get to this exercise statistics overview.

The rest looks understandable :)

2022-07-12 13:00 UTC, jschmautzer commented on docs/user/learning-analytics.rst
> +Students can compare their scores to the best, overall score as well as the average score for each individual exercise with the help of a line chart.
```suggestion
Students can compare their scores to the best overall score as well as the average score for each individual exercise with the help of a line chart.
```

2022-07-12 15:19 UTC, bassner requested changes

2022-07-12 15:19 UTC, bassner commented on README.md
> +15. **[Learning analytics]((https://docs.artemis.ase.in.tum.de/user/learning-analytics/))**: Artemis integrated different statistics for students to compare themselves to the course average. It allow
Why the doubled brackets? :)
```suggestion
15. **[Learning analytics](https://docs.artemis.ase.in.tum.de/user/learning-analytics/)**: Artemis integrated different statistics for students to compare themselves to the course average. It allows instructors to evaluate the average student performance based on exercises and learning goals.
```

2022-07-12 15:28 UTC, Marvin-Vitcu approved these changes
Tested on TS1. The link is there and works as intended.

2022-07-12 20:04 UTC, bassner submitted a review, later dismissed

2022-07-12 21:41 UTC, Mikael31 submitted a review, later dismissed
Good documentation and understandable for everyone

2022-07-13 12:42 UTC, jschmautzer submitted a review, later dismissed
documentation looks godd :)

2022-07-13 15:03 UTC, luisa-we approved these changes
Good documentation!
Tested on TS1, the link is present and works.

2022-07-13 15:05 UTC, sleiss approved these changes
Documentation looks good :+1:

2022-07-14 20:36 UTC, krusche requested changes
Good starting point, could you mention the learning goal statistics for students as well?

2022-07-15 13:25 UTC, babyygemperor approved these changes
Good documentation. Looks good 👍🏼

2022-07-18 13:57 UTC, luisa-we approved these changes
Documentation looks good to me!

2022-07-18 16:16 UTC, rhubinger approved these changes
Read through it, looks good!

2022-07-18 17:56 UTC, bassner approved these changes
LGTM!

2022-07-18 19:25 UTC, ge65cer approved these changes
Re-approve

2022-07-19 08:20 UTC, Mikael31 approved these changes
reviewed. looks good

2022-07-19 19:00 UTC, merged