`Development`: Add documentation article for open-source
ls1intum/Artemis pull request #5372
Opened 2022-07-12 12:56 UTC by Mtze

### Checklist
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

Documentation for open-source aspects of artemis are currently missing.
See [the confluence page](https://confluence.ase.in.tum.de/display/ArTEMiS/Feature+documentation).

### Steps for Testing

- Proof read the [new pages](https://artemis-platform--5372.org.readthedocs.build/en/5372/dev/open-source/)
- Deploy the PR to a test server and check that the new link is present on the About Us page

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2

2022-07-12 14:38 UTC, TheZoker approved these changes
LGTM 👍

2022-07-12 15:00 UTC, bassner commented
@Marvin-Vitcu That's because it links to this PR which isn't deployed to the production docs site yet, so it can't work and is fine

2022-07-12 15:02 UTC, bassner requested changes

2022-07-12 15:02 UTC, bassner commented on src/main/webapp/app/core/about-us/about-us.component.ts
> +        ['openSource', { openSourceUrl: 'https://docs.artemis.ase.in.tum.de/dev/open-source.html' }],
Same as above?
```suggestion
        ['openSource', { openSourceUrl: 'https://docs.artemis.ase.in.tum.de/dev/open-source/' }],
```

2022-07-12 15:24 UTC, Marvin-Vitcu submitted a review, later dismissed

2022-07-12 16:09 UTC, Mtze commented
@bassner thanks for the suggestion!

2022-07-12 16:29 UTC, b-fein commented on docs/dev/open-source.rst
> +With Artemis, we embrace all of the aspects:
```suggestion
With Artemis, we embrace all of those aspects:
```
Nipick: I think either ‘all the’ or ‘all of those’ sounds slightly better.

2022-07-12 16:29 UTC, b-fein commented on docs/dev/open-source.rst
> +* The foundation of learning and teaching is **sharing** knowledge. Artemis is used to conduct courses at universities and, at the same time, used as a education research platform.
```suggestion
* The foundation of learning and teaching is **sharing** knowledge. Artemis is used to conduct courses at universities and, at the same time, used as an education research platform.
```

2022-07-12 16:31 UTC, Mtze commented
Thanks @b-fein :)

2022-07-12 19:27 UTC, b-fein approved these changes

2022-07-12 20:01 UTC, bassner approved these changes

2022-07-13 10:16 UTC, SimonPaul02 approved these changes
Code looks good to me, tested on TS1, link works! (But it is not yet available)
![image](https://user-images.githubusercontent.com/68793520/178710521-4d33b323-2fe2-4fa2-837a-b57d9899af37.png)

2022-07-13 10:17 UTC, yuling-sun approved these changes
Tested on TS1. Link works as described.

2022-07-13 10:21 UTC, jbllhff approved these changes
Tested on ts2, looks good!

2022-07-13 15:00 UTC, sleiss approved these changes

2022-07-13 15:25 UTC, luisa-we approved these changes
Tested on TS1, the link works.
Documentation also looks good :)

2022-07-14 07:25 UTC, Mtze commented
Thanks everyone :)

2022-07-14 20:27 UTC, krusche approved these changes
Sounds great 👍

2022-07-14 20:28 UTC, merged