Modeling exercises: Add the possibility for instructors to drop an assessment instruction to Add new Feedback directly
ls1intum/Artemis pull request #5389
Opened 2022-07-14 11:10 UTC by Olha-D

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [ ] I implemented the changes with a good performance and prevented too many database calls.
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [ ] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context
Solves the Issue #5252 

### Description

I have added the possibility to drop an assessment instruction on the button Add new Feedback. On this event a function is called, that automatically creates a new feedback and adds the information of the dropped instruction to it.  
### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Modelling exercise with Assessment instructions 
- 1 submitted solution of the modelling exercise

1. Log in to Artemis
2. Navigate to Course Management
3. Find the course with the modelling exercise and click on the Submissions button near the modelling exercise. 
4. Click Open Assessment to the right from one of the submissions.
5. Now you should be able to drag one of the Assessment instructions to the Add new Feedback button and drop it there. Then a new Feedback should appear in the list of Feedbacks with the information from the Assessment instruction. 

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

![Feature](https://user-images.githubusercontent.com/69432438/178969625-bc2de413-d578-4390-9a1c-d2ca8485489c.gif)

2022-07-14 13:38 UTC, Strohgelaender commented
Could you also allow drag and drop for the whole section below that where all the feedback elements are listed? I think dragging something on a button is not quite obvious.

2022-07-14 15:50 UTC, ge65cer commented
I agree with Dominik, we should keep the features consistent across all applicable exercise types.

2022-07-19 16:39 UTC, Strohgelaender commented on src/main/webapp/app/exercises/shared/unreferenced-feedback/unreferenced-feedback.component.ts
> +    constructor(public structuredGradingCriterionService: StructuredGradingCriterionService) {}
```suggestion
    constructor(private structuredGradingCriterionService: StructuredGradingCriterionService) {}
```

2022-07-19 16:39 UTC, Strohgelaender commented on src/main/webapp/app/exercises/shared/unreferenced-feedback/unreferenced-feedback.component.ts
> +        if (newFeedback !== undefined) {
```suggestion
        if (newFeedback) {
```

2022-07-21 12:36 UTC, dfuchss approved these changes
Tested in Testing Session. Works as expected.

2022-07-21 12:38 UTC, Dominik-Weinzierl submitted a review, later dismissed
Looks good to me :+1:

2022-07-21 12:41 UTC, sleiss approved these changes
Tested in the testing session.

2022-07-21 12:42 UTC, dfuchss approved these changes
Re-Approve

2022-07-21 22:01 UTC, nairaarnez approved these changes
Tested in ts1, it works as described!

2022-07-22 06:01 UTC, ge65cer requested changes
See my comments below.

2022-07-22 08:07 UTC, jschmautzer submitted a review, later dismissed
tested on ts1, worked as described

2022-07-22 12:39 UTC, babyygemperor approved these changes
Tested on ts1, works as described

2022-07-24 11:34 UTC, nairaarnez submitted a review, later dismissed
Tested in TS1

2022-07-25 11:27 UTC, jschmautzer submitted a review, later dismissed
re-approve, tested on ts2

2022-07-26 09:03 UTC, ge65cer submitted a review, later dismissed
Approve code.

2022-07-26 15:11 UTC, Strohgelaender commented on src/main/webapp/i18n/de/fileUploadAssessment.json
> +            "assessInstructionWithDropOption": "Bitte klicke auf \"Neues Feedback hinzufügen\" oder ziehen Sie eine Bewertungsanweisung und legen Sie sie hier ab.",
```suggestion
            "assessInstructionWithDropOption": "Bitte klicke auf \"Neues Feedback hinzufügen\" oder ziehe eine Bewertungsanweisung und lege sie hier ab.",
```

2022-07-29 10:31 UTC, JohannesStoehr approved these changes
Code and screencast look good

2022-07-31 10:12 UTC, nairaarnez approved these changes
Re-tested in ts1. Re-approved

2022-07-31 14:22 UTC, jschmautzer approved these changes
re-approve, tested on ts1

2022-08-03 09:54 UTC, MetinLamby approved these changes
tested on ts1, works as shown in the video

2022-08-03 12:24 UTC, luisa-we approved these changes
Tested on TS1, works as expected!

2022-08-11 05:33 UTC, merged