`Development`: Update file upload exercise documentation
ls1intum/Artemis pull request #5428
Opened 2022-07-18 23:16 UTC by julian-christl

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [ ] I implemented the changes with a good performance and prevented too many database calls.
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [ ] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

2022-07-19 11:29 UTC, babyygemperor requested changes
Although I do realise that most of my requested changes are not from this PR, but it would be great if we could cover them in this PR.

2022-07-19 11:29 UTC, babyygemperor commented on docs/user/exercises/file-upload.rst
>  - When the exercise is released the students can upload the requested file.
is released, the students can (missing comma)

2022-07-19 11:29 UTC, babyygemperor commented on docs/user/exercises/file-upload.rst
>  - When the due date is over you can assess the submissions. From the assessment dashboard go to exercise assessment dashboard of the file upload exercise.
assessment dashboard, go to exercise (missing comma)

2022-07-19 11:29 UTC, babyygemperor commented on docs/user/exercises/file-upload.rst
>  - There you can assess the submitted student submissions, by first downloading the file, and then creating feedback with points.
Perhaps "adding feedback with points"?

2022-07-19 11:29 UTC, babyygemperor commented on docs/user/exercises/file-upload.rst
>  - Open |course-management|
Missing full stop at the end

2022-07-19 11:29 UTC, babyygemperor commented on docs/user/exercises/file-upload.rst
>  - Navigate into **Exercises** of your preferred course
Missing full stop at the end

2022-07-19 11:29 UTC, babyygemperor commented on docs/user/exercises/file-upload.rst
>  - Click on **Create new file upload exercise**
Missing full stop at the end

2022-07-19 11:29 UTC, babyygemperor commented on docs/user/exercises/file-upload.rst
>  - Fill out all mandatory values and click on |save|
Missing full stop at the end

2022-07-19 12:02 UTC, jschmautzer reviewed
only some small things :) 
Rest looks good.

2022-07-19 12:02 UTC, jschmautzer commented on docs/user/exercises/file-upload.rst
>  - When the due date is over you can assess the submissions. From the assessment dashboard go to exercise assessment dashboard of the file upload exercise.
```suggestion
- When the due date is over, you can assess the submissions. From the assessment dashboard go to the exercise assessment dashboard of the file upload exercise.
```

2022-07-19 18:57 UTC, nadinesamyy reviewed
Maybe in the sentence "Fill out all mandatory values and click on", the word "values" could be replaced by "fields", other than that it looks good

2022-07-19 20:27 UTC, jbllhff reviewed
Looks good after taking the previously mentioned comments into account.

2022-07-20 07:53 UTC, joaquinmurcia requested changes

2022-07-20 13:33 UTC, MetinLamby approved these changes
looks very good!

2022-07-20 20:56 UTC, alaraozdenler reviewed
Just one minor reformulation suggestion

2022-07-20 20:56 UTC, alaraozdenler commented on docs/user/exercises/file-upload.rst
>  - After a file was uploaded it can then be downloaded again with the link below.
After a file "is" uploaded", it can be" downloaded again with the link below.

2022-07-21 19:53 UTC, manuelmanso approved these changes
LGTM, just a small correction along with what others have already suggested

2022-07-21 19:53 UTC, manuelmanso commented on docs/user/exercises/file-upload.rst
> +2. Submission of a student
```suggestion
2. Submission by a student
```
Small correction

2022-07-21 22:34 UTC, nairaarnez approved these changes
Other than that it looks good!

2022-07-21 22:34 UTC, nairaarnez commented on docs/user/exercises/file-upload.rst
>  - You can get an overview of the exercise by clicking on the title.
I would change this to: instructors and tutors can get an

2022-07-27 17:20 UTC, SimonPaul02 approved these changes
I agree with the suggestions from other reviewers. The rest looks good to me

2022-07-27 17:20 UTC, yuling-sun approved these changes
Looks good for me. I didn't find any additional mistakes aside from those already mentioned.

2022-08-01 15:42 UTC, nairaarnez approved these changes
Approved after feedback was incorporated!

2022-08-02 06:52 UTC, jschmautzer approved these changes
re-approve (looks good to me)

2022-08-02 11:04 UTC, alaraozdenler approved these changes
Documentation looks good now!

2022-08-02 12:30 UTC, merged