`Development:` Added documentation about markdown support
ls1intum/Artemis pull request #5435
Opened 2022-07-19 22:38 UTC by stefanwaldhauser

### Checklist
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

Documentation about Artemis' markdown support is missing.

### Description

Add documentation about markdown support.

### Steps for Testing

1. Look at the new documentation about markdown support: 

### Review Progress

#### Code Review
- [] Review 1
- [] Review 2

2022-07-20 18:39 UTC, jschmautzer reviewed
Looks good to me :) 
Only some small issues to be consistent in the documentation with the capitalization.

2022-07-20 18:39 UTC, jschmautzer commented on docs/user/markdown-support.rst
> +Artemis extends the basic `Markdown <https://daringfireball.net/projects/markdown/>`__ syntax to support Artemis-specific features. This Artemis flavored Markdown is used to format text content acros
```suggestion
Artemis extends the basic `Markdown <https://daringfireball.net/projects/markdown/>`__ syntax to support Artemis-specific features. This Artemis flavored Markdown is used to format text content across the platform using an integrated Markdown editor.
```

2022-07-20 18:39 UTC, jschmautzer commented on docs/user/markdown-support.rst
> +The integrated markdown editor uses `Showdown <https://github.com/showdownjs/showdown>`__. A quick description of the supported syntax can be found `here <https://github.com/showdownjs/showdown/wiki/
```suggestion
The integrated Markdown editor uses `Showdown <https://github.com/showdownjs/showdown>`__. A quick description of the supported syntax can be found `here <https://github.com/showdownjs/showdown/wiki/Showdown's-Markdown-syntax>`__. 
```

2022-07-20 18:39 UTC, jschmautzer commented on docs/user/markdown-support.rst
> +The markdown editor contains a formatting toolbar at the top, allowing users to format text without learning Markdown syntax.
```suggestion
The Markdown editor contains a formatting toolbar at the top, allowing users to format text without learning Markdown syntax. 
```

2022-07-20 19:05 UTC, Hialus requested changes
As an MVP this is looking good already. I left some comments for improvements that I might appreciate in this PR or a future PR. Feel free to incorporate them however you want. 
And one more general feedback:
You currently link to 4 different sites explaining Markdown (Markdown, Showdown, Showdown Katex, and Showdown Highlight). It might be beneficial to add a full documentation of the supported Markdown in the future, so the user doesn't have to click through the docs of the libraries. I've seen websites do this quite often, and I personally appreciate it (example [GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)), as I then only have a single reference to consult if I need something specific.

2022-07-20 20:23 UTC, babyygemperor submitted a review, later dismissed
Looks good to me (other than the things already pointed)
No grammatical errors were found (apart from the capitalisation issue already mentioned)

2022-07-20 21:13 UTC, Marvin-Vitcu approved these changes
Documentation LGTM.

Tested on TS1. Link is there.

2022-07-21 19:50 UTC, manuelmanso submitted a review, later dismissed
Good starting point. @Hialus already left some good suggestions for what could be extended.

2022-07-21 22:26 UTC, nairaarnez submitted a review, later dismissed
The documentation looks good, it is easy to follow and understandable!

2022-07-24 08:57 UTC, MetinLamby submitted a review, later dismissed
nice documentation. Understandable and concise!

2022-07-25 07:58 UTC, jbllhff approved these changes
Tested on ts2, looks good!

2022-07-27 14:02 UTC, luisa-we approved these changes
Documentation looks good!
Also tested on TS1, link is there.

2022-08-01 09:20 UTC, krusche approved these changes
Good enough for a first documentation. As discussed, we should extend it in a follow-up

2022-08-01 09:28 UTC, merged