Remove existing participations when exam is regenerated.
ls1intum/Artemis pull request #5451
Opened 2022-07-21 10:22 UTC by sleiss

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [ ] I implemented the changes with a good performance and prevented too many database calls.
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [ ] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

2022-07-23 12:55 UTC, jbllhff submitted a review, later dismissed
tested on ts2, looks good!

2022-07-23 14:30 UTC, xlieA approved these changes
Tested on ts1. Everything works as described. Repeated steps 6-8 multiple times, the number of participants was always equal to the number of registered students.

2022-07-23 15:35 UTC, bassner requested changes
See #4826 for context :D

2022-07-23 15:35 UTC, bassner commented on src/test/java/de/tum/in/www1/artemis/ExamIntegrationTest.java
> +        assertThat(studentParticipations).hasSize(0);
```suggestion
        assertThat(studentParticipations).isEmpty();
```

2022-07-23 15:35 UTC, bassner commented on src/test/java/de/tum/in/www1/artemis/ExamIntegrationTest.java
> +        assertThat(studentParticipations).hasSize(0);
```suggestion
        assertThat(studentParticipations).isEmpty();
```

2022-07-23 16:58 UTC, sleiss commented
> See #4826 for context :D

@bassner Thanks, I fixed it :D

2022-07-23 17:50 UTC, sleiss commented
@jbllhff @xlieA Thanks for your reviews! As I adopted the code suggestions for the test case, your review was automatically removed.
Maybe you can just re-approve it since there was no additional change to the code, only tests.

2022-07-23 20:41 UTC, bassner submitted a review, later dismissed
Code LGTM now 👍

2022-07-24 08:35 UTC, krusche requested changes
I think there are two issues with the current implementation:
1. When regenerating the student exams, we do not really want to reset the exam, so I think it's dangerous to invoke this method, even if it now would make sense, it can change in the future. However the audit log does not really make sense
2. There is an issue in the current resetExam functionality which we should fix. Exercises in exams should not have release dates, due dates, etc. However resetting a quiz exercise in QuizExerciseService:407 sets a new release date in the future which might be ok for course quizzes, but not for exam quizzes.

I suggest:
1) we refactor the code to make the code more independent (issue 1)
2) Artemis only invokes reset in QuizExerciseService when it is a course exercise in ExerciseDeletionService:216 (as far as I can tell, the code in QuizExerciseService:407 is irrelevant for exams, reset is also not offered on exam exercises so far)

2022-07-24 08:51 UTC, krusche commented
I addressed issue 2 in #5466

2022-07-28 13:21 UTC, bassner submitted a review, later dismissed
Tested during the testing session - the participation counts were always correct after each regeneration.
Code LGTM 👍

2022-07-28 13:22 UTC, maximiliansoelch approved these changes
Tested during testing session, works as described.
Code LGTM 👍

2022-07-28 13:23 UTC, Dominik-Weinzierl approved these changes
Tested during the testing session - works good

2022-07-28 21:02 UTC, nairaarnez approved these changes
Tested in TS1, worked as described!

2022-07-29 06:52 UTC, krusche commented on src/main/java/de/tum/in/www1/artemis/web/rest/ExamResource.java
> +        // Reset existing student exams & participations
```suggestion
        // Reset existing student exams & participations in case they already exist
```

2022-07-29 10:01 UTC, krusche approved these changes

2022-07-29 10:02 UTC, merged