`Exam mode`: Fix navbar exam detection and hide breadcrumbs appropriately
ls1intum/Artemis pull request #5465
Opened 2022-07-23 19:27 UTC by bassner

### Checklist
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

The navbar should hide a few elements (notifications, breadcrumbs ..) when an exam is running. However, at the moment there are a few problems with the related implementation:
- The template calls a method to check if the exam is active at multiple locations. This is a bad practice as the function is called over and over again to check for different results, causing continuous load
- The breadcrumbs only check if an exam is running when they are generated; however, this is not sufficient as the state of the exam can change over time, and without an navigation event, the breadcrumbs are not regenerated

### Description

- Reimplemented the check for an exam active to only populate a component field that can be consumed by the template that is updated by timeouts
- Hide the entire breadcrumb row if an exam is active instead of checking this while generating them

### Steps for Testing

Prerequisites:
- 1 Course with an upcoming Exam
- 1 Student registered for the exam, with a generated student exam so they can participate

1. Open the exam page as student before it starts. Notification icon and breadcrumbs should be visible.
2. Enter your name and click start. The countdown for the exam should appear as normal.
3. As soon as the countdown for the start of the exam runs out, you should be forwarded to the exercise overview. At the same time, breadcrumbs and the notification icon in the navbar etc should disappear.
4. Let the time of the exam run out. As soon as the time is up, you should be forwareded to the "hand in" page and the breadcrumbs and notification icon should reappear.

See the video below for how it could look like.

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| navbar.component.ts | 82% | 92% |

### Screenshots

https://user-images.githubusercontent.com/23171488/180620028-1afd96a1-ce72-4d7b-b634-34fa554923c0.mov

2022-07-24 10:20 UTC, nairaarnez submitted a review, later dismissed
Tested in TS1, submitting and letting the submission run out. Notification icon and breadcrumbs work as described

2022-07-24 17:11 UTC, xlieA submitted a review, later dismissed
Tested on ts1. Everything works as described.

2022-07-25 07:52 UTC, jbllhff submitted a review, later dismissed
Tested on ts2, works fine!

2022-07-25 08:41 UTC, JohannesStoehr requested changes
Code looks good, but you have to fix the style issues

2022-07-25 08:41 UTC, JohannesStoehr commented on src/test/javascript/spec/component/admin/system-notification-management/system-notification-detail.component.spec.ts
> +        router.setUrl('');
There's a style issue in this file

2022-07-25 08:41 UTC, JohannesStoehr commented on src/test/javascript/spec/component/admin/system-notification-management/system-notification-management.component.spec.ts
> +        router.setUrl('');
Same as above

2022-07-25 08:41 UTC, JohannesStoehr commented on src/test/javascript/spec/service/navigation-util.service.spec.ts
> +    router.setUrl('a');
Style issues in the imports

2022-07-25 09:36 UTC, babyygemperor submitted a review, later dismissed
Tested on ts1, works as described

2022-07-25 09:40 UTC, max-bergmann submitted a review, later dismissed
Tested on TS3. Works as expected

2022-07-25 11:36 UTC, bassner commented on src/test/javascript/spec/component/admin/system-notification-management/system-notification-detail.component.spec.ts
> +        router.setUrl('');
See fdd1ac6 :)

2022-07-25 11:36 UTC, bassner commented on src/test/javascript/spec/component/admin/system-notification-management/system-notification-management.component.spec.ts
> +        router.setUrl('');
See fdd1ac6 :)

2022-07-25 11:36 UTC, bassner commented on src/test/javascript/spec/service/navigation-util.service.spec.ts
> +    router.setUrl('a');
See fdd1ac6 :)

2022-07-25 11:37 UTC, bassner commented
Only changed imports in test files, so previous manual tests are still valid - I'd appreciate re-approvals, though :)

2022-07-25 17:23 UTC, pantageepapa approved these changes
Tested on ts2, and works as described :)

2022-07-26 14:11 UTC, JohannesStoehr approved these changes
Thanks for fixing the issues.
Code looks good

2022-07-26 19:42 UTC, merged