`General`: Add assessment documentation
ls1intum/Artemis pull request #5483
Opened 2022-07-26 23:07 UTC by Hialus

### Checklist
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

2022-07-27 07:02 UTC, jschmautzer approved these changes
looks good and descriptive :)

2022-07-27 09:20 UTC, luisa-we approved these changes
Good documentation, very detailed!

2022-07-27 09:50 UTC, MetinLamby submitted a review, later dismissed
nicely written!

2022-07-27 09:52 UTC, Marvin-Vitcu commented on docs/user/exercises/assessment.rst
> +- **Semi-Automatic:** Artemis automatically grades students' submissions, but the tutors manually grade all submissions afterward.
Be consistent with the previous definitions:

```suggestion
- **Semi-Automatic:** Artemis automatically grades the submissions of students, but the tutors manually grade all submissions afterward.
```

2022-07-27 09:53 UTC, Marvin-Vitcu reviewed
Tested on TS1. The link for Assessment on the "About" page is missing.

2022-07-27 10:00 UTC, Strohgelaender commented on docs/user/exercises/assessment.rst
> +Assessment dashboard
Also change the other headings.
```suggestion
Assessment Dashboard
```

2022-07-27 10:00 UTC, Strohgelaender commented on docs/user/exercises/assessment.rst
> +The assessment dashboard shows the assessment progress of each exercise by showing the state of the exercise, the total number of submissions, the number of submissions that have been assessed, and t
```suggestion
It shows the assessment progress of each exercise by showing the state of the exercise, the total number of submissions, the number of submissions that have been assessed, and the number of complaints and more feedback requests.
```

2022-07-27 10:00 UTC, Strohgelaender commented on docs/user/exercises/assessment.rst
> +A complaint leads to a reevaluation of the submission by another tutor. This tutor sees the existing submission and the complaint reason. The tutor can then either accept the complaint or reject it.
```suggestion
A complaint leads to a reevaluation of the submission by another tutor. This tutor sees the existing assessment and the complaint reason. The tutor can then either accept or reject the complaint.
```

2022-07-27 10:00 UTC, Strohgelaender commented on docs/user/exercises/assessment.rst
> +If the tutor rejects the complaint, they cannot do this.
```suggestion
Only if the tutor accepts the complaint, they can modify the assessment's score.
```

2022-07-27 11:55 UTC, Strohgelaender requested changes
Also add the link to the german translation.

2022-07-27 12:30 UTC, Strohgelaender commented on src/main/webapp/i18n/en/aboutUs.json
> +            "text": "<a href={{ assessmentUrl }}>Assessmen:t</a> Double-blind grading with structured criteria, integrated training, a leader board, ratings, and complaints improve consistency and fa
```suggestion
            "text": "<a href={{ assessmentUrl }}>Assessment:</a> Double-blind grading with structured criteria, integrated training, a leader board, ratings, and complaints improve consistency and fairness."
```

2022-07-27 12:31 UTC, Hialus commented on src/main/webapp/i18n/en/aboutUs.json
> +            "text": "<a href={{ assessmentUrl }}>Assessmen:t</a> Double-blind grading with structured criteria, integrated training, a leader board, ratings, and complaints improve consistency and fa
Whoops 😅

2022-07-27 12:39 UTC, Strohgelaender commented on docs/user/exercises/assessment.rst
> +Manual assessment
```suggestion
Manual Assessment
```

2022-07-27 12:39 UTC, Strohgelaender commented on docs/user/exercises/assessment.rst
> +Automatic assessment
```suggestion
Automatic Assessment
```

2022-07-27 12:39 UTC, Strohgelaender commented on docs/user/exercises/assessment.rst
> +- **Semi-Automatic:** Artemis automatically grades the submissions of students, but the tutors manually grade all submissions afterward.
Not sure about the exact formulation, but I think this sentence should be more clear. 
```suggestion
- **Semi-Automatic:** Artemis provides an automatic starting point for the tutors to manually improve the grading afterward.
```

2022-07-27 23:00 UTC, nairaarnez approved these changes
It looks good! I just have two small suggestions: I would enumerate 
"by showing: 
1. The state of the exercise
2. The total number of submissions
3. etc"
In the text and the screenshot 
![image](https://user-images.githubusercontent.com/104493356/181386686-e4fab837-3643-4322-860e-cca71341805b.png)

And I would add a screenshot of the view described here:
![image](https://user-images.githubusercontent.com/104493356/181386800-e0194bf1-9224-436b-bc3c-2e80ade9be9b.png)

Just suggestions, approved!

2022-07-28 08:14 UTC, alaraozdenler approved these changes
Documentation looks good, no errors found

2022-07-28 09:04 UTC, luisa-we approved these changes
Documentation still looks good!
Tested on TS1, link is there.

2022-07-29 14:30 UTC, manuelmanso approved these changes
Docs are clear and well organized!

2022-07-29 15:20 UTC, merged