`Exam Mode`: Display correct working time within the exam details and course exam details
ls1intum/Artemis pull request #5561
Opened 2022-08-04 09:17 UTC by mallgaier

### Checklist
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
In the `exam-detail` component, the working time was displayed in secounds, while the header claimed that the working time is in minutes

### Description
To display the working time, the `artemisDurationFromSecounds` Pipe is now used, which automatically converts the working time into the correct format.
Additionally, the `short` pipe is now used for the `course-exam-detail` component (the tiles representing the individual exam), as the short one doesn't display seconds. As the working time is based on minutes, the seconds do not need to be displayed to the student.

### Steps for Testing
Prerequisites:
- 1 Instructor
- 1 visible Real Exam
- 1 visible Test Exam

1. Log in to Artemis
2. Navigate to Course Administration -> Exam
3. For both exams, open the exam checklist (e.g. by clicking on the ID or Title) and navigate down to till the working time is displayed
4. Verify, that the working time is displayed correctly
5. Navigate to Course -> Exams
6. Verify, that the working time on the tiles is correctly displayed without secounds.

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots
Issue:
![image](https://user-images.githubusercontent.com/94070506/182809603-15a7cc3f-1b23-47e4-bcbb-0e20ed34b3f6.png)
Solved: 
![image](https://user-images.githubusercontent.com/94070506/182811196-3b0e7d92-9ea8-456e-ab8f-0bd44d229193.png)

exam detail without seconds:
![image](https://user-images.githubusercontent.com/94070506/182810481-43ab32b8-2ccc-49e0-a204-742bd05a2a29.png)

2022-08-04 11:22 UTC, Strohgelaender submitted a review, later dismissed
code

2022-08-04 11:29 UTC, bassner requested changes
See below

2022-08-04 11:29 UTC, bassner commented on src/main/webapp/app/exam/manage/exams/exam-detail.component.html
> +                <dt><span jhiTranslate="artemisApp.examManagement.workingTime">Working Time</span></dt>
You need to update the translation keys for both EN and DE as well to actually change this in the UI :)

2022-08-04 11:30 UTC, JohannesStoehr submitted a review, later dismissed
Code looks good. You could think about explicitly passing the parameter via { short: true } instead of just true to make the code a bit more understandable

2022-08-04 14:58 UTC, bassner approved these changes

2022-08-05 14:34 UTC, Dominik-Weinzierl approved these changes
Re-Approve :+1:

2022-08-05 14:39 UTC, cathrinrl approved these changes
Tested on TS1, changes looked good.

2022-08-05 15:03 UTC, merged