`Notifications`: Fix sending plagiarism emails
ls1intum/Artemis pull request #5565
Opened 2022-08-05 06:57 UTC by JohannesStoehr

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [ ] I implemented the changes with a good performance and prevented too many database calls.
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [ ] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

2022-08-07 14:14 UTC, yuling-sun submitted a review, later dismissed
Tested on TS1. Works as described.

2022-08-07 14:14 UTC, SimonPaul02 approved these changes
Tested on TS1, works as described

2022-08-09 11:53 UTC, akesfeden commented
I don't know much about the email related parts of the project, are emails always in English? I couldn't see German translations for the strings in [messages.properties](https://github.com/ls1intum/Artemis/pull/5565/files#diff-e9d91b0ce71b56fa7bbe03d9addcd6434088a3a1ee27d0b8feda0de045282101) or [PlagiarismVerdict.java](https://github.com/ls1intum/Artemis/pull/5565/files#diff-50506eccb73cd0e4ce09c568303b6f2877e4c206adcee8c227eb7c9f19364cd7) that's why I asked.

2022-08-10 07:47 UTC, JohannesStoehr commented
> I don't know much about the email related parts of the project, are emails always in English? I couldn't see German translations for the strings in [messages.properties](https://github.com/ls1intum/Artemis/pull/5565/files#diff-e9d91b0ce71b56fa7bbe03d9addcd6434088a3a1ee27d0b8feda0de045282101) or [PlagiarismVerdict.java](https://github.com/ls1intum/Artemis/pull/5565/files#diff-50506eccb73cd0e4ce09c568303b6f2877e4c206adcee8c227eb7c9f19364cd7) that's why I asked.

You're right I missed that. Now the student can also receive their plagiarism case in German

2022-08-10 12:57 UTC, luisa-we submitted a review, later dismissed
Tested on TS1, works as expected.

2022-08-10 13:17 UTC, Mikael31 submitted a review, later dismissed
Tested on ts1. everything worked as expected

2022-08-15 14:16 UTC, Santia-go submitted a review, later dismissed
Tested on TS1 
Working as expected. The email is received immediately and it is possible to access to the case through the "Open in Artemis" button. 
<img width="848" alt="Screenshot 2022-08-15 at 16 14 46" src="https://user-images.githubusercontent.com/88991954/184652422-f6b2d151-258a-48f8-971d-d404dd8409a7.png">

2022-08-17 10:12 UTC, ge65cer requested changes
Tested on TS1, e-mails are sent for both the notification and the verdict. 👍  I have the following feedback:
* Render the Markdown in the notification body correctly
* Include the verdict information (percentage of point deduction or actual warning message) in the email
* Some small text suggestions

2022-08-17 10:12 UTC, ge65cer commented on src/main/resources/i18n/messages.properties
> +email.notification.title.post.plagiarismVerdict=New plagiarism verdict in exercise {0}
```suggestion
email.notification.title.post.plagiarismVerdict=Verdict reached in plagiarism case for exercise {0}
```

2022-08-17 10:12 UTC, ge65cer commented on src/main/resources/i18n/messages_de.properties
> +email.notification.title.post.plagiarismVerdict=Neue Entscheidung zu dem Plagiat in Aufgabe {0}
```suggestion
email.notification.title.post.plagiarismVerdict=Entscheidung zum Plagiatsfall in der Aufgabe {0} gefallen
```

2022-08-17 10:12 UTC, ge65cer commented on src/main/resources/i18n/messages_en.properties
> +email.notification.title.post.plagiarismVerdict=New plagiarism verdict in exercise {0}
As above

2022-08-17 10:20 UTC, JohannesStoehr commented
> Render the Markdown in the notification body correctly

I'll cover this in a follow up, where I refactor the emails. Otherwise we have to render the markdown in multiple places

> Include the verdict information (percentage of point deduction or actual warning message) in the email

The email is mostly a notification that there is a verdict. But we could make the email more informative in the future

2022-08-17 10:21 UTC, ge65cer submitted a review, later dismissed
@JohannesStoehr In that case, I can approve this PR.

2022-08-23 10:42 UTC, julian-christl submitted a review, later dismissed
The code changes look reasonable and consistent.

2022-08-23 14:59 UTC, ge65cer approved these changes
Re-approve

2022-08-25 11:07 UTC, jpbernius requested changes

2022-08-25 11:07 UTC, jpbernius commented on src/main/resources/i18n/messages_en.properties
> +email.notification.aux.plagiarismVerdict.warning=Due to the plagiarism attempt, you are warned. Any further plagiarism will lead to severe consequences!
Translation is inconsistent with German message:
> Weitere Plagiate können schwere Folgen haben!

vs
> Any further plagiarism will lead to severe consequences!

2022-08-31 22:41 UTC, julian-christl approved these changes
Reapprove code

2022-09-01 06:14 UTC, ge65cer approved these changes

2022-09-01 06:31 UTC, jpbernius approved these changes

2022-09-01 06:32 UTC, merged