`Bugfix`: Several Bugs in Connection with Example Submissions
ls1intum/Artemis pull request #5619
Opened 2022-08-22 08:26 UTC by stefanwaldhauser

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [ ] I implemented the changes with a good performance and prevented too many database calls.
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [ ] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

2022-08-25 12:01 UTC, ge65cer requested changes
When assessing an example submission, a request is sent to the server (`https://artemis-test1.artemis.in.tum.de/api/analytics/text-assessment/events`) that returns with an HTTP error status code of 400 (Bad Request).

<img width="800" alt="Screenshot 2022-08-25 at 13 57 56" src="https://user-images.githubusercontent.com/102237363/186658285-bdcf7e90-209c-4134-867d-8035892ca16a.png">

2022-08-25 12:02 UTC, canberkanar submitted a review, later dismissed
Tested on TS1 with text and modeling exercises. All feedback and links to grading instructions within feedback are preserved correctly. Nice fix 👍🏻

2022-08-25 14:48 UTC, akesfeden submitted a review, later dismissed
Tested on TS1 during testing session. Text and modeling exercises are successfully saved as example submissions with grading criteria preserved. Warning prompt when user clicks on "edit submission" works as expected. We noticed an issue about analytics events which will be handled in either this or a follow-up PR so I am approving now.

2022-08-25 16:28 UTC, manuelmanso approved these changes
Tested in TS1 as part of the testing session and works as expected, code also looks good.

2022-08-27 11:41 UTC, stefanwaldhauser commented
> When assessing an example submission, a request is sent to the server (`https://artemis-test1.artemis.in.tum.de/api/analytics/text-assessment/events`) that returns with an HTTP error status code of 400 (Bad Request).
> 
> <img alt="Screenshot 2022-08-25 at 13 57 56" width="800" src="https://user-images.githubusercontent.com/102237363/186658285-bdcf7e90-209c-4134-867d-8035892ca16a.png">

Good catch! I fixed this in 586187bff04d9d4a068984a96c207eb3ee33a680

2022-08-27 12:21 UTC, akesfeden approved these changes
Re-tested in TS1 to confirm analytics events are not sent anymore, looks good. Added a minor code change suggestion.

2022-08-27 12:21 UTC, akesfeden commented on src/main/webapp/app/exercises/text/assess/analytics/text-assesment-analytics.service.ts
> +        }
```suggestion
        return !!this.location?.path().includes('example-submission');
```
Just a minor suggestion to make it more concise.

2022-08-27 13:39 UTC, akesfeden approved these changes
Thanks for incorporating my suggestion. Re-approved.

2022-08-27 13:46 UTC, manuelmanso approved these changes
Re-approve after fixing the analytics error

2022-08-29 11:10 UTC, ge65cer approved these changes
Thanks for addressing my feedback, approved.
Please remove the unused imports before we merge this.

2022-08-29 11:10 UTC, ge65cer commented on src/test/javascript/spec/service/text-assessment-analytics.service.spec.ts
> +import { MockProvider } from 'ng-mocks';
Codacy warning.

2022-08-31 14:26 UTC, merged