`Programming exercises`: Add more information to grading table
ls1intum/Artemis pull request #5681
Opened 2022-09-25 23:59 UTC by JohannesStoehr

### Checklist
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

#5649 
Make the creation of test weights simpler, easier and less error-prone by providing more detail.

### Description

This PR adds some small things to make the grading table better:
- Each test now displays the amount of points it will grant for passing in the grading table.
- In the right column the total sum of all weights is now shown.
- The headers of the columns of the test case table are now also available in German.
- Since inactive test cases are already greyed out, the column for activity is not necessary and it did not provide any opportunity to sort the rows anyway. Therefore it is removed to save space.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Create a programming exercise
3. Go to the grading view
4. Change any values and check the shown values.

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

<img width="1671" alt="Bildschirmfoto 2022-09-26 um 01 58 04" src="https://user-images.githubusercontent.com/38322605/192171500-223009fb-fde8-47b4-a6bb-02b95ddfaffb.png">

2022-09-27 14:04 UTC, ge65cer reviewed
Tested on TS1, everything works. 👍 

On my screen, the table header is always abbreviated (datatable width is 804px). Could you maybe add a little more space, for example by allowing the collapse of the preview charts?
<img width="600" alt="Screenshot 2022-09-27 at 16 02 15" src="https://user-images.githubusercontent.com/102237363/192547946-146c40ff-97a9-49e8-92b4-14bbc56d6df2.png">

2022-09-27 19:53 UTC, simon-hng reviewed
Code changes look good to me.
Also tested locally on my machine and it works beautifully.

Very nice responsive design with the breakpoint for medium screens!

2022-09-27 20:57 UTC, julian-christl requested changes
Prevents approval:
- totalWeight recalculation (Reason: performance)

Should be addressed now or later:
- Input fields
- testName conditional
- Translation

Nice to have:
- {{...}} code style

2022-09-27 20:57 UTC, julian-christl commented on src/main/webapp/app/exercises/programming/manage/grading/programming-exercise-configure-grading.component.html
> +                                        }}</span>
```suggestion
                                        <span class="datatable-header-cell-label bold sortable">
                                            {{'artemisApp.programmingExercise.configureGrading.gradingTableHeader.testName' | artemisTranslate}}
                                        </span>
```
This style would make more sense to me. Unless eslint complains. If you agree, please replace the other occurrences in your PR.

2022-09-27 20:57 UTC, julian-christl commented on src/main/webapp/app/exercises/programming/manage/grading/programming-exercise-configure-grading.component.html
> +                                    />
I don't see the sense behind adding an input that is always disabled. Then you can just write in a cell like the former "Is active" column or the "Type" column, right?

2022-09-27 20:57 UTC, julian-christl commented on src/main/webapp/app/exercises/programming/manage/grading/programming-exercise-configure-grading.component.ts
> +        const totalWeight = this.testCases.reduce((sum, testCase) => sum + testCase.weight!, 0);
I suggest replacing this with a global totalWeight value as in the charts.

Then in the `updateEditedField` recalculate the total weight value only if a weight field was edited. This way you only recalculate when necessary. Technically, if you have access to the value from before (not sure) you could even update the value without iterating over the whole array but I'm not sure if you do.

2022-09-27 20:57 UTC, julian-christl commented on src/main/webapp/app/exercises/programming/manage/grading/programming-exercise-configure-grading.component.ts
> +            if (testCase.testName) {
Why do we have this distinction? What is the use case here? Do we hide test cases without a name? I don't see an indication of that.

2022-09-27 20:57 UTC, julian-christl commented on src/main/webapp/i18n/de/programmingExercise.json
> +                    "bonusMultiplier": "Bonus Multiplier",
```suggestion
                    "bonusMultiplier": "Bonus Multiplikator",
```

2022-09-28 13:02 UTC, julian-christl approved these changes
Thank you for incorporating the changes.
Code approved.

2022-09-28 14:50 UTC, canberkanar submitted a review, later dismissed
The added column LTM and the point calculation work correctly.

2022-09-28 14:52 UTC, simon-hng approved these changes
Still works as intended. Tested on TS1

2022-09-29 10:22 UTC, julian-christl approved these changes
Reapprove code

2022-09-29 18:59 UTC, simon-hng approved these changes
Second reapproval

2022-09-30 10:56 UTC, ge65cer approved these changes
Re-tested on TS1, no issues found. Code approved.

2022-09-30 17:36 UTC, merged