`Submission`: Prevent string submissions over max length
ls1intum/Artemis pull request #5706
Opened 2022-10-03 16:31 UTC by ge65cer

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [ ] I implemented the changes with a good performance and prevented too many database calls.
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [ ] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

2022-10-04 10:23 UTC, krusche commented on src/main/java/de/tum/in/www1/artemis/config/Constants.java
> +    public static final int MAX_QUIZ_ANSWER_TEXT_LENGTH = 1000; // 1.000 characters
```suggestion
    public static final int MAX_SHORT_ANSWER_QUIZ_TEXT_LENGTH = 255;
```

2022-10-04 14:19 UTC, JohannesStoehr requested changes

2022-10-04 14:19 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/domain/modeling/ModelingSubmission.java
> +    @Size(max = MAX_SUBMISSION_TEXT_LENGTH)
```suggestion
    @Size(max = MAX_SUBMISSION_TEXT_LENGTH, message = "The explanation of the modeling submission is too large.")
```

2022-10-04 15:34 UTC, JohannesStoehr submitted a review, later dismissed
Code looks good and should cover the error.
We should use @Valid more often in the future 💪

2022-10-04 17:39 UTC, JohannesStoehr approved these changes
Re-approve

2022-10-05 12:52 UTC, stefanwaldhauser approved these changes
Good change!

2022-10-05 15:02 UTC, manuelmanso approved these changes
Tested on ts3, works as expected. Code LGTM, also verified that the `maxCharacterCount` wasn't missing in any of the inputs in the client. Nice use of the `assertThatDb` too 👍

2022-10-07 10:12 UTC, jpbernius approved these changes

2022-10-07 10:13 UTC, merged