`General`: Add copy button to LTI configuration
ls1intum/Artemis pull request #5750
Opened 2022-10-18 17:39 UTC by manuelmanso

### Checklist
#### General
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
1. It can be annoying to have to copy all the LTI configuration fields manually.
2. When an LTI user is initialized, they are presented with a checkbox explaining their account was created and a password was created as well. They should save the password or they will have to reset it. It's easy for users to click ok without actually reading the dialog.
3. The LTI configuration page was showing a wrong breadcrumb

### Description
1. Added a reusable copy-icon-button and used it in all the LTI configuration fields for which a copy button is useful.
2. Added a checkbox so that users read the LTI initialization 
3. Fixed the breadcrumb to "LTI Configuration"

### Steps for Testing
Prerequisites:
- 1 Instructor
- Login to moodle https://moodle.ase.in.tum.de/

1. Log in to Artemis
2. Navigate/create online course with exercise, navigate to exercise page and then LTI configuration
3. Verify that the copy icon works as expected
4. Verify that the breadcrumb has been fixed

1. Launch an LTI exercise as a new user
2. Verify that the checkbox is present in the initialization dialog and that the user can only close the dialog when the checkbox is clicked

### Review Progress
#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage
| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

####  Copy buttons and breadcrumb

##### Before

##### After

#### LTI initialization checkbox

##### Before

##### After

2022-10-20 12:58 UTC, JohannesStoehr reviewed
The clone-repo-button also has a field and an additional button for copy+pasting. Maybe you can make your UI similar to this one?

2022-10-30 12:24 UTC, JohannesStoehr approved these changes
Code looks good to me

2022-10-30 17:51 UTC, JohannesStoehr submitted a review, later dismissed
Code after merge looks good as well

2022-10-31 17:39 UTC, maximiliansoelch submitted a review, later dismissed
Tested on TS1, copy buttons work and breadcrumb is fixed 👍

Regarding:
> Verify that the checkbox is present in the initialization dialog and that the user can only close the dialog when the checkbox is clicked

I managed to close the dialog without checking the box by hitting the `esc` key

2022-11-03 12:48 UTC, stefanwaldhauser requested changes
Code looks good and testing was fine too :) GJ. But please add a little test so the client test coverage does not drop

2022-11-03 12:48 UTC, stefanwaldhauser commented on src/main/webapp/app/shared/components/copy-icon-button/copy-icon-button.component.ts
> +export class CopyIconButtonComponent {
❌ Please write a quick unit test for this component. Should not take more than a couple of minutes

2022-11-03 12:48 UTC, stefanwaldhauser commented on src/main/webapp/app/shared/components/copy-icon-button/copy-icon-button.component.ts
> +    @Input() onCopyFinished: Function;
💡A more specific type should be good here as onCopyFinished will be called in this way ```
onCopyFinished($event, onCopyFinishedKey)
```

2022-11-03 12:50 UTC, simon-hng commented on src/main/webapp/app/exercises/shared/exercise/exercise-lti-configuration.component.ts
> +            setTimeout(() => {
see if this is possible with html/css

2022-11-03 12:51 UTC, simon-hng commented on src/main/webapp/i18n/de/global.json
> +            "edit": "Editieren",
```suggestion
            "edit": "Bearbeiten",
```

2022-11-03 12:56 UTC, akesfeden reviewed
Tested on TS2 during testing session. Copy button works as expected and confirmation popup looks better now. Breadcrumb also looks good. I can approve when the client test mentioned by @stefanwaldhauser is added.

2022-11-05 12:24 UTC, manuelmanso commented
Closing as it will be included as part of the larger https://github.com/ls1intum/Artemis/pull/5812

2022-11-05 12:24 UTC, closed without merging