`Programming Exercises`: Synchronize Result display in exercise view
ls1intum/Artemis pull request #5771
Opened 2022-10-24 14:22 UTC by JohannesStoehr

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [ ] I implemented the changes with a good performance and prevented too many database calls.
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [ ] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

2022-10-26 07:27 UTC, ge65cer requested changes
Missing icon in the timeline for manual assessment.
<img width="923" alt="Screenshot 2022-10-26 at 09 27 08" src="https://user-images.githubusercontent.com/102237363/197961905-107db18a-d20a-41ba-962f-72fc89ba1f49.png">

https://artemis-test1.artemis.in.tum.de/courses/62/exercises/1106 (Test User 1)

2022-10-26 12:03 UTC, ge65cer commented on src/test/javascript/spec/component/overview/result-history/result-history.component.spec.ts
> -    it('should return the right values for result score', () => {
Unused imports.

2022-10-26 18:06 UTC, stefanwaldhauser submitted a review, later dismissed
Works as expected except the small issues from above and some small things.

2022-10-26 18:06 UTC, stefanwaldhauser commented on src/main/java/de/tum/in/www1/artemis/domain/Feedback.java
> +     * @return true if it is static code analysis feedback else false
Does the retur text make sense here? Seems to be from another method

2022-10-26 18:06 UTC, stefanwaldhauser commented on src/main/java/de/tum/in/www1/artemis/domain/Feedback.java
> +     * @return true if it is static code analysis feedback else false
Does the retur text make sense here? Seems to be from another method

2022-10-26 18:06 UTC, stefanwaldhauser commented on src/main/webapp/app/exercises/shared/result/result.component.ts
> +            console.log(this.result);
Console.log left in?

2022-10-26 18:06 UTC, stefanwaldhauser commented on src/test/javascript/spec/component/utils/result.utils.spec.ts
> +    it.each([
<3 I like the it.each. Need to use it more also

2022-10-26 18:06 UTC, stefanwaldhauser commented on src/test/javascript/spec/component/utils/result.utils.spec.ts
> +describe('ResultUtils', () => {
Great Test!

2022-10-26 20:43 UTC, stefanwaldhauser approved these changes
Approved since feedback was adressed! Gj :)

2022-10-31 12:40 UTC, stefanwaldhauser submitted a review, later dismissed
Reapprove! Changes from last review are good! Gj

2022-11-02 07:40 UTC, manuelmanso requested changes
Code changes look good, however I found three issues when testing.

1. For text exercises, the submission view doesn't show the graded result even when there is one
![image](https://user-images.githubusercontent.com/11006274/199428373-ff67393d-6f21-483a-9175-bc11477d9009.png)

2. For modelling exercises, the submission view has an issue displaying the date

![image](https://user-images.githubusercontent.com/11006274/199428451-3d93f897-6cc3-4a4c-9eb3-b22cf1b13fc5.png)

3. Before starting a practice repository for a programming exercise you didn't participate in, the result shows "You have missed the deadline". After you start the practice repository, it shows "No graded result" as shown below
![image](https://user-images.githubusercontent.com/11006274/199426428-b56cb18c-f0b2-4f68-9db2-7185a9d93e84.png)

2022-11-07 16:16 UTC, manuelmanso approved these changes
Tested in ts1, issues have been fixed!

2022-11-11 20:23 UTC, tobias-lippert approved these changes
Code LGTM

2022-11-12 12:07 UTC, simon-hng submitted a review, later dismissed
Code looks good

2022-11-13 15:16 UTC, stefanwaldhauser approved these changes
Reapprove!

2022-11-13 15:28 UTC, tobias-lippert approved these changes
Tested again on ts1. Everything worked as expected. Code looks still good to me.

2022-11-13 22:17 UTC, merged