Docs/gitlab ci
ls1intum/Artemis pull request #5807
Opened 2022-11-04 11:34 UTC by bensofficial

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [ ] I implemented the changes with a good performance and prevented too many database calls.
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [ ] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.ase.in.tum.de/user/exam_mode/) as reference.
4. ...

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

2022-12-02 07:15 UTC, b-fein reviewed
Looks good. I’ve got a few suggestions where I think the documentation should be extended with some additional information.

2022-12-02 07:15 UTC, b-fein commented on docs/dev/setup/gitlabci-gitlab.rst.txt
> +    **Note:** For local development, you might add ``--clone-url http://gateway.docker.internal:80`` or ``--clone-url http://172.17.0.1:80`` to the command above.
```suggestion
    .. note::
        For local development, you might add ``--clone-url http://gateway.docker.internal:80`` or ``--clone-url http://172.17.0.1:80`` to the command above.
```
This renders the note in a coloured block.

2022-12-02 07:15 UTC, b-fein commented on docs/dev/setup/gitlabci-gitlab.rst.txt
> +
```suggestion

.. note::
    Adding a runner in a production setup works the same way.
    The GitLab administration page also contains alternative ways of setting up GitLab runners.
    All variants should allow the passing of the configuration options ``tag-list``, ``run-untagged``, ``locked``, and ``access-level`` similarly as in the Docker command above.
    If forgotten, Artemis will not use this runner to run the tests for exercise submissions.


```

2022-12-02 07:15 UTC, b-fein commented on docs/dev/setup/gitlabci-gitlab.rst.txt
> +    Therefore, a random token has to be generated.
```suggestion
    Therefore, a random string has to be generated, e.g., via a password generator.
    This should be used in place of ``notification-plugin-token`` value in the example config below.
```

2022-12-02 07:15 UTC, b-fein commented on docs/dev/setup/gitlabci-gitlab.rst.txt
> +    Please make sure, that the GitLab Runner can access Artemis via the URL specified.
```suggestion
    Please make sure that the GitLab Runner can access Artemis via the URL specified under ``artemis.version-control.url``.
```

2022-12-19 16:18 UTC, b-fein approved these changes
Thank you! One small formatting suggestion, looks good otherwise.

2022-12-19 16:18 UTC, b-fein commented on docs/dev/setup/gitlabci-gitlab.rst.txt
> +    This token is used in the Artemis configuration as `artemis.version-control.token`.
```suggestion
    This token is used in the Artemis configuration as ``artemis.version-control.token``.
```
italics → monospace

2022-12-19 18:33 UTC, b-fein approved these changes

2022-12-28 16:51 UTC, Strohgelaender commented on docs/dev/setup/gitlabci-gitlab.rst
> +                url: http://gitlab # TODO
Instead of `TODO` maybe write e.g. `change this value`.

2022-12-30 10:05 UTC, b-fein approved these changes

2023-01-01 14:02 UTC, tunargs approved these changes
Looks great

2023-01-02 16:55 UTC, Mtze requested changes
I followed your tutorial to setup a local test environment. Unfortunately it doesn't work for me yet. Even with the "fixes" in the inline comments, I still can't execute a build since the spring config requires the gitlab url to be `localhost` to create the repository in the gitlab container but has to be `gitlab` for the runner to be able to clone properly. (even the clone url workaround seems to not work for me) 

Do you have a working local setup?

2023-01-04 20:05 UTC, bensofficial commented on docs/dev/setup/gitlabci-gitlab.rst
> +                url: http://gitlab # change this value
Resolved in testing session. c.f. changes in commit 3682457

2023-01-04 20:05 UTC, bensofficial commented on docs/dev/setup/gitlabci-gitlab.rst
> +            url: http://artemis:8080 # change this value
Resolved in testing session. c.f. changes in commit 3682457

2023-01-04 20:06 UTC, bensofficial commented on docs/dev/setup/gitlabci-gitlab.rst
> +
Resolved in testing session. c.f. changes in commit 3682457

2023-01-07 13:56 UTC, merged