`Development`: Refactor ExerciseDateService to reduce service dependencies
ls1intum/Artemis pull request #5842
Opened 2022-11-14 11:37 UTC by b-fein

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context
Makes the instance method `ExerciseDateService::getDueDate` static to reduce dependencies on that service and to make it usable from static contexts in other services. This reduces code duplication (as noticed in #5833).

### Steps for Testing

1. Code review should be enough, no logic has been changed.

### Review Progress

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage
unchanged

2022-11-14 14:03 UTC, JohannesStoehr requested changes
Changes look good. Left one comment.
If you want to, you can think about adding a static import for that method, if it is used multiple times in a class

2022-11-14 14:03 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/service/ComplaintService.java
> +        // At least result.getCompletionDate is present, since it was checked earlier
Maybe add this as javadoc above the method

2022-11-14 20:35 UTC, JohannesStoehr approved these changes
Code changes look good to me

2022-11-15 10:34 UTC, frederik-kt approved these changes
Code changes look good.

2022-11-17 19:41 UTC, merged