`Development`: Add git information to header/footer on dev/test server & about page
ls1intum/Artemis pull request #5862
Opened 2022-11-21 16:22 UTC by TheZoker

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

### Description

This adds a git commit information into the header, when Artemis is run in development mode or on a test server 

![image](https://user-images.githubusercontent.com/1368405/203105409-a3c91948-f476-4d33-8d3c-278c3da9f45f.png)

And also adds git information into the footer (also only in dev mode and on test servers):
![image](https://user-images.githubusercontent.com/1368405/203105529-71e14dc0-6379-4b9b-9c0a-4f4f6d3deea1.png)

Commit ID and branch is also added to the about page no matter in which mode artemis is running:
![image](https://user-images.githubusercontent.com/1368405/203105703-51b2563c-b123-42c8-8ce3-bd9413931d98.png)

### Steps for Testing

1. Start Artemis in dev mode
2. Mouseover the version in the header & have a look at the footer & about page
3. Run artemis on a test server and repeat 2.
4. Run artemis on a prod server, only about page should have information

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

2022-11-22 10:13 UTC, JohannesStoehr requested changes

2022-11-22 10:13 UTC, JohannesStoehr commented on src/main/webapp/app/shared/layouts/navbar/navbar.component.ts
> +                this.testServer = profileInfo.testServer == undefined ? false : profileInfo.testServer;
```suggestion
                this.testServer = profileInfo.testServer ?? false;
```

2022-11-22 10:13 UTC, JohannesStoehr commented on src/main/webapp/i18n/de/git.json
> +        "username": "Commit Benutzername"
The German nouns should either contain hyphens (-) or be merged to one word

2022-11-22 10:13 UTC, JohannesStoehr commented on src/main/webapp/i18n/de/git.json
> +    "git": {
We normally have artemisApp as the first level in the translation files

2022-11-25 10:44 UTC, JohannesStoehr submitted a review, later dismissed
Thanks for incorporating my suggestions. Code looks good to me

2022-11-28 15:43 UTC, pellumbbaboci submitted a review, later dismissed
Tested on ts1 and locally, works as expected and code LGTM. 
There are conflicts with develop branch as recently there were changes in footer components. Can you resolve those conflicts?

2022-11-28 16:12 UTC, TheZoker commented
Thanks for the hint! I will rebase the PR

2022-11-28 18:47 UTC, pellumbbaboci requested changes
As seen in the picture, footer is showing incorrectly. Can you check again?

![footer](https://user-images.githubusercontent.com/26312757/204354117-7eb8ff7b-e913-4586-97ba-f32c4025188b.png)

2022-11-29 09:01 UTC, TheZoker commented
Thanks for the hint, it seems that one `row` class got removed during the footer PR. I'm not sure why the client-tests fail, since the `ngbTooltip` prop of the div was not an issue before, when the test passed. I'll investigate

2022-11-29 10:28 UTC, danielbode requested changes
Nice PR, works as expected. Tested locally and on ts0. I just added some feedback to the code.

It would also be nice to format the timestamp. I think `Nov 28, 2022 20:44:06` looks better than `2022-11-28T20:44:06Z`.

2022-11-29 10:28 UTC, danielbode commented on src/main/webapp/app/shared/layouts/footer/footer.component.ts
> +    testServer: Boolean;
```suggestion
    testServer: boolean;
```

2022-11-29 10:28 UTC, danielbode commented on src/main/webapp/app/shared/layouts/footer/footer.component.ts
> +    inProduction: Boolean;
```suggestion
    inProduction: boolean;
```

2022-11-29 10:28 UTC, danielbode commented on src/main/webapp/app/shared/layouts/footer/footer.component.ts
> +    inProduction: Boolean;
It is recommended to always use primitive boolean type for declarations: https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#the-primitives-string-number-and-boolean

2022-11-29 10:28 UTC, danielbode commented on src/main/webapp/i18n/de/git.json
> +            "title": "Git-Information",
```suggestion
            "title": "Git-Informationen",
```

2022-11-29 11:14 UTC, tobias-lippert approved these changes
Tested locally and on ts1. Works as expected. Nice improvement.

2022-11-30 09:24 UTC, danielbode approved these changes

2022-11-30 10:39 UTC, JohannesStoehr requested changes

2022-11-30 10:39 UTC, JohannesStoehr commented on src/main/webapp/app/shared/layouts/footer/footer.scss
> +        .footer-git {
Codacy

2022-11-30 13:19 UTC, pellumbbaboci approved these changes
LGTM

2022-12-05 14:45 UTC, rriyaldhi approved these changes
Tested on TS1 and works as expected.

2022-12-05 14:45 UTC, evgeny1984 approved these changes
Tested on the ts1. Everything worked as expected on different screen sizes. The code also looks good.

2022-12-05 14:46 UTC, danielbode approved these changes
Reapprove after adding tests.

2022-12-05 14:47 UTC, pellumbbaboci approved these changes
REAPROVE

2022-12-06 07:23 UTC, merged