`Quiz`: Visual Editor for Multiple Choice Questions
ls1intum/Artemis pull request #5903
Opened 2022-11-29 04:50 UTC by sebastiannikles

### Checklist
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
When creating/editing multiple-choice quiz questions, the only option to specify all the information including question, hints, explanations and answer options is a text editor, which uses markup.

While this should not be too much of a problem for users that are used to writing markup, this can be quickly overwhelming and confusing for inexperienced users as a study for my Master's thesis has shown.

A visually simpler approach could help such users here.

### Description
Other LMS such as Canvas offer a more visual mode when it comes to editing and creating quiz questions. Here, the question is shown more or less like it will be in the final rendering and the user can just type in all the information.

I've taken that approach for Artemis as well and users can now switch to the visual mode for multiple choice questions where the question and the different answer options are shown more clearly and not just in text form. It's possible to switch between the modes as the markdown will be parsed again when switching.

For now, this editor is very simple and supports only text input. In the future, it could be worthwhile supporting more input options such as files or styling options here.

### Steps for Testing

Prerequisites:
- 1 Instructor who can create quizzes
- 1 course

1. Log in to Artemis
2. Navigate to Course Management
3. Navigate to the exercises page
4. Create a new quiz
5. Add a multiple choice question
6. Switch to the visual mode to edit the question

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots

2022-11-29 08:00 UTC, LiaLism submitted a review, later dismissed
Visual Editor is easy to use and works as expected. Tested on ts1.

2022-12-01 15:40 UTC, Yunqing-Wang approved these changes
The function works well, tested on ts 1. But as I tried to submit the quiz, no result will be shown after 1min although I refreshed the website
![image](https://user-images.githubusercontent.com/73842142/205095420-d46fa8cf-ea1c-4eba-b42e-57386113de2f.png)

2022-12-04 15:15 UTC, krusche commented
please find more (experienced) reviewers

2022-12-04 16:16 UTC, timo07k submitted a review, later dismissed
Visual editor works well. Tested on TS1.

2022-12-11 14:39 UTC, evgeny1984 requested changes
The feature works good, tested on ts1. 2 suggestions:

1. Distinction between wrong and correct answer using icon or color
2. I can only create the correct answer option in visual editor, not the wrong one.

2022-12-11 18:35 UTC, PhilipWerz submitted a review, later dismissed
Visiual editor works good. Have tried a few things. Tested on TS1.

Note: 
- a bit weird that one has to remove standard text from answer field (but is the same for normal edit mode)

2022-12-12 09:39 UTC, Santia-go reviewed
Agreed with @evgeny1984 
All options by default are green, this could be confusing for the creators.  
Keep the wrong answer in other color (red preferible)

2022-12-18 13:05 UTC, tunargs approved these changes
Tested on ts1. Works as intended

2023-01-20 08:13 UTC, rriyaldhi requested changes
Functionality looks good, but left some suggestions

2023-01-26 01:30 UTC, sebastiannikles commented on src/main/webapp/app/exercises/quiz/shared/questions/multiple-choice-question/multiple-choice-visual-question.component.ts
> +    set question(question: MultipleChoiceQuestion) {
We need a two-way binding here so the parent component noticed when the question was changed in the visual mode and can update the views (the warning for instance) accordingly.

2023-01-27 09:29 UTC, rriyaldhi approved these changes
Code looks good to me. Thanks for applying the suggestions.

2023-02-08 16:59 UTC, frederik-kt reviewed
There is some padding missing in the question section. This is Chrome.
![Screenshot (94)](https://user-images.githubusercontent.com/64478731/217599369-e0d7629b-52c9-474f-a34f-f5979b98d544.png)

2023-02-08 17:08 UTC, manuelmanso submitted a review, later dismissed
Tested on ts2, works as expected. 

I have a suggestion for the behavior of adding answer options. Instead of always showing the "New Answer Option" section and having the user fill in the fields and then click the "+" to actually add the option. Instead, I suggest only showing a "+" button to add a new option, and once the button is clicked the new option is alreadyv valid. For me this is preferable since in the current way it's possible for a user to fill in a new answer option but forget to click the "+" button.

2023-02-08 17:15 UTC, danielbode submitted a review, later dismissed
Tested on ts2. The visual mode works fine.

I have one improvement suggestion. There is this toolbar in the edit mode and if you switch to the visual mode it disappears:

<img width="528" alt="Bildschirm­foto 2023-02-08 um 18 07 41" src="https://user-images.githubusercontent.com/44734881/217601719-5c7ff80b-c215-4e31-a02e-3c84b3e0a57f.png">

I think this toolbar is especially useful in the visual tab because like you said in the PR description it mostly targets users that aren't familiar with markdown and they otherwise might not know how to make text bold or italic.

2023-02-08 18:59 UTC, YeetTheFirst21 submitted a review, later dismissed
Tested on TS2 in the testing session, looks nice but a few improvements to the visuals just like stated by the others would be nice

2023-02-13 21:31 UTC, bassner requested changes
Hey, please see the code comments below, thanks :)

2023-02-13 21:31 UTC, bassner commented on src/main/webapp/content/scss/themes/_dark-variables.scss
> +
Please use default colors here. We have themed presets for "success" (answer correct) and "danger" (answer wrong). The add container colors seems to be some sort of blue, please use the "primary" color here.
If you need to use custom colors, please prepare a very good reason and justify this, as documented at https://docs.artemis.cit.tum.de/dev/guidelines/client-design/

2023-02-13 21:31 UTC, bassner commented on src/main/webapp/app/exercises/quiz/shared/questions/multiple-choice-question/multiple-choice-question.component.scss
> +    color: white;
Please do not use hardcoded colors

2023-02-13 21:31 UTC, bassner commented on src/test/javascript/spec/component/quiz-exercise/quiz-exercise-visual-editor.component.spec.ts
> +    }));
This test is useless. I think we can remove it. All other tests will fail if the component can't be created

2023-02-13 21:31 UTC, bassner commented on src/test/javascript/spec/component/quiz-exercise/quiz-exercise-visual-editor.component.spec.ts
> +        expect(comp).not.toBeNull();
This is not needed, same in the other test. The beforeEach above will already fail if comp is really null

2023-02-14 11:58 UTC, rriyaldhi submitted a review, later dismissed
Functionality looks good. Tested on TS2.

2023-02-22 08:00 UTC, danielbode approved these changes
Tested on ts2. Reapproved.

2023-02-22 12:17 UTC, bassner requested changes
Hey!
Thank you for updating the code. I've tested this and have a few concerns:

1. The buttons don't look good on small screen widths (could happen on mobile phones):
![image](https://user-images.githubusercontent.com/23171488/220614559-524b660c-a985-4836-8b07-f7d4724f65d9.png)

2. The dark mode appearance of the editor is very different and doesn't look very polished. Why do we have a background color that separates it from the underlying background? In the white mode it's all white. This also leads to spacing issues; the text and the icons are directly pushed towards the border of that gray box. Also, there seems to not be a visible border box on the individual answer options like in the light mode. Please adapt the appearance to look similar in both themes; just the used colors should be inverted, basically.

![image](https://user-images.githubusercontent.com/23171488/220615921-e2b6c959-26a3-431e-82db-33acfb1612ac.png)

3. I think using the blue "+" button on the right side of the question text input box of the new answer option is not a good approach. This can be confusing. What would a user think who sees this for the first time? What does the button do? Do I add another "question text" as it's next to the question text input field? What if I forget to click that little plus button? My new answer option won't be saved, right?

I recommend the same approach that is used to add new questions.
- Do not show the "New answer option" box at all. Instead, add a big green "+ Add answer option" below existing answer options (styled like the "Add Multiple-Choice question" button).
- If clicked, add a new empty answer option. It's actually added to the question, but simply empty at the beginning. The user can then edit it. Everything that is typed there will be saved when "Save" is clicked, without the need to click another button just to confirm that new answer option.

2023-02-25 22:20 UTC, sebastiannikles commented
Should all be updated as requested. The problem with the background color was a general thing with the parent component. Should work now.

2023-03-04 13:48 UTC, bassner requested changes

2023-03-04 13:48 UTC, bassner commented on src/main/webapp/content/scss/themes/_dark-variables.scss
> +
One last thing, sorry.
Seems like you updated the definitions to default colors in the light theme only in 5ccb99481c94f136b5cf9529d4eace2429f46dfe. We need to do this for the dark theme, too.

2023-03-07 15:04 UTC, bassner approved these changes
LGTM!

2023-03-08 16:57 UTC, merged