`General`: Add tooltip to due date of exercise course card
ls1intum/Artemis pull request #5938
Opened 2022-12-09 12:07 UTC by JohannesStoehr

### Checklist
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

#5029 redesigned the exercise header and added a tooltip to the dates of the exercise, when hovering over them. But an other place, namely the course card was left out.

### Description

This PR adds a short tooltip to the course exercise card that displays the due date, when hovering over it.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Exercise with due date

1. Log in to Artemis
2. Navigate to the course
3. Hover over the due date in the exercise card
4. Make sure that you are redirected, even when clicking directly on the due date

### Review Progress

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

<img width="1116" alt="Bildschirm­foto 2022-12-09 um 11 39 13" src="https://user-images.githubusercontent.com/38322605/206699074-e0c8d20d-e516-4356-97ce-973c712a915f.png">

2022-12-09 15:02 UTC, evgeny1984 submitted a review, later dismissed
Tested on TS2, works as described, no issues. The code changes are also looking good.

2022-12-09 17:38 UTC, ge65cer requested changes
Good addition! 👍  However, the client tests failed.

2022-12-10 14:03 UTC, stefanwaldhauser approved these changes
Nice Tooltip :)

2022-12-10 18:52 UTC, timo07k submitted a review, later dismissed
Tooltip works as expected. Tested on TS1.

2022-12-11 09:33 UTC, LiaLism submitted a review, later dismissed
Tooltip worked as expected. Tested on ts1.

2022-12-14 17:41 UTC, evgeny1984 submitted a review, later dismissed
Re-approved after minor changes. Tested on the ts1, works as expected.

2022-12-16 09:54 UTC, krusche commented on src/main/webapp/app/overview/course-exercises/course-exercise-row.component.ts
> +    routerLink: any[];
can we use `string[]` here?
(we generally want to avoid `any`)

2022-12-16 16:43 UTC, merged