`Development`: Upgrade from tslint to eslint
ls1intum/Artemis pull request #5947
Opened 2022-12-10 14:13 UTC by ge65cer

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I implemented the changes with a good performance and prevented too many database calls.
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [ ] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.ase.in.tum.de/user/exam_mode/) as reference.
4. ...

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test

### Test Coverage

### Screenshots

2022-12-10 17:14 UTC, krusche commented on package.json
> +    "eslint": "^8.28.0",
avoid ^ please

2022-12-10 17:14 UTC, krusche requested changes
can you please revert the changes in package.json and package-lock.json related to pure whitespace ? we should avoid this

2022-12-10 20:38 UTC, krusche commented
why are there still so many changes in `package-lock.json`?

2022-12-16 16:19 UTC, ge65cer commented
@krusche I might have had a different node version, now used node v18.

2022-12-19 20:43 UTC, ge65cer commented
Resolved merge conflicts.

2022-12-20 09:56 UTC, krusche commented
client-style seems to fail, we should fix that before we merge this PR

2022-12-20 10:04 UTC, krusche commented
I run `npm install` once more, now the number of changes is more reasonable

2022-12-20 10:57 UTC, b-fein commented
According to the log the CI fails as in GitHub Actions config Node 16 is still used instead of 18 as required by the `package.json`. Should be fixed with #5987.

2022-12-20 18:46 UTC, ge65cer commented
Waiting for #5987

2022-12-20 21:47 UTC, ge65cer commented
All green now. ✅

2022-12-21 09:45 UTC, krusche commented
@ge65cer does this mean we can merge the PR and finally get rid of TSLint? Or should we ask some developers to test / review the changes?

2022-12-21 17:10 UTC, ge65cer commented
@krusche From my perspective it can be merged.

2022-12-23 20:54 UTC, krusche approved these changes

2022-12-23 21:29 UTC, merged