`General`: Improve error page
ls1intum/Artemis pull request #6053
Opened 2023-01-08 22:25 UTC by ge65cer

### Checklist
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

Artemis did not show an error page when the requested page does not exist.

### Description

Fixed the handling of 404 errors.
Added two buttons to the error page to navigate to the start page or report an issue in GitHub.

### Steps for Testing

Prerequisites:
- 1 User

1. Navigate to a non-existent URL in the client
2. See the error page

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

_unchanged_

### Screenshots

![error-page](https://user-images.githubusercontent.com/102237363/211222067-a3ee36c5-bf15-4649-aaf6-8ec670c945f1.png)

2023-01-09 10:07 UTC, Strohgelaender commented on src/main/webapp/app/shared/layouts/error/error.component.html
> +        <a class="btn btn-secondary" href="https://github.com/ls1intum/Artemis/issues/new/choose" jhiTranslate="error.action.report">Report bug</a>
The about us component uses https://github.com/ls1intum/Artemis/issues/new?projects=ls1intum/1 which allows the user to just submit any text without using the issue templates. Can you also change the URL there, maybe using a shared constant?

2023-01-10 09:34 UTC, LiaLism approved these changes
The error page works as expected. I did not experience the issues mentioned above. Tested on ts1.

2023-01-10 09:58 UTC, simon-hng approved these changes
Code

2023-01-10 15:41 UTC, ge65cer reviewed
There seems to be a routing issue for the communication/messages tab. I need to investigate, maybe these routes are not registered correctly.

<img src="https://user-images.githubusercontent.com/102237363/211595409-0ff2daa3-88c9-4f12-8a37-0eba134841fb.png" width="500" />

2023-01-10 20:08 UTC, tunargs approved these changes
Tested on ts2. works as expected

2023-01-11 15:39 UTC, Hialus requested changes
Works as expected for URLs that do not follow any specified routing scheme.
For URLs that follow a specified routing scheme, but are still invalid (e.g. non existent id) the behavior is all over the place.
1. For /courses/{id}: Shows an empty page if the id is invalid
2. For /courses/{id1}/exercises/{id2}: Shows (not redirects) the home screen

Considering that this is likely handled by each page individually this could be done in a follow-up PR, as this would require touching all affected pages. But having consistent behavior would be important IMO. (If you do this also consider noting this down in the docs)

And something major that does not happen in another PR, so it is likely caused by yours: The course management page shows the course overview page: 
<img width="677" alt="grafik" src="https://user-images.githubusercontent.com/18218285/211847690-8d5225cb-d958-4475-aa87-36b9cec62b95.png">
This doesn't even apply only to this page. The general routing for courses seems to be broken. E.g. https://artemis-test1.artemis.in.tum.de/courses/40/exercises/622 also shows the overview page
This needs to be fixed!


Tested on TS10 and verified on TS1, while using TS3 to check the routing on another PR.

2023-01-23 22:05 UTC, stefanwaldhauser approved these changes
Code lgtm!

2023-02-08 15:54 UTC, Yunqing-Wang reviewed
![image](https://user-images.githubusercontent.com/73842142/217581268-bd81b287-59ae-4ae7-a439-a9ae40749d31.png)
I got the bad request error message

2023-03-02 12:04 UTC, closed without merging