`Bugfix`: Fix custom group names displayed to instructors
ls1intum/Artemis pull request #6061
Opened 2023-01-11 17:18 UTC by TheZoker

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

When writing some e2e tests I realised, that currently custom group names for courses are not shown, since they are guarded by a `!course.isAtLeastInstructor`. So users with alteast instructor permission are **NOT** allowed to see the custom groups. It seems this was done by mistake.

### Description

This PR changes `!course.isAtLeastInstructor` to `course.isAtLeastInstructor`, so users with at least instructor permission can see the custom group names.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Navigate to Course Administration
3. Create a new course or use existing course
4. Look for this view:
![image](https://user-images.githubusercontent.com/1368405/211873051-4d2c2361-6875-422c-9f08-556d86c272d1.png)
5. You should be able to see the marked segment

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test

2023-01-11 18:34 UTC, laadvo approved these changes
Tested on ts1 by creating a new course with custom groups, the group names are now displayed as expected to the instructor.

2023-01-12 09:04 UTC, frederik-kt approved these changes
Tested on TS1. Works and makes sense.

2023-01-12 10:43 UTC, Strohgelaender approved these changes

2023-01-12 10:46 UTC, Strohgelaender requested changes
I looked at it again and I actually think that this is expected. As you can see in your screenshot, an instructor now sees dulicated information: One the groups with a link to the user management, and once only the group names.


I'd sugesst the following: To make the intention more clear, use a structure like this:
```
<div *ngIf="course.isAtLeastInstructor; else groupsWithoutLink">
....
</div>
<ng-template #groupsWithoutLink>
....
</ng-template>

2023-01-12 15:59 UTC, Vinicius-Agreste submitted a review, later dismissed
Worked as expected on ts2 with an already existing course.

2023-01-12 17:17 UTC, TheZoker commented
> I looked at it again and I actually think that this is expected. As you can see in your screenshot, an instructor now sees duplicated information: Once the groups with a link to the user management, and once only the group names.

You are right, I missed that the names are laready displayed within the links. I changed the logic according to your suggestion!

2023-01-12 20:19 UTC, JohannesStoehr submitted a review, later dismissed
Logik is still correct and more safe than before due to else statement.
Code looks good to me

2023-01-12 21:39 UTC, Strohgelaender submitted a review, later dismissed

2023-01-12 21:51 UTC, timo07k approved these changes
Everything still working as expected. Tested on TS1.

2023-01-12 21:53 UTC, PhilipWerz approved these changes
Everything worked as it should. Tested on TS1.

2023-01-13 08:22 UTC, LiaLism approved these changes
Everything worked as expected. Tested on ts1.

2023-01-13 12:24 UTC, krusche commented
can you add a comment in the HTML that this is intended and shortly explain why?

2023-01-18 09:35 UTC, LiaLism approved these changes
Reapproved. Tested on ts0.

2023-01-20 09:18 UTC, JohannesStoehr approved these changes
Rechecked code and verified the comments

2023-01-20 09:47 UTC, frederik-kt approved these changes
Reapprove

2023-01-22 00:06 UTC, Strohgelaender approved these changes

2023-01-22 09:11 UTC, merged