`Programming exercises`: Fix appearance of feedback view in Safari
ls1intum/Artemis pull request #6068
Opened 2023-01-12 17:26 UTC by JohannesStoehr

### Checklist
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

The detailed feedback view has some visual bugs in Safari.

### Description

Resolves the bugs:
- Two triangles indicating whether the feedback category is opened or closed
- The footer does not extend to the very right

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 Programming Exercise

1. Log in to Artemis
2. Participate in the exercise
3. Click on the result on the top right and inspect the feedback view

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests (at least one in Safari and one in Chrome)
- [ ] Test 1
- [ ] Test 2

### Screenshots

Broken:
![Bildschirm­foto 2023-01-12 um 18 21 46](https://user-images.githubusercontent.com/38322605/212136933-5e192ca9-9baf-4a65-aa7a-a40586fa3f17.png)
Fixed:
![Bildschirm­foto 2023-01-12 um 18 19 55](https://user-images.githubusercontent.com/38322605/212136825-433478da-3f1e-4c86-980f-499f37fcf198.png)

2023-01-12 20:39 UTC, PhilipWerz submitted a review, later dismissed
Triangles where not shown as expected. The footer does now extend to the very right. So both works as expected. Tested on TS1.

Note:
I noticed that there might be a space missing between the (1) and the number of points:

![image1](https://user-images.githubusercontent.com/68745570/212175975-21b7495a-3498-4df0-b35b-23b089545c61.jpeg)

2023-01-13 00:16 UTC, ge65cer requested changes
Tested on Safari, looks good.

2023-01-13 00:47 UTC, simon-hng commented on src/main/webapp/app/exercises/shared/feedback/node/feedback-node.component.html
> +        <span *ngIf="feedbackItemGroup.credits !== 0" class="fw-bold">{{ roundValueSpecifiedByCourseSettings(feedbackItemGroup.credits, course) }}P </span>
resolved in https://github.com/ls1intum/Artemis/pull/6068/commits/2b376f4c7646e8ec02d1bcdca775a15ffe1d8763

2023-01-13 09:54 UTC, simon-hng approved these changes

2023-01-13 13:06 UTC, ge65cer approved these changes

2023-01-20 11:07 UTC, merged