`Exam mode`: Fix bug where complaints are still treated as submitted in the UI even on error
ls1intum/Artemis pull request #6202
Opened 2023-02-04 17:46 UTC by akesfeden

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 Submitted Exam with  at least 1 text, 1 modeling, 1 file upload and 1 programming exercise. (Exercises can be in different exams)

1. Log in to Artemis
2. Navigate to Course Administration
3. As an Instructor, evaluate 1 text, 1 modeling, 1 file upload and 1 programming exercise.
4. As a Student, make a complaint to each one of the above exercises.
5. As an Instructor, 

#### Exam Mode Testing
Changes only involve assessment mode and covered by the testing steps above.

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test

### Test Coverage

### Screenshots

2023-02-05 13:00 UTC, JohannesStoehr requested changes
Code looks good apart from this:

2023-02-05 15:23 UTC, akesfeden commented on src/main/webapp/app/exercises/text/assess/text-submission-assessment.component.ts
> +                this.participation?.id!,
Thanks, I moved eslint-disable comment to correct lines.

2023-02-05 17:07 UTC, Vinicius-Agreste requested changes
Tested on ts1.Programming and modelling exercises did not work as expected (Text and File Upload worked flawlessly). I was able to accept (solve) the complaint in both while having an incomplete feedback.

2023-02-05 17:27 UTC, akesfeden commented
@Vinicius-Agreste can you share the urls of the unexpected programming and modeling assessments on TS1?

2023-02-05 17:57 UTC, akesfeden commented
@Vinicius-Agreste I think I got the issue. This PR was about preventing the UI to be in an unusable state with disabled when there a complaint is accepted with invalid feedback, but the issue you found seems to be about determining when does a feedback considered invalid and raising an error according to that (more related to the feedbacks themselves rather than the complaint). But I can try to address that here too.

2023-02-06 06:36 UTC, akesfeden commented
@Vinicius-Agreste The validations for programming and modeling exercises are added in https://github.com/ls1intum/Artemis/pull/6202/commits/ef97bc5c9b4a294f29d94c51f08c78f55fa35543, could you check again?

2023-02-06 17:30 UTC, laadvo approved these changes
Tested using an exam with all 4 different types of exercises, everything is working as expected. Tested on ts1.

2023-02-07 14:38 UTC, Vinicius-Agreste reviewed
@akesfeden thank you for addressing my review. I tested it again and got the same result.
 If I understood it correctly, the apparent bug I faced is not really related to your PR. If you'd like, I can approve your PR and explain the bug I found in greater detail somewhere else. Let me know.
I went ahead and tested on a new Exam and noticed that when accepting a complaint with an incomplete feedback (without text) the feedback's points are added to the exercise calculation. See the following example: In this modelling exercise I added the first feedback "no" adding 0.5 points. Then, the student submits a complaint. I create a new, incomplete feedback (-0.5 points) and accept the complaint. The complaint gets resolved, and the -0.5 points are added to the exercise result (you can see the empty feedback message in the exercise result student view).
![image](https://user-images.githubusercontent.com/49817098/217273865-87a8e42d-c17f-4a4f-b2ca-2476b48b15bd.png)

![image](https://user-images.githubusercontent.com/49817098/217275220-3a4d5d7c-3b0e-405a-aeb2-fac9ef26b5f7.png)

2023-02-07 17:54 UTC, Vinicius-Agreste approved these changes

2023-02-07 18:23 UTC, JohannesStoehr approved these changes
Thanks for addressing my comment. Code looks good

2023-02-08 08:22 UTC, merged