`Programming exercise`: Change text color to green if build is successful with 0 tests passed
ls1intum/Artemis pull request #6205
Opened 2023-02-06 14:53 UTC by simon-hng

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I implemented the changes with a good performance and prevented too many database calls.
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exam_mode/) as reference.
4. ...

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test

### Test Coverage

### Screenshots

2023-02-06 14:54 UTC, Strohgelaender commented on src/main/webapp/app/exercises/shared/result/result.utils.ts
> + * This could be because all test cases have visibility after the due date.
```suggestion
 * This could be because all test cases are only visible after the due date.
```

2023-02-06 15:47 UTC, tobias-lippert submitted a review, later dismissed
Code LGTM

2023-02-06 16:08 UTC, Strohgelaender commented on src/main/webapp/i18n/de/result.json
> +            "onlyCompilationTested": "Dein Code wurde erfolgreich kompiliert. Im moment sind keine Testfälle sichtbar",
```suggestion
            "onlyCompilationTested": "Dein Code kompiliert erfolgreich. Derzeit sind keine Testfälle sichtbar",
```

2023-02-07 12:31 UTC, JohannesStoehr requested changes
Code looks good apart from these two things

2023-02-07 12:31 UTC, JohannesStoehr commented on src/main/webapp/i18n/de/result.json
> +            "onlyCompilationTested": "Dein Code kompiliert erfolgreich. Derzeit sind keine Testfälle sichtbar",
```suggestion
            "onlyCompilationTested": "Dein Code kompiliert erfolgreich. Derzeit sind keine Testfälle sichtbar.",
```

2023-02-07 12:31 UTC, JohannesStoehr commented on src/test/javascript/spec/component/utils/result.utils.spec.ts
> +import { getResultIconClass, getTextColorClass, getUnreferencedFeedback, isOnlyCompilationTested, ResultTemplateStatus } from 'app/exercises/shared/result/result.utils';
Order of imports is not alphabetically

2023-02-07 17:28 UTC, simon-hng commented on src/test/javascript/spec/component/utils/result.utils.spec.ts
> +import { getResultIconClass, getTextColorClass, getUnreferencedFeedback, isOnlyCompilationTested, ResultTemplateStatus } from 'app/exercises/shared/result/result.utils';
```suggestion
import { ResultTemplateStatus, getResultIconClass, getTextColorClass, getUnreferencedFeedback, isOnlyCompilationTested } from 'app/exercises/shared/result/result.utils';
```

2023-02-09 23:45 UTC, TheZoker approved these changes
Code LGTM 👍

2023-02-10 15:48 UTC, YeetTheFirst21 approved these changes
Tested on TS1 in the test session, seems to be working fine.

![Screenshot_20230210_044753](https://user-images.githubusercontent.com/80704436/218134878-6ea37277-7280-4671-b774-4fa0833d82b8.png)

2023-02-10 15:52 UTC, pellumbbaboci approved these changes
Tested on ts1 during testing session. Works as expected and code looks good!

2023-02-10 15:53 UTC, Vinicius-Agreste approved these changes
Tested on ts1. Worked as expected.

2023-02-10 15:53 UTC, danielbode approved these changes
Tested on ts1. Works as expected.

2023-02-10 16:23 UTC, rriyaldhi approved these changes
Tested during testing session on TS1 and works as expected.

2023-02-26 09:53 UTC, merged