`Development`: Move assessment due date check into ExerciseDateService
ls1intum/Artemis pull request #6224
Opened 2023-02-09 13:43 UTC by Strohgelaender

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I implemented the changes with a good performance and prevented too many database calls.
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exam_mode/) as reference.
4. ...

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test

### Test Coverage

### Screenshots

2023-02-18 15:46 UTC, tobias-lippert approved these changes
Carefully looked through the code and checked that the logic regarding due date checks wasn't accidentally inverted.
Didn't find any issues.

2023-02-23 15:44 UTC, JohannesStoehr requested changes

2023-02-23 15:44 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/service/CourseScoreCalculationService.java
> +        boolean isNonAutomaticAssessmentDone = !isAssessedAutomatically(exercise) && (exerciseDateService.isAfterAssessmentDueDate(exercise));
```suggestion
        boolean isNonAutomaticAssessmentDone = !isAssessedAutomatically(exercise) && exerciseDateService.isAfterAssessmentDueDate(exercise);
```

2023-02-23 15:44 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/service/ResultService.java
> +    // TODO improve naming (more like prepareFeedbackForClient)
Why don't you resolve this todo?

2023-03-10 15:50 UTC, b-fein submitted a review, later dismissed
Code changes look good.

2023-03-14 16:36 UTC, stefanwaldhauser submitted a review, later dismissed
Sensible refactoring

2023-03-15 10:44 UTC, JohannesStoehr submitted a review, later dismissed
Thanks for addressing my review. Code looks good to me

2023-03-15 16:26 UTC, TimOrtel submitted a review, later dismissed
The code changes look fine. I think its a very nice refactoring to eliminate duplicated code.

2023-03-26 10:36 UTC, b-fein submitted a review, later dismissed
re-:+1: code

2023-03-27 09:59 UTC, JohannesStoehr reviewed
Benedict made some methods static to reduce the dependencies between the services in #5842. Maybe we can do the same with the new methods here?

2023-03-31 15:25 UTC, JohannesStoehr submitted a review, later dismissed
Comments were addressed. Code looks good to me

2023-03-31 18:17 UTC, b-fein submitted a review, later dismissed
re-:+1: code

2023-05-13 12:03 UTC, closed without merging