`General`: Remove participant score pages
ls1intum/Artemis pull request #6239
Opened 2023-02-12 21:13 UTC by ge65cer

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I implemented the changes with a good performance and prevented too many database calls.
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exam_mode/) as reference.
4. ...

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test

### Test Coverage

### Screenshots

2023-02-12 21:42 UTC, Strohgelaender commented on src/test/javascript/spec/component/exam/exam-scores/exam-scores.component.spec.ts
> -    it('should not delegate user if authorisation is not sufficient', () => {
unused imports in this file.

2023-02-12 22:52 UTC, JohannesStoehr requested changes
Can you give the dropdown a suiting name that is displayed next to the arrow?
I would currently expect some more context regarding the assessment and not scores or plagiarism cases

2023-02-13 08:07 UTC, ge65cer commented
@JohannesStoehr It's a split button where I put everything related to student submissions. Would you prefer a separated dropdown?

2023-02-13 11:42 UTC, Strohgelaender requested changes
Please also remove the related server endpoints.

2023-02-13 12:34 UTC, JohannesStoehr commented
> @JohannesStoehr It's a split button where I put everything related to student submissions. Would you prefer a separated dropdown?

In that case I would expect a dropdown labeled "Student Scores/Assessment" and clicking on one of the options would then redirect to that page

2023-02-13 12:36 UTC, ge65cer commented
@JohannesStoehr That would have the downside that the Assessment Dashboard would no longer accessible with one click.

2023-02-14 12:06 UTC, ge65cer commented
Server tests fail due to coverage. I think it is safe to decrease the threshold in this case, @krusche?
(This PR only removes code.)

2023-02-14 12:13 UTC, LiaLism approved these changes
Everything worked as expected. Tested on ts0.

2023-02-14 19:35 UTC, timo07k submitted a review, later dismissed
Everything works as expected. Tested on TS1.

2023-02-15 14:24 UTC, luisa1999 approved these changes

2023-02-15 17:48 UTC, Vinicius-Agreste approved these changes
Tested on ts2. Worked as expected. Looks good.

2023-02-16 08:00 UTC, PhilipWerz submitted a review, later dismissed
Everything works as expected. Dropdown looks good. Tested on TS1.

Remark:
Score Button still visible in "Course Management" Overview Page. (According to the description not part of the PR thouh)

2023-02-17 12:17 UTC, krusche commented
> @JohannesStoehr That would have the downside that the Assessment Dashboard would no longer be accessible with one click.

Can we add links to `scores`, `plagiarism cases` and `grading key` on the assessment dashboard page?

2023-03-02 06:51 UTC, ge65cer commented
![screenshot](https://user-images.githubusercontent.com/102237363/222352895-617346d0-a724-43c0-817f-4f9e32d1e233.png)

2023-03-03 11:18 UTC, JohannesStoehr approved these changes
I like the new buttons in the assessment dashboard. Looks good to me now

2023-03-04 11:19 UTC, merged