`General`: Improve QoL of LTI launch with prefilled username
ls1intum/Artemis pull request #6265
Opened 2023-02-17 09:10 UTC by manuelmanso

### Checklist
#### General
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
Improve the QoL of an LTI launch by prefilling the username field with the corresponding username for the LTI launch. That way, users can more easily now what user they are logging in as and only need to fill in the password.

Also prevents user from using ESC to close the initializer modal showing the password, forcing them to actually read the content and save the password. Adds a copy button for the password as well

### Description

- Prefills the username field with the corresponding username from the LTI launch
- Prevent users from closing modal with ESC (keyboard: false)
- Add copy button for password field

### Steps for Testing
Prerequisites:
- 1 Instructor

Launch as new LTI student 
1. Verify that password copy button is present in the password modal and that it works
2. Verify that it's not possible to close modal with "ESC" key (or any other key)

Launch as existing LTI student 
1. Verify that notification is shown "LTI launch as {username}" with the correct username
2. Verify that the username is already prefilled in the login bar

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| ExerciseService.java | 85% | 77% |
| programming-exercise.component.ts | 13% | 95% |

### Screenshots

Password initializer modal with copy button

![image](https://user-images.githubusercontent.com/11006274/219600549-a3c925c3-6eb4-4a4a-afc4-7ef0a9f669d6.png)

2023-02-26 15:21 UTC, JohannesStoehr requested changes
Apart from this, code looks good

2023-02-26 15:21 UTC, JohannesStoehr commented on src/test/javascript/spec/service/account.service.spec.ts
> +import { post } from '../helpers/sample/metis-sample-data';
Unused import

2023-02-27 09:05 UTC, manuelmanso commented on src/test/javascript/spec/service/account.service.spec.ts
> +import { post } from '../helpers/sample/metis-sample-data';
Thanks, fixed!

2023-02-27 14:13 UTC, frederik-kt approved these changes
Tested on TS1. Could not close modal and username was prefilled correctly.

2023-02-27 14:13 UTC, rriyaldhi approved these changes
Tested on TS1 and works according to the testing steps.

2023-02-27 14:14 UTC, danielbode approved these changes
Tested on ts1 during a testing session. Works as expected!

2023-03-03 11:16 UTC, JohannesStoehr approved these changes
Thanks for fixing the code issue. Code looks good to me now

2023-03-05 19:05 UTC, merged