Update Atlassian Versions
ls1intum/Artemis pull request #6307
Opened 2023-02-28 14:03 UTC by Mtze

### Motivation and Context

Atlassian Updates 

- Bitbucket → [7.21.10](https://confluence.atlassian.com/bitbucketserver/bitbucket-data-center-and-server-7-21-release-notes-1115129015.html)  
- Bamboo → [9.2.1](https://confluence.atlassian.com/bambooreleases/bamboo-9-2-release-notes-1207179202.html)  
- Jira → [9.4.0](https://confluence.atlassian.com/jirasoftware/jira-software-9-4-x-release-notes-1178869757.html)

2023-03-01 11:10 UTC, Hialus requested changes

2023-03-01 11:10 UTC, Hialus commented on src/main/docker/atlassian.yml
> +        image: ghcr.io/ls1intum/artemis-jira:9.4.0
```suggestion
        image: ghcr.io/ls1intum/artemis-jira:9.4.3
```

2023-03-01 13:07 UTC, Hialus submitted a review, later dismissed

2023-03-01 17:18 UTC, TheZoker requested changes
Prelive bitbucket has been updated to `8.8.2`

2023-03-01 17:18 UTC, TheZoker commented on src/main/docker/atlassian.yml
> +        image: ghcr.io/ls1intum/artemis-bitbucket:7.21.10
```suggestion
        image: ghcr.io/ls1intum/artemis-bitbucket:8.8.2
```

2023-03-04 10:27 UTC, TheZoker approved these changes
e2e tests run again, so issues seem to be fixed now 🎉

2023-03-04 11:17 UTC, merged