Add even more communication tests
ls1intum/Artemis pull request #6415
Opened 2023-04-05 12:56 UTC by TheZoker

## Don't merge this before #6393
----

### Checklist
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

### Description

This PR adds even more communication tests. Especially the lecture posts are now tested thoroughly. 
This PR adds the following tests:
- Students should be able to filter for post by own
- Instructor should be able pin a post within exercises
- Instructor should be able to archive a post within exercises
- Other students should be able to filter for exercise post by context
- Students should be able to filter for exercise post by own
- Students should be able to create posts within lectures
- Instructor should be able pin a post within lectures
- Instructor should be able to archive a post within lectures
- Students should be able to search for lecture posts
- Other students should be able to filter for lecture post by context
- Other students should be able to react to a lecture post

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2

2023-04-07 10:30 UTC, bassner requested changes

2023-04-13 11:49 UTC, TheZoker commented on src/test/cypress/e2e/course/CourseCommunication.cy.ts
> +function prepareContextTitle(title: string) {
Yes this warning war correct, I missed the function when refactoring the code. Thanks for the hint!

2023-04-17 14:45 UTC, tobias-lippert submitted a review, later dismissed
Code LGTM

2023-04-17 14:45 UTC, rriyaldhi approved these changes
Test looks good for me 👍

2023-04-21 13:35 UTC, merged