General: Allow tutors to grade presentations
ls1intum/Artemis pull request #6461
Opened 2023-04-19 09:38 UTC by DominikRemo

# ‼️ Changes to the database. Please do not deploy to the test servers until the changelogs have been approved

- Add columns to grading_scale table to support grading for presentations
- Update the datatype of presentation_score column to support grading for presentations

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [ ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.

### Motivation and Context

### Description

### Steps for Testing

### Review Progress

#### Performance Review
- [ ] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2023-04-24 11:28 UTC, jakubriegel reviewed
Code looks fine 👍🏻 

I was testing it locally, but wasn't able to complete the testing steps as there was no checkbox for the presentation on course create page. I've recorded a Loom to explain it better: https://www.loom.com/share/7d373081d4ea4a9f8953b022d2ed4390

2023-04-24 19:49 UTC, YeetTheFirst21 submitted a review, later dismissed
Tested on TS1, all seems to be working as expected

![Screenshot 2023-04-24 214903](https://user-images.githubusercontent.com/80704436/234100764-adfdac21-e908-4ece-9950-3ca84d507f68.png)

2023-04-24 20:04 UTC, jakubriegel approved these changes
Tested locally. Works fine 👍🏻

2023-04-24 21:48 UTC, YeetTheFirst21 submitted a review, later dismissed
Tested again on TS1, seems to be working fine

2023-04-25 07:10 UTC, jakubriegel approved these changes

2023-04-26 11:12 UTC, JohannesStoehr requested changes
Looked through the code and left a comment.

2023-04-26 11:12 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/web/rest/ParticipationResource.java
> +                }
I'd prefer an Exception here, otherwise the user might be confused why their chosen number was changed without an error

2023-04-26 12:30 UTC, JohannesStoehr approved these changes
Thanks for addressing my comment. Code looks good to me

2023-04-26 16:44 UTC, laadvo reviewed
Tested setting the grading key on ts1, I noticed that the save button is enabled when '.' is inputed or the input filed is left empty, I'm not sure if this is expected. Also observed interesting behavior when inputing a number starting with a dot, for example  '.9' or '.7. These two examples can be seen in the video below.

https://user-images.githubusercontent.com/73339358/234645229-803b0bd8-3580-433f-ba60-aadd9a5e765b.mp4

2023-04-26 17:21 UTC, laadvo approved these changes
Tested on ts2, everything is working as expected. The problem I encountered before is not related to the PR

2023-04-26 17:38 UTC, jakubriegel approved these changes

2023-04-26 20:57 UTC, YeetTheFirst21 approved these changes
Tested again on TS1, all seems to be working fine.

2023-04-27 16:32 UTC, maximiliansoelch requested changes
Tested on TS1 and found some issues:

1. The tooltip description is inaccurate. It explains the differences between _Basic_ and _Graded_
![Screenshot 2023-04-27 at 17 43 49](https://user-images.githubusercontent.com/9954674/234926248-a5f7d017-450a-4567-a7ac-2eee361a5418.png)
---
2. When graded presentations are used, this checkbox in the course edit view should be disabled (similar to how it is done in 3.) with a helpful tooltip message describing the reason for it.
![Screenshot 2023-04-27 at 17 51 43](https://user-images.githubusercontent.com/9954674/234926489-7a63f04e-5ded-46a0-8873-43d0bb9739a8.png)
---
3. When presentations (presentation scores) in the course are enabled, the controls are disabled correctly. However, the tooltip text should also state the reason instead of the general description.
![Screenshot 2023-04-27 at 18 15 59](https://user-images.githubusercontent.com/9954674/234926983-ad7d90d5-abca-4ad9-b1d2-19a545fcee70.png)
---
4. Invalid grade inputs result in a confirmation, which is very confusing. However, the values don't get saved despite the message. 
5. Further, when viewing the participations as an instructor, the order of the button (first delete, then update presentation) is not optimal.

https://user-images.githubusercontent.com/9954674/234928194-278022d8-6d56-4d03-9418-bf73086d1fff.mov

---
6. Switching between the two presentation modes (None, Graded) loads the default values in the UI. This can lead to confusion:

https://user-images.githubusercontent.com/9954674/234929067-c2da2fed-6472-44e3-ab96-816b94d5e5ea.mov

2023-04-27 16:41 UTC, rriyaldhi approved these changes
Tested on TS2 and works according to the testing steps

2023-04-27 17:40 UTC, DominikRemo commented
> Tested on TS1 and found some issues:
> 
> 1. The tooltip description is inaccurate. It explains the differences between _Basic_ and _Graded_
> 
> 2. When graded presentations are used, this checkbox in the course edit view should be disabled (similar to how it is done in 3.) with a helpful tooltip message describing the reason for it.
> 
> 3. When presentations (presentation scores) in the course are enabled, the controls are disabled correctly. However, the tooltip text should also state the reason instead of the general description.
> 
> 4. Invalid grade inputs result in a confirmation, which is very confusing. However, the values don't get saved despite the message.
> 5. Further, when viewing the participations as an instructor, the order of the button (first delete, then update presentation) is not optimal.
> 
> 
> 6. Switching between the two presentation modes (None, Graded) loads the default values in the UI. This can lead to confusion:
> 
> 
> 7. Switching between presentation scores and graded presentations also results in some weird behavior with values that were took over from the other presentation mode:
> 

1. Setting the presentations score will be moved from the course edit page to the grading key dialog, this will be done in a FollowUp in the beginning of next month
2. Since the checkbox will be removed in the FollowUp there is only a error message when you try to safe invalid changes, which is expected behaviour
3. Same as 2nd. It is disabled for now, but this will change when the third option (“Basic”) is added in the follow up
4. I was actually surprised when you inputed the value “as” but I tested it on other input fields as well and it seems to be a general issue with number fields. Maybe we could open a new issue for that
5. The order is kept the same as with previous presentations to make the transition to the new system easier
6. Switching between presentation modes is like generating a new grading key, you should not expect the same values to be there when they have not been saved priviously
7. This is due to the fact that switching between Presentations is rather simple (extremely simple once the presentation score setting has been moved to the grading key page.). Accidentally switching from graded to basic presentations would either mean that previous presentations are set to 1 or they get deleted (which would be very unfortunate)

2023-04-28 10:49 UTC, maximiliansoelch approved these changes
Apart from the issues I mentioned above, which will be fixed in a follow-up, everything works as expected 👍

2023-05-01 06:14 UTC, merged