`Exam mode`: Improve usability of attendance check
ls1intum/Artemis pull request #6463
Opened 2023-04-20 03:28 UTC by pellumbbaboci

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [ ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exam_mode/) as reference.
4. ...

### Review Progress

#### Performance Review
- [ ] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2023-05-02 15:20 UTC, tobias-lippert submitted a review, later dismissed
Tested in testing session on ts1. Worked as expected.

2023-05-02 15:20 UTC, sven0311 commented
If all students are signed, but one (or more) students are missing some of the other toggles it shows the Red Cross correctly in the overview, but in the "Verify attendance" view it shows that all students are checked successfully. IMO this should show that the toggle is missing

2023-05-04 13:33 UTC, TheZoker approved these changes
Tested within testing session on TS3 and works as expected!

2023-05-04 13:34 UTC, rriyaldhi submitted a review, later dismissed
Tested on TS3 during the testing session and works as expected.

2023-05-04 13:34 UTC, FelixTJDietrich approved these changes
Testing on ts3 during testing session. Everything looks good and works as expected.

2023-05-04 14:50 UTC, TheZoker requested changes

2023-05-04 14:50 UTC, TheZoker commented on src/main/webapp/i18n/de/exam.json
> +                "allStudentsCheckedPassed": "Alle Studenten wurden erfolgreich geprüft",
```suggestion
                "allStudentsCheckedPassed": "Alle Studenten wurden erfolgreich überprüft",
```

2023-05-04 14:51 UTC, TheZoker submitted a review, later dismissed

2023-05-04 14:51 UTC, rriyaldhi approved these changes
Reapprove after translation

2023-05-04 16:30 UTC, danielbode reviewed
We are required to use gender neutral "Studierende" instead of "Studenten".

2023-05-04 17:03 UTC, TheZoker approved these changes

2023-05-04 17:26 UTC, rriyaldhi approved these changes

2023-05-05 06:47 UTC, FelixTJDietrich approved these changes

2023-05-07 19:31 UTC, merged