`development`: Remove flake detection
ls1intum/Artemis pull request #6488
Opened 2023-04-26 14:18 UTC by heddendorp

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context

As the flake detection leads to security incidents every now and then and is not actively used in the development workflow, this PR removes it and related scripts.

2023-04-27 23:37 UTC, TheZoker submitted a review, later dismissed

2023-04-28 08:33 UTC, 4ludwig4 requested changes
Looks fine in general, I just might have found one file which isn't necessary anymore:

The file `docker/cypress/cypress.Dockerfile` is not used anywhere else after your changes in the current develop, so it can be deleted.
When I searched for this, I also found that file occurring in the `cypress.rst`, so maybe also recheck those for old commits from you and clean it up.

2023-04-28 08:38 UTC, 4ludwig4 commented
Another thing which shouldn't be forgotten when removing the flakiness tests in the repo here is the manual deactivation/deletion/filing of its bamboo plan. If any action is necessary just get in contact with me, Florian, Matthias, ... if you don't have access.

2023-05-02 06:58 UTC, TheZoker approved these changes

2023-05-03 09:30 UTC, TheZoker approved these changes

2023-05-04 09:40 UTC, 4ludwig4 approved these changes

2023-05-06 19:43 UTC, merged