`Programming exercises`: Move participation loading to for-dashboard
ls1intum/Artemis pull request #6489
Opened 2023-04-26 16:19 UTC by JohannesStoehr

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [ ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exam_mode/) as reference.
4. ...

### Review Progress

#### Performance Review
- [ ] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2023-04-26 16:52 UTC, bassner commented on src/main/webapp/app/overview/course-exercises/course-exercise-row.component.ts
> +            this.gradedStudentParticipation = this.participationService.getSpecificStudentParticipation(this.exercise.studentParticipations, false);
Caused unused import of HttpResponse that was previously used here

2023-04-27 15:44 UTC, TimOrtel submitted a review, later dismissed
The code looks good to me.

2023-05-03 15:11 UTC, MaximilianAnzinger requested changes

2023-05-04 06:38 UTC, MaximilianAnzinger approved these changes
Code LGTM
Manual LGTM

2023-05-04 10:43 UTC, YeetTheFirst21 approved these changes
Tested on TS2, there seems to be no details call when results are expanded or on any quiz and modelling exercise.

Only on programming exercises, a details call is given when the buildlog is requested which seems like intended to me:

![Screenshot 2023-05-04 124057](https://user-images.githubusercontent.com/80704436/236182198-4c4ad482-5ba7-4a7d-bfd6-6569e780cfdd.png)

2023-05-04 22:15 UTC, pellumbbaboci submitted a review, later dismissed
Manual: Tested on ts1 and its working as expected

2023-05-05 10:35 UTC, YeetTheFirst21 submitted a review, later dismissed
Tested again on TS1, all seems to be working including the new test cases

![Screenshot 2023-05-05 123451](https://user-images.githubusercontent.com/80704436/236436228-2e44fa05-0121-4063-96ae-6111b44eadd0.png)

2023-05-05 16:55 UTC, MaximilianAnzinger submitted a review, later dismissed
Tested the newly added steps (4-7) on local Atlassian setup. LGTM 👍

2023-05-08 15:08 UTC, Hialus approved these changes
Tested in testing session on TS1.
Code also looks good to me 👍🏻

2023-05-08 15:11 UTC, DominikRemo approved these changes
Tested in testing session on ts1. Works for me 👍

2023-05-08 15:12 UTC, Hialus approved these changes

2023-05-08 15:12 UTC, pellumbbaboci approved these changes
Tested during testing session on ts1 and works as expected

2023-05-08 15:14 UTC, tobias-lippert approved these changes
Tested in testing session on ts1. Nothing seems to be broken and the details endpoint is not called when the exercise row is extended

2023-05-08 15:14 UTC, pal03377 approved these changes
tested on ts1, works as expected

2023-05-09 19:33 UTC, krusche commented on src/main/java/de/tum/in/www1/artemis/repository/StudentParticipationRepository.java
> +            @Param("includeTestRuns") boolean includeTestRuns);
I suggest we work on this in a follow up

2023-05-09 19:52 UTC, merged