`General`: Fix broken refresh button
ls1intum/Artemis pull request #6490
Opened 2023-04-26 17:56 UTC by pal03377

### Checklist
#### General

- [X] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [X] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [X] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [X] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).

### Motivation and Context

@krusche pointed out an issue with the refresh button on course pages: Pressing the refresh button didn't trigger a request to the server and just caused the loading spinner to spin forever.

### Description

My investigation showed that the issue was in #6318, which changed the way courses are loaded on the client: 
Previously, the request to `findOneForDashboard` was directly consumed, because it was `.subscribe`d to. The change was to use a `.pipe` instead for simpler error handling. This however also meant that the actual course result would only be fetched after the `loadCourse` result was consumed = subscribed to. This was not the case for the refresh function.

This PR adds an artificial `subscribe` to the generated observable to change the behavior back again and fix the course refresh. It also adds a test so that this issue won't happen in the future anymore.

### Steps for Testing

Prerequisites:
- 1 Student
- 1 Instructor
- 1 Course

1. Log in to Artemis
2. Navigate to the course
3. Click "refresh". Verify that the course is refreshed and not loading forever.
4. Modify the course in some way as the instructor (e.g. change the title).
5. Verify that the refresh triggers the change.
6. Go to #6318 and verify that the testing steps there are unaffected.

### Review Progress

#### Performance Review
- [X] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

After clicking "refresh":

Before, forever:
![image](https://user-images.githubusercontent.com/9006596/234660756-2a8ddc02-f9e3-4f5a-ba7e-78dc4aad7381.png)

Now, after some short waiting time:
![screenshot-2023-04-26_001261](https://user-images.githubusercontent.com/9006596/234660858-9b6148c5-9e2e-4984-8e19-e66e6df64544.png)
(refresh finished)

2023-04-26 20:52 UTC, YeetTheFirst21 submitted a review, later dismissed
Tested on TS2, also checked all test cases on the previous pr and all seems to be working as expected. See the screenshots attached below for the given errors and refresh working through network tab and visually.

![Screenshot 2023-04-26 224309](https://user-images.githubusercontent.com/80704436/234699331-518e328c-250a-4d9e-828e-afdb0dda8ef9.png)
![Screenshot 2023-04-26 224342](https://user-images.githubusercontent.com/80704436/234699339-75e29296-e52e-44a7-aa5a-3a1c027fefca.png)
![Screenshot 2023-04-26 224735](https://user-images.githubusercontent.com/80704436/234699341-b49fed46-9207-4861-a16f-7e31ac90fda1.png)
![Screenshot 2023-04-26 224812](https://user-images.githubusercontent.com/80704436/234699343-f4733f70-2236-4d4d-a8c6-46d6e88793d8.png)
![Screenshot 2023-04-26 224907](https://user-images.githubusercontent.com/80704436/234699346-e88a7e28-9adc-4368-ad83-f9b58da9d4e7.png)
![Screenshot 2023-04-26 224921](https://user-images.githubusercontent.com/80704436/234699347-15f61126-daee-48cd-bf40-1e9cbaa832ef.png)

2023-04-27 10:19 UTC, pal03377 commented
> Step 5 never happens:
> 5. Note that a confirmation dialog opens up and that dialog includes the registration confirmation message from the course settings.

Thanks for testing! This is intended behavior, as [there was no confirmation message given in the settings of that course](https://artemis-test2.artemis.in.tum.de/course-management/8695). I just tested adding one myself again and if a confirmation message is present, the dialog is indeed shown.

2023-04-27 10:20 UTC, FelixTJDietrich approved these changes
The previous issue I commented seems to be intended behaviour. Approved.

2023-04-27 10:23 UTC, pal03377 commented on src/main/webapp/app/overview/course-overview.component.ts
> +        observable.subscribe();
Good idea, thanks! I implemented it in [this commit](https://github.com/ls1intum/Artemis/pull/6490/commits/f799469abfc189c9cfbeccd1c27c393a79fde9f6).

2023-04-27 13:14 UTC, sven0311 approved these changes
Code looks good and works like expected

2023-04-27 13:14 UTC, lennart-keller approved these changes

2023-04-27 13:15 UTC, FelixTJDietrich submitted a review, later dismissed
Still works as intended on ts2. Reapproved.

2023-04-27 18:23 UTC, dearjasmina submitted a review, later dismissed
works as expected, tested on server 2

2023-04-28 12:31 UTC, bassner requested changes

2023-04-28 12:31 UTC, bassner commented on src/main/webapp/app/overview/course-overview.component.ts
> +        this.loadCourseSubscription = observable.subscribe();
If you unsubscribe in the `ngOnDestroy`, we should also check if `loadCourseSubscription` already contains a subscription from a previous refresh round, and unsubscribe from it. What do you think?

```suggestion
        this.loadCourseSubscription?.unsubscribe();
        this.loadCourseSubscription = observable.subscribe();
```

2023-04-28 15:08 UTC, FelixTJDietrich approved these changes
Changes look good to me and it still works as expected. Re-approved.

2023-04-28 15:21 UTC, JohannesStoehr approved these changes
Code looks good to me.
My comment about unsubscribing was addressed 👍

2023-04-29 10:26 UTC, merged