`Development`: Add script to generate a code coverage table automatically
ls1intum/Artemis pull request #6501
Opened 2023-04-28 15:42 UTC by FelixTJDietrich

### Checklist
#### General

- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context

Filling out the code coverage table of PRs has been very time consuming and cumbersome, especially for larger pull requests. Some automation in that regard would save lots of time and ensure that the code coverage table is complete and correct.

@Mtze requested this script to be added to the Artemis repository in the `supporting_scripts` top level directory, which as it turns out does not exist.

### Description

Added a `supporting_scripts` top level directory with a `generate_code_cov_table` subdirectory containing the python script to automatically generate a code coverage table from the Bamboo build artefacts.

The script requires you to provide Bamboo login credentials and by default compares the changed files between a selected branch head (default: checked out branch) and its base commit (branching point from `origin/develop`). Afterwards, the Bamboo build plan artefacts (default: latest build number) are crawled for each changed file and the line coverage is extracted. Finally, a table according to the PR template is created and stored in the clipboard.

Additionally, added a comment in the `PULL_REQUEST_TEMPLATE.md` hinting at the existence of this script.

### Steps for Testing

1. Follow the setup steps in the `supporting_scripts/generate_code_cov_table/README.md`
2. Example command: `python generate_code_cov_table.py --branch-name feature/programming-exercise/exercise-options-consolidation`
3. Try out different branches (both `client_tests` and `server_tests` have to pass for that branch, use `--info` for more information on how to change the Bamboo build number etc.)
4. Enable `--verbose` flag and check if skipped files and included files are correct
5. Past the table into a markdown viewer and check if it is correct

### Review Progress

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2

#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots

**Output of `python generate_code_cov_table.py --branch-name feature/programming-exercise/exercise-options-consolidation`:**
<img width="1462" alt="image" src="https://user-images.githubusercontent.com/5898705/235191216-6619c7ca-9e9a-49d0-abb5-6a0d8e54027a.png">

**Verbose flag activated:**
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/5898705/235191110-acd9c18e-e616-4148-a31a-a283c092838f.png">

**Example of a generated table:**
<img width="631" alt="image" src="https://user-images.githubusercontent.com/5898705/235191511-c3cbbe87-43ac-430b-bb3d-775b827401f3.png">

2023-04-28 22:03 UTC, pal03377 requested changes
Very cool tool + code looks mostly very good, well done! 🎉 I also tested it with on an unrelated branch to verify the functionality.

However, I think for this script to be discoverable by new developers, it should be mentioned somewhere in the Artemis documentation. This should be added to this PR. Only then it really makes sense to have it here and not be forgotten sometime in the future.

2023-04-29 07:24 UTC, FelixTJDietrich commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!--       You can use `supporting_script/generate_code_cov_table/generate_code_cov_table.py` to automatically generate one from the corresponding Bamboo build plan artefacts. -->
Maybe we can detect that automatically in the future and remove them. But I will leave it at that now

2023-04-29 07:25 UTC, FelixTJDietrich commented on supporting_scripts/generate_code_cov_table/generate_code_cov_table.py
> +    url = f"{base_url}/rest/api/latest/plan/{project_key}-{plan_key}/branch?max-results=100"
Fixed, I'm using a different endpoint now, this is no longer necessary

2023-04-29 07:26 UTC, FelixTJDietrich commented on supporting_scripts/generate_code_cov_table/generate_code_cov_table.py
> +                print(f"Skipping {file_name}")
I changed it and use the logging library now :)

2023-04-29 07:28 UTC, FelixTJDietrich commented
Thanks @pal03377 for the detailed review, as always :) I implemented all the improvements. I think for discoverability, adding it to the PR template is enough.

2023-04-29 10:48 UTC, pal03377 submitted a review, later dismissed

2023-05-06 20:45 UTC, Hialus requested changes
I tried this script out and it worked very well. Though it could use some error handling.
For example, if the tests are not done yet or if the tests failed your script currently simply throws an `IndexError: list index out of range` without any further information why it failed.

I also really don't like the fact that I have to provide my TUM credentials. At the very least you should support PATs for this. 
Though the best way would be to not use Bamboo at all. GitHub also executes the tests and records the coverage. Exporting this coverage as an artifact of the job would allow you to use this instead. This may not even require any PATs, though support for them would be nice.
This way we could then also integrate this script into the testing workflow and maybe add the option to add and update this table automatically. Though this would obviously be something for another PR.

A last point: The code currently does not adhere to [PEP-8](https://peps.python.org/pep-0008/). I think it would be important to follow this well-established style guide. E.g. There should be two empty lines before a function definition.

2023-05-07 08:23 UTC, FelixTJDietrich commented
> I tried this script out and it worked very well. Though it could use some error handling. For example, if the tests are not done yet or if the tests failed your script currently simply throws an `IndexError: list index out of range` without any further information why it failed.
> 
> I also really don't like the fact that I have to provide my TUM credentials. At the very least you should support PATs for this. Though the best way would be to not use Bamboo at all. GitHub also executes the tests and records the coverage. Exporting this coverage as an artifact of the job would allow you to use this instead. This may not even require any PATs, though support for them would be nice. This way we could then also integrate this script into the testing workflow and maybe add the option to add and update this table automatically. Though this would obviously be something for another PR.
> 
> A last point: The code currently does not adhere to [PEP-8](https://peps.python.org/pep-0008/). I think it would be important to follow this well-established style guide. E.g. There should be two empty lines before a function definition.

Thanks, I will implement the feedback. I initially tried the PAT approach, but somehow that only works for the Bamboo REST requests and not for the artifacts. For example, I can't manage to request the following url using the PAT, only user auth works for me: `https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4773-12/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.repository/ExamUserRepository.html`. With a PAT I get redirected to log in.

I also just noticed that the script only works for branches that have been checked out before. I will try to fix that.

2023-05-07 09:05 UTC, Hialus commented
> Thanks, I will implement the feedback. I initially tried the PAT approach, but somehow that only works for the Bamboo REST requests and not for the artifacts. For example, I can't manage to request the following url using the PAT, only user auth works for me: `https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4773-12/artifact/shared/Coverage-Report-Client-Tests/app/exam/manage/students/exam-students.component.ts.html`. With a PAT I get redirected to log in.

You'd probably have to use the Bamboo REST API to do this, which should also give you everything you need.

> Regarding getting the code coverage through GitHub, I tried to automate the steps that I was doing manually using Bamboo. How would you get the coverage with GitHub? I saw the `codecov.io` reports [example](https://app.codecov.io/github/ls1intum/Artemis/commit/fae94f5a2ac30888b2bf00a3aa7f0e45642d4a5a/indirect-changes), but I don't know what to do there.

If you want we can work on the GitHub side together. I could adjust the workflows and then you could simply use the GitHub REST API, which is fairly easy to use. Just write me on Slack if you want to do this 🙂

2023-05-09 16:15 UTC, FelixTJDietrich commented
I improved the error handing, PEP8 style, and better user feedback. Also `origin/*` as branch name is now supported and there is a progress bar now and clearer instructions :)

As for user auth, we sadly have to keep it, but I added a security risk note in the documentation, and you always have the option to get safely prompted for it. The reason for PAT not working is that I somehow cannot download the artifacts and have to request the generated html report without the REST API, I tried for a bit and could not figure it out. I'm using the REST API for the rest of the script though, but I thought it does not make sense to have both PAT and user auth. 

As for having it work with GitHub workflows, I would leave this to a future PR.

2023-05-11 15:55 UTC, DominikRemo approved these changes
Works well for me 🚀

2023-05-11 16:37 UTC, pal03377 approved these changes
Works well, progress bar is really cool & code looks good 💯

2023-05-19 12:33 UTC, rriyaldhi reviewed
Tested using this PR: [#6495](https://github.com/ls1intum/Artemis/pull/6495), there is 1 row that shows N/A:
<img width="710" alt="image" src="https://github.com/ls1intum/Artemis/assets/10885503/441e4b59-5838-4d2a-8ecb-96730c962612">

The other rows are correct.

2023-05-19 12:54 UTC, FelixTJDietrich commented
> Tested using this PR: [#6495](https://github.com/ls1intum/Artemis/pull/6495), there is 1 row that shows N/A: <img alt="image" width="710" src="https://user-images.githubusercontent.com/10885503/239532898-441e4b59-5838-4d2a-8ecb-96730c962612.png">
> 
> The other rows are correct.

Fixed thanks! The issue was a regex one. I'm now doing it more reliably.

2023-05-19 13:21 UTC, rriyaldhi submitted a review, later dismissed
Tested using this PR: [#6495](https://github.com/ls1intum/Artemis/pull/6495) and works as expected.

2023-05-19 13:48 UTC, laadvo submitted a review, later dismissed
Retested after the testing session, the N/A%s from before are now gone.
Before:
![image](https://github.com/ls1intum/Artemis/assets/73339358/12542e1a-cbff-46e3-9f2f-90adf2d36cfc)
Now:
![image](https://github.com/ls1intum/Artemis/assets/73339358/46748052-e52e-430d-b121-2b9da0e98474)

2023-05-19 18:03 UTC, pellumbbaboci approved these changes
Tested with different branches on Mac Pro , works perfectly 👍

2023-05-21 15:43 UTC, pal03377 submitted a review, later dismissed
Tested the script again. For deleted files, the coverage is `N/A`, which I think is ok.

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [app.constants.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4847-71/artifact/shared/Coverage-Report-Client-Tests/app/app.constants.ts.html) | 100% | ✅❌ |
| [assessment-locks.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4847-71/artifact/shared/Coverage-Report-Client-Tests/app/assessment/assessment-locks/assessment-locks.component.ts.html) | 90.32% | ✅❌ |
| [translation.config.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4847-71/artifact/shared/Coverage-Report-Client-Tests/app/core/config/translation.config.ts.html) | 100% | ✅❌ |
| [declarations.d.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4847-71/artifact/shared/Coverage-Report-Client-Tests/app/declarations.d.ts.html) | N/A% | ❌ |
| [environment.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4847-71/artifact/shared/Coverage-Report-Client-Tests/app/environments/environment.ts.html) | 100% | ✅❌ |
| [test-case-distribution-chart.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4847-71/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/manage/grading/charts/test-case-distribution-chart.component.ts.html) | 97.46% | ✅❌ |
| [navbar.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4847-71/artifact/shared/Coverage-Report-Client-Tests/app/shared/layouts/navbar/navbar.component.ts.html) | 90.87% | ✅❌ |
| [statistics-average-score-graph.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4847-71/artifact/shared/Coverage-Report-Client-Tests/app/shared/statistics-graph/statistics-average-score-graph.component.ts.html) | 94.19% | ✅❌ |



The code looks good to me except for minor comments.

2023-05-21 15:43 UTC, pal03377 commented on supporting_scripts/generate_code_cov_table/generate_code_cov_table.py
> +import re
Unused import

```suggestion
```

2023-05-21 15:43 UTC, pal03377 commented on supporting_scripts/generate_code_cov_table/generate_code_cov_table.py
> +        logging.info(f"Branch {branch_name} not found in Bamboo")
This error might be a bit misleading, e.g. if Bamboo sends a response of 500 or 503. Then you would get a "branch not found" error although the issue is another. Also, I think this should be a `logging.error` here.

2023-05-21 15:43 UTC, pal03377 commented on supporting_scripts/generate_code_cov_table/generate_code_cov_table.py
> +        logging.info(f"Code coverage report not found for {key}, please wait for the tests to finish and try again")
```suggestion
        logging.warning(f"Code coverage report not found for {key}, please wait for the tests to finish and try again")
```

2023-05-22 10:16 UTC, rriyaldhi approved these changes

2023-05-22 12:48 UTC, DominikRemo submitted a review, later dismissed
Works well for me, reapproved 🚀

2023-05-26 12:59 UTC, pal03377 approved these changes
code looks good, just 2 more minor suggestions here

2023-05-26 12:59 UTC, pal03377 commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!--       Remove rows with only trivial changed from the table. -->
*changes

2023-05-26 12:59 UTC, pal03377 commented on supporting_scripts/generate_code_cov_table/.gitignore
> +venv
Maybe also add `__pycache__` and `*.pyc` files here? Maybe also `.DS_Store`

2023-05-26 13:04 UTC, pal03377 approved these changes

2023-05-26 22:05 UTC, pal03377 submitted a review, later dismissed

2023-05-29 19:29 UTC, DominikRemo submitted a review, later dismissed

2023-05-31 11:36 UTC, Hialus requested changes
Tried it again and providing the password over the CLI doesn't work as it should:
- The help dialog says `--password PASSWORD   Bamboo password (optional, will be prompted if not provided)`
- I run `python3 generate_code_cov_table.py --username ge49juk --branch-name "bugfix/improve-consistency-check"`
- I get the error `generate_code_cov_table.py: error: the following arguments are required: --password`
- What I would expect: If `--password` is not provided I can input it in the CLI

Note: I did not set up a .env file.

2023-06-02 06:49 UTC, FelixTJDietrich commented
> Tried it again and providing the password over the CLI doesn't work as it should:
> 
> * The help dialog says `--password PASSWORD   Bamboo password (optional, will be prompted if not provided)`
> * I run `python3 generate_code_cov_table.py --username ge49juk --branch-name "bugfix/improve-consistency-check"`
> * I get the error `generate_code_cov_table.py: error: the following arguments are required: --password`
> * What I would expect: If `--password` is not provided I can input it in the CLI
> 
> Note: I did not set up a .env file.

Thanks for finding that. I tested it without .env file but forgot that I still had my password in the environment. Now it is working again :| 

Also there is a windows encoding issue with the emojis when using the default copy to clipboard option. Hopefully that is fixed now 🤞 but I cannot test it.

2023-06-02 18:01 UTC, DominikRemo approved these changes
Reapproved

2023-06-05 17:42 UTC, bassner approved these changes

2023-06-05 17:42 UTC, merged