`Programming Exercise`: improve user interface for programming exercise creation
ls1intum/Artemis pull request #6563
Opened 2023-05-10 11:58 UTC by simon-hng

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [ ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exam_mode/) as reference.
4. ...

### Review Progress

#### Performance Review
- [ ] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2023-05-13 08:41 UTC, JohannesStoehr requested changes
I don't see how the issue is addressed at all.
E.g. the language dependent settings like sequential test runs are still nowhere near the language setting itself.

The PR description is also not giving any reason to deviate from the suggested order in the issue.

2023-05-13 12:03 UTC, simon-hng commented
> I don't see how the issue is addressed at all. E.g. the language dependent settings like sequential test runs are still nowhere near the language setting itself.
> 
> The PR description is also not giving any reason to deviate from the suggested order in the issue.

Those were annotated with a question mark. Every other setting without a question mark was moved into the corresponding section. I also think those settings are okay where they are as e.g. sequential test runs should not belong to the programming language section

2023-05-13 13:35 UTC, JohannesStoehr submitted a review, later dismissed
Code changes and restructuring looks good to me.
I also agree that we should group the options logically, since most settings will sooner or later be independent on the programming language.

2023-05-14 07:37 UTC, b-fein commented
> Those were annotated with a question mark.

That was unclear by me in the issue description. I think what I wanted to say with that is that those options are checkbox ‘questions’ and can be answered yes/no;on/off. (I have no idea any more why I did it that way). Sorry for being unclear there.

---

Though, I think especially the three options

- static code analysis
- sequential test runs
- testwise coverage

should be grouped together wherever makes sense, since which ones can be active depends on the choices of the other two. As a user I’d like to see feedback in form of the implications of my choices in one of the options shown on the same page, rather than three steps later in the wizard or off-screen at the bottom of the page.
All three are additionally only available for some programming languages. Therefore, I initially grouped them into the programming language specific settings group. I also think it is unrealistic that those three options will always be possible for all languages at some point in the future (e.g. SCA or testwise coverage for assembler, VHDL?).
Of course the SCA option has grading implications, which makes it difficult to place there. To solve that it could be possible to split up the checkbox for the option itself and then the penalty for it into the two different sections.

2023-05-15 21:58 UTC, dakennguyen approved these changes
Tested on ts1, can create ex successfully both in normal and guided mode

2023-05-15 22:30 UTC, simon-hng commented
> > Those were annotated with a question mark.
> 
> That was unclear by me in the issue description. I think what I wanted to say with that is that those options are checkbox ‘questions’ and can be answered yes/no;on/off. (I have no idea any more why I did it that way). Sorry for being unclear there.
> 
> Though, I think especially the three options
> 
> * static code analysis
> * sequential test runs
> * testwise coverage
> 
> should be grouped together wherever makes sense, since which ones can be active depends on the choices of the other two. As a user I’d like to see feedback in form of the implications of my choices in one of the options shown on the same page, rather than three steps later in the wizard or off-screen at the bottom of the page. All three are additionally only available for some programming languages. Therefore, I initially grouped them into the programming language specific settings group. I also think it is unrealistic that those three options will always be possible for all languages at some point in the future (e.g. SCA or testwise coverage for assembler, VHDL?). Of course the SCA option has grading implications, which makes it difficult to place there. To solve that it could be possible to split up the checkbox for the option itself and then the penalty for it into the two different sections.

That is a really good point! I updated the PR accordingly and added those checkboxes to the grading section since this was where the static code analysis was initially.

I understand that the visibility of those settings is programming language dependent, however I think that grading is still a better place since those settings are related to tests and when they are not available for the language type, those checkboxes are hidden anyways.

I also disagree with splitting up the checkbox since this adds a lot of complexity for users and the code alike.

What do you think about the solution proposed in the screenshots? Although not perfect, I think this is the best we can do right now

2023-05-16 15:24 UTC, b-fein commented
> I understand that the visibility of those settings is programming language dependent, however I think that grading is still a better place since those settings are related to tests and when they are not available for the language type, those checkboxes are hidden anyways.
> What do you think about the solution proposed in the screenshots?

Looks good, thank you! :+1:

2023-05-17 02:44 UTC, krusche commented
I don't agree to some changes shown in the screenshots. The preview for repos and build plans is directly influenced by the short name and should stay just below it so that instructors immediately see which names would be created based on changes in the short name.

2023-05-17 02:50 UTC, krusche commented
I suggest we have a short meeting and discuss how we want to arrange the options

2023-06-10 12:03 UTC, closed without merging

2023-06-15 08:00 UTC, simon-hng commented
- [ ] Move `Enable SCA, Sequential Test Runs and Record Testwise Coverage` into `Programming Language`
- [ ] Split grading into checkbox and grading settings, keep checkbox where is and  and move penalty into grading
- [ ] Move `Should this exercise be included in the course score calculation` to the top including points and bonus points.
- [ ] Rename `Difficulty` into `Mode`
- [ ] Move `Allow Offline IDE`, `Allow Online Editor` into `Mode`
- [ ] Rename `Mode` setting into `Participation`
- [ ] Move `Submission policy`
- [ ] Move `Assessment Instructions` into grading