Feature/iris websocket service
ls1intum/Artemis pull request #6575
Opened 2023-05-13 17:29 UTC by SabrinaGlatz

### Checklist
#### General

- [x ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x ] I documented the Java code using JavaDoc style.

### Motivation and Context
 A service is needed to send an IrisMessage to the client over the websocket.
 

### Description
 
-Added a service that can send an IrisMessage to the client over the websocket.
-Added a unit test to test this service

### Steps for Testing

### Review Progress

#### Performance Review
- [ ] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ x] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage
 100%
 100%

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| IrisWebsocketService.java | 100% | ✅                           |

2023-05-14 16:20 UTC, SolizerCodes approved these changes
Reviewed the code. Other classes utilizing websocket do it equally, so LGTM.

2023-05-14 23:46 UTC, Hialus requested changes
Thanks for implementing this! 🚀 
Theres some small improvements that you can do, but the code is already looking pretty good!

2023-05-14 23:46 UTC, Hialus commented on src/main/java/de/tum/in/www1/artemis/service/iris/IrisWebsocketService.java
> +    private static final Logger log = LoggerFactory.getLogger(IrisWebsocketService.class);
Since you are not using the logger here, you should remove it.

2023-05-14 23:46 UTC, Hialus commented on src/main/java/de/tum/in/www1/artemis/service/iris/IrisWebsocketService.java
> +
There usually is not space between JavaDoc comments and their target.
```suggestion
```

2023-05-14 23:46 UTC, Hialus commented on src/main/java/de/tum/in/www1/artemis/service/iris/IrisWebsocketService.java
> +
There usually is not space between JavaDoc comments and their target.
```suggestion
```

2023-05-14 23:46 UTC, Hialus commented on src/test/java/de/tum/in/www1/artemis/iris/IrisWebsocketTest.java
> +        database.addUsers(TEST_PREFIX, 2, 0, 0, 0);
Do you actually need two student users here? I only see one being used.

2023-05-15 09:02 UTC, Hialus approved these changes
Looks good now 👍🏻

2023-05-15 17:13 UTC, RY997 approved these changes
Run the tests locally and looked at the code, LGTM

2023-05-15 19:13 UTC, SolizerCodes approved these changes

2023-05-16 08:28 UTC, merged