`General`: Improve layout of exercise management overview
ls1intum/Artemis pull request #6599
Opened 2023-05-17 17:23 UTC by JohannesStoehr

### Checklist
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Improve the layout of the exercise manage over view to use the space more efficiently.

### Description

The course header is now even shorter still including longer descriptions by reducing font size of the description.
Move headlines and create exercise buttons in the exercise overview (see screenshot)

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student

1. Log in to Artemis
2. Navigate to Course Administration
3. Check that the course header looks good with different screen sizes, descriptions lengths and with and without a course icon.
4. Check that the exercise management overview for the instructor looks good and displays all relevant information
5. Check that creating a programming, quiz and modeling/text/fileupload (one of the three) still works

### Review Progress

#### Performance Review
- [ ] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

![image](https://github.com/ls1intum/Artemis/assets/38322605/6b40be49-9a8f-4e8d-bab8-dd01281b98a7)

2023-05-19 10:07 UTC, JohannesStoehr commented
> Tested on ts1. Everything looks good with/without picture and with long/short description. Creating and importing exercises also works.

Thanks for testing!

> I had one issue: When completely deleting the course description, the header does not update until you exit course administration and enter the course again. On the other hand, when changing the course description, the update is shown immediately.

This is unrelated to this PR and is also present on develop. So it should not hinder merging this PR

2023-05-19 22:14 UTC, SolizerCodes submitted a review, later dismissed

2023-05-21 12:50 UTC, eceeeren approved these changes
Tested on ts2. The issue that @SolizerCodes mentioned will be ignored. Everything else works as expected.

2023-05-21 13:11 UTC, fschoenberger requested changes
Deployed to TS1. When logging in as instructor or student I get many internal server errors.

2023-05-22 13:09 UTC, JohannesStoehr commented on src/main/webapp/app/exercises/programming/manage/programming-exercise.component.html
> +                        <span *ngIf="programmingExercise.testRepositoryUrl"><a href="{{ programmingExercise.testRepositoryUrl }}" target="_blank">Test</a></span>
This only links to our own repositories and is fine

2023-05-22 19:55 UTC, RY997 submitted a review, later dismissed
Tested on ts2, worked as expected

2023-05-23 08:27 UTC, SabrinaGlatz submitted a review, later dismissed
Tested on TS1. Works as expected.

2023-05-23 10:46 UTC, SolizerCodes submitted a review, later dismissed

2023-05-23 10:47 UTC, dakennguyen requested changes
tested on ts2, the layout is good, but the server responds with 500 when I try to update a long title. Could you pls confirm if it's relevant?

2023-05-23 17:46 UTC, greekgeek1 approved these changes
Tested on ts3. Works as expected. Could not recreate the error observed by dakennguyen.

2023-05-23 21:50 UTC, dakennguyen submitted a review, later dismissed
> tested on ts2, the layout is good, but the server responds with 500 when I try to update a long title. Could you pls confirm if it's relevant?

It works now on ts1. I think it was because of the internal server error that we have on develop branch

2023-05-25 11:36 UTC, MaximilianAnzinger submitted a review, later dismissed
Code looks good to me.

The `Potentially unsafe external link` Warnings seem to be insignificant since the links are internal.

2023-05-25 17:50 UTC, bassner commented
@JohannesStoehr We have some conflicts in this PR

2023-05-27 10:33 UTC, MaximilianAnzinger approved these changes
Code changes look good to me

2023-05-29 18:27 UTC, tobias-lippert approved these changes
Tested on ts2. 
Course header and course management overview look both good (with and without a course icon)
Creating a text exercise is still possible.

2023-05-29 22:34 UTC, eceeeren approved these changes
Tested on TS2, works as expected.
However it still gives an Internal Server Error when adding a very long title, this is not related to this PR right?

2023-05-30 07:17 UTC, asliayk approved these changes
tested on ts1, course header and exercise management layouts look as expected with an icon or without an icon. I could also create a programming exercise.

2023-06-11 10:30 UTC, merged