Documentation: Android Application
ls1intum/Artemis pull request #6610
Opened 2023-05-20 11:08 UTC by TimOrtel

In this PR I added documentation on the usage of the Artemis Android Application. It also lays foundation for the Documentation of the iOS application.

2023-05-22 14:50 UTC, tobias-lippert reviewed
just some small comments

2023-05-22 14:50 UTC, tobias-lippert commented on docs/user/native-applications.rst
> +    #. View exercise details and problem state
I think this should be problem statement instead of problem state

2023-05-22 14:50 UTC, tobias-lippert commented on docs/user/native-applications.rst
> +Users may receive push notifications on their Android clients. When first logging in into an Artemis instance, users will be asked if they want to receive push notifications on that device.
logging in to

2023-05-23 11:00 UTC, sven0311 requested changes
Looks good to me except Tobias remarks and one minor remark 👍

2023-05-23 11:41 UTC, DemjenDavid submitted a review, later dismissed
I think it looks great, the "log in to" is the only thing to note

2023-05-26 08:19 UTC, sven0311 approved these changes

2023-05-26 10:07 UTC, tobias-lippert approved these changes
LGTM

2023-05-30 12:33 UTC, maximiliansoelch commented on docs/user/native-applications.rst
> +The mobile applications have been designed to be compatible with all Artemis instances. Therefore, users of all Artemis instances can use the mobile application provided by us. Nevertheless, it is po
```suggestion
The mobile applications have been designed to be compatible with all Artemis instances. Therefore, users of all Artemis instances can use the mobile application provided by us. Nevertheless, it is possible to fork our repositories and release your own versions of the native applications.
```

2023-05-30 12:33 UTC, maximiliansoelch commented on docs/user/native-applications.rst
> +Please report any issues on the `GitHub repository <https://github.com/ls1intum/artemis-android>`_.
```suggestion
Please report any issues on the `GitHub repository <https://github.com/ls1intum/artemis-android/issues>`_.
```
```suggestion
Please report any issues on the `GitHub repository <https://github.com/ls1intum/artemis-android>`_.
```

2023-05-30 12:33 UTC, maximiliansoelch commented on docs/user/native-applications.rst
> +Then, enter the url of the server as you would enter it into the browser:
```suggestion
Then, enter the URL of the server as you would enter it into the browser:
```

2023-05-30 12:33 UTC, maximiliansoelch commented on docs/user/native-applications.rst
> +If the client could connect successfully to Artemis, the "Set custom instance" button will be enabled.
```suggestion
The "Set custom instance" button will be enabled if the client could connect successfully to Artemis.
```

2023-05-30 12:33 UTC, maximiliansoelch commented on docs/user/native-applications.rst
> +In this screen, users can choose which notification types to receive as push notifications, and can enable/disable push notifications for this device.
```suggestion
In this screen, users can enable/disable push notifications for this device and also choose which notification types they want to receive.
```

2023-06-01 18:33 UTC, merged