feature/iris new message notification
ls1intum/Artemis pull request #6646
Opened 2023-05-30 22:15 UTC by dakennguyen

- Add mock endpoints and domain models
- Adjust JavaDoc
- Chatbot module is created & chatbot button is added
- Dialog box to accept the chat is added
- Dialog box buttons style is changed
- Chatbot module & components moved into exercise module
- Iris: Add database changelog and integration tests (#6537)
- add basic iris websocket service for client and server
- chores: fix a method name
- chores: update after receiving feedback
- added session.service.ts
- renamed models & services
- PCIL23UX-17: Create model&store
- PCIL23UX-17: Make some messages readonly, add tests
- PCIL23UX-17: Make tests work, update store and model
- PCIL23UX-17: extend a test, close stream on store destruction
- PCIL23UX-17: satisfy eslint
- PCIL23UX-17: simplify store
- PCIL23UX-17: Reintroduce subscribable actions
- PCIL23UX-17: refactoring
- PCIL23UX-16: Rebase store on websockets & tests
- PCIL23UX-17, PCIL23UX-16: rebase on new commits
- widget added
- add the test for http-message.service.ts
- add the test for session.service.ts
- Small changes in the chatbot layout
- Maximize and minimize icons are added
- CloseChat function is created for the icon
- Message sending is triggered by pressing "Enter"
- Chat input padding is fixed
- Accidental commit fix
- prettier fix
- PCIL23UX-16: refactoring
- i18n added
- Missing i18n fields are fixed
- Unnecessary comment deleted & variable format fix
- Iris: Add IrisWebsocketService (#6575)
- remove IrisWebsocketService.java
- button bug and the position of the widget fixed
- tooltip & refactoring
- first name of the user added
- widget auto-scroll added
- auto-close widget bug fixed
- reverse commit
- Dark theme support is added for chatbot
- minor updates
- minor updates
- backdrop update
- Chatbot design fix
- bug fixed
- PCIL23UX-17, PCIL23UX-16: SessionId handling, refactorings
- docs&remove wrong init
- PCIL23UX-18: fetch session id on page loading
- Chatbot made available only for programming
- Iris: Add IrisModel interface and IrisGPT3_5Service (#6536)
- refactoring
- Data sharing warning is added
- refactoring
- Implement onSend function for iris submit button
- WIP
- SETUP
- refactoring
- PR comments
- refactoring
- Handle multiple contents
- Revert "SETUP"
- Chatbot translations moved to another file
- Integrate with the store
- Add isLoading to store
- Chatbot module is created & chatbot button is added
- Dialog box to accept the chat is added
- Dialog box buttons style is changed
- Chatbot module & components moved into exercise module
- widget added
- rebase
- Maximize and minimize icons are added
- CloseChat function is created for the icon
- Message sending is triggered by pressing "Enter"
- Chat input padding is fixed
- prettier fix
- i18n added
- button bug and the position of the widget fixed
- Missing i18n fields are fixed
- Unnecessary comment deleted & variable format fix
- tooltip & refactoring
- first name of the user added
- widget auto-scroll added
- auto-close widget bug fixed
- reverse commit
- minor updates
- Dark theme support is added for chatbot
- minor updates
- backdrop update
- Chatbot design fix
- Chatbot made available only for programming
- bug fixed
- refactoring
- refactoring
- Data sharing warning is added
- refactoring
- refactoring
- Chatbot translations moved to another file
- close button feature & design updates
- prettier fix
- Chatbot scroll strategy fix
- Iris: Add testserver for Iris (#6605)
- minor fix
- minor fix
- Handle errors
- client test added
- minor fix
- widget test added
- Subscribe to websocket when receive a new message
- SETUP
- move components to iris module
- minor refactoring + merge conflicts solved
- `Iris`: Add chat button & widget, and a pop-up window (#6584)
- `Iris`: Combine GPT 3.5, WebSocket, and database services (#6590)
- move ui components to iris package, make dispatch resolvable, integrate session retrieval
- Revert file
- Add style for client-chat-error
- test
- Fix cache error
- fix: remove duplicate slash
- Comments from the old PR
- Fetch previous messages in a session
- Render with markdown syntax for iris messages
- Render unread message indicator
- Store number of new messages on state
- SETUP

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [ ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exam_mode/) as reference.
4. ...

### Review Progress

#### Performance Review
- [ ] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2023-06-06 10:40 UTC, eceeeren submitted a review, later dismissed
Tested on TS9, works fine!

2023-06-06 10:49 UTC, asliayk approved these changes
tested on ts9, worked as expected

2023-06-06 16:36 UTC, JohannesStoehr requested changes
Code looks good, but you missed one import:

2023-06-06 16:36 UTC, JohannesStoehr commented on src/test/javascript/spec/component/iris/ui/exercise-chatbot.component.spec.ts
> -                afterClosed: jest.fn().mockReturnValue(of('true')),
Unused import because of this

2023-06-12 14:50 UTC, DemjenDavid submitted a review, later dismissed
Tested on ts9 on 2 browsers

2023-06-12 16:52 UTC, RY997 submitted a review, later dismissed
Worked as expected. For me it would be better to adjust the upper and lower padding/margin when displaying "UNREAD MESSAGE".
![image](https://github.com/ls1intum/Artemis/assets/60965100/4a8cf46a-600e-49e5-9bc7-114ce615c02c)

2023-06-13 09:11 UTC, greekgeek1 submitted a review, later dismissed
Tested on ts9. Works as expencted

2023-06-13 12:38 UTC, SabrinaGlatz approved these changes
tested on ts9. It works as expected, but I have I have one small  comment: 
I left the page while iris answered my question. When I returned, I didn't see the indicator anymore. Could be added, but I'm not sure if it's necessary.

2023-06-13 19:31 UTC, dakennguyen commented on src/test/javascript/spec/component/iris/ui/exercise-chatbot.component.spec.ts
> -                afterClosed: jest.fn().mockReturnValue(of('true')),
thank you! that was a good catch!

2023-06-13 22:34 UTC, asliayk approved these changes
reapproved

2023-06-13 23:07 UTC, MichaelOwenDyer approved these changes

2023-06-14 09:18 UTC, undernagruzez approved these changes
LGTM

2023-06-15 16:04 UTC, RY997 approved these changes
Looks good!

2023-06-16 08:32 UTC, JohannesStoehr approved these changes
New code looks good to me

2023-06-16 10:25 UTC, merged