Documentation/fix manual assessment process
ls1intum/Artemis pull request #6648
Opened 2023-05-31 08:53 UTC by tunargs

### Checklist
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context
This PR adds more to the manual assessment documentation.

### Description
Manual assessment documentation now contains the following headlines:
- Assessment Dashboard
- Structured Grading Criteria
- Integrated Training Process
- Double-blind Grading
- Grading Leaderboard

Also, its page is on the top level in the documentation (not hidden below the exercises section).

### Steps for Testing
1. Go to 
2. Carefully read the documentation and provide feedback wherever necessary
3. Make sure that everything is well documented and easy to follow

#### Manual Tests
- [ ] Test 1
- [ ] Test 2

2023-05-31 09:31 UTC, b-fein requested changes

2023-05-31 09:48 UTC, tunargs commented on docs/user/assessment/double_blind.png
@krusche shared it on Slack. Possibly he knows better.

2023-05-31 09:54 UTC, MaximilianAnzinger requested changes
I'm missing information for students where to find the Complain-Button and for Instructors/Tutors where I can access and reevaluate those.

Optional:
Would it make sense to include Exercise Dashboards and the Editor when assessing Programming Exercises?
I think that would be a great addition for tutors.

2023-05-31 10:34 UTC, terlan98 reviewed
Looks good overall 👍 

One small addition could be to mention the locking logic (once a tutor starts assessing a submission, the system locks it and it can be unlocked by canceling  the assessment)

2023-06-06 06:14 UTC, terlan98 commented on docs/user/assessment.rst
> +   Upon evaluation, the reviewer puts a "lock" on the complaint disabling inconsistency and ambiguity, which expires in 24 hours.
This is correct but locks are also put when there's no complaint. If the tutor starts assessing any submission (without complaint) it gets locked and as far as I know the lock is not released until the tutor cancels or submits the assessment. I think this information should also be mentioned somewhere.

2023-06-06 11:12 UTC, DemjenDavid requested changes
"It shows the assessment progress of each exercise by showing the state of the exercise" - shows and showing does not sound good
"To ensure consistency, fairness, and transparency and simplify the grading process" - and and sounds weird, and the commas are not consistent. I would say "To ensure consistency, fairness, transparency, and to simplify the grading process" or replace the and with "as well as to"
"Compared to the complaints" should be "Unlike complaints"

2023-06-06 12:59 UTC, fschoenberger submitted a review, later dismissed

2023-06-06 16:41 UTC, terlan98 submitted a review, later dismissed
Thanks for addressing my comment

2023-06-06 16:44 UTC, tunargs commented
> Thanks for addressing my comment

Thanks too for your comments ☺️

2023-06-06 16:45 UTC, tunargs commented
> The guide for the Exercise Dashboard / Assessment is perfect. Everything you didn't mention is pretty clear/intuitive/self-explanatory I think. Thank you for adding this.
> I'll recheck once you have integrated the suggestions made by others 👍

Great thanks 😊

2023-06-06 18:48 UTC, MaximilianAnzinger submitted a review, later dismissed
Thx for including my suggestions! 👍

2023-06-12 14:18 UTC, DemjenDavid approved these changes

2023-06-13 08:54 UTC, greekgeek1 commented on docs/user/assessment.rst
Looks good! Just a few small comments:
- Line 29: work,
- Line 38: given each ...
- Line 49: fairness, and transparency ...
- Line 64: deadline for ... ; identities; instead of "to the identity of each other" maybe "to each other's identities"
- Line 164: exercises

2023-06-13 08:55 UTC, greekgeek1 submitted a review, later dismissed
The documentation looks good. Left some small comments for assessment.rst

2023-06-13 13:40 UTC, fschoenberger approved these changes

2023-06-15 19:22 UTC, krusche approved these changes
Thanks. This is a good first iteration that we can further improve in a follow up PR

2023-06-15 19:22 UTC, merged