`Assessment`: Fix sorting in exercise scores table
ls1intum/Artemis pull request #6673
Opened 2023-06-06 16:30 UTC by JohannesStoehr

### Checklist
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context

Fix sorting in exercise scores table and make the sorting function more resilient for the future.

### Description

The sorting function was not able to handle potential additions of optional chaining and array accesses using `[0]` in the string. This is now handled correctly, fixing the sorting of some columns in the exercise scores table.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Programming Exercise with some submissions

1. Log in to Artemis
2. Navigate to the exercise scores table
3. Check that sorting each column works as expected

### Review Progress

#### Performance Review
- [x] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

2023-06-07 02:13 UTC, SolizerCodes approved these changes
Sorting all the different fields works on ts5

2023-06-07 07:10 UTC, DominikRemo requested changes
Tested on ts2 and it works well.

However, your Client Tests fail to compile:
`Error: src/test/javascript/spec/service/sort.service.spec.ts(46,9): error TS2322: Type 'undefined' is not assignable to type '{ i: number; }[]'.`

2023-06-07 11:49 UTC, DominikRemo approved these changes
Thank you for fixing the client test

2023-06-08 05:53 UTC, b-fein approved these changes

2023-06-08 05:53 UTC, b-fein commented on src/main/webapp/app/shared/service/sort.service.ts
> +        // Get rid of all optional chainings as they are handled down below. After that split the path into all array and attribute accesses
```suggestion
        // Get rid of all optional chainings as they are handled down below. After that split the path into all array and attribute accesses
        // Example: path 'some?.path[0].x' will be split into pathArray ['some', 'path', '0', 'x']
```
Small example makes it easy to understand what the overall intention of the replacements and splitting is.

2023-06-08 09:59 UTC, terlan98 submitted a review, later dismissed
Tested on TS2. Works as expected 👍 
Code LGTM

2023-06-09 06:07 UTC, b-fein approved these changes
Code looks good

2023-06-09 06:10 UTC, terlan98 approved these changes
Reapproved

2023-06-09 08:54 UTC, sven0311 approved these changes
Tested on Ts1. Sorting works as expected

2023-06-09 10:05 UTC, DominikRemo approved these changes
Reapproved

2023-06-10 04:08 UTC, SolizerCodes approved these changes
Reapprove

2023-06-10 13:43 UTC, undernagruzez approved these changes
Works as expected, LGTM

2023-06-12 21:09 UTC, merged