add initial docu outline
ls1intum/Artemis pull request #6685
Opened 2023-06-07 20:31 UTC by sven0311

### Checklist
#### General

- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [ ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

This PR adds documentation on how to use the [Exam Participation Checker iPad application](https://github.com/ls1intum/ArtemisExamChecker)

### Description

This PR only adds documentation and does not touch code at all.

### Steps for Testing

1. Take a look at the code documentation.
2. Inspect the Exam -> Exam Participation Checker page and read the documentation carefully

### Review Progress

#### Code Review
- [ ] Docu Review 1
- [ ] Docu Review 2

2023-06-08 11:33 UTC, Strohgelaender commented
We usually want to use "real" names like these in our documentation, not "Artemis Test User": 
![grafik](https://github.com/ls1intum/Artemis/assets/26540346/96f403ae-01fc-4dad-9187-598a197072ca)

2023-06-08 13:34 UTC, pellumbbaboci submitted a review, later dismissed
Documentation looks good to me, however if you decide to change the user names, the suggestion from @Strohgelaender then maybe you can also change the exam name from `Sven's Test Exam` to maybe `Final Test Exam`

2023-06-08 16:27 UTC, terlan98 requested changes
Found a typo. The rest looks good.

2023-06-08 16:27 UTC, terlan98 commented on docs/user/exams/instructors_guide.rst
> +    Seats and rooms can currenlty only be assigned via the bulk import of students, by defining the seat and room in the ``CSV`` file.
```suggestion
    Seats and rooms can currently only be assigned via the bulk import of students, by defining the seat and room in the ``CSV`` file.
```

2023-06-09 06:33 UTC, b-fein requested changes
The detailed documentation for the app itself looks good. I think, however, that the documentation needs to be embedded into some additional high-level context so that people who have never heard about the app can understand what the details mean.

2023-06-09 06:33 UTC, b-fein commented on docs/user/exams/exam_participation_checker.rst
> +
I think the documentation needs some kind of abstract paragraph at the start. Right now the first thing the documentation tells me is to look somewhere else. When someone has never heard of this _thing_ before: Why is telling me to go to exam creation? What is even? What does it do?
From the documentation afterwards it is clear that it is an app (only for Apple devices has to be inferred from the link; only iPad?). Then comes a list of detailed description of specific functions of the app. It is not clear, however, what the high-level goal is those try to achieve.

Just two/three sentences would probably be enough:
- what is it? → it is an iPad app that connects to Artemis
- high-level: what does it do? → instructors can use it to check the participants during a physical exam

2023-06-09 06:33 UTC, b-fein commented on docs/user/exams/instructors_guide.rst
> +    To upload the images each student needs to have a matriculation number assigned. This is used to match the image with the according student.
This whole section is only really necessary when using the app. Therefore, I’d replace this new section with a note something like:

```rst
..note::
    Artemis also supports validating participants signatures for in-person exams.
    For more information please see :ref:`Exam Participation Checker <exam_participation_checker>`.
```

The remaining information I’d move into a new ‘Requirements’ section on the app documentation page. That way all information necessary to use the app (except base-exam setup, which is already linked to) is available on a single page.

2023-06-12 19:55 UTC, terlan98 submitted a review, later dismissed
LGTM 👍

2023-06-13 00:55 UTC, pellumbbaboci approved these changes
documentation looks good to me 👍

2023-06-13 13:19 UTC, greekgeek1 submitted a review, later dismissed

2023-06-13 13:19 UTC, greekgeek1 commented on docs/user/exams/exam_participation_checker.rst
LGTM, small note on line 9, it would sound better as: "..., such as uploading seating arrangements and images..."

2023-06-15 20:47 UTC, merged