`Development`: Lazily load notifications when opening sidebar
ls1intum/Artemis pull request #6698
Opened 2023-06-12 15:49 UTC by JohannesStoehr

### Checklist
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context

Improve the performance by only loading the amount of unread messages and lazily load notifications once the sidebar is opened.

### Description

This PR adds a new Rest-Endpoint that returns the amount of unread notifications. This is used to display the user if they have unread messages. The actual messages are only loaded once the notification sidebar is opened.
Additionally the lastNotificationRead is now only updated if it actually affects any notification. I.e. if there are no unread messages, the date is not updated via a rest call.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students

1. Log in to Artemis
2. Do something to receive a notification. E.g. wait until a new exercise is released.
3. Check that the bell icon shows unread messages when freshly loading the page.
4. Check that you can then see the notification in the side bar.
5. Check that the notification is marked as read and you no longer have unread notifications even when reloading.

### Review Progress

#### Performance Review
- [x] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

2023-06-12 22:13 UTC, SolizerCodes approved these changes
Works on ts1 👍

2023-06-13 09:22 UTC, MichaelOwenDyer submitted a review, later dismissed
Looks good to me 👍🏽

2023-06-13 11:33 UTC, asliayk approved these changes
works well on ts2

2023-06-13 11:48 UTC, SabrinaGlatz submitted a review, later dismissed
tested on ts1, works as expected

2023-06-13 19:28 UTC, YeetTheFirst21 approved these changes
Tested on TS1,

all seems to be working as expected

2023-06-15 17:37 UTC, tobias-lippert reviewed
Code looks good, just two questions

2023-06-15 17:37 UTC, tobias-lippert commented on src/main/webapp/app/shared/notification/notification-sidebar/notification-sidebar.component.ts
> -    private loadNotifications(): void {
why is this method no longer private?

2023-06-15 17:37 UTC, tobias-lippert commented on src/test/javascript/spec/component/shared/notification/notification-sidebar.component.spec.ts
> +            tick(2000);
Do we need the 2000 in the tick?

2023-06-16 08:13 UTC, JohannesStoehr commented on src/test/javascript/spec/component/shared/notification/notification-sidebar.component.spec.ts
> +            tick(2000);
I adapted this from the test above.

2023-06-16 08:13 UTC, JohannesStoehr commented on src/main/webapp/app/shared/notification/notification-sidebar/notification-sidebar.component.ts
> -    private loadNotifications(): void {
So that it can be called in the tests

2023-06-16 11:20 UTC, MaximilianAnzinger approved these changes
Code LGTM

2023-06-17 09:42 UTC, MaximilianAnzinger reviewed
Other than my one comment recent code changes look good to me.

2023-06-17 09:42 UTC, MaximilianAnzinger commented on src/test/java/de/tum/in/www1/artemis/notification/NotificationResourceIntegrationTest.java
> +import org.junit.jupiter.api.*;
We decided to use wildcards only if there are at least 4 imports.

2023-06-17 09:54 UTC, MaximilianAnzinger submitted a review, later dismissed
Code LGTM 👍

2023-06-17 11:39 UTC, asliayk approved these changes
reapproved

2023-06-17 12:46 UTC, tobias-lippert approved these changes
Reapprove

2023-06-17 12:47 UTC, MichaelOwenDyer submitted a review, later dismissed
Reapprove

2023-06-23 08:36 UTC, Strohgelaender requested changes

2023-06-23 08:36 UTC, Strohgelaender commented on src/main/java/de/tum/in/www1/artemis/web/rest/NotificationResource.java
> +    @PreAuthorize("hasRole('USER')")
```suggestion
    @EnforceAtLeastStudent
```

2023-06-23 09:09 UTC, SolizerCodes approved these changes
Reapprove

2023-06-23 09:19 UTC, tobias-lippert submitted a review, later dismissed
Reapprove after fixing merge conflict

2023-06-23 09:35 UTC, YeetTheFirst21 approved these changes
retested on TS1,

all seems to be working as expected.

2023-06-23 11:54 UTC, MaximilianAnzinger submitted a review, later dismissed
Code LGTM 👍

2023-06-27 08:31 UTC, MaximilianAnzinger submitted a review, later dismissed
Left one comment. Other than that Code LGTM 👍

2023-06-27 08:31 UTC, MaximilianAnzinger commented on src/test/javascript/spec/component/shared/notification/notification-sidebar.component.spec.ts
> +        it('should not load notifications if some are present', () => {
```suggestion
        it('should not load notifications repeatedly', () => {
```
Maybe I misunderstand the description of this test. I would appreciate a name that is more descriptive/easier to understand.

2023-06-27 08:39 UTC, MaximilianAnzinger approved these changes
Code LGTM 👍

2023-06-27 10:38 UTC, SolizerCodes approved these changes
Still works on ts5

2023-06-27 11:26 UTC, tobias-lippert submitted a review, later dismissed
Reapprove after adding client tests

2023-06-27 19:16 UTC, YeetTheFirst21 submitted a review, later dismissed
Retested again on Ts1, all seems to be still working as expected after changes.

2023-06-30 09:32 UTC, krusche requested changes
The query for unread seems to be quite slow. We should investigate how to make it faster, e.g. by introducing additional indices.

2023-07-07 19:04 UTC, MaximilianAnzinger approved these changes
You added an empty line that usually is not in the changelog. Other than that Code looks good.

2023-07-07 19:04 UTC, MaximilianAnzinger commented on src/main/resources/config/liquibase/master.xml
> +
```suggestion
```

2023-07-09 12:53 UTC, MaximilianAnzinger approved these changes

2023-07-16 09:53 UTC, YeetTheFirst21 approved these changes
Retested on TS1,

all seems to be working as expected

2023-08-12 13:28 UTC, krusche commented
we first change how often notifications are loaded, see #7048 and then reconsider this PR

2023-08-29 12:03 UTC, JohannesStoehr commented
Solved differently in #7048

2023-08-29 12:03 UTC, closed without merging