`Development`: Reduce run-time of slow server tests
ls1intum/Artemis pull request #6703
Opened 2023-06-13 14:54 UTC by laadvo

### Checklist
#### General

- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I documented the Java code using JavaDoc style.

### Motivation and Context

### Description

**AttachmentUnitIntegrationTest**
- updateAttachmentUnit_asInstructor_shouldUpdateAttachmentUnit()
   before: 
   now: 

- createAttachmentUnit_asInstructor_shouldCreateAttachmentUnit()
  before: 
   now:  

### Review Progress

#### Performance Review
- [ ] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2023-06-15 11:57 UTC, dearjasmina approved these changes
changes look good

2023-06-15 21:07 UTC, dearjasmina submitted a review, later dismissed
reapproved :)

2023-06-16 07:53 UTC, DominikRemo requested changes
Overall, the changes look good to me 🚀
Found two small issues

2023-06-16 07:53 UTC, DominikRemo commented on src/test/java/de/tum/in/www1/artemis/lecture/CompetencyIntegrationTest.java
> +            boolean istTeamExercise) {
Typo

2023-06-16 07:53 UTC, DominikRemo commented on src/test/java/de/tum/in/www1/artemis/util/DatabaseUtilService.java
> +    public List<Course> createMultipleCoursesWithAllExercisesAndLectures(String userPrefix, int numberOfCourses, int numberOfTutorParticipations) throws Exception {
since `createCoursesWithExercisesAndLecturesAndLectureUnits` creates two courses already, `numberOfCourses` is misleading

2023-06-16 13:03 UTC, DominikRemo approved these changes

2023-06-16 13:12 UTC, merged