`Development`: Add Postgres Docker Compose Setup
ls1intum/Artemis pull request #6759
Opened 2023-06-23 14:48 UTC by 4ludwig4

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context

As we want to move towards Postgres, we already implemented a Docker container. We also add support for Docker Compose Setups to enable developers to try Postgres with Artemis quickly.

### Description

We streamlined the official naming of PostgreSQL to Postgres as this informal naming is used in the rest of the project apparently.
We added Artemis Docker Compose Setups for Postgres and updated the Docs.
Therefore we introduced a new Docker Compose section in the administrator section of the Docs.

### Steps for Testing

**Artemis Postgres Prod Setup**
1. change the permissions in your repository according to the [administrator documentation](TODO INSERT LINK) for the prod setup
2. run the Artemis Postgres Prod Setup: ``docker compose -f docker/artemis-prod-postgres.yml up``
3. check Artemis
4. shutdown Artemis Postgres Prod Setup: ``docker compose -f docker/artemis-prod-postgres.yml down`` and optionally delete the contents of ``./docker/.docker-data/artemis-postgres-data`

**Artemis Postgres Dev Setup**
1. run the Artemis Postgres Dev Setup: ``docker compose -f docker/artemis-dev-postgres.yml up``
2. check Artemis
3. shutdown and delete the volumes of Artemis Postgres Prod Setup: ``docker compose -f docker/artemis-dev-postgres.yml down -v``

Check that the other Docker Compose setups you are using still work.

### Review Progress

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

2023-06-30 09:17 UTC, TheZoker approved these changes
Changes LGTM 👍

2023-07-02 16:19 UTC, jakubriegel submitted a review, later dismissed
Code looks good 👍🏻 
Both local and dev set up work on my machine 👍🏻 

I think merge should be synchronised with #6443. Artemis was much slower than on MySQL for me, but that my be connected to arm vs x64 container.

2023-07-06 09:37 UTC, TheZoker approved these changes

2023-07-07 07:41 UTC, 4ludwig4 commented
> I think merge should be synchronised with #6443.

@jakubriegel What do you mean with "synchronized"? There shouldn't be any conflicts between the two PRs.

2023-07-07 15:52 UTC, jakubriegel commented
> #6443

Just to make sure that this change also supports arm. It is does, then nothing to be done here

2023-07-07 15:52 UTC, jakubriegel commented
> > I think merge should be synchronised with #6443.
> 
> @jakubriegel What do you mean with "synchronized"? There shouldn't be any conflicts between the two PRs.

Just to make sure that this change also supports arm. It is does, then nothing more to be done here

2023-07-12 08:23 UTC, 4ludwig4 commented
@jakubriegel @TheZoker can you please re-approve if my commit to fix the merge conflicts looks good?

2023-07-13 08:32 UTC, TheZoker approved these changes

2023-07-27 13:24 UTC, Mtze commented
Please fix the merge conflicts first ;)

2023-07-27 23:46 UTC, Hialus approved these changes
Changes look good to me.
Though there are some merge conflicts in the .env files.

2023-08-18 12:26 UTC, 4ludwig4 commented
@Mtze I solved the conflicts and also added common cypress environment settings into one common file.

@TheZoker @Hialus could you please re-review the changes?! Thanks in advance.

2023-08-19 12:29 UTC, jakubriegel requested changes
Step 2 (`docker compose -f docker/artemis-prod-postgres.yml up`) starts `artemis-app` without any port exposed, so it is impossible to reach the app from web browser. Most like some config is missing here: https://github.com/ls1intum/Artemis/pull/6759/files#diff-ba5a738c18007d79118321b9c8bf8ac4fe0d466e59605735174862c97d8bf5c5R6

2023-08-23 19:37 UTC, 4ludwig4 commented
> Step 2 (`docker compose -f docker/artemis-prod-postgres.yml up`) starts `artemis-app` without any port exposed, so it is impossible to reach the app from web browser. Most like some config is missing here: https://github.com/ls1intum/Artemis/pull/6759/files#diff-ba5a738c18007d79118321b9c8bf8ac4fe0d466e59605735174862c97d8bf5c5R6

Mhh maybe I should add in the docs that the ``prod`` setups are served via ``nginx`` on Port 80/443 and the ``dev`` setups are served without a reverse proxy on Port 8080?

Port 8080 is exposed in the inherited ``artemis.yml``.

2023-08-31 20:21 UTC, 4ludwig4 commented
Fixed the merge conflicts again.

2023-09-01 05:33 UTC, b-fein approved these changes

2023-09-01 05:33 UTC, b-fein commented on .bamboo/E2E-tests/execute.sh
> +  echo "Invalid database type. Please choose either mysql or postgres."
```suggestion
  echo "Invalid database type. Please choose either mysql or postgresql."
```
The if-condition above checks for `postgresql`.

2023-09-01 07:58 UTC, Hialus submitted a review, later dismissed
Went through the code again and it still looks good to me 🚀

2023-09-02 21:09 UTC, b-fein submitted a review, later dismissed

2023-09-02 22:10 UTC, Hialus submitted a review, later dismissed

2023-09-10 09:50 UTC, 4ludwig4 commented
Fixed the merge conflicts again.

2023-09-10 10:25 UTC, b-fein approved these changes

2023-09-10 10:57 UTC, Hialus approved these changes

2023-09-12 12:08 UTC, Mtze approved these changes

2023-09-14 08:51 UTC, merged