`Text exercises`: Remove feedback conflict badge and views
ls1intum/Artemis pull request #6769
Opened 2023-06-26 10:57 UTC by pal03377

# Database changes! Do not deploy on a normal test server.

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [X] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [X] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
#### Client
- [X] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [X] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.

### Motivation and Context

The feedback conflict/consistency feature causes high coupling between Artemis and Athena. The feature hasn't been in use in production, apparently: There are no feedback conflict entries present at all on the production servers.

Removing this feature will make the integration of Athena-New and dropping the old system much easier. We will opt for a decoupled system

### Description

Changes affecting the text exercise assessment mode:
- Remove `Feedback Conflicts` warning badge in the textblock feedback editor
- Remove Feedback Conflict Resolve page

Endpoints:
- ...

Database:
- ...

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exam_mode/) as reference.
4. ...

### Review Progress

#### Performance Review
- [X] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [X] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

**Before**: Feedback conflict warning badge (screenshot from a thesis, hard to reproduce without Athena running)
![screenshot-2023-06-26_001465](https://github.com/ls1intum/Artemis/assets/9006596/066a8400-a296-4c50-9330-8e046da6973c)
**After:** The badges never appear:
![screenshot-2023-06-26_001467](https://github.com/ls1intum/Artemis/assets/9006596/3ebd30aa-4fcc-4f29-bde7-308d481663e0)

**Before:** Feedback conflict resolve view (screenshot from a thesis, hard to reproduce without Athena running)
![screenshot-2023-06-26_001466](https://github.com/ls1intum/Artemis/assets/9006596/84e2c9fe-5e81-41fb-be69-797acdb3637e)
**After:** (removed)

2023-06-27 19:52 UTC, FelixTJDietrich submitted a review, later dismissed
Great job on cleanly removing everything related to the feature. I looked around and could not find any other remains :) The added tests also seem okay to me, I don't know how sensible it is to add more in this PR. Code LGTM, also tested on TS4 during a testing session and everything works as before. Approved!

2023-06-28 15:46 UTC, TheZoker approved these changes
Tested during testing session on TS4 and LGTM 👍

2023-06-28 19:45 UTC, simon-hng approved these changes
Tested during testing session

2023-06-30 16:55 UTC, greekgeek1 submitted a review, later dismissed
Tested on ts3, works as expected

2023-07-02 12:12 UTC, FelixTJDietrich approved these changes
Code looks good to me after resolving the merge conflicts 🎉

2023-07-02 12:14 UTC, terlan98 requested changes
The changes look good to me 👍  I also could not find any remaining feedback-conflict-related parts. 

There's just 1 unused import. It'd be nice if you could remove that.

2023-07-02 12:14 UTC, terlan98 commented on src/main/webapp/app/exercises/text/assess/text-assessment.service.ts
>  import { TextSubmission } from 'app/entities/text-submission.model';
Unused import

```suggestion
```

2023-07-02 12:32 UTC, terlan98 approved these changes
Thanks for removing the unused import 🙂  Approved

2023-07-02 12:33 UTC, FelixTJDietrich approved these changes

2023-07-02 12:33 UTC, simon-hng approved these changes

2023-07-02 12:54 UTC, TheZoker approved these changes

2023-07-03 12:23 UTC, maximiliansoelch approved these changes

2023-07-03 18:46 UTC, Strohgelaender approved these changes

2023-07-04 13:34 UTC, merged