`Development`: Move methods from UtilService to Factory
ls1intum/Artemis pull request #6818
Opened 2023-07-03 21:40 UTC by laadvo

### Checklist
#### General

- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [ ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I documented the Java code using JavaDoc style.

### Motivation and Context

When refactoring `DatabaseUtilService` some methods responsible for creating objects (with no database interractions) were put into the new UtilServices instead of Factories. This is fixed in this PR.

### Description

Mostly just methods were moved, some minor changes were made (eg. removing randomization for quiz exercises...). TODO

### Review Progress

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2

### Test Coverage

unchanged

2023-07-07 06:35 UTC, DominikRemo requested changes

2023-07-07 06:35 UTC, DominikRemo commented on src/test/java/de/tum/in/www1/artemis/exercise/programmingexercise/ProgrammingExerciseBitbucketBambooIntegrationTest.java
> +    @RepeatedTest(1000)
👀

2023-07-07 08:51 UTC, laadvo commented on src/test/java/de/tum/in/www1/artemis/exercise/programmingexercise/ProgrammingExerciseBitbucketBambooIntegrationTest.java
> +    @RepeatedTest(1000)
thanks for noticing 😅

2023-07-07 11:29 UTC, lennart-keller submitted a review, later dismissed
Code lgtm :)

2023-07-07 15:33 UTC, DominikRemo commented on src/test/java/de/tum/in/www1/artemis/exercise/programmingexercise/ProgrammingExerciseBitbucketBambooIntegrationTest.java
> +import org.junit.jupiter.api.*;
```suggestion
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
```

2023-07-07 15:34 UTC, DominikRemo approved these changes
Code LGTM

2023-07-07 16:17 UTC, DominikRemo requested changes
I was to fast with my last approval ^^"
Merging the changes from develop seems to have broken something within the tests so they fail now

2023-07-09 08:22 UTC, terlan98 reviewed
Code LGTM but the tests are failing, as mentioned by Dominik

2023-07-10 16:20 UTC, DominikRemo requested changes
Code looks good to me, left one comment

2023-07-10 16:20 UTC, DominikRemo commented on src/test/java/de/tum/in/www1/artemis/exam/ExamIntegrationTest.java
> +
Unused according to teamscale

2023-07-11 16:56 UTC, DominikRemo approved these changes
LGTM

Thanks for addressing my suggestion

2023-07-13 08:09 UTC, lennart-keller approved these changes
Recent code changes look good to me

2023-07-13 10:16 UTC, merged