Development: Utilise StudentParticipation instead of FileUploadSubmission for getting the last submission
ls1intum/Artemis pull request #6849
Opened 2023-07-07 05:24 UTC by MarkusPaulsen

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [ ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I documented the Java code using JavaDoc style.

### Motivation and Context
The parameter fileUploadSubmission is currently getting used for getting the last submission in FileUploadSubmissionService. The data of this parameter is under the control of the user, which may pose certain risks.

### Description
Instead of FileUploadSubmission fileUploadSubmission, we now use StudentParticipation participation for getting the last submission in FileUploadSubmissionService, as the data of this parameter is not under the control of the user.

### Steps for Testing
We just want to make sure that I didn't accidentally break the implementation.

Prerequisites:
- 1 Instructor
- 1 Student

Course (Instructor/Student):
1. Look at a course with course image (e.g. 6.0 Testing Session Course 1 on TS1). Alternatively, create one
2. Make sure the image gets rendered correctly

After each step, commit and see if the changes were persisted by reloading
Programming Exercise (Instructor, Student):
1. Create a programming exercise with the online editor activated.
2. Change the programming language and make sure the template problem statement gets changed. Also change the application language and then the programming language and check if the natural language changes.
3. Participate in the programming exercise/alternatively edit the solution/template in the online editor
4. Create a folder
5. Create a folder within the folder
6. Create a file within the second folder
7. Rename the file
9. Delete the file and folders
10. No issues should occur

Fileupload Exercise (Instructor, Student):
1. Create a file upload exercise with a description. Upload an image to the description
2. Start the exercise, the image should show up properly as well as the rest of the description
3. Participate in the exercise
4. Upload another file
5. View/Download the image
6. No issues should occur

Quiz Exercise (Instructor):
1. Create a Quiz Exercise with a Drag and Drop Question including Background and image drag items
2. Preview the quiz and make sure all images get rendered properly

Split Lecture PDF (Instructor):
1. Open the lecture tab and click on "Create Lecture"
4. Fill in the title and channel name
5. Check "Automatic unit processing" at the bottom
7. Select a multipage PDF to process and hit "Process units". If you use a PDF that fits the requirements, skip point 5. Otherwise, continue.
8. Add units manually, at least two and set the pages accordingly. Then hit "submit.
9. Open the lecture and download a lecture unit attachment.
11. No issues should occur

#### Exam Mode Testing

We would need to test the participation checker which requires testing it on an app. However, the changes to the two endpoints are the exact same changes I did to a few other endpoints. Meaning if one fails, all should fail.
=> I deem it unnecessary to test every single of these endpoints. They already get tested by the other endpoints.

### Review Progress

#### Performance Review
- [ ] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

2023-07-08 13:11 UTC, MaximilianAnzinger submitted a review, later dismissed
Code LGTM 👍

2023-07-08 21:32 UTC, SolizerCodes submitted a review, later dismissed
Tested on ts6, works well 👍

2023-07-09 21:45 UTC, undernagruzez submitted a review, later dismissed
Tested on ts6, works as expected

2023-07-10 13:08 UTC, RY997 approved these changes
Code LGTM

2023-07-13 16:51 UTC, dearjasmina submitted a review, later dismissed
tested on ts 3, works as expected, code looks good

2023-07-13 19:59 UTC, bassner requested changes
In my opinion we should test these changes as they are relevant for the security of the application.

2023-07-21 08:47 UTC, Strohgelaender requested changes
The server style action is currently failing, please run `spotlessApply` to fix the reported issues.

2023-07-21 08:50 UTC, Strohgelaender commented on src/main/java/de/tum/in/www1/artemis/service/FileUploadSubmissionService.java
> +                    fileService.resetOnPath(savePath);
Maybe change the method name to something like `evictCacheForPath`? By just reading the code I would have not thought that this method is used for caching-related functionality.

2023-07-26 12:14 UTC, RY997 approved these changes
Reapprove

2023-07-26 13:06 UTC, krusche approved these changes
Code looks good to me and makes sense 👍

2023-07-26 13:42 UTC, dearjasmina approved these changes
reapprove

2023-07-26 13:57 UTC, Strohgelaender approved these changes
code looks good.

2023-07-26 18:40 UTC, merged