`Development`: Rename "Athene" to "Athena"
ls1intum/Artemis pull request #6862
Opened 2023-07-08 01:09 UTC by pal03377

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [X] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
None of the checks apply, I just renamed parts of the code
#### Client
None of the checks apply, I just renamed parts of the code

### Motivation and Context

Historically, both names, "Athene" and "Athena" have been used for the semi-automatic (text) assessment system.
We want to be consistent about this. Therefore, we decided to always use the name "Athena" (same as the repository name: https://github.com/ls1intum/Athena) from now on.

As part of migrating the current connection between Artemis and Athena to the new system already found at https://github.com/ls1intum/Athena (#6861), I am also doing a renaming. This is a separate PR so that the actual integration PR will be easier to review.

### Description

I renamed every instance of code with the name "athene" in it to "athena". This includes run configurations. I will submit a PR to https://github.com/ls1intum/artemis-ansible-collection covering this as well.

The only place where the name `athene` is still used is the `de.tum.in.ase.athene` gradle package, which I don't want to rename as it will be removed in a future PR anyways. Therefore, some imports like `import de.tum.in.ase.athene.protobuf.Cluster;` are still using the old name as well.

### Steps for Testing

Unfortunately, you cannot really test the functionality of this PR, as the old Athena system is currently down.
As long as nothing breaks, this is fine, though. In a future PR, the new connection to Athena will be tested anyways and until then, everything remains as-is anyways.

Still, you can
1. Try to find remaining places to rename
2. Deploy this PR to a test server and verify that it generally works
3. Run this PR locally using the `Artemis (Server, Athena)` run configuration to verify that this still generally works as well

### Review Progress

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2

### Test Coverage

unchanged (only renaming)

2023-07-08 08:15 UTC, FelixTJDietrich submitted a review, later dismissed
I guess everything related to the `de.tum.in.ase.athene` package can't be renamed right now, you will probably change it during the integration anyways. I did not find any other changes besides the renaming and some import improvements in `AthenaServiceTest.java` (transforming a `.*` import). Also didn't find any other locations to rename, except the Apollon thingy.

Code LGTM, thanks for renaming it for consistency and maintainability!

2023-07-08 08:15 UTC, FelixTJDietrich commented on src/main/java/de/tum/in/www1/artemis/service/connectors/apollon/ApollonHealthIndicator.java
> +     * Ping Athena at /queueStatus and check if the service is available.
Should this be Apollon?

2023-07-08 12:27 UTC, julian-christl commented on src/main/java/de/tum/in/www1/artemis/service/connectors/apollon/ApollonHealthIndicator.java
> +     * Ping Athena at /queueStatus and check if the service is available.
```suggestion
     * Ping Apollon at /queueStatus and check if the service is available.
```

2023-07-08 12:45 UTC, julian-christl requested changes
I only found one more occurrence (apart from the ones mentioned in the PR description)

2023-07-08 12:45 UTC, julian-christl commented on src/test/cypress/e2e/exam/ExamAssessment.cy.ts
> +// This is a workaround for uncaught athena errors. When opening a text submission athene throws an uncaught exception, which fails the test
```suggestion
// This is a workaround for uncaught athena errors. When opening a text submission athena throws an uncaught exception, which fails the test
```

2023-07-08 16:50 UTC, FelixTJDietrich approved these changes
Code LGTM

2023-07-09 06:37 UTC, julian-christl approved these changes

2023-07-10 17:06 UTC, MichaelOwenDyer approved these changes
LGTM

2023-07-11 12:42 UTC, maximiliansoelch approved these changes

2023-07-15 06:26 UTC, krusche commented
Thanks for this contribution. I think this PR is not critical (please correct me if I'm wrong). Due to the necessary config changes, I would postpone merging this PR for another 1-2 weeks as we currently focus on other important bugfixes

2023-08-11 01:39 UTC, julian-christl approved these changes
Reapprove code

2023-08-27 03:57 UTC, pal03377 commented
This is no longer needed because all changes are included in #6861, which is `maintainer-approved`.

2023-08-27 03:57 UTC, closed without merging