`Assessment`: Fix the assess next button when no more submissions are…
ls1intum/Artemis pull request #6904
Opened 2023-07-14 14:32 UTC by Strohgelaender

… assessable

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [ ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exam_mode/) as reference.
4. ...

### Review Progress

#### Performance Review
- [ ] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2023-07-14 15:55 UTC, dearjasmina submitted a review, later dismissed
While testing the exam mode, the functionality you implemented works for all exercise types apart from modeling exercise. For a modeling exercise, my screen looks like this:
<img width="1662" alt="image" src="https://github.com/ls1intum/Artemis/assets/24391701/58251ac6-f1c8-4949-8dda-d68ec63c08f6">

2023-07-14 15:59 UTC, RY997 requested changes
For normal exercise mode, it worked for all exercise types except modeling exercise. After click "assess new submission", it shows like this.
![image](https://github.com/ls1intum/Artemis/assets/60965100/59d4b851-f343-453f-bd66-de6aa91dd118)

2023-07-14 20:08 UTC, RY997 approved these changes
The issue has been fixed. Approve!

2023-07-14 22:52 UTC, JohannesStoehr requested changes
Code looks good to me.
Can you also add a test for this behavior of returning undefined in case there is no submission?

2023-07-15 07:20 UTC, asliayk submitted a review, later dismissed
tested on ts2, works as expected

2023-07-15 14:13 UTC, JohannesStoehr approved these changes
Thanks for adding tests as well. Code approved!

2023-07-15 22:21 UTC, pal03377 requested changes
I found a few places where I would like the type definitions to be more clear. Except for those places, I'm happy with the code changes.

2023-07-15 22:21 UTC, pal03377 commented on src/main/webapp/app/exercises/file-upload/assess/file-upload-assessment.component.ts
> +                    this.submission = submission;
I think this is more clear:
```suggestion
                    this.submission = undefined;
```

This also reveals that `submission` has the wrong type: It's not `undefined`-able, but actually, its values can be `undefined`.

2023-07-15 22:21 UTC, pal03377 commented on src/main/webapp/app/exercises/file-upload/assess/file-upload-assessment.component.ts
>              next: (submission: FileUploadSubmission) => {
```suggestion
            next: (submission?: FileUploadSubmission) => {
```

2023-07-15 22:21 UTC, pal03377 commented on src/main/webapp/app/exercises/file-upload/participate/file-upload-submission.service.ts
> +                return undefined;
```suggestion
                if (!res) {
                    return undefined;
                }
                return this.submissionService.convertSubmissionFromServer(res);
```

Just a suggestion (matter of taste), I'll leave it to you

2023-07-15 22:21 UTC, pal03377 commented on src/main/webapp/app/exercises/modeling/assess/modeling-assessment-editor/modeling-assessment-editor.component.ts
> +                    this.submission = submission;
```suggestion
                    this.submission = undefined;
```

2023-07-15 22:21 UTC, pal03377 commented on src/main/webapp/app/exercises/modeling/assess/modeling-assessment-editor/modeling-assessment-editor.component.ts
>              next: (submission: ModelingSubmission) => {
```suggestion
            next: (submission?: ModelingSubmission) => {
```

2023-07-15 22:21 UTC, pal03377 commented on src/main/webapp/app/exercises/modeling/assess/modeling-assessment-editor/modeling-assessment-editor.component.ts
> +                    this.submission = submission;
```suggestion
                    this.submission = undefined;
```

2023-07-15 22:21 UTC, pal03377 commented on src/main/webapp/app/exercises/modeling/assess/modeling-assessment-editor/modeling-assessment-editor.component.ts
>              next: (submission: ModelingSubmission) => {
```suggestion
            next: (submission: ModelingSubmission | undefined) => {
```

2023-07-15 22:21 UTC, pal03377 commented on src/main/webapp/app/exercises/modeling/participate/modeling-submission.service.ts
> +                if (res) {
same suggestion as above ("guard if" instead of this)

2023-07-15 22:21 UTC, pal03377 commented on src/main/webapp/app/exercises/programming/assess/code-editor-tutor-assessment-container.component.ts
> +                                this.submission = submission;
```suggestion
                                this.submission = undefined;
```

2023-07-15 22:21 UTC, pal03377 commented on src/main/webapp/app/exercises/text/participate/text-submission.service.ts
> +                const submission = response.body;
```suggestion
                const submission = response.body;
                if (!submission) {
                    return undefined;
                }
```

2023-07-16 11:31 UTC, pal03377 approved these changes
All my previous concerns have been addressed. Good job! 🎉

2023-07-16 14:26 UTC, JohannesStoehr approved these changes
Reapprove code after Paul's review

2023-07-16 15:30 UTC, greekgeek1 approved these changes
Tested on ts3, works as expected

2023-07-17 08:53 UTC, laadvo approved these changes
tested on ts1, no more submissions to assess is shown for all types of exercises

2023-07-18 21:08 UTC, merged