`Assessment`: Improve feedback deletion confirmation alert
ls1intum/Artemis pull request #6925
Opened 2023-07-17 15:33 UTC by Strohgelaender

### Checklist
#### General
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
Deleting a feedback triggers a browser confirmation alert. We usually don't use such confirmation alerts and instead use our own delete confirmation dialog.

### Description
This PR replaces the confirmation alert with the typical delete dialog. Instead of the feedback id (which provides no value to the tutor) the detail text is shown in the confirmation alert.

### Steps for Testing
Prerequisites:
- 1 Tutor
- 1 Programming Exercise

1. Assess the submission and add feedback (inline feedback and general feedback)
2. Delete the feedback again
3. The confirmation alert looks good.

Note: Feedback for modeling elements and text blocks use a different deletion mechanism, this PR only changes general feedback and code inline feedback.

### Review Progress

#### Performance Review
- [x] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots
old: 
![grafik](https://github.com/ls1intum/Artemis/assets/26540346/4a014a3f-f87f-4cb0-9083-9e297c9a08e8)

now: 
![grafik](https://github.com/ls1intum/Artemis/assets/26540346/7a1ee831-97f4-4c95-82b8-15cebfd77086)

2023-07-17 19:00 UTC, MichaelOwenDyer approved these changes
Looks good, but I question whether it is wise to include the entire feedback text in the confirmation window... maybe just a snippet would be better?

2023-07-17 20:23 UTC, JohannesStoehr requested changes
Code looks good overall. Left one nitpick:

2023-07-17 20:23 UTC, JohannesStoehr commented on src/main/webapp/i18n/en/feedback.json
> +                "question": "Are you sure you want to delete the Feedback \"{{ text }}\"?"
```suggestion
                "question": "Are you sure you want to delete the feedback \"{{ text }}\"?"
```
I'm also thinking about adding a colon, what is your opinion?
```suggestion
                "question": "Are you sure you want to delete the feedback: \"{{ text }}\"?"
```

2023-07-18 11:36 UTC, undernagruzez approved these changes
Tested on ts5, works as expected

2023-07-19 11:26 UTC, bassner requested changes
Looks like we have a small merge conflict here

2023-07-20 10:16 UTC, JohannesStoehr submitted a review, later dismissed
Approve code

2023-07-20 15:17 UTC, RY997 submitted a review, later dismissed
Tested on ts4, worked well

2023-07-20 22:18 UTC, MaximilianAnzinger approved these changes
Code LGTM

2023-07-25 21:21 UTC, DominikRemo approved these changes
Code LGTM

2023-08-17 07:49 UTC, terlan98 requested changes
Tested on TS5. The new alert works as described. I found 2 issues:
- I found 1 indentation issue, which is also causing the client tests to fail (because to Prettier is complaining)
- I'm not sure if it's related to this PR, but when the user opens an ongoing assessment and deletes an existing feedback, the save and submit buttons do not get enabled. The user has to add a new feedback or edit an existing one to enable the buttons.

2023-08-17 07:49 UTC, terlan98 commented on src/main/webapp/app/assessment/assessment-detail/assessment-detail.component.ts
> +        private dialogErrorSource = new Subject<string>();
```suggestion
    private dialogErrorSource = new Subject<string>();
```

2023-08-22 12:28 UTC, terlan98 approved these changes
Thanks for addressing my comment. Approved 👍

2023-08-23 17:57 UTC, RY997 approved these changes
Tested on ts1, worked well. Reapprove!

2023-09-01 09:21 UTC, krusche commented
Will merge as soon as the checks are executed successfully

2023-09-03 07:23 UTC, merged