`Development`: Switch Postgres E2E Setup to Jenkins/Gitlab
ls1intum/Artemis pull request #6948
Opened 2023-07-21 00:33 UTC by TheZoker

### Checklist
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

We are currently only testing the E2E test with the Atlassian suite (bamboo, bitbucket, jira). 

### Description

This PR switches the postgres E2E plan to using Gitlab and Jenkins. It also fixes the gitlab health check and adds local user management (necessary users are created before each run). 

### Review Progress

#### Code Review
- [ ] Review 1
- [ ] Review 2

2023-07-21 13:00 UTC, Strohgelaender requested changes
This PR makes the server tests running for over one hour and probally get stuck somewhere.

2023-07-25 14:28 UTC, pal03377 submitted a review, later dismissed
Code looks good! Also, the health status of GitLab will be fixed 🎉

2023-07-25 14:28 UTC, pal03377 commented on src/test/cypress/support/users.ts
> +}
```suggestion
};
```

2023-07-25 14:28 UTC, pal03377 submitted a review, later dismissed

2023-07-25 15:29 UTC, pal03377 approved these changes

2023-07-25 16:10 UTC, tobias-lippert approved these changes
Code LGTM

2023-07-25 20:16 UTC, merged