`Exam mode`: Fix an issue when submitting complaints
ls1intum/Artemis pull request #6956
Opened 2023-07-21 15:36 UTC by Strohgelaender

### Checklist
#### General
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [ ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context
#6875 fixed a special case where complaints were not possible but missed that check on the server side.

### Description
Fix the server side of this check

### Steps for Testing
Prerequisites:
- 1 Instructor
- 2 Student
- 1 Exam

1. Edit the course to have some low complaint text limit (e.g 10 characters)
2. Submit a exam complaint which uses more than 10 characters
3. Everything should work
4. Course complains should still be limited to 10 characters.

### Review Progress

#### Performance Review
- [x] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage
TODO

2023-07-21 20:51 UTC, JohannesStoehr submitted a review, later dismissed
Code looks good to me

2023-07-21 21:03 UTC, pal03377 requested changes
I have a suggestion for you to consider about the architecture of this change as well as some minor comment improvement suggestions. 

Otherwise, everything looks good & especially the tests look really clean! 🎉

2023-07-21 21:03 UTC, pal03377 commented on src/test/java/de/tum/in/www1/artemis/assessment/AssessmentComplaintIntegrationTest.java
> +        // 26 characters, exceeds course limit but lower than 2000 --> allowed
```suggestion
        // 26 characters, exceeds course limit but lower than 2000 --> allowed for exam exercise
```

2023-07-21 21:03 UTC, pal03377 commented on src/test/java/de/tum/in/www1/artemis/assessment/AssessmentComplaintIntegrationTest.java
> +        // 2004 characters
```suggestion
        // 2004 characters (4 over the limit of 2000)
```

2023-07-21 21:03 UTC, pal03377 commented on src/main/java/de/tum/in/www1/artemis/service/ComplaintResponseService.java
> +            }
I would also be fine with how it currently implemented, but personally I would tend towards making the limit part of the exercise. What do you think?

2023-07-22 02:28 UTC, pal03377 submitted a review, later dismissed
Code looks good & the small refactoring since my last review is quite sensible 🎉

2023-07-22 12:51 UTC, terlan98 submitted a review, later dismissed
Tested on TS5 with low complaint text limit and disabled complaints. Works as expected 👍 

Found a small, non-blocking typo in the code when going through Paul's suggestions. I did not do a full code review, though.

2023-07-22 12:58 UTC, terlan98 approved these changes

2023-07-22 13:00 UTC, pal03377 approved these changes

2023-07-22 13:24 UTC, MaximilianAnzinger approved these changes
LGTM

2023-07-22 19:47 UTC, merged