`Programming exercises`: Allow editing submission policy on creating and importing exercises
ls1intum/Artemis pull request #7008
Opened 2023-07-30 10:07 UTC by basak-akan

### Checklist
#### General

- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

Editing submission policy should be enabled while creating and importing new programming exercises. However, the submission policy cannot be edited on the edit programming exercise page, it is only possible over the grading page. 

### Description

Submission policy editing is enabled for creating and importing exercises (enabled for not in edit mode).
An indicator that the policy can be changed on the grading page with a link is added.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Create a programming exercise 
2. Verify Submission Policy editing is enabled
3. Navigate to edit programming exercise
4. Verify submission policy is disabled
5. Verify an indicator with a link is shown
6. Verify link navigates to the grading page of the exercise edit policy tab

### Review Progress

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2023-08-01 13:56 UTC, JohannesStoehr requested changes

2023-08-01 13:56 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseImportBasicService.java
> +        importSubmissionPolicy(importedExercise);
Why is the order relevant here?
Maybe leave a comment in the code explaining it

2023-08-01 13:56 UTC, JohannesStoehr commented on src/main/webapp/i18n/de/programmingExercise.json
> +                "goToGradingToEditInformation": "Gehen Sie zur Seite Benotung, um die Einreichungsrichtlinien zu bearbeiten.",
```suggestion
                "goToGradingToEditInformation": "Gehe zur Bewertungsseite, um die Einreichungsrichtlinien zu bearbeiten.",
```

2023-08-01 13:56 UTC, JohannesStoehr commented on src/main/webapp/i18n/en/programmingExercise.json
> +                "goToGradingToEditInformation": "Go to the Grading Page to edit Submission Policy.",
```suggestion
                "goToGradingToEditInformation": "Go to the grading page to edit submission policy.",
```
This is a proper sentence and not a heading

2023-08-03 22:51 UTC, MaximilianAnzinger reviewed
Overall code quality looks good. Left one comment.

2023-08-03 22:51 UTC, MaximilianAnzinger commented on src/main/webapp/i18n/de/programmingExercise.json
> +                "goToGradingToEditInformation": "Gehe zur Bewertungsseite, um die Einreichungsrichtlinien zu bearbeiten.",
```suggestion
                "goToGradingToEditInformation": "Gehe zur Bewertungsseite, um die Abgaberichtlinie zu bearbeiten.",
```

2023-08-04 09:14 UTC, JohannesStoehr submitted a review, later dismissed
Approve Code

2023-08-06 18:06 UTC, terlan98 submitted a review, later dismissed
Tested on TS5. Works as expected 👍 The submission policy is editable during the creation and import of an exercise. Later, it can be edited only from the grading page.

I think it would be better to put the new hintbox containing the link to the grading page before the Submission Limit and Exceeding Submission Limit Penalty
<img width="900" alt="Screenshot" src="https://github.com/ls1intum/Artemis/assets/22798314/ab1e0382-1be5-4525-a1d5-269e4931020f">

Also tested the internal server errors mentioned in the description. The 1st error is solved by this PR. _However, I could not reproduce the 2nd error on `develop` and thus can't really verify whether it exists._

2023-08-13 15:02 UTC, laadvo approved these changes
Tested on ts1, the submission policy can be edited when an exercise gets created and imported. No internal server errors appeared when importing

2023-08-14 09:10 UTC, MaximilianAnzinger submitted a review, later dismissed
Code LGTM 👍

2023-08-14 21:37 UTC, JohannesStoehr approved these changes
Reapprove code

2023-08-17 06:56 UTC, terlan98 approved these changes
Re-tested on TS5. Still works 👍

2023-08-17 12:51 UTC, rriyaldhi approved these changes
Code lgtm 👍

2023-08-22 13:04 UTC, bassner approved these changes

2023-08-22 13:05 UTC, merged