`Development`: Reduce transferred data for course (un)enrollment endpoints
ls1intum/Artemis pull request #7042
Opened 2023-08-04 11:52 UTC by MaximilianAnzinger

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [ ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exam_mode/) as reference.
4. ...

### Review Progress

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2023-08-04 13:19 UTC, pal03377 approved these changes
The code changes look like a good + clean performance improvement!

2023-08-04 13:19 UTC, pal03377 commented on src/test/javascript/spec/service/account.service.spec.ts
> +        accountService.syncGroups(user3.groups);
type error (which you already told me you will fix soon :) )

2023-08-04 15:40 UTC, pal03377 approved these changes
code

2023-08-05 11:28 UTC, julian-christl approved these changes
As you are not directly accessing the user resource, returning a user is not in any way useful.
Good job, code approved.

2023-08-06 09:54 UTC, jakubriegel requested changes
Local tests:
- I was not able to enrol for the course myself (the course didn't appear on the list
- but I was able to enrol for the course by admin
- I was able to unenroll myself

2023-08-07 10:59 UTC, MaximilianAnzinger commented
> Local tests:
> 
> * I was not able to enrol for the course myself (the course didn't appear on the list
> * but I was able to enrol for the course by admin
> * I was able to unenroll myself

I'm not able to reproduce this. See the attached (Test course with (un)enrollment configured & logged in as a test user (1) )

<img width="1728" alt="Screenshot 2023-08-07 at 12 57 58" src="https://github.com/ls1intum/Artemis/assets/44003963/1c5c7021-d2a6-4ff2-b81f-d4a4ea78e60e">

Is there a error message or something that might explain this?

2023-08-07 14:35 UTC, sleiss approved these changes

2023-08-08 01:23 UTC, merged