`Development`: Add auxiliary repository support for Local VC CI
ls1intum/Artemis pull request #7064
Opened 2023-08-11 09:41 UTC by laurenzfb

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [ ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exam_mode/) as reference.
4. ...

### Review Progress

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2023-09-11 20:19 UTC, JohannesStoehr requested changes

2023-09-11 20:19 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/service/connectors/localci/LocalCIBuildJobExecutionService.java
> +        }
Please use `Hibernate.isInitialized` instead of catching the exception

2023-09-11 20:19 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/service/RepositoryAccessService.java
> +    public void checkAccessAuxiliaryRepositoryElseThrow(boolean atLeastEditor, ProgrammingExercise exercise, User user) {
Where is the difference to the above method. Can we combine them?

2023-09-11 20:19 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/service/connectors/localci/LocalCIBuildJobExecutionService.java
> +
```suggestion
```

2023-09-11 20:19 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/service/connectors/localci/LocalCIBuildJobExecutionService.java
> +        }
Why can't you directly do this when getting the auxiliaryRepositoriesUrls above?

2023-09-11 20:19 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/service/connectors/localci/LocalCIBuildJobManagementService.java
```suggestion
```

2023-09-11 20:19 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/service/connectors/localci/LocalCIContainerService.java
> +
```suggestion
```

2023-09-11 20:19 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/service/connectors/localvc/LocalVCServletService.java
> +        boolean isAuxiliaryRepository = auxiliaryRepositoryService.isAuxiliaryRepositoryOfExercise(repositoryTypeOrUserName, exercise);
Why did you add a new variable for this?

2023-09-11 20:19 UTC, JohannesStoehr commented on src/main/webapp/app/exercises/programming/manage/programming-exercise-detail.component.html
> +                                <div *ngif="!localVCEnabled">
Since you only want to add the ngIf, you should use a `ng-container`.

2023-09-12 08:17 UTC, laurenzfb commented
Thank you for the review, @JohannesStoehr ! I implemented your suggested changes.

2023-09-14 15:45 UTC, Strohgelaender approved these changes
tested in testing session, works as expected.

Editing repositories also works (which is a great improvement to Bamboo where this is not possible), but still triggers a warning. In a followup we should remove these warnings in the client.

2023-09-14 16:26 UTC, dearjasmina approved these changes
tested in a testing session
maybe one idea for a follow up, make a better error message when tutor tries to push some changes

2023-09-14 16:27 UTC, aplr approved these changes
tested during testing session, worked as expected

2023-09-14 18:40 UTC, tobias-lippert approved these changes
Tested during testing session.

2023-09-14 19:20 UTC, JohannesStoehr approved these changes
Approve Code

2023-09-15 12:29 UTC, merged