`Programming exercises`: Fix repository export anonymization
ls1intum/Artemis pull request #7066
Opened 2023-08-11 15:59 UTC by FelixTJDietrich

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.

#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

After exporting an anonymized repository from Artemis I found a file called `FETCH_HEAD` containing the TUM identifier:
```
f6f04166d2beaa36d1e6cd819b72b92edb07855d	not-for-merge	branch 'main' of https://<REDACTED_TUM_ID>@bitbucket.ase.in.tum.de/scm/IOSOSINTRO2223S1DH/iososintro2223s1dh-<REDACTED_TUM_ID>.git
```

Consulting with @maximiliansoelch and @krusche this seems to be an oversight and should be removed for anonymization reasons.

### Description

Remove `.git/FETCH_HEAD` when anonymizing the `.git` directory.
> FETCH_HEAD is a short-lived reference in Git that records the branch which has been fetched from a remote repository. It keeps track of the last fetched HEAD from all branches in the remote repository, including the specific commit hash that was last fetched. 

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Review Progress

#### Performance Review
- [ ] ~I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance~ (unchanged)
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2023-08-16 19:24 UTC, terlan98 approved these changes
Tested on TS6 with [exercise 10](https://artemis-test6.artemis.cit.tum.de/course-management/7/programming-exercises/10). Works as expected. FETCH_HEAD is not present in the .git directory 👍 

Thanks for the fix

2023-08-16 19:47 UTC, terlan98 requested changes
I re-tested on TS5 with [exercise 8](https://artemis-test5.artemis.cit.tum.de/course-management/4/programming-exercises/8) and somehow I can still see the FETCH_HEAD in the .git directory. Moreover, the directory has an additional config file, containing the user name

<img width="500" alt="Screenshot 2023-08-16 at 23 46 34" src="https://github.com/ls1intum/Artemis/assets/22798314/af2c4ae0-45e4-4d56-93ea-99ce9143d115">

2023-08-16 19:53 UTC, FelixTJDietrich commented
@terlan98 Thanks for testing! This is very strange 🤔 logs is also there. The anonymisation does not work for that exercise at all, I don't know what's wrong. Something strange is going on, but this might be unrelated to my PR.

2023-08-17 06:41 UTC, terlan98 approved these changes
Tested again with a [different exercise](https://artemis-test5.artemis.cit.tum.de/course-management/4/programming-exercises/99) on TS5. It worked again. I assume something is wrong with [exercise 8](https://artemis-test5.artemis.cit.tum.de/course-management/4/programming-exercises/8).

Code also looks good 👍

2023-08-21 12:49 UTC, reschandreas approved these changes
Code LGTM 👍🏻 , thanks for fixing this!

2023-08-23 17:41 UTC, RY997 approved these changes
Tested on ts1 [exercise 12334](https://artemis-test1.artemis.in.tum.de/course-management/203/programming-exercises/2728/scores), worked well.

2023-08-24 10:11 UTC, lennart-keller approved these changes
Code changes lgtm

2023-08-25 06:17 UTC, dearjasmina approved these changes
code looks good

2023-08-29 22:25 UTC, FelixTJDietrich commented
Thanks everyone for reviewing and testing the PR 🙏 

@bassner I looked into this and it seems to be an issue with `combineAllStudentCommits`, everything is wrapped in this `try (Git studentGit = new Git(repository)) {...}` block and when it fails it just logs without aborting the export:
`log.warn("Cannot reset the repo {} due to the following exception: {}", repository.getLocalPath(), ex.getMessage());`
At least that is what I think is happening, I do not know how to access the ts5 logs. 

Since I'm very occupied right now with reaching my thesis deadline successfully, I would rather create an issue for this and rename the PR

2023-09-04 08:11 UTC, bassner approved these changes

2023-09-05 07:29 UTC, merged