`General`: Request data export for another user as administrator
ls1intum/Artemis pull request #7081
Opened 2023-08-15 09:01 UTC by tobias-lippert

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Administrator
- 1 user with fewer privileges
- 

1. Log in to Artemis as admin
2. Navigate to Privacy Statement
3. Navigate to data export
4. Try to request one for yourself
5. Try to request one for another user
6. In both cases, check that you get the confirmation
7. Log in as a user that is not an admin
8. Do 2-4. 
9. Check that you cannot do 5.

### Review Progress

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [data-export.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5299/latest/artifact/shared/Coverage-Report-Client-Tests/app/core/legal/data-export/data-export.component.ts.html) | 100% | ✅ |
| [data-export.service.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5299/latest/artifact/shared/Coverage-Report-Client-Tests/app/core/legal/data-export/data-export.service.ts.html) | 100% | ✅ |
| [delete-button.directive.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5299/latest/artifact/shared/Coverage-Report-Client-Tests/app/shared/delete-dialog/delete-button.directive.ts.html) | 97.56% | ✅ |
| [delete-dialog.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5299/latest/artifact/shared/Coverage-Report-Client-Tests/app/shared/delete-dialog/delete-dialog.component.ts.html) | 95.83% | ✅ |
| [delete-dialog.model.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5299/latest/artifact/shared/Coverage-Report-Client-Tests/app/shared/delete-dialog/delete-dialog.model.ts.html) | 100% | ✅ |
| [delete-dialog.service.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5299/latest/artifact/shared/Coverage-Report-Client-Tests/app/shared/delete-dialog/delete-dialog.service.ts.html) | 100% | ✅|

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| DataExportService.java | |  |
| DataExportResource.java | |  |

### Screenshots

2023-08-15 11:31 UTC, terlan98 requested changes
Tested on TS6. The English translation keys are missing when the "Request data export for another user" checkbox is enabled:

  <img width="400" alt="Screenshot 2023-08-15 at 15 30 23" src="https://github.com/ls1intum/Artemis/assets/22798314/61fd360e-3ba6-4faa-9640-28b5262772f9">

2023-08-23 15:40 UTC, MaximilianAnzinger reviewed
Code looks good. I left some suggestions and a question.

2023-08-23 15:40 UTC, MaximilianAnzinger commented on src/main/java/de/tum/in/www1/artemis/service/dataexport/DataExportService.java
> +    public RequestDataExportDTO requestDataExportForUserAsAdmin(String login) {
JavaDoc would be nice

2023-08-23 15:40 UTC, MaximilianAnzinger commented on src/main/java/de/tum/in/www1/artemis/web/rest/admin/AdminDataExportResource.java
> +import org.springframework.web.bind.annotation.*;
I think Teamscale is right this time.

2023-08-23 15:40 UTC, MaximilianAnzinger commented on src/main/webapp/app/shared/type-ahead-search-field/type-ahead-user-search-field.component.html
> +        (input)="onChange()"
is it really necessary to call onChange? I've never seen this in any other component I think.

2023-08-24 08:30 UTC, tobias-lippert commented on src/main/java/de/tum/in/www1/artemis/web/rest/DataExportResource.java
> +    private boolean checkIfUserCanRequest(User user) {
there's none after I removed the check for the admin endpoint as I think they should always be able to request.
I combined them to one method again.

2023-08-25 06:53 UTC, Strohgelaender approved these changes
lgtm

2023-08-25 08:25 UTC, Strohgelaender requested changes
tested in testing session, the client is not using the correct admin endpoint.

2023-08-25 09:52 UTC, MaximilianAnzinger approved these changes
Tested during testing session.

2023-08-25 09:52 UTC, Strohgelaender approved these changes
tested in testing session, works. code lgtm.

2023-08-25 09:52 UTC, lennart-keller approved these changes
Tested during testing session. Works well.

2023-08-25 09:52 UTC, jakubriegel approved these changes
Works (testing session) 👍🏻

2023-08-25 09:53 UTC, basak-akan approved these changes
Tested during the testing session works as described

2023-08-25 09:54 UTC, RY997 approved these changes
Tested in test session

2023-08-25 09:56 UTC, MaximilianAnzinger approved these changes
Tested during testing session.

Thank you for implementing my suggestions / answering my questions. Code LGTM 👍

2023-08-26 18:12 UTC, nityanandaz approved these changes
Code looks good, tested during 2023-08-25 testing session

2023-08-29 12:16 UTC, merged