`Programming Exercises`: Export files embedded with HTML syntax
ls1intum/Artemis pull request #7187
Opened 2023-09-12 15:05 UTC by tobias-lippert

### Checklist
#### General

- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

The export of a programming exercise doesn't contain files embedded using HTML syntax because the regex doesn't match them.

### Description

Added a second regex to also match files embedded with HTML syntax refactored some code to reuse logic for both regex expressions.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Programming exercise

1. Embedded some files in the problem statement using both markdown and html syntax
2. Export (Download) the exercise
3. Verify that the export contains all embedded files.

### Review Progress

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2023-09-12 20:53 UTC, JohannesStoehr requested changes

2023-09-12 20:53 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java
> +import java.util.Set;
Is this change intentional?

2023-09-12 20:53 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java
> +    private static final String EMBEDDED_FILE_HTML_SYNTAX_REGEX = "<img src=\"/api/files/markdown/.*?\" .*?>";
Why do you need the question marks after the `.*`?

2023-09-12 20:53 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java
> +    private void copyFilesEmbeddedWithMarkdownSyntax(ProgrammingExercise exercise, List<String> exportErrors, Set<String> embeddedFilesWithMarkdownSyntax, Path embeddedFilesDir) {
Can you swap this method with the one above? I think that order would make more sense

2023-09-14 06:43 UTC, tobias-lippert commented on src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java
> +import java.util.Set;
no

2023-09-14 09:37 UTC, JohannesStoehr submitted a review, later dismissed
Code looks good to me now

2023-09-14 11:57 UTC, MaximilianAnzinger requested changes

2023-09-14 11:57 UTC, MaximilianAnzinger commented on src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java
> +     * <p>
```suggestion
```

2023-09-14 11:57 UTC, MaximilianAnzinger commented on src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java
> +     * <p>
```suggestion
```

2023-09-14 11:57 UTC, MaximilianAnzinger commented on src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseExportService.java
> +     * <p>
```suggestion
```

2023-09-14 12:01 UTC, MaximilianAnzinger approved these changes
Code LGTM
Tested on TS2, works

2023-09-14 12:29 UTC, JohannesStoehr approved these changes

2023-09-14 14:29 UTC, dearjasmina approved these changes
tested in the testing session, works as described

2023-09-14 14:30 UTC, laurenzfb approved these changes
Tested in testing session. Worked as expected!

2023-09-14 14:30 UTC, Strohgelaender approved these changes
tested in testing session, works as expected.

2023-09-15 05:19 UTC, merged