`General`: enhance exercise-group controls with exercise type icons on desktop
ls1intum/Artemis pull request #7216
Opened 2023-09-18 10:14 UTC by milljoniaer

### Checklist
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
Stephan suggested adding exercise-type icons for the Create/Import Exercise buttons in the exercise group management view to improve UX. 

### Description
These icons are already displayed on mobile, when the button label is not displayed anymore. This PR displays them also on desktop after the label.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Exam with 1 Exercise Group
- View the control section there on mobile and desktop
- Verify that the exercise-type icons are displayed on both

### Review Progress

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

Desktop:
![image](https://github.com/ls1intum/Artemis/assets/78978542/1bdd74de-94b7-4805-8bea-6678781a19aa)

Mobile:
![image](https://github.com/ls1intum/Artemis/assets/78978542/c1bca1af-c444-4db6-9f5e-9404259ad649)

2023-09-18 11:04 UTC, lennart-keller approved these changes
Code changes lgtm. Have you considered putting the icons in the front instead? Personally, I am a bit unsure what looks better:
<img width="963" alt="icons" src="https://github.com/ls1intum/Artemis/assets/44754405/710e40c2-8ccb-420f-af49-fd55fa155a12">

2023-09-18 11:12 UTC, DominikRemo approved these changes
Code LGTM
Tested on ts2 and works as expected

2023-09-18 11:38 UTC, JohannesStoehr requested changes
Looks good over all and I personally like the icons behind the text better as you already did.
Can you also add these icons to the course exercise page? Additionally I noticed that the import and create option in the exam page is the other way round compared to the course page. You could unify that order as well (I'd suggest creation above/before import)

2023-09-18 15:34 UTC, milljoniaer commented
Thank you for your feedback, I sticked to the exercise icon at the end, added the icon also in the course exercise views and unified the order of create/import buttons. Please have another look at the PR.

2023-09-18 15:38 UTC, JohannesStoehr submitted a review, later dismissed
Thanks for unifying the two occurrences.
Code looks good to me

2023-09-18 17:02 UTC, DominikRemo approved these changes

2023-09-18 17:37 UTC, terlan98 approved these changes
Tested on TS5. The icons are visible for exam exercise groups and course exercises 👍

2023-09-18 20:47 UTC, krusche commented on src/main/webapp/app/exercises/shared/manage/exercise-create-buttons.component.ts
> +    getExerciseTypeIcon(exerciseType: ExerciseType) {
This code already exists in `ExamExerciseImportComponent`. Please unify it in a common util or service class

2023-09-19 11:14 UTC, JohannesStoehr submitted a review, later dismissed
Reapprove after unification

2023-09-19 12:52 UTC, DominikRemo approved these changes
Tested on ts1. Works as expected

2023-09-19 12:54 UTC, terlan98 approved these changes
Re-tested on TS5 and reapproved

2023-09-19 13:24 UTC, lennart-keller approved these changes
Recent code changes lgtm

2023-09-22 14:03 UTC, merged