`Development`: Add JavaDocs to UtilServices and Factories [1]
ls1intum/Artemis pull request #7241
Opened 2023-09-21 19:15 UTC by DominikRemo

### Checklist
#### General
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context

Improve the readability of UtilServices and Factories by adding JavaDoc to the helper functions

### Description

Added documentation to following files:
- [x] assessment/ComplaintUtilService.java
- [x] assessment/GradingScaleFactory.java (already commented)
- [x] assessment/GradingScaleUtilService.java

### Steps for Testing
_JavaDoc changes only_

### Review Progress

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2

2023-09-21 20:25 UTC, laadvo requested changes
Already looks good but I have a few suggestions on how to further improve the Javadocs

2023-09-21 20:25 UTC, laadvo commented on src/test/java/de/tum/in/www1/artemis/assessment/ComplaintUtilService.java
> +     * @param type       The type of the complaint to create.
We should rename this to "complaintType" to stay consistent with other methods.

2023-09-21 20:25 UTC, laadvo commented on src/test/java/de/tum/in/www1/artemis/assessment/GradingScaleUtilService.java
> +     * Creates a set of grade steps.
Here you could also explain how many grade steps are created and that one is a failing one and the other a passing one.

2023-09-21 20:25 UTC, laadvo commented on src/test/java/de/tum/in/www1/artemis/assessment/GradingScaleUtilService.java
> +     * @param valid        whether the grade steps should be valid (i.e. the upper bound of a grade step is equal to the lower bound of the next grade step)
whether **one** grading step is valid.

2023-09-21 20:25 UTC, laadvo commented on src/test/java/de/tum/in/www1/artemis/assessment/GradingScaleUtilService.java
> +     * Creates a grading scale with the given parameters.
Here I think you should also write about the `fail("Invalid grading scale parameters")` in case of invalid values.

2023-09-21 20:25 UTC, laadvo commented on src/test/java/de/tum/in/www1/artemis/assessment/GradingScaleUtilService.java
> +     * Creates a grading scale with a sticky grade step.
Here you could also consider explaining the fail statement, or at least mention that there is one.

2023-09-25 15:25 UTC, Strohgelaender commented on src/test/java/de/tum/in/www1/artemis/assessment/ComplaintUtilService.java
> +     * @param currentUser              The user that replies to more feedback requests.
```suggestion
     * @param currentUser              The user that replies to the complaint.
```

2023-09-28 21:24 UTC, laadvo approved these changes
Looks good to me, thanks for implementing my suggestions :)

2023-09-29 06:55 UTC, MaximilianAnzinger approved these changes
The documentation looks good. Thank you for adding this 👍

2023-09-29 08:33 UTC, merged