`General`: Document Exam Exercise Update Notifications
ls1intum/Artemis pull request #7294
Opened 2023-09-29 11:12 UTC by tobias-lippert

### Checklist
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context

The exam exercise update notification feature lacks documentation

### Description

Added documentation including screenshots.

### Steps for Testing
Have a look at the docs
Code Review

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://ls1intum.github.io/Artemis/user/exam_mode/) as reference.
4. ...

### Review Progress

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2

### Screenshots

2023-09-29 11:25 UTC, MaximilianAnzinger submitted a review, later dismissed
LGTM one suggestion: Maybe it should be more obvious that manual merging is not possible in the online editor? Some highlighting since this might be a problem?

2023-09-29 12:03 UTC, florian-glombik requested changes
Some comments on the formulations, the error with the headline must be fixed to ensure that the documentation compiles

2023-09-29 12:03 UTC, florian-glombik commented on docs/user/exams/students_guide.rst
> +If your instructor updates the problem statement for an exercise during the exam, you will receive a notification as seen in the screenshot below and can toggle between a diff view and the new proble
I think that the sentence is missing some commas; I would also rather speak of switching between the dif and not toggling

```suggestion
If your instructor updates the problem statement for an exercise during the exam, you will receive a notification, as seen in the screenshot below, and can switch between a diff view and the new problem statement, as shown in the second and third screenshot.
```

2023-09-29 12:07 UTC, florian-glombik commented on docs/user/exams/instructors_guide.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Suggestion on wrong part of the code

2023-09-29 12:08 UTC, florian-glombik commented on docs/user/exams/students_guide.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The docu does not compile without this change

```suggestion
Updated Problem Statement during the Exam
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

2023-09-29 12:09 UTC, florian-glombik commented on docs/user/exams/instructors_guide.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See https://github.com/ls1intum/Artemis/pull/7294#discussion_r1341288830 for the intended change

2023-09-30 09:05 UTC, laurenzfb submitted a review, later dismissed
Overall LGTM but I do agree on the suggested changes by @florian-glombik

2023-09-30 16:55 UTC, aplr submitted a review, later dismissed
LGTM w/ change requests from @florian-glombik also. Good to read & understandable otherwise.

2023-10-07 14:02 UTC, b-fein submitted a review, later dismissed

2023-10-08 14:14 UTC, laurenzfb approved these changes
LGTM after changes!

2023-10-08 14:29 UTC, b-fein approved these changes

2023-10-09 06:31 UTC, MaximilianAnzinger approved these changes

2023-10-09 09:27 UTC, aplr approved these changes

2023-10-09 21:33 UTC, florian-glombik submitted a review, later dismissed
Thanks for incorporating the feedback! Looks good to me now!

2023-10-10 07:27 UTC, b-fein submitted a review, later dismissed

2023-10-10 07:40 UTC, aplr approved these changes

2023-10-10 07:53 UTC, laurenzfb submitted a review, later dismissed

2023-10-10 21:07 UTC, krusche requested changes
Could you also document this feature on https://artemis.in.tum.de/features/instructors and on https://artemis.in.tum.de/features/students ?

And does it make sense to put the exam announcement and time extension in this PR as well?

2023-10-11 20:25 UTC, tobias-lippert commented
@krusche Gonna add that. Regarding the second aspect, I do not know much about the exam announcement feature but as far as I know they work still a bit differently at the moment. @aplr What do you think? Do you want to add your documenation to this PR?

2023-10-12 16:29 UTC, aplr commented
@krusche @tobias-lippert If you don't have opposing views, I'd prefer to add time extensions & announcements in another PR.

2023-10-12 21:05 UTC, krusche commented
> @krusche @tobias-lippert If you don't have opposing views, I'd prefer to add time extensions & announcements in another PR.

As long as we document this asap, I'm fine

2023-10-13 06:00 UTC, b-fein approved these changes

2023-10-13 08:07 UTC, laurenzfb approved these changes

2023-10-13 08:39 UTC, MaximilianAnzinger approved these changes

2023-10-14 07:02 UTC, merged