`Assessment`: Improve UX during repository export
ls1intum/Artemis pull request #7304
Opened 2023-10-03 10:31 UTC by milljoniaer

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [ ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [ ] I followed the [coding and design guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [ ] I followed the [coding and design guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://ls1intum.github.io/Artemis/user/exam_mode/) as reference.
4. ...

### Review Progress

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2023-10-05 11:01 UTC, FelixTJDietrich submitted a review, later dismissed
Code looks good and works as expected on ts5.

Correctly disabled checkbox: ✅
<img width="809" alt="Screenshot 2023-10-05 at 12 57 45" src="https://github.com/ls1intum/Artemis/assets/5898705/5c15b3ef-d8f8-479e-b5f9-892229a04ba9">

Export dialog is unchanged and anonymization checkbox is unchecked: ✅
<img width="806" alt="Screenshot 2023-10-05 at 12 58 15" src="https://github.com/ls1intum/Artemis/assets/5898705/859a188a-c20f-4e99-aaf2-f6f8cb560749">

2023-10-05 11:02 UTC, jakubriegel requested changes
Code looks ok, but on ts5 the checkbox is active:
<img width="1134" alt="image" src="https://github.com/ls1intum/Artemis/assets/32958017/1e62c408-fdcf-400c-b837-392a9a18919d">

2023-10-05 11:05 UTC, FelixTJDietrich commented
> Code looks ok, but on ts5 the checkbox is active: <img alt="image" width="1134" src="https://user-images.githubusercontent.com/32958017/272880178-1e62c408-fdcf-400c-b837-392a9a18919d.png">

Which checkbox are you referring to? `Anonymize repository` should be unchecked here by default and checked when downloading a repo during assessment.

2023-10-05 11:27 UTC, jakubriegel approved these changes
After finding the right export button works as it should:
<img width="991" alt="image" src="https://github.com/ls1intum/Artemis/assets/32958017/614df477-8803-4624-9fb9-6a52b3d04521">

2023-10-05 12:37 UTC, Strohgelaender reviewed
I don't like the solution of using `!!participationIdList?.length` as a condition. This might work for now, but could breaks easily if the export component gets added to another places.

Can you not just check the access rights of the current user? If the user is only tutor, the anomymize repository option should always be active and disabled.

2023-10-05 16:56 UTC, milljoniaer commented on src/main/webapp/app/exercises/programming/assess/repo-export/programming-assessment-repo-export-dialog.component.html
> +                    [disabled]="!!participationIdList?.length"
I have forgotten to also disable this checkbox if `!!participationIdList?.length` applies to stick to the logic before.

2023-10-05 18:21 UTC, RY997 approved these changes
Tested on ts5, worked well.

2023-10-07 12:42 UTC, jakubriegel approved these changes
Code ok after update

2023-10-09 07:49 UTC, Strohgelaender submitted a review, later dismissed
lgtm now

2023-10-09 09:12 UTC, Strohgelaender approved these changes
re-approve code

2023-10-09 15:57 UTC, laurenzfb approved these changes
Tested in testing session, lgmt!

2023-10-09 16:57 UTC, aplr approved these changes
Tested in testing session, works well, aside from the follow-up. LGMT

2023-10-09 18:06 UTC, laadvo approved these changes
Code looks good

2023-10-11 07:30 UTC, FelixTJDietrich approved these changes
Code changes LGTM

2023-10-14 06:56 UTC, merged