´Programming Exercises´: Fix Maven Sequential Test Runs
ls1intum/Artemis pull request #7322
Opened 2023-10-04 17:17 UTC by laurenzfb

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [ ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [ ] I followed the [coding and design guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/server/).

#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

A previous change ([#7038](https://github.com/ls1intum/Artemis/pull/7038)) `ProgrammingExerciseRepositoryService.java` concerning setting up the build stage for Maven sequential test run exercises lead to not finding the stagePom.xml and creating an incomplete build stage. For some reason, this problem does not occur locally.

### Description

I reverted the affected code back to before the mentioned PR.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Create a Java Maven programming exercise with sequential test runs enabled
2. Template and solution build results should be as expected

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

2023-10-04 18:46 UTC, DominikRemo requested changes
Sorry, wrong PR x.x"

2023-10-04 19:09 UTC, Strohgelaender approved these changes
code changes look reasonable 
(This PR is still in draft status, is this on purpose?)

2023-10-04 19:58 UTC, laurenzfb commented
@Strohgelaender According to the tests, java.nio.file.Files should not be used. That's probably why it was changed to FileUtils by the previous PR in the first place. But that does not work on deployments for some reason. Since I haven't yet found a solution that also works with the tests, I put this back on draft.

2023-10-05 06:22 UTC, b-fein commented
> But that does not work on deployments for some reason.

I think it does not work because the `pom.xml` template is part of the WAR archive in a properly deployed system. Therefore the `getFile()` resolves to a non-existing location. Using the `getInputStream` in this case is the only way I think to get the file contents.

To make the calls equivalent, it might be necessary to put in an additional (pseudocode, I don’t know the exact method name)
```java
Files.createDirectories(buildStagePath);
```
to create the parent directories of the target file.

2023-10-05 06:27 UTC, b-fein commented
Better idea: Does the `FileService` still have a method `copyResource`? That would be more appropriate here since `Optional<Resource> stagePomXml`.

2023-10-05 07:23 UTC, Strohgelaender commented on src/main/java/de/tum/in/www1/artemis/service/programming/ProgrammingExerciseRepositoryService.java
> +            Files.copy(stagePomXml.get().getInputStream(), buildStagePath.resolve(POM_XML));
```suggestion
             FileUtils.copyToFile(stagePomXml.get().getInputStream(), buildStagePath.resolve(POM_XML).toFile());
```

2023-10-05 12:44 UTC, laurenzfb commented
@Strohgelaender Thanks for the suggestion, it works!

2023-10-05 13:18 UTC, jakubriegel approved these changes
Code LGTM, works on ts4 👍🏻

2023-10-05 13:42 UTC, lennart-keller approved these changes
code lgtm

2023-10-05 16:34 UTC, laadvo reviewed
Tested on ts1, for the template build now only 9 tests get run instead of 13 (see screenshot)
![image](https://github.com/ls1intum/Artemis/assets/73339358/1e5d26cb-2d67-41ac-b8f7-7fc59f368eff)
I am guessing this is the expected behavior but wanted to ask to be sure.

2023-10-05 19:58 UTC, DominikRemo reviewed
Tested on ts1 and encountered same behaviour as @laadvo 

See course "Dominik Test Course", Exercise "Test 7322-2"
https://artemis-test1.artemis.in.tum.de/course-management/214/programming-exercises/3424

EDIT:
In Exercise "Test 7322", I encountered the same behaviour. After clicking the resubmit button, I got _0 of 13 passed_ as expected.

2023-10-05 21:20 UTC, laurenzfb commented
Ok, my mistake... That is actually the expected behavior. Sequential test runs first run the structural tests and only if they pass, then they run the behavioral tests. Thus, the template build only shows 9 tests. The exercise I created that ran all 13 tests was with regular test runs. @DominikRemo when reloading the build it also showed 0 of 13 passed but when you actually click on the build result, it should only show the 9 tests.

2023-10-06 14:18 UTC, florian-glombik approved these changes
Sequential test runs were executed properly on ts1 (9 for template, 13 for solution on the strategy pattern exercise).

Code changes are looking good

2023-10-06 15:25 UTC, laadvo approved these changes
@laurenzfb thanks for explaining the behavior, builds with sequential test runs seem to be working as expected :+1:

2023-10-07 09:42 UTC, Strohgelaender commented
The issue you encountered here is described in https://github.com/ls1intum/Artemis/issues/2285. When creating the programming exercise, both the template and solution repository get built at the same time. If the template build finishes before the solution, only the 9 structural test cases that got executed are reported back to Artemis.

If the solution finishes first, Artemis knows that actually 13 test cases should exist. The following template result then also has 13 test cases, but some of them just were not executed. 

For some reason, this feedback is not shown in the feedback modal, but it is present in the server response. We should look into why this is the case and fix that.
![grafik](https://github.com/ls1intum/Artemis/assets/26540346/0ebf1530-4da0-4498-997f-31814549d5fc)

Before #6682 this issue was not fixable on Artemis, because Bamboo would automatically trigger a build as soon as the template commit gets added to the repository. However, since we now trigger builds by Artemis, we could always build the solution first and wait for its result until triggering the template. The same is already done when registering template changes for the same reason (the solution build is used to create the test cases which are then present when processing the template result).

2023-10-07 15:44 UTC, merged