`Development`: Reorganize setup documentation
ls1intum/Artemis pull request #7323
Opened 2023-10-04 18:31 UTC by b-fein

### Checklist
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context
Closes #6449.
Closes #5657.

The setup documentation at the moment interleaves documentation that is only relevant for local development setups and documentation that is only relevant for production setups. This makes it hard to follow the documentation in both cases.

### Description
This PR aims to reorganise the sections of the setup documentation so that ones only relevant for production setups (e.g., customisation, privacy statement) are moved to the admin docs.
Additionally, the setup for extension services is also moved to the admin docs. To make sure users are aware of those special services, a note is added to the start of the development docs that explains that this page only explains the core setup but the additional services to extend Artemis functionality are available.

Thus, the actual content of the individual sections has been mostly unchanged (except for small formatting adjustments like adapting the section nesting depth) and only been extracted into separate files and moved into a different directory.

As a future PR the Gitlab/Jenkins setup docs can be further improved to move the nginx-setup instructions from there to the admin section as well. However, in this first step this has not been done, since it would require restructuring within the section, rather than moving entire independent sections from dev to admin docs.

### Steps for Testing
Look at the setup docs for developers and admins and check that the sections you would expect are still there and that images are shown.

- https://artemis-platform--7323.org.readthedocs.build/en/7323/dev/setup.html
- https://artemis-platform--7323.org.readthedocs.build/en/7323/admin/setup.html
- https://artemis-platform--7323.org.readthedocs.build/en/7323/admin/extension-services.html

### Review Progress
#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

2023-10-16 14:38 UTC, DominikRemo requested changes
Already looks good. Left some comments

2023-10-16 14:38 UTC, DominikRemo commented on docs/dev/setup/server.rst
> +      text-assessment-analytics-enabled: true
This was moved to docs/admin/setup/text-assessment-analytics.rst

We should remove this occurrence

2023-10-16 14:38 UTC, DominikRemo commented on docs/admin/setup/legal/privacy-statement-templates.rst
> +.. code-block:: markdown
Before these Changes, the templates were not highlighted at all. Now, the German privacy statement (top of image) is highlighted differently compared to the English version (bottom of image) and the imprint templates (headings not highlighted):
![Screenshot 2023-10-16 at 16 17 24](https://github.com/ls1intum/Artemis/assets/47261058/2a275b4d-4ecc-4ca6-b618-e64e4ee576a3)

2023-10-16 14:38 UTC, DominikRemo commented on docs/admin/setup/kubernetes.rst
IMO, the Kubernetes guide should stay in the dev setup guide because "this does not result in a production-ready deployment"

2023-10-17 15:06 UTC, b-fein commented on docs/admin/setup/kubernetes.rst
Neither does it result in a working dev-deployment at the moment. I’d leave it in the admin section as a special deployment similar to the multi-instance Artemis setup. Maybe someone that is familiar with Kubernetes can extract relevant pointers about how to deploy Artemis in their cluster using this documentation whereas I don’t think any developer is going to set up their dev-env using Kubernetes.

I think the goal is to whenever https://github.com/ls1intum/artemis-helm is ready, completely replace this part of the setup documentation with an updated one anyway.

2023-10-18 18:05 UTC, DominikRemo approved these changes
Thank you for implementing my feedback and improving our documentation :)

2023-10-26 12:17 UTC, laadvo approved these changes
The new reorganized setup documentation is easier to follow, as only steps that are relevant are provided and others are moved to the admin section. LGTM, just left one optional suggestion.

2023-10-26 12:17 UTC, laadvo commented on docs/admin/setup/kubernetes.rst
> +   This does not result in a production-ready deployment.
```suggestion
   These steps were part of an experimental setup and do not result in a production-ready deployment.
```

2023-10-27 18:52 UTC, merged