`General`: Add contributors to about us page
ls1intum/Artemis pull request #7371
Opened 2023-10-14 08:36 UTC by MaximilianAnzinger

### Checklist
#### General

- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context
Adds new contributors to the about us page.

### How to add yourself
1. Checkout the `chore/about-us` branch locally
2. Add yourself to this file: `src/main/resources/public/content/about-us.json`
 - Use `fullName` for your name
 - Use `sortBy` if the automatic sorting does not detect your last name correctly (if your name consists of mulitple words)
3. Add your image to the `public/images/about` directory and link that image using the `photoDirectory` key. Make sure to use a square, otherwise crop your image before uploading it.

### Steps for Testing
View the about us page and check that the new contributors are visible and sorted.

2023-11-02 13:55 UTC, vinceclifford submitted a review, later dismissed
Works as expected

2023-11-02 13:56 UTC, rstief approved these changes
Tested on ts3 all new additions are there and page looks good.

2023-11-03 18:37 UTC, krusche commented on src/main/resources/public/images/about/Maximilian_Anzinger.jpg
This file is too large. Please provide a smaller version that is at most 100KB

2023-11-03 18:37 UTC, krusche commented on src/main/resources/public/images/about/Laurenz_Blumentritt.jpg
This file is too large. Please provide a smaller version that is at most 100KB

2023-11-03 18:37 UTC, krusche commented on src/main/resources/public/images/about/Valentin_Boehm.jpg
This file is too large. Please provide a smaller version that is at most 100KB

2023-11-03 18:37 UTC, krusche commented on src/main/resources/public/images/about/Andreas_Resch.png
This file is too large. Please provide a smaller version that is at most 100KB

2023-11-03 18:38 UTC, krusche requested changes
some images are too large, please provide smaller versions

2023-11-06 09:33 UTC, rstief approved these changes

2023-11-08 14:26 UTC, JohannesStoehr approved these changes
Updated links work and changes overall look good!

2023-11-08 16:42 UTC, vinceclifford approved these changes
LGTM, tested on TS3

2023-11-08 16:43 UTC, Predixx approved these changes
Tested on ts3 with Vincent Clifford. Images all look great and are displayed correctly

2023-11-10 06:51 UTC, merged