`Tutorial groups`: Usability issue for creating new tutorial for campus and language suggestions
ls1intum/Artemis pull request #7389
Opened 2023-10-16 12:26 UTC by max-bergmann

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [ ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [ ] I followed the [coding and design guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [ ] I followed the [coding and design guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

fixes https://github.com/ls1intum/Artemis/issues/7292

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://ls1intum.github.io/Artemis/user/exam_mode/) as reference.
4. ...

### Review Progress

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2023-10-19 03:01 UTC, Strohgelaender commented on src/main/java/de/tum/in/www1/artemis/web/rest/tutorialgroups/TutorialGroupResource.java
> +        var user = userRepository.getUser();
The groups are needed in the next call (checkHasAtLeastRoleInCourseElseThrow), which currently leads to an additional database request.

2023-10-24 16:56 UTC, sarpsahinalp reviewed
I can't see the changes on ts3
![image](https://github.com/ls1intum/Artemis/assets/92453703/7eac9840-b48c-4513-a10b-6b4311964619)

Default values are not selectable
![image](https://github.com/ls1intum/Artemis/assets/92453703/9485dfd3-3432-46fc-83a4-c5c39c2aa3eb)

2023-10-28 16:59 UTC, Strohgelaender commented on src/main/webapp/app/course/tutorial-groups/tutorial-groups-management/tutorial-groups/crud/tutorial-group-form/tutorial-group-form.component.ts
> +            if (!languages.includes('German')) this.languages.push('German');
```suggestion
            if (!languages.includes('English')) {
                this.languages.push('English');
            }
            if (!languages.includes('German')) {
                this.languages.push('German');
            }
```

2023-10-29 15:41 UTC, JanaNF requested changes
Maunal tested on legacy ts2. Worked mostly as expected.

But for the languages: If I added a new language (e.g. Russisch) it did not show up as a default value for the other tutorial (like it did with the locations). I don't know if this is something you want to happen or not. Please let me know.

2023-10-29 16:41 UTC, max-bergmann commented
> Maunal tested on legacy ts2. Worked mostly as expected.
> 
> But for the languages: If I added a new language (e.g. Russisch) it did not show up as a default value for the other tutorial (like it did with the locations). I don't know if this is something you want to happen or not. Please let me know.

Thanks for your review. Originally, the change was only meant for several campuses in different courses, but I have now included the change for the languages as well.

2023-10-29 17:34 UTC, vinceclifford requested changes
I reviewed the PR previously with Jana when the selection between German and English was still working. 

I tested on TS3 and the requirements (the language selection) were not fulfilled. 
Firstly, I can't choose between English and German. There is no drop-down menu. Screenshot of me entering German down below. 
Secondly, previous inputs are not "transferred" to different courses. If I select Straubing as the campus in Course1 and then go to Course2, I will not get Straubing recommended. However, if I create another tutorial group in Course1 I will see my previous input. I don't know if this is as it should be. 
However, the selection of German and English is not shown to me. 

![Screenshot 2023-10-29 at 18 28 23](https://github.com/ls1intum/Artemis/assets/79379318/b8f59df1-35f8-40d7-a066-0c44e9365467)

2023-10-29 17:36 UTC, JanaNF approved these changes
Tested again on ts2. Worked as expected

2023-10-30 15:13 UTC, milljoniaer submitted a review, later dismissed
Tested ts4, works as expected

2023-10-30 15:18 UTC, Strohgelaender requested changes
Please implement my change request above, this currently leads to unneccesary database requests.

2023-11-02 13:40 UTC, rstief approved these changes
Tested on legacy ts3 in testing session.

2023-11-02 13:41 UTC, MaximilianAnzinger approved these changes
Tested during testing session

2023-11-02 13:56 UTC, lennart-keller approved these changes
Tested in testing session

2023-11-07 21:00 UTC, merged