`Communication`: Hide notifications for active channel on lecture and exercise page
ls1intum/Artemis pull request #7406
Opened 2023-10-17 12:57 UTC by lennart-keller

… page

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I documented the TypeScript code using JSDoc style.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

Notifications are shown for the active channel on the lecture/exercise detail pages, even though the channel is open.

### Description

Notifications for the open channel are temporarily disabled as long as the sidebar is visible

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### Review Progress

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2023-10-17 14:52 UTC, Kroko-fant submitted a review, later dismissed
Tested in a testing session worked as expected

2023-10-17 14:53 UTC, basak-akan approved these changes
Tested in the testing session on TS2, notifications for the open channel disabled 👍

2023-10-17 15:02 UTC, rstief submitted a review, later dismissed
Tested in session on ts2

2023-10-17 17:17 UTC, MaximilianAnzinger approved these changes
Code lgtm

2023-10-17 19:20 UTC, jakubriegel commented on src/main/webapp/app/overview/discussion-section/discussion-section.component.ts
>       * on leaving the page, the modal should be closed
This comment is not up to date now

2023-10-17 19:21 UTC, jakubriegel reviewed
Small note about one comment

2023-10-18 06:30 UTC, krusche requested changes
can you write some client tests to verify the new behavior

2023-12-14 18:41 UTC, closed without merging