`Development`: Allow native apps to access code of conduct template
ls1intum/Artemis pull request #7413
Opened 2023-10-18 07:30 UTC by TimOrtel

On the native applications, we have to enforce that students accept a code of conduct before accessing the messaging features due to play store and app store guidelines.

However, some courses do not have a code of conduct set. In these cases, we want to, instead, query the code of conduct template and show it to the user. 

With this PR, we allow all students to query the code of conduct template, so that we can download it on the native apps.

See PRs:
- https://github.com/ls1intum/artemis-android/pull/5 
- https://github.com/ls1intum/artemis-ios/pull/37

2023-10-18 07:35 UTC, nityanandaz approved these changes

2023-10-18 07:59 UTC, Strohgelaender requested changes
In PR #7154 the user auto-accepts the code of conduct if it is missing or empty. This would be inconsistent with the behavior of the webapp.

2023-10-18 08:31 UTC, TimOrtel commented
@Strohgelaender the difference between the behaviors of the webapps and the native apps is intentional. We would also like to skip the additional check on the native clients, but we cannot without breaking the rules of the app stores.

2023-10-18 09:13 UTC, TimOrtel commented
I have added a hint to the template such that everyone knows that the template can also be directly shown to users.

2023-10-18 09:35 UTC, Strohgelaender approved these changes
approve after discussion on Slack

2023-10-18 16:40 UTC, nityanandaz approved these changes
Agree for iOS

2023-10-19 08:46 UTC, lennart-keller approved these changes
both lines lgtm ;)

2023-10-19 08:53 UTC, Kroko-fant approved these changes
Code looks good to me

2023-10-19 18:18 UTC, dearjasmina approved these changes
code lgtm

2023-10-21 10:13 UTC, merged