`General`: Hide unavailable buttons from tutors in lecture overview and course management
ls1intum/Artemis pull request #7423
Opened 2023-10-19 15:06 UTC by JohannesStoehr

### Checklist
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Fixes #7422 and also one other occurrence I noticed when fixing this issue.

### Description

Fixes authorities and hides the following buttons from tutors:
- Manage button in the lecture view inside a course (the one from #7422)
- "Edit"/"Attachment"/"Units" buttons in the manage page of a lecture
- Scores button in the course management tab bar

### Steps for Testing

Prerequisites:
- 1 Tutor
- 1 Editor/Instruktor

1. Go to each button and check that they are not displayed to tutors.
2. Check that editors/instructors can still see and use the buttons

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked

![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test9)

### Review Progress

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

The hidden Buttons:

Manage button, e.g. here: https://artemis-test1.artemis.in.tum.de/courses/118/lectures/215
<img width="572" alt="Bildschirmfoto 2023-10-19 um 17 04 08" src="https://github.com/ls1intum/Artemis/assets/38322605/39f2d2f3-4aea-4b9a-9e57-9f4748069a55">

"Edit"/"Attachment"/"Units" buttons, e.g. here: https://artemis-test1.artemis.in.tum.de/course-management/118/lectures/215
<img width="572" alt="Bildschirmfoto 2023-10-19 um 17 04 19" src="https://github.com/ls1intum/Artemis/assets/38322605/f8a01080-2221-43e2-b41c-04d810f6c0c9">

Scores button, e.g. here: https://artemis-test1.artemis.in.tum.de/course-management/118
<img width="768" alt="Bildschirmfoto 2023-10-19 um 17 06 21" src="https://github.com/ls1intum/Artemis/assets/38322605/bda76702-0d7c-4e65-8b92-f1446993b5bc">

2023-10-19 15:43 UTC, konrad2002 approved these changes
LGTM
Tested on Legacy TS2

2023-10-19 17:42 UTC, Strohgelaender approved these changes
code lgtm, thanks for adding a small additional client test

2023-10-20 07:06 UTC, MaximilianAnzinger approved these changes
Code lgtm

2023-10-20 08:54 UTC, dearjasmina submitted a review, later dismissed
tested on ts1, works as described for both tutor and instructor roles 👍🏻

2023-10-20 19:17 UTC, JanaNF commented
Manual tested on ts1. Worked as expected

2023-10-20 19:23 UTC, JanaNF approved these changes
Tested on ts1. All good

2023-10-20 20:57 UTC, konrad2002 requested changes
tested it on legacy ts11

I'm not sure if it is supposed to be like this, but as a tutor I wasn't able to open the tutorial groups page..

As instructor this worked

### Tutor:
![grafik](https://github.com/ls1intum/Artemis/assets/44098768/412b3eec-bc8e-49d2-928b-57c0819b72a0)
When clicking, nothing happens (+ no error in console)

### Instructor:
![grafik](https://github.com/ls1intum/Artemis/assets/44098768/d0c552c1-46a6-4c1d-a838-5c1abd474be4)
After clicking on tutorials

2023-10-21 09:32 UTC, JohannesStoehr commented on src/main/webapp/app/course/manage/overview/course-management-card.component.html
> +            *ngIf="course.timeZone || course.isAtLeastInstructor"
We currently don't load the tutorialGroupsConfiguration here and to keep this PR small I decided to only use the timeZone here, which is also a prerequisite for tutorials

2023-10-21 12:19 UTC, konrad2002 approved these changes

2023-10-22 11:34 UTC, MaximilianAnzinger approved these changes
Code

2023-10-24 11:06 UTC, Strohgelaender approved these changes

2023-10-24 17:03 UTC, sarpsahinalp approved these changes
Tested on ts3 works as expected.
Tutor side:
![image](https://github.com/ls1intum/Artemis/assets/92453703/e0106e1e-54d1-4870-b381-5cbf537e6517)

Instructor side:
![Screenshot from 2023-10-24 19-02-33](https://github.com/ls1intum/Artemis/assets/92453703/fb80c658-5a5d-4322-9b7e-164495357456)

2023-10-26 09:52 UTC, merged