`Development`: Adapt LTI advantage deep linking service for exercise selection from Moodle
ls1intum/Artemis pull request #7425
Opened 2023-10-19 20:26 UTC by basak-akan

> [!WARNING]  
> **Deploy only locally or on ts11!** The LTI feature is only available on TS11.

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [ ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exam_mode/) as reference.
4. ...

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked

![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test9)

### Review Progress

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2023-11-11 09:34 UTC, JanaNF approved these changes
Manual tested on legacy ts11. Worked as expected.

Note: As in your video, when adding a new external tool, I got the "Required Activity Name" warning even though I filled it out. I was still able to add the tool, but I was a little confused at first. If you could change this, it would be very helpful.

2023-11-11 12:15 UTC, farisd16 approved these changes
tested on legacy ts11, works as expected

2023-11-15 12:16 UTC, Gusti2010 submitted a review, later dismissed
Tested manually on TS11. Works as expected!

2023-11-15 20:02 UTC, b-fein requested changes
Code looks mostly good.

I don’t thing the `LtiDeepLinkingService` works as intended, though, in case there are multiple deep linking requests at the same time.

In client code a few constructs could be simplified by using Angular functionality.

2023-11-17 15:18 UTC, basak-akan commented
> Code looks mostly good.
> 
> I don’t thing the `LtiDeepLinkingService` works as intended, though, in case there are multiple deep linking requests at the same time.
> 
> In client code a few constructs could be simplified by using Angular functionality.

@b-fein Thank you for your insights on the code review. I've taken your observations into account and refactored the LtiDeepLinkingService to handle concurrent deep-linking requests. Also, I've simplified the client code constructs by integrating more of Angular's built-in features as suggested. Could you please review the changes again?

2023-11-19 22:43 UTC, JanaNF reviewed
Tried to test on legacy_ts11 but I couldn’t connect to the server.

I wrote with Laurenz and he said:
_"A new config variable was introduced by a PR, but this is not included in the config for TS11. This is why it always fails at startup. I think the PR was merged without regard to the config change and is now causing problems on all test servers where the config has not yet been adjusted. The PR with the config change is already in Develop and I suspect that if your PRs are running with the latest changes from Develop, then there will be problems"_

I think your PR is affected.

2023-11-20 14:37 UTC, JanaNF approved these changes
I could your PR on legacy_ts11 again :tada: Everything still works

2023-11-20 19:03 UTC, b-fein approved these changes
Thanks for implementing the previous suggestions. Code looks good with only a few tiny questions and optional suggestions.

2023-11-20 19:03 UTC, b-fein commented on src/test/java/de/tum/in/www1/artemis/connectors/LtiDeepLinkingServiceTest.java
> +package de.tum.in.www1.artemis.connectors;
```suggestion
package de.tum.in.www1.artemis.connectors.lti;
```
If the package matches the production package structure methods only used in tests could be made package-private.

2023-11-21 00:56 UTC, AntonGeTUM submitted a review, later dismissed
Tested on TS11, works as expected

2023-11-23 15:25 UTC, basak-akan commented on src/main/webapp/app/lti/lti13-deep-linking.component.html
> +                            <!-- <input class="form-check-input" type="checkbox" />-->
Somehow I missed to remove it, it is removed now.

2023-11-23 20:38 UTC, b-fein approved these changes
Code looks good now. :+1:

2023-11-23 23:39 UTC, JanaNF submitted a review, later dismissed
Re-tested on legacy_ts11. Worked as expected.

2023-11-26 15:01 UTC, lennart-keller reviewed
Code looks good to me. Left a few questions

2023-11-26 15:01 UTC, lennart-keller commented on src/test/java/de/tum/in/www1/artemis/LtiIntegrationTest.java
> +        claims.put("https://purl.imsglobal.org/spec/lti/claim/deployment_id", "07940580-b309-415e-a37c-914d387c1150");
Maybe you can reuse the constants for the URLs here :)

2023-11-26 18:04 UTC, basak-akan commented on src/main/java/de/tum/in/www1/artemis/domain/lti/Lti13DeepLinkingResponse.java
> +public class Lti13DeepLinkingResponse {
I am not sure if it fits the criteria for being a record. It contains a custom constructor and methods (validateClaims, getClaims). But sure, I can transfer these methods to LtiDeepLinkingService and implement a static factory method to replace the custom constructor. What do you think?

2023-11-29 15:51 UTC, lennart-keller commented on src/main/java/de/tum/in/www1/artemis/domain/lti/Lti13DeepLinkingResponse.java
> +public class Lti13DeepLinkingResponse {
I guess it's fine to keep it like this.

2023-11-29 15:57 UTC, lennart-keller approved these changes
code lgtm. Thanks for addressing my feedback

2023-11-30 18:14 UTC, laurenzfb submitted a review, later dismissed
Tested in testing session. Worked as expected!

2023-11-30 18:38 UTC, sarpsahinalp submitted a review, later dismissed
Tested in testing session. Worked as expected!

2023-11-30 18:43 UTC, b-fein submitted a review, later dismissed
Code re-approve

2023-11-30 19:41 UTC, vinceclifford submitted a review, later dismissed
Works as expected, tested during testing session

2023-12-02 09:57 UTC, laurenzfb approved these changes
Reapprove

2023-12-04 09:03 UTC, b-fein approved these changes

2023-12-04 09:53 UTC, lennart-keller approved these changes
Recent code changes lgtm

2023-12-04 15:01 UTC, vinceclifford approved these changes
Reapproval

2023-12-04 18:30 UTC, sarpsahinalp approved these changes
Re-approve

2023-12-04 22:55 UTC, merged