`Development`: Add JavaDocs to UtilServices and Factories [14]
ls1intum/Artemis pull request #7470
Opened 2023-10-29 20:19 UTC by DominikRemo

### Checklist
#### General
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context

Improve the readability of UtilServices and Factories by adding JavaDoc to the helper methods

### Description

Added documentation to following files:
- [ ] user/UserFactory.java
- [ ] user/UserUtilService.java

### Review Progress

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2

2023-11-13 10:15 UTC, LenaKahle reviewed
Looks good, but the spelling of "User" is inconsistent. From what I can see, it is always capitalized in the main description, but in the parameter description sometimes not:      
     * @param loginPrefix        The prefix that will be added in front of every user's login
     * @param commonPasswordHash The password hash that will be set for every user
in other places, "User" is also capitalized in the parameter descriptions:
     * @param prefix              The prefix for the User login

2023-11-15 10:25 UTC, xHadie requested changes

2023-11-15 10:36 UTC, JanaNF reviewed
You used quite a lot of passive voice, please consider rephrasing these sentences. To find the talked about passages you can copy your JavaDoc into Grammarly.

In Addition, have a look at my comments below.

2023-11-15 10:36 UTC, JanaNF commented on src/test/java/de/tum/in/www1/artemis/user/UserUtilService.java
> +     * @param registrationNumberPrefix The prefix that will be added in front of every user's registration number
"user's" is written in lower case - inconsistent style

2023-11-15 10:36 UTC, JanaNF commented on src/test/java/de/tum/in/www1/artemis/user/UserUtilService.java
> +     * @param loginPrefix        The prefix that will be added in front of every user's login
"user's" is written in lower case - inconsistent style

2023-11-15 10:36 UTC, JanaNF commented on src/test/java/de/tum/in/www1/artemis/user/UserUtilService.java
> +     * @param commonPasswordHash The password hash that will be set for every user
"user" is written in lower case - inconsistent style

2023-11-15 10:36 UTC, JanaNF commented on src/test/java/de/tum/in/www1/artemis/user/UserUtilService.java
> +     * @param groups             The groups that the users will be added to
"users" is written in lower case - inconsistent style

2023-11-15 10:36 UTC, JanaNF commented on src/test/java/de/tum/in/www1/artemis/user/UserUtilService.java
> +     * @param authorities        The authorities that the users will have
"users" is written in lower case - inconsistent style

2023-11-15 10:36 UTC, JanaNF commented on src/test/java/de/tum/in/www1/artemis/user/UserUtilService.java
> +     * @param amount             The amount of users to generate
"users" is written in lower case - inconsistent style

2023-11-15 10:36 UTC, JanaNF commented on src/test/java/de/tum/in/www1/artemis/user/UserUtilService.java
> +     * @param loginPrefix        The prefix that will be added in front of every user's login
"user's" is written in lower case - inconsistent style

2023-11-15 10:36 UTC, JanaNF commented on src/test/java/de/tum/in/www1/artemis/user/UserUtilService.java
> +     * @param commonPasswordHash The password hash that will be set for every user
"user" is written in lower case - inconsistent style

2023-11-15 10:36 UTC, JanaNF commented on src/test/java/de/tum/in/www1/artemis/user/UserUtilService.java
> +     * @param groups             The groups that the users will be added to
"users" is written in lower case - inconsistent style

2023-11-15 10:36 UTC, JanaNF commented on src/test/java/de/tum/in/www1/artemis/user/UserUtilService.java
> +     * @param authorities        The authorities that the users will have
"users" is written in lower case - inconsistent style

2023-11-15 10:36 UTC, JanaNF commented on src/test/java/de/tum/in/www1/artemis/user/UserUtilService.java
> +     * Creates and saves the provided number of students, tutors, editors and instructors. Also creates and saves an admin User if it does not exist.
The first sentence appears to be a fragment - please consider rewriting is as a complete sentence.
Please consider changing` "Also ..."` to `"It also .." `

2023-11-15 10:36 UTC, JanaNF commented on src/test/java/de/tum/in/www1/artemis/user/UserUtilService.java
> +     * corresponding role. The admin User's login is "admin". To avoid accumulating a high number of Users per Course, this method also removes existing users from Courses before
Please consider rephrasing the sentence "To avoid.." in a better way to make it more understandable

2023-11-15 10:36 UTC, JanaNF commented on src/test/java/de/tum/in/www1/artemis/user/UserUtilService.java
> +     * @param prefix The prefix that will be added in front of every user's login
"user's" is written in lower case - inconsistent style

2023-11-15 14:30 UTC, LenaKahle approved these changes
Approve.

2023-11-15 15:18 UTC, laadvo approved these changes
Looks good :+1:

2023-11-15 15:20 UTC, merged