`General`: Fix button authorities using jhiHasAnyAuthority
ls1intum/Artemis pull request #7471
Opened 2023-10-29 21:10 UTC by JohannesStoehr

### Checklist
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).

### Motivation and Context

Fix #7467 and other similar problems related to `jhiHasAnyAuthority` leading to visible buttons that should not be visible.

### Description

`jhiHasAnyAuthority` only checks that the user has that authority in any course. So an instructor or tutor in one course could be a student in another but the directive would still show this html element to the user. Instead `isAtLeastTutor` and similar attributes of courses and exercises should be used in an `ngIf`.
If the whole route is already reserved for specific authorities, there is no use in checking them again inside the html.

The only visible change to the UI should be the button mentioned in the issue, the rest is removal and refactoring of redundant code.

### Steps for Testing

Prerequisites:
- 1 Instructor 
- 1 Student that is instructor in another course

1. Log in to Artemis
2. Create a competency as instructor
3. View the competency as the student that is instructor in another course
4. Check that there is no edit button on the right in the header

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked

![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test9)

### Review Progress

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

2023-10-29 21:20 UTC, Hialus submitted a review, later dismissed
Code changes looks good to me. 👍🏻

2023-10-29 21:45 UTC, JanaNF approved these changes
Manual tested on legacy ts2. Worked as expected

2023-10-30 07:09 UTC, MaximilianAnzinger approved these changes
Code lgtm

2023-10-30 10:22 UTC, Strohgelaender commented on src/main/webapp/app/course/competencies/competency.service.ts
>              res.body.exercises.forEach((exercise) => ExerciseService.parseExerciseCategories(exercise));
Can you also set the access rights for the exercises here for consitency?

2023-10-30 10:58 UTC, sarpsahinalp approved these changes
Tested on ts2. Works as expected!

2023-10-30 14:23 UTC, egekurt123 approved these changes
Works as expected on ts2

2023-10-30 15:09 UTC, Strohgelaender submitted a review, later dismissed
code

2023-10-30 15:42 UTC, Gusti2010 approved these changes
tested on ts1 and works as expected!

2023-10-30 22:22 UTC, JanaNF submitted a review, later dismissed
Manual tested on legacy ts2. Worked as expected

2023-10-30 22:53 UTC, MaximilianAnzinger submitted a review, later dismissed
code

2023-10-30 22:54 UTC, vinceclifford requested changes
Tested on TS3. Tested with user nr. 4 as a student. Instructors were user nr. 13 & 14. However, the student was able to edit the competency. Tested on the course Vincent-Test-Course2

<img width="1010" alt="image" src="https://github.com/ls1intum/Artemis/assets/79379318/c8f9dc0e-d507-4afc-a102-925f0e17009e">
<img width="1010" alt="image" src="https://github.com/ls1intum/Artemis/assets/79379318/2d53d632-33dc-41e1-a15b-2a9a67a7e5ce">

2023-11-02 09:37 UTC, MaximilianAnzinger approved these changes

2023-11-03 17:17 UTC, vinceclifford approved these changes
Reapproved. Tested on ts2

2023-11-04 17:55 UTC, JanaNF approved these changes
Tested again on ts2. Still works

2023-11-04 20:43 UTC, Hialus approved these changes
Reapprove code

2023-11-05 14:37 UTC, merged