`General`: Fix exercise category selection
ls1intum/Artemis pull request #7473
Opened 2023-10-30 14:25 UTC by florian-glombik

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [ ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exam_mode/) as reference.
4. ...

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked

![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test9)

### Review Progress

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2023-11-05 11:48 UTC, JanaNF approved these changes
Manual tested on legacy ts2. Worked as expected. 

I have noticed two things:
1. If there is already an added category and you write something in the line, the text is not  aligned in the middle. Perhaps you should consider changing this because it will look tidier.
2. The color picker is sometimes placed somewhere and not very near to the category.

2023-11-05 18:22 UTC, MaximilianAnzinger approved these changes
Code lgtm

2023-11-05 22:59 UTC, florian-glombik commented
Thanks for your reviews!

@JanaNF I am planning on addressing bought suggestions in a follow-up, as this PR already fixes a bunch of issues related to the categories! :)

2023-11-06 16:51 UTC, milljoniaer submitted a review, later dismissed
Code looks good, just one typo, but no blocker. LGTM 👍

2023-11-06 16:51 UTC, milljoniaer commented on src/main/webapp/app/shared/category-selector/category-selector.component.ts
> +         * without {@link event#stopPropagation} would the color picker would close immediately as the mouseEvent
Typo, one "would" is sufficient

2023-11-08 09:34 UTC, JanaNF submitted a review, later dismissed
Reapproved. Manual tested on legacy ts2. Still works. (And thanks for creating the issue with the alignment :))

2023-11-09 11:23 UTC, milljoniaer approved these changes

2023-11-10 21:53 UTC, MaximilianAnzinger submitted a review, later dismissed

2023-11-11 07:49 UTC, milljoniaer approved these changes
re-approve

2023-11-11 09:50 UTC, MaximilianAnzinger approved these changes
Code

2023-11-11 14:12 UTC, basak-akan approved these changes
Tested on TS1, works as described.

2023-11-11 17:16 UTC, JanaNF requested changes
Manual tested on ts2. Things described worked as expected, but if I add a category, which name is longer than the text field, the name goes over the text field layout. 
![image](https://github.com/ls1intum/Artemis/assets/41042413/c99d9ac2-af68-456e-80b8-c2fbbb2a3ed1)

2023-11-13 13:18 UTC, merged