`Exam mode`: improve attendance check with websocket based id information
ls1intum/Artemis pull request #7476
Opened 2023-10-30 16:57 UTC by max-bergmann

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [ ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exam_mode/) as reference.
4. ...

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked

![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test9)

### Review Progress

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2023-11-08 11:04 UTC, JohannesStoehr requested changes

2023-11-08 11:04 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/web/rest/StudentExamResource.java
> +                .orElseThrow(() -> new EntityNotFoundException("User with login: \"" + studentLogin + "\" does not exist"));
We often have "ElseThrow" variants of the database retrievals. Can you also add one for this query and replace the other calls to this method as well?

2023-11-08 11:04 UTC, JohannesStoehr commented on src/main/webapp/i18n/de/exam.json
> +                        "description": "Eine Klausur-Aufsicht hat die Anwesenheitskontrolle für Dich ausgelöst. Bitte folge den Anweisungen der Aufsicht.",
```suggestion
                        "description": "Eine Klausur-Aufsicht hat die Anwesenheitskontrolle für dich ausgelöst. Bitte folge den Anweisungen der Aufsicht.",
```

2023-11-12 20:55 UTC, JohannesStoehr approved these changes
Code looks good to me

2023-11-13 07:41 UTC, MichaelOwenDyer approved these changes
Code looks good

2023-11-13 08:28 UTC, milljoniaer submitted a review, later dismissed
Tested on ts4, works as expected 👍

2023-11-13 08:44 UTC, valentin-boehm submitted a review, later dismissed
Tested on TS4 👍

2023-11-13 08:56 UTC, RY997 approved these changes
Tested on TS4

2023-11-13 09:49 UTC, bassner commented on src/main/java/de/tum/in/www1/artemis/web/rest/StudentExamResource.java
> +        studentExam.getUser().setVisibleRegistrationNumber();
This is not needed, correct? You're only using the studentExam id further down

2023-11-13 10:20 UTC, Strohgelaender commented on src/main/java/de/tum/in/www1/artemis/domain/exam/event/ExamAttendanceCheckEvent.java
> + * An event indicating an updated working time for a specific student exam.
copied javadoc.

2023-11-13 12:54 UTC, Strohgelaender commented
How does this event get triggerd? Only from the attendance check app? I don't see a way to fire this event as an instructor by looking at the code changes?

I think the long text "An exam supervisor has triggered the attendance check for you. Please follow the instructions of the supervisor." is unnecessary, especially considering the the responsible instructor should already by standing next to the student and be talking to the student when this popup shows up. I'd like to see that removed, but this can also be done in a followup considering the time pressure.

Your screenshot does not include the registration number, but it gets set when calling `own-student-exam`. Why is this the case? I think this information should be added to the popup.

2023-11-13 12:59 UTC, Strohgelaender approved these changes
code aproved, only one optional change:

2023-11-13 12:59 UTC, Strohgelaender commented on src/main/webapp/app/exam/shared/events/exam-live-event.component.html
> +                    <tr *ngIf="examAttendanceCheckEvent.text && examAttendanceCheckEvent.text.length > 0">
![grafik](https://github.com/ls1intum/Artemis/assets/26540346/aa994d63-c75c-4fa5-83a6-a52e973a7300)

```suggestion
                    <tr *ngIf="examAttendanceCheckEvent.text">
```

2023-11-13 13:16 UTC, merged