`Development`: Update programming exercise grading documentation
ls1intum/Artemis pull request #7511
Opened 2023-11-05 13:20 UTC by Strohgelaender

### Checklist
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context

### Description

### Steps for Testing
view the documentation

### Review Progress

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2

2023-11-05 18:13 UTC, tobias-lippert requested changes
Please do not use test users in your videos. Either cut out the navbar post production or use a TUM Login.

2023-11-05 21:46 UTC, tobias-lippert submitted a review, later dismissed
LGTM now

2023-11-06 09:09 UTC, xHadie requested changes
Overall pretty good and understandable, but there are some grammar mistakes in your changes. I would suggest putting your changes through a grammar checker to polish things up a bit!

2023-11-06 09:59 UTC, simon-hng commented on docs/user/exercises/programming-exercise-setup.inc
> +    <iframe src="https://tum.live/w/artemisintro/40748?video_only=1&t=0" allowfullscreen="1" frameborder="0" width="600" height="400">
```suggestion
    <iframe src="https://tum.live/w/artemisintro/40748/PRES?video_only=1&" allowfullscreen="1" frameborder="0" width="600" height="400">
```

2023-11-06 10:53 UTC, tobias-lippert submitted a review, later dismissed
Reapprove

2023-11-06 11:16 UTC, xHadie approved these changes
LGTM 🙂

2023-11-06 11:16 UTC, tobias-lippert submitted a review, later dismissed
Reapprove

2023-11-06 11:31 UTC, b-fein approved these changes

2023-11-06 11:31 UTC, b-fein commented on docs/user/exercises/programming-exercise-setup.inc
> +#. `Adapt the interactive problem statement`_: Clearly define your exercise in the problem statement Use tasks to create a group of test cases.
```suggestion
#. `Adapt the interactive problem statement`_: Clearly define your exercise in the problem statement. Use tasks to create a group of test cases.
```

2023-11-06 11:34 UTC, b-fein approved these changes

2023-11-06 17:19 UTC, tobias-lippert approved these changes
Reapprove

2023-11-07 10:22 UTC, LenaKahle commented on docs/user/exercises/programming-exercise-import.inc
> +  Instructors can import exercises from courses, where they are registered as instructors
unnecessary comma (from courses where they are registered)

2023-11-07 10:25 UTC, LenaKahle approved these changes
Looks good, I added 2 comments for small grammar/typo issues.

2023-11-07 14:07 UTC, tobias-lippert approved these changes
Reapprove

2023-11-07 14:09 UTC, b-fein approved these changes

2023-11-08 09:05 UTC, JanaNF approved these changes
Looks good

2023-11-08 09:06 UTC, LenaKahle approved these changes
Reapprove.

2023-11-10 06:54 UTC, merged