`Notifications`: Add version to push notifications.
ls1intum/Artemis pull request #7550
Opened 2023-11-08 17:15 UTC by TimOrtel

### Motivation and Context
Currently, we do not send a notification-version to the native clients in push notifications. If we ever want to change the data structure of push notifications, the native clients not using the latest versions may start having issues because they cannot understand that they are receiving a new format and may be interpreting it wrong. This would make it harder to update the format in the future. 

With this small change, we simply add a version field to push notifications, such that we can, in the future, simply increment it on the server and be sure that native clients that do not support the updated push notifications can safely discard them.

2023-11-08 19:43 UTC, jakubriegel requested changes
Code looks ok, please use the official PR description template

2023-11-09 15:01 UTC, nityanandaz approved these changes
I agree with this approach

2023-11-09 21:22 UTC, Strohgelaender requested changes
the java code style checks fail.

2023-11-15 09:46 UTC, rstief approved these changes
Code LGTM

2023-11-15 10:52 UTC, jakubriegel approved these changes
LGTM

2023-11-15 20:47 UTC, merged