`Programming Exercise`: Import also title and shortname
ls1intum/Artemis pull request #7558
Opened 2023-11-09 11:46 UTC by milljoniaer

### Checklist
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context
Stephan requested that we should also import title and shortname for programming exercises.

### Description
This PR removes the cleanup of title and shortname during import of programming exercises.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Navigate to Exercise Administration
3. Click "Import Programming Exercise"
4. Chose an existing Programming Exercise
5. Verify that title and short-name are imported as well (screenshot)

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked

![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test9)

### Review Progress

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots
![image](https://github.com/ls1intum/Artemis/assets/78978542/ee5439a1-f079-451b-9a65-d8c13563b5cb)

2023-11-09 18:10 UTC, JanaNF approved these changes
Manual tested on legacy ts2. Worked as expected.

Feature idea:
Maybe you could implement this for the other exercise types too. For quizzes, this works too, but when I tried this with modeling exercises, the title was not included. Just think about it.

2023-11-09 22:16 UTC, vinceclifford approved these changes
Works as expected, tested on TS2.

2023-11-09 23:27 UTC, florian-glombik approved these changes
Code changes look good

2023-11-10 07:28 UTC, reschandreas submitted a review, later dismissed
code lgtm

2023-11-10 09:52 UTC, JohannesStoehr requested changes

2023-11-10 09:52 UTC, JohannesStoehr commented on src/test/javascript/spec/component/programming-exercise/programming-exercise-update.component.spec.ts
> +            expect(comp.programmingExercise.shortName).toEqual(programmingExercise.shortName);
Can you please move this into verifyImport() as well?

2023-11-10 17:30 UTC, sarpsahinalp approved these changes
Tested on ts2. Works as expected.

2023-11-11 14:21 UTC, basak-akan approved these changes
Tested on TS1, title and short-name are imported while importing programming exercise

2023-11-13 10:35 UTC, MichaelOwenDyer approved these changes
Code looks good to me 👍🏽

2023-11-13 17:35 UTC, JohannesStoehr approved these changes
Code

2023-11-15 15:04 UTC, reschandreas approved these changes
reapprove after code-changes

2023-11-15 20:46 UTC, merged