`Assessment`: Fix score view for accepted complaints
ls1intum/Artemis pull request #7568
Opened 2023-11-10 10:40 UTC by Strohgelaender

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [ ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exam_mode/) as reference.
4. ...

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked

![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test9)

### Review Progress

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2023-11-11 09:54 UTC, JohannesStoehr requested changes
Other than that the code looks good

2023-11-11 09:54 UTC, JohannesStoehr commented on src/main/webapp/app/exercises/shared/exercise-scores/exercise-scores.component.ts
> +            participation.results?.last();
```suggestion
```

2023-11-15 16:06 UTC, Ceiridge commented
- Tested on test2 with @MaximilianJG 
- The score page didn't show anything about assessments or gradings
- The complaints were visible for the student after accepting/rejecting
- Canceling and continuing assessments works
- **But**: Practice mode exercises with submissions are not shown at all in the assessment dashboard and thus also the assessment cannot be started

<img width="391" alt="image" src="https://github.com/ls1intum/Artemis/assets/40047520/eeac1071-b1de-401c-ab0c-0bccaf18915b">

<img width="710" alt="image" src="https://github.com/ls1intum/Artemis/assets/40047520/21d6bfb0-28be-49d0-b041-568b93e9c596">

2023-11-15 16:07 UTC, MaximilianJG commented
Worked mainly as expected on test server 2. (Testing session with @Ceiridge) 

Student was able to create a complaint, which we could assess. This complaint was then sent to the student which he could then view. We were also able to save and continue / cancel assessments. 

Nonetheless we had one issue. When the student started a practice exercise submission this was not viewable in the assessment dashboard. (only the actual submission) 
<img width="1160" alt="Screenshot 2023-11-15 at 17 04 34" src="https://github.com/ls1intum/Artemis/assets/64839680/be811e1f-820e-4db8-a0cd-71ebd9242b2d">

2023-11-15 16:09 UTC, Strohgelaender commented
> But: Practice mode exercises with submissions are not shown at all in the assessment dashboard and thus also the assessment cannot be started

That's correct and expected. Practice mode submission are just for the student to try out changes, they are not assessable and should not show up here. The issue fixed in this PR was that on the scores page an additional "assess submission" was shown, even though assessment should not be allowed.

2023-11-27 16:45 UTC, tobias-lippert submitted a review, later dismissed
Code LGTM

2023-12-01 17:52 UTC, maximiliansoelch approved these changes
Code looks good.
Tested on legacy ts1 and works as described. 

Just found a minor styling issue that was not introduced in this PR but should be fixed either here or in a follow-up.

2023-12-01 17:52 UTC, maximiliansoelch commented on src/main/webapp/app/exercises/shared/exercise-scores/manage-assessment-buttons.component.html
> +                class="btn btn-danger btn-sm mb-1"
Noticed that the _cancel assessment_ button is misaligned compared to the _continue assessment_ button.
It was not introduced by this PR, but should be fixed anyway:
![image](https://github.com/ls1intum/Artemis/assets/9954674/bb5b6a86-d936-41cd-b47a-5b76b13b1e1c)

```suggestion
                class="btn btn-sm me-1 mb-2 btn-danger"
```

2023-12-01 19:27 UTC, maximiliansoelch approved these changes
Reapprove after style correction commit

2023-12-01 22:52 UTC, merged