`Adaptive learning`: Fix score display for competency details view
ls1intum/Artemis pull request #7617
Opened 2023-11-18 08:16 UTC by MaximilianAnzinger

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [ ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exam_mode/) as reference.
4. ...

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked

![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test9)

### Review Progress

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2023-11-28 21:23 UTC, JanaNF submitted a review, later dismissed
Manual tested on legacy_ts2. Worked as expected.

2023-11-29 19:31 UTC, Strohgelaender requested changes
Do we really need all submissions and all results? Consider if only the latest submission / result is also fine.

Also note that some results should ne be sent to the user, e.g. if a manual assessment ist done but the assessment due date is not over yet. Simply loading all results here is not correct.

2023-12-01 09:58 UTC, lennart-keller approved these changes
Code lgtm :)

2023-12-01 09:59 UTC, MaximilianAnzinger commented on src/main/java/de/tum/in/www1/artemis/repository/CompetencyRepository.java
> +     * Fetches a competency with all linked exercises, lecture units, the associated participations, progress, and completion of the specified user.
```suggestion
     * Fetches a competency with all linked exercises, lecture units, the associated progress, and completion of the specified user.
```

2023-12-01 10:00 UTC, lennart-keller approved these changes
Reapprove code

2023-12-02 03:57 UTC, Ceiridge commented
It's not possible to add a programming exercise to a competency, but only text units for example:
![image](https://github.com/ls1intum/Artemis/assets/40047520/3adea08a-f4fb-4659-b074-474536b43e53)

2023-12-06 12:35 UTC, Gusti2010 approved these changes
Tested on TS11_Legacy. Works as expected!

![image](https://github.com/ls1intum/Artemis/assets/93329151/5da3cf3e-9d1f-4910-b5c2-3ed0d4fc0b24)

2023-12-06 16:16 UTC, georgyia approved these changes
tested manually on ts2, works as expected

2023-12-08 16:00 UTC, LenaKahle approved these changes
Approve, tested on legacy ts11.

2023-12-15 23:41 UTC, merged