`Communication`: Show messaging page if only communication is enabled
ls1intum/Artemis pull request #7622
Opened 2023-11-18 14:43 UTC by lennart-keller

### Checklist
#### General

- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).(https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

We are in the process of unifying the communication and messaging pages of Artemis. Even if only communication is enabled, the messaging page should be used to create new messages.

### Description

If communication is enabled, also the messaging page will be activated in the course. However, it only shows course-wide channels. The client also hides buttons to create new channels, group chats, and one-to-one chats and the server only allows to create these if messaging is enabled.

### Steps for Testing

Prerequisites:
- 1 Instructor (to change course settings)
- 1 Student

1. Deactivate messaging and communication in a course
    1. Neither the communication tab or messaging tab should be visible
    2. On a lecture/exercise details page, there is no "communication" sidebar to the right
2. Activate communication
    1. Both the communication tab and messaging tab should be visible
    2. The messaging tab should only show course-wide channels (no group chats etc.)
    3. Test all the buttons you see with both the instructor and students (hide, favorite, settings, "go to exercise", ...)
    4. Write some messages and check this works on lecture/exercise pages and the messages tab
    5. Write a message with a user mention: Clicking on the mention should NOT open a one-to-one chat
3. Add both communication and messaging
    1. Now, also group chats and one-to-one messages should be visible. Check you can create new ones.
4. Disable communication
    1. The communication tab is hidden, the messages tab stays the same

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked

![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test9)

### Review Progress

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

If only communication is enabled, the messaging tab will still be shown. However, the sidebar only shows course-wide channels and hides buttons to create new channels, group chats and one-to-one chats:
![communication-only](https://github.com/ls1intum/Artemis/assets/44754405/94d5da51-02e9-4c8d-870b-ae22fa54d68e)

If messaging is enabled, the sidebar shows group chats etc.:
![communication-and-messaging](https://github.com/ls1intum/Artemis/assets/44754405/52128bdd-4be2-43d6-baad-2f142e1f02b8)

2023-11-19 22:37 UTC, JanaNF reviewed
Tried to test on legacy_ts11 and legacy_ts2 but I couldn’t connect to the server. 

I wrote with Laurenz and he said:
_A new config variable was introduced by a PR, but this is not included in the config for TS11. This is why it always fails at startup.
I think the PR was merged without regard to the config change and is now causing problems on all test servers where the config has not yet been adjusted
The PR with the config change is already in Develop and I suspect that if your PRs are running with the latest changes from Develop, then there will be problems_

I think your PR is affected.

2023-11-20 14:30 UTC, JanaNF approved these changes
I could test your PR on legacy_ts11 again :tada: Worked as expected.

2023-11-21 00:07 UTC, AntonGeTUM submitted a review, later dismissed
Tested on TS11, works as described

2023-11-21 09:58 UTC, MaximilianAnzinger requested changes
Mostly looks good.

Left some susgestions & ArchitectureTest fails.

2023-11-21 10:06 UTC, lennart-keller commented on src/main/java/de/tum/in/www1/artemis/service/metis/ConversationMessagingService.java
> +        log.debug("      conversationMessageRepository.save DONE");
These should stay (for now)

2023-11-21 10:12 UTC, lennart-keller commented on src/main/java/de/tum/in/www1/artemis/service/metis/conversation/ChannelService.java
> +        if (channel == null) {
You are right, I moved the null check to another place, where it makes more sense.

2023-11-21 10:22 UTC, lennart-keller commented on src/main/webapp/app/overview/course-conversations/layout/conversation-selection-sidebar/conversation-selection-sidebar.component.html
This already is a helper boolean, which is just set once in `ngOnInit`

2023-11-21 10:24 UTC, lennart-keller commented on src/main/webapp/app/course/manage/course-management-tab-bar/course-management-tab-bar.component.html
> +        <a class="tab-link" *ngIf="isMessagingEnabled(course) || isCommunicationEnabled(course)" [routerLink]="['/courses', course.id, 'messages']" routerLinkActive="active">
I created helper variables

2023-11-21 10:43 UTC, MaximilianAnzinger approved these changes
Thx for integrating my suggestions LGTM 👍

2023-11-21 10:47 UTC, basak-akan approved these changes
Code looks good 👍

2023-11-21 12:48 UTC, sarpsahinalp approved these changes
Manually tested on ts2. Seems to be working!

2023-11-22 09:29 UTC, reschandreas approved these changes
retested locally after demonstration in testing session two days ago, works as expected! also thanks for fixing the unrelated issues found in the testing session!

2023-11-22 09:53 UTC, Gusti2010 commented
tested manually on ts11_Legacy. Works as expected!

2023-11-22 09:54 UTC, Gusti2010 approved these changes
tested manually on ts11_Legacy. Works as expected!

2023-11-22 09:57 UTC, rstief approved these changes
tested on ts2. Everything works as expected.

2023-11-22 15:08 UTC, merged