`Development `: Add database tests run configurations and docs
ls1intum/Artemis pull request #7658
Opened 2023-11-23 14:13 UTC by jakubriegel

### Checklist
#### General
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context

### Description

### Steps for Testing
- read the docs and verify if they are clear
- checkout the branch and run database tests from IntelliJ

### Review Progress
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2

2023-11-23 15:12 UTC, JanaNF requested changes
The documentation is easy to understand. 
I checked your documentation with Grammarly. Have a look at my comments and please consider changing some sentences.

2023-11-23 15:12 UTC, JanaNF commented on docs/dev/setup/local-database-tests.rst
> +Before running those tests make sure that the following steps were executed:
Missing "," after "those tests".
Please consider not using passive voice and therefore rephrasing the "Before running..." sentence.

2023-11-23 15:12 UTC, JanaNF commented on docs/dev/setup/local-database-tests.rst
> +Database tests can be executed by running of the run configurations provided in the repository:
Please consider not using passive voice and therefore rephrasing the "Database tests..." sentence.
In the same sentence "of" is not needed. You can remove it.

2023-11-23 15:12 UTC, JanaNF commented on docs/dev/setup/local-database-tests.rst
> +Or by creating a custom configuration. Screenshot below presents an example of such run configuration:
I would change "Or ..." --> to  "Or alternatively, ..."
Add an article to "Screenshot ..." --> "The screenshot ..."
Add "a" before "... such run ..." --> "... such a run ..."

2023-11-23 15:12 UTC, JanaNF commented on docs/dev/setup/local-database-tests.rst
> +Executing tests from console
Add an article to "... console" --> "... the console"

2023-11-23 15:12 UTC, JanaNF commented on docs/dev/setup/local-database-tests.rst
> +Database tests can be executed by running the dedicated Gradle command:
Please consider not using passive voice and therefore rephrasing the "Database tests..." sentence.

2023-11-23 18:37 UTC, sarpsahinalp commented on docs/dev/setup/local-database-tests.rst
> +   :alt: An example of IntelliJ run configuration fro starting Postgres server tests.
Typo here in fro, should be from.

2023-11-23 20:24 UTC, b-fein commented on docs/dev/setup/local-database-tests.rst
> +   :align: center
```suggestion
   :align: center
   :scale: 50 %
```
The screenshot is pretty big and filly nearly the complete screen without scaling.

2023-11-23 20:24 UTC, b-fein commented on docs/dev/setup/local-database-tests.rst
> +Database tests are standard server integration tests executed against real database (MySQL or Postgres) started as Docker containers. Gradle test task will automatically pull necessary images and sta
```suggestion
Database tests are the standard server integration tests executed against a real database (MySQL or Postgres) started as Docker containers. The Gradle test task will automatically pull the necessary images and start the containers.
```

2023-11-23 20:24 UTC, b-fein commented on docs/dev/setup/local-database-tests.rst
> +Before running those tests, make sure that the following steps were executed:
```suggestion
Before running those tests, make sure you have got a working Docker setup:
```

2023-11-23 20:24 UTC, b-fein commented on docs/dev/setup/local-database-tests.rst
> +1. Install `Docker Desktop <https://docs.docker.com/desktop/#docker-for-mac>`__ or `Docker Engine and Docker CLI <https://docs.docker.com/engine/install/>`__.
```suggestion
1. Install `Docker Desktop <https://docs.docker.com/desktop/>`__ or `Docker Engine and Docker CLI <https://docs.docker.com/engine/install/>`__.
```
Non-mac-specific link

2023-11-23 20:24 UTC, b-fein commented on docs/dev/setup/local-database-tests.rst
> +2. Enable `remote access for Docker daemon <https://docs.docker.com/config/daemon/remote-access/>`__.
```suggestion
2. Enable `remote access for the Docker daemon <https://docs.docker.com/config/daemon/remote-access/>`__.
```

2023-11-23 23:20 UTC, JanaNF approved these changes

2023-11-24 13:40 UTC, b-fein approved these changes

2023-11-24 15:05 UTC, egekurt123 approved these changes
LGTM

2023-11-26 13:10 UTC, sarpsahinalp approved these changes

2023-11-26 22:12 UTC, krusche approved these changes

2023-11-26 22:12 UTC, merged