`Development`: Add documentation describing password and secret handling in production setups
ls1intum/Artemis pull request #7688
Opened 2023-11-29 08:21 UTC by b-fein

### Checklist

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context
The Artemis configuration files contain a few secrets/passwords that should be changed before using Artemis in production instances.

### Description
Adds a documentation page for administrators to inform them which passwords and secrets have to be changed.

The name of the environment variable describing the JWT secret was incorrect. According to [Spring relaxed binding rules](https://github.com/spring-projects/spring-boot/wiki/Relaxed-Binding-2.0#environment-variables) `base64-secret` in the YAML has to be represented as `BASE64SECRET` since `_` are reserved for `.` in the YAML (i.e., the previous env-name would point to a value `base64.secret` instead).

Additional change:
Removes the default value for the JWT secret token since that *has* to be changed for a production setup to not accidentally allow insecure production instances.
Note: Technically, this is a breaking change for administrators that forgot to actively set a value here. This should be noted as part of the release notes.

### Steps for Testing
Look at https://artemis-platform--7688.org.readthedocs.build/en/7688/admin/setup/security.html and check for understandability, formatting, and typos.

### Review Progress

#### Code Review
- [x] Code Review 1
- [x] Code Review 2

2023-11-29 10:38 UTC, LenaKahle submitted a review, later dismissed
Approve.

2023-11-29 12:44 UTC, egekurt123 reviewed
One small spelling mistake,

2023-11-29 12:44 UTC, egekurt123 commented on docs/admin/setup/security.rst
> +that have to be overriden in your own configuration files or via environment
overriden -> overridden (with double d)

2023-11-29 13:10 UTC, xHadie approved these changes
Looks good!

2023-11-29 13:57 UTC, MaximilianJG commented
Understandability, formatting is pretty good. No Typos as far as I can see. LGTM!

2023-11-29 15:02 UTC, egekurt123 approved these changes

2023-11-30 01:40 UTC, sarpsahinalp approved these changes
Ran the changes through Grammerly. It seems to be passing!

2023-12-02 04:01 UTC, Ceiridge requested changes

2023-12-02 04:01 UTC, Ceiridge commented on docs/admin/setup/security.rst
> +    Without replacing the default values the connection to them will not work.
It would be great for better understanding to add commas. For example:
`Without replacing the default values, the connection to them will not work.`

2023-12-02 04:01 UTC, Ceiridge commented on docs/admin/setup/security.rst
> +    Jenkins, …) are not listed here since the general setup documentation
`here, since`

2023-12-02 04:01 UTC, Ceiridge commented on docs/admin/setup/security.rst
> +    Ensure restrictive access to the configuration files so that access is only
`files, so that`

2023-12-03 16:19 UTC, LenaKahle approved these changes
Re-approve.

2023-12-03 16:47 UTC, Ceiridge approved these changes
Very well done :)

2023-12-04 20:46 UTC, dfuchss approved these changes
lgtm

2023-12-04 22:35 UTC, merged