`Exercices`: Set the maximum length of characters in the categories section at 25
ls1intum/Artemis pull request #7767
Opened 2023-12-10 22:59 UTC by yassinsws

#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [ ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes Affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description
Made the maximum length of characters equals 25. 
### Steps for Testing
Prerequisites:
- 1 Instructor
- Try to create an exercise and define a category with more than 25 characters.

2023-12-11 08:31 UTC, rstief approved these changes
tested on ts1, worked as expected.

2023-12-11 08:46 UTC, RY997 approved these changes
Code LGTM

2023-12-11 09:25 UTC, dearjasmina approved these changes
code lgtm

2023-12-11 10:22 UTC, AntonGeTUM approved these changes
Tested on ts11, works as described

2023-12-11 10:40 UTC, LenaKahle approved these changes
Approve, tested on legacy ts2.

2023-12-11 10:52 UTC, bensofficial requested changes
Wouldn't it make sense to check the length limit on the server as well?
Client-side limits can probably be circumvented quite easily.

2023-12-11 14:17 UTC, Hialus requested changes
> Wouldn't it make sense to check the length limit on the server as well? Client-side limits can probably be circumvented quite easily.
> 
> In my opinion the limits should be the same for client, server, and database. The database column is currently [limited to 255 chars](https://github.com/ls1intum/Artemis/blob/3f0878371d18ccba1d991febe15254b142f280fc/src/main/resources/config/liquibase/changelog/00000000000000_initial_schema.xml#L378C9-L383C23). Changing the limit within the database is probably not as easy as we have to think about what we do with the already existing categories longer than the limit.

I agree with Benjamin here. If you limit the value in the client, then you should also limit it on the server. Please note that this means that the values have to be synced and therefore placed in proper constant files ideally.
Though adjusting it in the database will be difficult when considering existing data.

I think a better solution might be to instead improve the display of long categories on the client side without changing the max allowed length

2023-12-11 23:10 UTC, Predixx approved these changes
tested on ts2. It showed no category after I made one with too many chars

2023-12-13 11:54 UTC, Gusti2010 approved these changes
Tested on TS_11 Legacy. Works as expected!

2023-12-13 13:58 UTC, konrad2002 approved these changes
tested on legacy ts11, worked as expected

2023-12-13 14:13 UTC, egekurt123 approved these changes
Manually tested on ts5, works as expected

2023-12-13 19:24 UTC, MaximilianJG approved these changes
Tested on T2: Working as expected. Can't define a category with more than 5Char. 

![Screenshot 2023-12-13 at 20 24 32](https://github.com/ls1intum/Artemis/assets/64839680/2710b2be-7878-4989-bea5-f430dd2814e0)

2023-12-14 03:39 UTC, georgyia approved these changes
tested manually on ts3, works as expected

2024-01-05 12:04 UTC, closed without merging