`Development`: Update components to use self closing html tags & add linter rule
ls1intum/Artemis pull request #7802
Opened 2023-12-18 09:34 UTC by aplr

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context

HTML tags for custom components are long and verbose. This leads to a lot of typing, selecting, scrolling, and reading. For a lot of our custom components, we don't even need the closing tags, as they don't have any slots / children.

With HTML linting now enabled, this gives us the opportunity to prefer self-closing html tags in order to make the code less verbose and more readable

### Description

* Added eslint rule which warns when empty closing tags are present: `@angular-eslint/template/prefer-self-closing-tags`
* Ran `eslint --fix` to automatically re-format html w/ closing tags. 
* As `eslint --fix` is run on pre-commit, developers don't really have to do anything, the code will fix itself.

### Steps for Testing

Lint:
* Create HTML tag without content
* eslint warning should appear, suggesting to prefer self-closing tags

Fix:
* Create HTML tag without content
* run `eslint --fix`
* empty html tag should be reformatted to self-closing tag

Nothing to test manually really, it's just `eslint --fix`.

2023-12-18 13:37 UTC, xHadie requested changes
The automatic refactoring did not work as expected. Some componenets appear to be getting completely removed.

2023-12-18 13:37 UTC, xHadie commented on src/main/webapp/app/admin/audits/audits.component.html
There seems to be an issue. The `</fa-icon>` was removed and we now have `<th/><th/>` instead.
Probably because `</fa-icon>` was supposed to be `<fa-icon/>`. This hinders the automatical tag fixing.

2023-12-18 15:17 UTC, aplr commented on src/main/webapp/app/admin/audits/audits.component.html
@xHadie where exactly do you observe such a behaviour? Does this break actual components, or do you just observe this from the code?

2023-12-18 16:18 UTC, xHadie commented on src/main/webapp/app/admin/audits/audits.component.html
I commented on the audits.component.html where the issue was observeable in the github diff view, but for some reason it disappeared and looks fine now. Might have been a local issue with my browser.
Sorry for the confusion!

2023-12-18 16:18 UTC, xHadie approved these changes

2024-01-08 08:42 UTC, Strohgelaender commented
IntelliJ complains about empty tags:
![grafik](https://github.com/ls1intum/Artemis/assets/26540346/369508cc-4fb1-48fe-b032-2066864a6814)

Do you know if this is valid? Or is this just an issue for plain HTML pages and not for angular applications?

2024-01-08 09:21 UTC, aplr commented
> IntelliJ complains about empty tags: ![grafik](https://private-user-images.githubusercontent.com/26540346/294847492-369508cc-4fb1-48fe-b032-2066864a6814.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDU2NDksIm5iZiI6MTcwNDcwNTM0OSwicGF0aCI6Ii8yNjU0MDM0Ni8yOTQ4NDc0OTItMzY5NTA4Y2MtNGZiMS00OGZlLWIwMzItMjA2Njg2NGE2ODE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA5MTU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhYjM2OTVkYzg1YzFkNzFmZDBiNjdjZjM1Njk5NDNjZjJhZTNkM2U1NGVjZDhkNDk3MzU3NGU1ZjQ5MzY3MTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zKfW1Nn-ge0-KIrRhM8_qs2dX47J1o_SmV9GeJVEaKs)
> 
> Do you know if this is valid? Or is this just an issue for plain HTML pages and not for angular applications?

Ah yea, also saw this. I guess IntelliJ does not recognize the tag as an angular component. Could be a custom web component as well, which does not undergo compilation pipelines. I will have a check, but as it [was announced as a feature with angular 16](https://blog.angular.io/angular-v16-is-here-4d7a28ec680d), we should be fine :)

2024-02-16 06:47 UTC, closed without merging