`Plagiarism checks`: Fix comparison highlighting
ls1intum/Artemis pull request #7854
Opened 2024-01-07 14:41 UTC by jakubriegel

### Checklist
#### General
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [ ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exam_mode/) as reference.
4. ...

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked

![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test9)

### Review Progress

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2024-01-11 07:19 UTC, b-fein commented
The new ordering of the elements in the last commit seems to have fixed the problem. The pairs that are matched now make sense. ⇒ I guess the original problem described in issue #6579 is fixed.

However, I‘m not sure if the new column calculation is correct (don’t know how it looked like before). There are quite a few places where the highlighting ends in the middle of tokens:
![image](https://github.com/ls1intum/Artemis/assets/64250573/92402195-9ed9-4ad9-9be9-c693bbf57adf)

2024-01-11 10:28 UTC, MarkusPaulsen reviewed
Code looks good, waiting for reviews.

2024-01-14 12:27 UTC, nata-81 submitted a review, later dismissed
tested on ts5:
  text: with users 1 and 2 works as expected.
  programming exercise: try to test with 1 but could not start the exercise. then with users 
  2 and 3 and received this error: 
<img width="1165" alt="image" src="https://github.com/ls1intum/Artemis/assets/67416888/b14d4c1f-78ec-4020-b9c6-163ba7f2576c">
What is the problem why can't I see the comparison? Thank you in advance!

2024-01-14 12:41 UTC, jakubriegel commented
> tested on ts5:
> 
>   text: with users 1 and 2 works as expected.
> 
>   programming exercise: try to test with 1 but could not start the exercise. then with users 
> 
>   2 and 3 and received this error: 
> 
> <img width="1165" alt="image" src="https://github.com/ls1intum/Artemis/assets/67416888/b14d4c1f-78ec-4020-b9c6-163ba7f2576c">
> 
> What is the problem why can't I see the comparison? Thank you in advance! 

TS5 has some issues with GitLab integration. You can try on TS1 where the set up works fin

2024-01-14 12:50 UTC, konrad2002 approved these changes
manually tested on legacy ts1, works as expected

2024-01-14 13:19 UTC, basak-akan submitted a review, later dismissed
Tested on TS1 for fix 2 and 3, worked well. Also code lgtm.

2024-01-14 19:35 UTC, xHadie approved these changes
_Manually tested on TS11_Legacy_
Works as expected!

2024-01-14 20:48 UTC, coolchock approved these changes
code lgtm

2024-01-15 08:55 UTC, b-fein requested changes
For programming exercises, the highlighted sections now match the ones shown in the JPlag report. :+1:

Change requested: During debugging of this issue we collected a lot of non-trivial information that might be helpful for someone working in this area in the future. Please extend the code comments a bit to explain the rationale of the changes.

2024-01-15 08:55 UTC, b-fein commented on src/main/webapp/app/exercises/shared/plagiarism/plagiarism-split-view/plagiarism-split-view.component.ts
> +        const elements = submission.elements?.sort((a, b) => a.id - b.id);
Please add a comment describing why this order is important.

2024-01-15 08:55 UTC, b-fein commented on src/main/webapp/app/exercises/shared/plagiarism/plagiarism-split-view/text-submission-viewer/text-submission-viewer.component.ts
> +     * Builds the required HTML to highlight the lines with matches in the file content.
Please extend the comment to describe _why_ only full lines are highlighted (in case of programming exercises).

2024-01-15 10:28 UTC, b-fein approved these changes

2024-01-15 10:36 UTC, konrad2002 approved these changes
retested on legacy ts1, works as expected

2024-01-15 15:47 UTC, xHadie approved these changes

2024-01-15 17:08 UTC, MarkusPaulsen approved these changes
Code looks good and tested on TS1

2024-01-16 16:59 UTC, merged