`Development`: Cleanup home component after JIRA removal
ls1intum/Artemis pull request #8346
Opened 2024-04-08 15:20 UTC by krusche

### Checklist
#### General

- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Motivation and Context
We still have some old code regarding captchas in JIRA. This PR removes it to make the client code for the login easier

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Try out wrong and correct credentials
3. Try our external and internal accounts

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked

![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test9)

### Review Progress

#### Performance Review
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

2024-04-10 22:05 UTC, pzdr7 approved these changes
Code

2024-04-11 09:19 UTC, julian-christl requested changes

2024-04-11 09:19 UTC, julian-christl commented on src/main/webapp/i18n/de/home.json
> -            "externalUserManagementWarning": "<span class='bold'>Du hast dein Passwort zu oft falsch eingegeben. :-(</span><br />Bitte öffne <a href='{{ url }}' target='_blank'>{{ name }}</a>, melde
You forgot to remove it for the English version.

2024-04-11 09:19 UTC, julian-christl commented on src/main/webapp/i18n/de/home.json
>              "loginWarning": "Scheint so, als hättest du Probleme bei der Anmeldung :-(<br />Bitte besuche <a href='{{ url }}'>{{ name }}</a> und versuche dich dort anzumelden.<br />Danach versuche es
You can remove this too (en & de)

2024-04-11 10:19 UTC, merged