`General`: Adapt footer for small screens and environments
ls1intum/Artemis pull request #8359
Opened 2024-04-09 11:13 UTC by rabeatwork

### Checklist
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
Especially for small screens, it's important to have a compressed footer and not to waste any space.

### Description
The footer in the exercises was partially very high. The footer height has been reduced overall, and for small screens, the buttons are turned into icon buttons. Also, the general Artemis footer was set to 4rem by default. That's fine for development but too high for production. This has been adjusted as well.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Exercise (e.g. Programming)

1. Log in to Artemis
2. Navigate to Course Management
3. Add/Edit a Exercise (e.g. Programming)
4. Verify that the footer is reduced in height 
5. Resize the Viewport 
6. Verify that the buttons switch to icon buttons 

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked

![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test9)

### Review Progress

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Screenshots

<img width="374" alt="image" src="https://github.com/ls1intum/Artemis/assets/75392103/f8f569c8-67fd-499d-a86e-a5f2214efea8">
<img width="373" alt="image" src="https://github.com/ls1intum/Artemis/assets/75392103/a5bdb582-0551-4ce6-b018-9121d63d4efc">
<img width="594" alt="image" src="https://github.com/ls1intum/Artemis/assets/75392103/418bc2e5-990b-44ed-9412-691f54d3d8ce">

2024-04-09 21:13 UTC, milljoniaer approved these changes
Thank you! Code LGTM 👍

2024-04-10 15:41 UTC, JohannesWt requested changes
See small comments

2024-04-10 15:41 UTC, JohannesWt commented on src/main/webapp/app/exercises/quiz/participate/quiz-participation.component.scss
>      .question-index {
I can't see that the css class `.question-index` is used as well in the `quiz-participation.component.html`. Most probably it can be removed as well.

2024-04-10 15:41 UTC, JohannesWt commented on src/main/webapp/i18n/en/exercise.json
> +            "notificationText": "What did you change?",
```suggestion
            "notificationText": "What has been changed?",
```

2024-04-10 15:41 UTC, JohannesWt commented on src/main/webapp/i18n/en/lecture.json
> +                "notificationPlaceholder": "What did you change?",
```suggestion
                "notificationPlaceholder": "What has been changed?",
```

2024-04-10 16:25 UTC, muradium commented
<img width="1486" alt="Screenshot 2024-04-10 at 6 23 57 PM" src="https://github.com/ls1intum/Artemis/assets/56686446/ecdbd97b-bad1-4174-8afe-8d7be1ccaf6e">


Save icon does not adapt to page zoom anymore. Also the task green ticks stay the same size and go off the center, if that's related.

2024-04-10 20:37 UTC, rabeatwork commented
> <img alt="Screenshot 2024-04-10 at 6 23 57 PM" width="1486" src="https://private-user-images.githubusercontent.com/56686446/321317262-ecdbd97b-bad1-4174-8afe-8d7be1ccaf6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3ODE1MTAsIm5iZiI6MTcxMjc4MTIxMCwicGF0aCI6Ii81NjY4NjQ0Ni8zMjEzMTcyNjItZWNkYmQ5N2ItYmFkMS00MTc0LThhZmUtOGQ3YmUxY2NhZjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDIwMzMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMjk1ZTk4Y2Y3ODNhZTg1NTA2ZjVlNTM0ZDg2ZTI3MzJlMmZkODE3MjkzZDllNDliNTI3MWFiMDllZmQwNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wDOEbF48XUV3WUicrcxXzpOoJUjhCt7cqYh4Z9AfBzs">
> Save icon does not adapt to page zoom anymore. Also the task green ticks stay the same size and go off the center, if that's related.

Which browser do you use?

2024-04-11 07:08 UTC, JohannesWt approved these changes
Code looks good

2024-04-11 07:53 UTC, milljoniaer approved these changes

2024-04-11 09:09 UTC, krusche commented on src/main/webapp/i18n/en/exercise.json
> +            "notificationText": "What did you change?",
we prefer "What did you change?"

2024-04-11 09:09 UTC, merged