`General`: Handle error when course title too long
ls1intum/Artemis pull request #8544
Opened 2024-05-04 10:07 UTC by sarpsahinalp

### Checklist
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Server
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).

### Motivation and Context

Currently, there is no limit on the length of course titles. However, when they exceed a certain length, Artemis signals an Internal Server Error, making it unclear what went wrong.

### Description

Give a character limit for the course title in the same way the restrictions for the short name are displayed.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Login as Admin
2. Create new course with very long title
3. See the error message with title too long

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked

![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)

### Review Progress

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

2024-05-04 10:47 UTC, coolchock commented
I think you should consider the review from coderabbit. When I try to update the course title and set a very long string I also get an Internal Server Error:
![image](https://github.com/ls1intum/Artemis/assets/73854755/442cab45-3a0c-4368-8ba5-f232354f17e3)

2024-05-04 10:55 UTC, egekurt123 commented
"I think we should also handle this on the client side by checking for invalid inputs. Otherwise, it just shows an 'Internal Error' without giving users any information about what went wrong."

2024-05-04 11:09 UTC, sarpsahinalp commented
> "I think we should also handle this on the client side by checking for invalid inputs. Otherwise, it just shows an 'Internal Error' without giving users any information about what went wrong."

This is not needed since the error message is also displayed in the UI

2024-05-05 14:54 UTC, edkaya approved these changes
Tested on ts3, works as expected

2024-05-06 10:25 UTC, florian-glombik commented
I agree with @egekurt123 and think that it would be better to have a client-side validation as well.

2024-05-06 11:42 UTC, florian-glombik requested changes
The translation `titleTooLong` does not seem to exist in the `error.json` on the client side. So the translation will not work, please add the translation there.
I do also think that `courseTitleTooLong` would be a more descriptive translationKey name.

Additionally I think that a client validation should be added. The save option should be invalid if more than 255 chars are entered and the field should have an indication to be invalid.

2024-05-06 16:04 UTC, florian-glombik reviewed
Thank you for addressing the comments from my previous review!

The formulation of the error message is a matter of taste, so choose the version you like best. 

Since there are no approves on the PR yet, would you mind getting rid of the magic number in the client validation?

2024-05-06 16:04 UTC, florian-glombik commented on src/main/webapp/app/course/manage/course-update.component.ts
> +                    validators: [Validators.required, Validators.maxLength(255)],
`255` could be encapsulated in a variable as done in the server part

2024-05-06 16:14 UTC, florian-glombik approved these changes
Code looks good to me and tested on ts3 - works well 👍 

Thank you for addressing the review comments!

2024-05-06 17:30 UTC, egekurt123 approved these changes
Code LGTM, Manually tested on ts3, works as expected

2024-05-07 10:03 UTC, az108 approved these changes
Tested manually on t3 (branch was still deployed there) , works as expected and Code LGTM

2024-05-07 12:20 UTC, edkaya approved these changes
Reapprove

2024-05-07 16:57 UTC, merged