`Development`: Created Multiple Cards for New Sidebar
ls1intum/Artemis pull request #8554
Opened 2024-05-07 12:42 UTC by egekurt123

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Server
- [ ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [ ] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.

#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [ ] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.

#### Changes affecting Programming Exercises
- [ ] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server configured with **Gitlab** and **Jenkins**.

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exam_mode/) as reference.
4. ...

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked

![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)

### Review Progress

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2024-05-08 15:23 UTC, rabeatwork commented on src/main/webapp/app/shared/sidebar/sidebar-accordion/sidebar-accordion.component.ts
> +    getSize() {
This information should be part in the sidebar data itself. :)

2024-05-08 15:23 UTC, rabeatwork commented on src/main/webapp/app/shared/sidebar/sidebar-card-medium/sidebar-card-medium.component.scss
> +.bg-module {
I would suggest to do a follow-up PR to combine the classes we need for all SidebarCard sizes into a separate SCSS file. This way, we won't have to duplicate them.

2024-05-12 15:11 UTC, JohannesWt commented on src/main/webapp/app/shared/sidebar/sidebar-card-medium/sidebar-card-medium.component.ts
> +    @Input() sidebarItem: SidebarCardElement;
I would set the sidebarItem required as it must not be null anyways.
```suggestion
    @Input({required:true}) sidebarItem: SidebarCardElement;
```

2024-05-12 15:13 UTC, JohannesWt commented on src/main/webapp/app/shared/sidebar/sidebar-card-small/sidebar-card-small.component.ts
>      @Input() sidebarItem: SidebarCardElement;
The sidebar item should also be required that it is not undefined `@Input({required:true})`

2024-05-12 15:14 UTC, JohannesWt commented on src/main/webapp/app/shared/sidebar/sidebar-card-small/sidebar-card-small.component.ts
>      @Input() sidebarItem: SidebarCardElement;
Then also the question marks of force Reload become obsolete

2024-05-12 15:17 UTC, JohannesWt commented on src/main/webapp/app/types/sidebar.ts
> +    size: 'S' | 'M' | 'L' | string;
If only S, M, L are allowed as Sizes one could also Create a `SidebarCardElementSize`-Enum

2024-05-12 15:19 UTC, JohannesWt requested changes
Looks good in general. But you could make more use of the required Input option to make null/undefined checks obsolete

2024-05-13 11:57 UTC, rabeatwork commented on src/main/webapp/app/shared/sidebar/sidebar-card.directive.ts
> +    @Input() size: string;
default M

2024-05-13 19:53 UTC, JohannesWt approved these changes
Code looks good after changes

2024-05-14 15:06 UTC, az108 approved these changes
Code LGTM

2024-05-14 16:41 UTC, pzdr7 approved these changes
Thanks for implementing the suggested changes! While I would have preferred an enum for the card size (like e.g. ButtonSize) I suppose the type definition is fine.

Code LGTM

2024-05-15 17:46 UTC, sarpsahinalp approved these changes
code lgtm

2024-05-16 08:45 UTC, egekurt123 commented on src/main/webapp/app/shared/sidebar/sidebar-card.directive.ts
> +    @Input() size: string;
will be pushed in a follow-up PR

2024-05-16 08:48 UTC, rabeatwork approved these changes
Maintainer approved

2024-05-17 09:42 UTC, rabeatwork approved these changes
re-approve

2024-05-17 09:43 UTC, pzdr7 approved these changes
Reapprove after merge conflicts

2024-05-17 10:03 UTC, JohannesWt approved these changes
Reapprove

2024-05-17 17:41 UTC, az108 approved these changes
reapprove

2024-05-18 11:06 UTC, merged