`Development`: update naming convention in server and client guidelines
ls1intum/Artemis pull request #8584
Opened 2024-05-13 10:58 UTC by BBesrour

### Checklist
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context

As discussed in the dev meeting (13.05.2024), we need to update the naming convention for constants in the server and client where constant names should adhere to the SCREAMING_SNAKE_CASE rule. 

### Description

Updated docs

### Steps for Testing

Read the updated docs. --TODO: ADD LINK--

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked

![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)

### Review Progress

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Screenshots

2024-05-13 11:26 UTC, rstief approved these changes
LGTM

2024-05-13 11:28 UTC, marlon-luca-bu approved these changes
Reflects the changes as discussed in the meeting 👍

2024-05-13 12:08 UTC, florian-glombik requested changes
I've found some small mistakes in the description text - apart from these it looks good to me

2024-05-13 12:08 UTC, florian-glombik commented on docs/dev/guidelines/server.rst
> +Variable names should also use camelCase style, where the first letter should be lowercase. For constants, i.e. arguments with the ``static final`` keywords, use all uppercase letters with underscore
```suggestion
All methods and classes should use camelCase style. The only difference: the first letter of any class should be capitalized. Most importantly, use intention-revealing, pronounceable names.
Variable names should also use camelCase style, where the first letter should be lowercase. For constants, i.e. arguments with the ``static final`` keywords, use all uppercase letters with underscores to separate words: SCREAMING_SNAKE_CASE.
```

2024-05-13 12:08 UTC, florian-glombik commented on docs/dev/guidelines/server.rst
> +The only exception for this rule is for the logger, which should be named ``log``.
```suggestion
The only exception to this rule is for the logger, which should be named ``log``.
```

2024-05-13 17:57 UTC, Strohgelaender approved these changes

2024-05-13 18:08 UTC, egekurt123 approved these changes

2024-05-14 18:23 UTC, florian-glombik approved these changes
Thanks for the small fixes, looks good to me now!

2024-05-14 19:18 UTC, SimonEntholzer approved these changes

2024-05-15 22:31 UTC, rstief approved these changes

2024-05-17 17:27 UTC, merged