`Tutorial groups`: Add utilization and attendance to tutorial groups sidebar
ls1intum/Artemis pull request #8586
Opened 2024-05-13 13:37 UTC by rabeatwork

### Checklist
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

The utilization rate is an important indicator for students whose tutorial groups have been canceled due to a public holiday, for example. It allows them to easily see which alternative tutorial groups they can attend instead.

### Description

Add the Utilization (and attendance if not capacity is available) to the sidebar. 

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Students
- 1 Tutorial Group with capacity and attendance
- 1 Tutorial Group with no capacity

1. Log in to Artemis
2. Navigate to Tutorial Groups 
3. See the capacity/average attendance for the tutorial group 

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked

![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)

### Review Progress

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Screenshots

![Screenshot 2024-05-13 at 15 29 02](https://github.com/ls1intum/Artemis/assets/75392103/941d9bc9-bebd-48a3-881d-74113b5aadc9)

2024-05-13 15:58 UTC, JohannesStoehr requested changes
Should we also color the tutorials according to their utilization like the exercises are colored for difficulty? There is also a utilization meter in Artemis that uses color as well: 
![Bildschirmfoto 2024-05-12 um 23 07 33](https://github.com/ls1intum/Artemis/assets/38322605/5aa1e9c2-e701-4a47-9cef-960847062a65)

2024-05-13 15:58 UTC, JohannesStoehr commented on src/main/webapp/app/overview/course-overview.service.ts
> +                : this.translate.instant('artemisApp.courseOverview.sidebar.noUpcomingSession'),
```suggestion
            subtitleLeft: tutorialGroup.nextSession?.start?.format('MMM DD, YYYY') ?? this.translate.instant('artemisApp.courseOverview.sidebar.noUpcomingSession'),
```

2024-05-13 15:58 UTC, JohannesStoehr commented on src/main/webapp/i18n/de/student-dashboard.json
> +                "noUpcomingSession": " Kein Termin"
Is the space intended? I personally think that we should add this to the html-file and not the translation, what do you think?

2024-05-13 19:07 UTC, pzdr7 approved these changes
Tested on TS1.

- G1 Created a tutor group; left capacity blank; registered 2 students
- G2 Created a tutor group; capacity 7; registered 2 students
- G3 Created a blank tutor group (no capacity, no students)

![image](https://github.com/ls1intum/Artemis/assets/38403547/e35fba61-69e3-49c2-8e7d-d966f908bc4a)

-> Works as expected! ✅

2024-05-14 08:25 UTC, egekurt123 approved these changes
Tested manually on TS1, works as expected

2024-05-14 14:13 UTC, JohannesStoehr approved these changes
Code and screenshots look good to me

2024-05-14 16:33 UTC, pzdr7 approved these changes
Reapprove

2024-05-15 07:50 UTC, az108 approved these changes
reapprove

2024-05-15 08:22 UTC, egekurt123 approved these changes
reapprove after small changes

2024-05-17 07:12 UTC, merged