`Development`: Extract build agent git service
ls1intum/Artemis pull request #8595
Opened 2024-05-14 20:13 UTC by krusche

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Server
- [ ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [ ] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.

#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [ ] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.

#### Changes affecting Programming Exercises
- [ ] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server configured with **Gitlab** and **Jenkins**.

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exam_mode/) as reference.
4. ...

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked

![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)

### Review Progress

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2024-05-18 12:30 UTC, BBesrour commented on src/main/java/de/tum/in/www1/artemis/service/connectors/GitService.java
> +        super.deleteLocalRepository(repository);
We can remove the rest of the method and only keep `cachedRepositories.remove(repoPath);`

2024-05-23 21:19 UTC, JohannesStoehr requested changes

2024-05-23 21:19 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/service/connectors/AbstractGitService.java
> +    protected static SshdSessionFactoryBuilder getSshdSessionFactoryBuilder(Optional<String> gitSshPrivateKeyPath, Optional<String> gitSshPrivateKeyPassphrase, URL gitUrl) {
Can you extract the inner classes from this method? It's quite hard to follow which method belongs to what

2024-05-23 21:19 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/service/connectors/AbstractGitService.java
> +        // Create the JGit repository object
I think this is a left over?

2024-05-23 21:19 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/service/connectors/AbstractGitService.java
> +                .setup(); // scan environment GIT_* variables
```suggestion
        if (isBare) {
            builder.setBare();
            builder.setGitDir(localPath.toFile());
        }
        else {
            builder.setGitDir(localPath.resolve(".git").toFile());
        }
        builder.setInitialBranch(defaultBranch).setMustExist(true).readEnvironment().findGitDir().setup(); // scan environment GIT_* variables
```

2024-05-23 21:19 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/service/connectors/AbstractGitService.java
> +            // and https://www.eclipse.org/lists/jgit-dev/msg03734.html
These links are already in the javadoc of this method. Do we want to repeat them again?

2024-05-23 21:19 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/service/connectors/AbstractGitService.java
> +                return null;
Why does this not throw an exception?

2024-05-23 21:19 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/service/connectors/localci/buildagent/BuildJobGitService.java
> +
```suggestion
```

2024-05-24 11:37 UTC, pzdr7 approved these changes
Tested on TS1.

Things I've tried:

- Create programming exercise ✅ 
- Trigger template, solution builds ✅ got a result for each
- Make submission using code editor ✅  got a result
- Make submission using cloned repo ✅  got a result
- Cancel a build job ✅

2024-05-24 12:02 UTC, BBesrour commented on src/main/java/de/tum/in/www1/artemis/service/connectors/AbstractGitService.java
> +                return null;
Since the PR focuses on separating concerns for GitService, we want to keep the same behavior for now. Changing this would modify behavior of some other parts which would out of scope of this PR.

2024-05-24 13:47 UTC, Strohgelaender commented on src/main/java/de/tum/in/www1/artemis/service/connectors/localci/buildagent/BuildJobExecutionService.java
> +                    Paths.get(CHECKED_OUT_REPOS_TEMP_DIR, commitHash, repositoryUri.folderNameForRepositoryUri()));
(nitpick)
we prefer `Path.of` over `Paths.get`.
```suggestion
                    Path.of(CHECKED_OUT_REPOS_TEMP_DIR, commitHash, repositoryUri.folderNameForRepositoryUri()));
```

2024-05-24 13:47 UTC, Strohgelaender commented on src/main/java/de/tum/in/www1/artemis/service/connectors/AbstractGitService.java
> +                .setSshDirectory(new java.io.File(gitSshPrivateKeyPath.orElseThrow())).setHomeDirectory(new java.io.File(System.getProperty("user.home")));
Can you import the `File` class instead of using full qualified names?

2024-05-24 13:47 UTC, Strohgelaender commented on src/main/java/de/tum/in/www1/artemis/service/connectors/localci/buildagent/BuildJobGitService.java
> +    }
```suggestion
```

2024-05-24 13:47 UTC, Strohgelaender commented on src/main/java/de/tum/in/www1/artemis/service/connectors/localci/buildagent/BuildJobGitService.java
> +        return getExistingCheckedOutRepositoryByLocalPath(localPath, repoUri, defaultBranch);
```suggestion
        try (Git git = cloneCommand().setURI(gitUriAsString).setDirectory(localPath.toFile()).call()) {
            return getExistingCheckedOutRepositoryByLocalPath(localPath, repoUri, defaultBranch);
        }
```

2024-05-24 16:30 UTC, az108 submitted a review, later dismissed
Works as expected, tested in testing session together and tested it myself aswell

2024-05-24 17:04 UTC, SimonEntholzer submitted a review, later dismissed
Tested in testing session, and code (mostly small changes) look good

2024-05-24 17:07 UTC, pzdr7 submitted a review, later dismissed
Reapprove

2024-05-24 19:50 UTC, Jan-Thurner reviewed
The code looks good for the most part. However, I have a few questions in the comments.

2024-05-24 20:04 UTC, BBesrour commented on src/main/java/de/tum/in/www1/artemis/service/connectors/AbstractGitService.java
> +            return false;
This was taken from gitService and we shouldn't change it in this PR since we want to keep the same behavior (mostly).

2024-05-24 20:09 UTC, Jan-Thurner submitted a review, later dismissed
Code LGTM

2024-05-25 10:32 UTC, SimonEntholzer submitted a review, later dismissed
Tested on Ts3

2024-05-25 11:10 UTC, pzdr7 approved these changes
Tested again on TS3.

- Created a programming exercise ✅ 
- Triggered template / solution builds manually; got a result each time ✅ 
- Participated; got a result ✅ 
- Canceled a build job ✅

2024-05-25 12:39 UTC, BBesrour approved these changes
Tested on TS2 and staging

2024-05-25 12:41 UTC, pzdr7 approved these changes
Tested on LocalCI Staging

2024-05-25 13:04 UTC, merged