`Development`: Add endpoint for learning path competency graph
ls1intum/Artemis pull request #8649
Opened 2024-05-22 14:57 UTC by JohannesStoehr

### Checklist
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

@JohannesWt wants a new endpoint with the following structure given the learning Path id:
```
"nodes": [
	 	{
	 		"id": 1,
	 		"label": "Competency 1",
	 		"softDueDate": "21.02.2022, 10:42"
	 		"progress": 50,
	 		"mastery": 50,
	 		"confidence": 80
	 	},
	 	{
	 		"id": 2,
	 		"label": "Competency 2",
	 		"progress": 50,
	 		"mastery": 50,
	 		"confidence": 80
	 	},
	 ],
	 "edges": [
	 	{
	 		"id": 42
	 		"source": 1,
	 		"target": 2,
	 		"type": "extends"
	 	}	
	 ]
```

### Description

Added the endpoint as requested

### Steps for Testing

No manual testing possible, since the end point is not yet used

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked

![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)

### Review Progress

#### Performance Review
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2

### Test Coverage

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [LearningPathService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6626/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.learningpath/LearningPathService.html) | 99% | ✅  |
| [LearningPathResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6626/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/LearningPathResource.html) | 98% | ✅  |
| [CompetencyProgressDTO.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6626/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest.dto.competency/CompetencyProgressDTO.html) | 100% | ✅ |
| [LearningPathCompetencyGraphDTO.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6626/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest.dto.competency/LearningPathCompetencyGraphDTO.html) | 100% | ✅ |

2024-05-22 15:13 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/repository/CompetencyProgressRepository.java
> +    }
This is not the complete error message but only the name of the entity that was not found. The complete error message is built inside the exception

2024-05-22 15:16 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/service/learningpath/LearningPathService.java
> +    }
The processing is done inside a stream. If the set or stream are empty, then there will also not be any processing

2024-05-22 15:16 UTC, JohannesStoehr commented on src/test/java/de/tum/in/www1/artemis/competency/LearningPathIntegrationTest.java
> +        var courseWithoutCompetencies = courseUtilService.createCoursesWithExercisesAndLectures(TEST_PREFIX, false, false, 0).getFirst();
I only refactored the access to the first element. The behavior is the exact same

2024-05-22 15:17 UTC, JohannesStoehr commented on src/main/java/de/tum/in/www1/artemis/repository/CompetencyProgressRepository.java
> +    }
Yes, we customised it

2024-05-22 15:33 UTC, JohannesWt submitted a review, later dismissed
Code LGTM 👍

2024-05-22 16:13 UTC, JohannesWt submitted a review, later dismissed
Reapprove after adding softDueDate

2024-05-22 17:22 UTC, pzdr7 approved these changes
Code looks good. One small comment

2024-05-22 17:22 UTC, pzdr7 commented on src/main/java/de/tum/in/www1/artemis/web/rest/LearningPathResource.java
> +            throw new AccessForbiddenException("You are not allowed to access another users learning path.");
```suggestion
            throw new AccessForbiddenException("You are not allowed to access another user's learning path.");
```

2024-05-23 12:39 UTC, JohannesWt submitted a review, later dismissed
Reapprove 👍

2024-05-23 12:46 UTC, pzdr7 approved these changes
Code

2024-05-27 09:12 UTC, MaximilianAnzinger requested changes

2024-05-27 10:17 UTC, JohannesWt approved these changes
Reapprove

2024-05-27 10:18 UTC, pzdr7 approved these changes

2024-05-27 18:50 UTC, pzdr7 commented on src/main/java/de/tum/in/www1/artemis/service/learningpath/LearningPathService.java
> +    public LearningPathCompetencyGraphDTO generateLearningPathCompetencyGraph(@NotNull LearningPath learningPath) {
It seems the server style wants you to add a javadoc comment here:

/home/runner/work/Artemis/Artemis/src/main/java/de/tum/in/www1/artemis/service/learningpath/LearningPathService.java:289:5: Missing a Javadoc comment. [MissingJavadocMethod]

2024-05-27 19:44 UTC, pzdr7 approved these changes

2024-05-27 20:02 UTC, JohannesWt approved these changes

2024-05-28 07:07 UTC, MaximilianAnzinger approved these changes
Maintainer approved

2024-05-28 19:25 UTC, JohannesWt approved these changes
Reapprove

2024-05-28 19:38 UTC, pzdr7 approved these changes
Reapprove

2024-05-29 07:17 UTC, merged