`Development`: Add Playwright E2E tests for programming exercise participation
ls1intum/Artemis pull request #8713
Opened 2024-06-02 20:34 UTC by muradium

### Checklist
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context
We want to test programming exercise participation in different programming languages

### Description
Adds E2E tests in Playwright for programming exercises in Swift, Kotlin, VHDL and Assembler for submissions using online code editor and Git

### Steps for Testing
- **Code Review**: Ensure that tests pass for valid reasons, functionality is adequately tested and check the code quality.
- **Run the tests**: Tests are checked by automatic run in CI environment. You can also run them locally and check if they pass.

**Steps for running the tests:**
1. Navigate to **src/tests/playwright**
2. Configure Playwright using playwright.env file based on your local setup. Current configuration should work for default Artemis setup.
3. Run `npm install && npm run playwright:setup`
4. Run tests with following commands and confirm that they pass:
- `npx playwright test e2e/exercise/programming/ProgrammingExerciseParticipation.spec.ts -g "Makes a successful Swift submission"`
- `npx playwright test e2e/exercise/programming/ProgrammingExerciseParticipation.spec.ts -g "Makes a successful Kotlin submission"`
- `npx playwright test e2e/exercise/programming/ProgrammingExerciseParticipation.spec.ts -g "Makes a successful VHDL submission"`
- `npx playwright test e2e/exercise/programming/ProgrammingExerciseParticipation.spec.ts -g "Makes a successful Assembler submission"`

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked

![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test9)

### Review Progress

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

2024-06-02 21:08 UTC, sarpsahinalp reviewed
When trying to run the tests locally I get the following error:
![image](https://github.com/ls1intum/Artemis/assets/92453703/3bbe75ed-ff9d-4e61-9935-3cb0ed03883b)

2024-06-03 09:51 UTC, BBesrour reviewed
I tried running the tests locally but I can get this error. I am not sure if it's due to my setup.
![image](https://github.com/ls1intum/Artemis/assets/58034472/6044dd78-f08e-4e9b-bcd0-f55b570e9e00)
Also, Test aren't running on CI

2024-06-06 09:38 UTC, sarpsahinalp requested changes
Three tests seems to be failing

- Exam Results › Check exam exercise results › Check exam result overview
```
FAILURE: ExamResults.spec.ts:137:13 Check exam result overview
  [chromium] › e2e/exam/ExamResults.spec.ts:137:13 › Exam Results › Check exam exercise results › Check exam result overview 

    "beforeAll" hook timeout of 360000ms exceeded.

      51 |         let exerciseArray: Array<Exercise> = [];
      52 |
(109 more lines...)
Failed
```

- Programming exercise assessment › Assesses the programming exercise submission and verifies it
```
FAILURE: ProgrammingExerciseAssessment.spec.ts:52:9 Assesses the programming exercise submission and verifies it

  [chromium] › e2e/exercise/programming/ProgrammingExerciseAssessment.spec.ts:52:9 › Programming exercise assessment › Assesses the programming exercise submission and verifies it 

    Error: Timed out finding an element matching the "locator('#open-exercise-dashboard').first()" locator

       at support/commands.ts:63

(42 more lines...)
Failed
```

- Quiz Exercise Assessment › MC Quiz assessment › Assesses a mc quiz submission automatically
```

FAILURE: QuizExerciseAssessment.spec.ts:19:13 Assesses a mc quiz submission automatically

Quiz Exercise Assessment › MC Quiz assessment › Assesses a mc quiz submission automatically 

    Error: Timed out finding an element matching the "locator('jhi-course-exercise-details #submission-result-graded')" locator

       at support/commands.ts:63

(60 more lines...)
```

2024-06-07 17:25 UTC, BBesrour approved these changes
The issue previously mentioned is probably due to my setup.
Tests are passing on CI.

2024-06-08 23:15 UTC, sarpsahinalp approved these changes
Tests pass locally

2024-06-09 08:06 UTC, coolchock approved these changes
the tests were explained and presented in the testing session. Code looks good to me 👍

2024-06-09 20:37 UTC, SimonEntholzer approved these changes

2024-07-01 12:05 UTC, closed without merging