`Development`: Remove multiple occurrences of deprecated code
ls1intum/Artemis pull request #8721
Opened 2024-06-03 15:39 UTC by MaximilianAnzinger

### Checklist
#### General

- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

Replaces the following deprecated method calls:
- `isEqualToIgnoringGivenFields`
- `isEqualToComparingFieldByField`
- `URL` constructor
- `mvnRequest.setGoals`
- `isEqualToComparingOnlyGivenFields`

### Review Progress

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2

2024-06-03 16:23 UTC, JohannesStoehr requested changes
The tests with `usingRecursiveComparison().ignoringFields(...)` seam to fail

2024-06-03 17:00 UTC, Strohgelaender commented
The recursive comparator does not work since the old method uses the equals-method all top-level fields (where in the most cases then just a comparison by ID is performed) whereas the recursive comparator checks every field recursively leading to many differences (because relations are not loaded and so on). You can replace that by explicit `isEqualTo` assertions on the checked fields.

2024-06-04 14:34 UTC, JohannesStoehr approved these changes

2024-06-04 16:58 UTC, Strohgelaender approved these changes
lgtm now

2024-06-04 20:00 UTC, krusche approved these changes

2024-06-04 20:01 UTC, merged