`Integrated code lifecycle`: Add screencasts for build agent and queue features
ls1intum/Artemis pull request #8737
Opened 2024-06-04 13:18 UTC by laurenzfb

### Checklist
#### General

- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

The documentation for ICL is incomplete as screen casts for the newly added features are missing.

### Description

I added screencasts for the agent and queue features. I also moved the ICL setup up before Jenkins and Gitlab, as it is the prefered setup.

### Steps for Testing

### Review Progress

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2

2024-06-04 13:42 UTC, rstief approved these changes
documentation looks good

2024-06-04 18:23 UTC, florian-glombik requested changes
Looks good except for the typos

The second video had a rather bad resolution, still acceptable, but if that only happened at the compression we might want to upload a video with a higher resolution there 😅

2024-06-04 18:23 UTC, florian-glombik commented on docs/dev/setup/integrated-code-lifecycle.rst
> +This section describes how to set up a programming exercise environment based on Integrated Code Lifecycle which includes a local Version Control system and a local Continuous Integration system.
```suggestion
This section describes how to set up a programming exercise environment based on the Integrated Code Lifecycle, which includes a local Version Control system and a local Continuous Integration system.
```

2024-06-04 18:23 UTC, florian-glombik commented on docs/dev/setup/integrated-code-lifecycle.rst
>  These two systems are integrated into the Artemis server application and thus the setup is greatly simplified compared to the external options.
Not directly related, but we could address it aswell

```suggestion
These two systems are integrated into the Artemis server application, and thus, the setup is greatly simplified compared to the external options.
```

2024-06-04 18:43 UTC, BBesrour submitted a review, later dismissed
Looks good!
Small nitpick, as Florian pointed out, the quality of the second screencast is a slightly worse than the first one

2024-06-05 07:21 UTC, laurenzfb commented
@florian-glombik @BBesrour Thanks for the suggestions! I'll try to get a better version of the second screencast!

2024-06-05 09:28 UTC, rstief approved these changes

2024-06-05 10:08 UTC, BBesrour approved these changes
Thanks for improving the quality! Looks good!

2024-06-05 10:25 UTC, florian-glombik approved these changes
Thank you for fixing the typos and uploading the video with higher resolution!

2024-06-05 10:40 UTC, egekurt123 approved these changes
Screencasts LGTM

2024-06-05 14:34 UTC, merged