Team Exercises: Fix missing button when individual deadline set
ls1intum/Artemis pull request #8804
Opened 2024-06-16 23:45 UTC by EneaGore

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [X] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [X] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [X] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Fixes issue [8610](https://github.com/ls1intum/Artemis/issues/8610)

### Description
When booleans are set whether a button should be shown or not individual deadline is not considered. Now it is included in all exercises.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exercise of each type

1. Log in to Artemis
2. Create Team and individual Exercises
3. 1 Student/Team participates before deadline, 1 after deadline
4. Change individual deadline
5. Confirm that button to submit is available and submit button also looks and works correctly.

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked

![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test9)

### Review Progress

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots

Before:
![buttonMissingindividual](https://github.com/ls1intum/Artemis/assets/73840596/7577690d-abc7-44e9-a364-1c0258f3a7ec)
![buttonMissingTeam](https://github.com/ls1intum/Artemis/assets/73840596/6a2463af-e56d-463c-b940-b53ca9b4fce7)
After:
![buttonthere](https://github.com/ls1intum/Artemis/assets/73840596/a68a6671-18db-43cf-8783-dfafff64480e)

2024-06-17 09:34 UTC, SimonEntholzer approved these changes
Code fix makes sense :+1:

2024-06-17 10:37 UTC, JohannesStoehr requested changes

2024-06-17 10:37 UTC, JohannesStoehr commented on src/main/webapp/app/exercises/modeling/participate/modeling-submission.component.ts
> +            dayjs(this.participation.initializationDate).isAfter(this.participation?.individualDueDate);
```suggestion
            dayjs(this.participation.initializationDate).isAfter(getExerciseDueDate(this.modelingExercise, this.participation));
```

2024-06-17 10:37 UTC, JohannesStoehr commented on src/main/webapp/app/exercises/modeling/participate/modeling-submission.component.ts
> +            dayjs(this.participation.initializationDate).isAfter(this.participation?.individualDueDate);
Please also adapt the other occurrences

2024-06-19 13:22 UTC, JohannesWt submitted a review, later dismissed
Tested in testing session - works as expected 👍

2024-06-19 13:22 UTC, JohannesStoehr approved these changes
Tested in Testing session. Worked as expected

2024-06-19 13:22 UTC, az108 submitted a review, later dismissed
Works as expected on TS4. LGTM

2024-06-19 13:23 UTC, coolchock submitted a review, later dismissed
tested in testing session, works as described

2024-06-19 13:29 UTC, BBesrour submitted a review, later dismissed
Demonstrated in a testing session, also code lgtm

2024-06-21 18:30 UTC, krusche submitted a review, later dismissed

2024-06-22 08:49 UTC, merged