Fix Server Tests
ls1intum/Artemis pull request #8816
Opened 2024-06-17 22:01 UTC by JohannesStoehr

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [ ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [ ] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.

#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [ ] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.

#### Changes affecting Programming Exercises
- [ ] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server configured with **Gitlab** and **Jenkins**.

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exam_mode/) as reference.
4. ...

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked

![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)
![](https://byob.yarr.is/ls1intum/Artemis/artemis-test9)

### Review Progress

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2024-06-25 09:26 UTC, Jan-Thurner requested changes
When trying to access the learning paths, an internal server error is thrown and the page is empty: 
![image](https://github.com/ls1intum/Artemis/assets/107639007/d9cf72c6-e461-4d4d-a132-44fc4cb269a7)

Edit: The newest push has not yet been deployed. I am retesting now.

2024-06-25 09:33 UTC, Jan-Thurner approved these changes
Tested again on TS5. Works as expected.

2024-06-25 10:10 UTC, pzdr7 commented on src/test/javascript/spec/component/learning-paths/components/learning-path-nav.component.spec.ts
> +        expect(loadCompetenciesSpy).toHaveBeenCalledWith(learningPathId);
Exactly once?

2024-06-25 12:11 UTC, pzdr7 approved these changes

2024-06-25 14:56 UTC, rstief approved these changes
Tested on ts5 LGTM. 
Just a minor nitpick: The `accordion-body` styles set the `overflow` to `scroll` which causes it to look like this on windows:
![image](https://github.com/ls1intum/Artemis/assets/118574504/bb44a0d2-04b7-4218-938c-ee0c7af70517)

2024-06-25 15:06 UTC, EneaGore reviewed
Testing on TS5. Works as expected, but after i delete an exercise which was connected to a competency i get an error 500 when accessing the page again. Probably its not specifically connected to this PR though.
![500nav](https://github.com/ls1intum/Artemis/assets/73840596/894c5dd3-4bbb-4ee1-b977-37813d012ffc)

2024-06-25 17:52 UTC, edkaya approved these changes
Tested on ts5, works as expected. Some UI sidenotes that can be done in a follow up PR: 
- I see a scrollbar in content part, which can be hidden if you don't have an exceeding content. 
<img width="1327" alt="Screenshot 2024-06-25 at 19 49 32" src="https://github.com/ls1intum/Artemis/assets/117287716/0d2153f0-660f-47a7-a5da-ea891ebedd6d">
- We might want to have the overview scrollbar in auto mode instead scroll 
<img width="415" alt="Screenshot 2024-06-25 at 19 50 38" src="https://github.com/ls1intum/Artemis/assets/117287716/8972ff6d-4e40-4c77-9e70-8cea5858720e">

2024-06-25 18:50 UTC, JohannesWt commented
> Tested on ts5, works as expected. Some UI sidenotes that can be done in a follow up PR:
> 
> * I see a scrollbar in content part, which can be hidden if you don't have an exceeding content.
> 
> <img alt="Screenshot 2024-06-25 at 19 49 32" width="1327" src="https://private-user-images.githubusercontent.com/117287716/342850738-0d2153f0-660f-47a7-a5da-ea891ebedd6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNDE0ODIsIm5iZiI6MTcxOTM0MTE4MiwicGF0aCI6Ii8xMTcyODc3MTYvMzQyODUwNzM4LTBkMjE1M2YwLTY2MGYtNDdhNy1hNWRhLWVhODkxZWJlZGQ2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQxODQ2MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMWZmZGI2ZGU0Nzc4YTc4ZjcxYTk2ZjM5NjRjZjlmMjA1NDIxZjBlNTA0NDAyMThkZGNjODVlMjIxZTY2MzZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xPJzU7lHFDiVQxtlEH67WSCZlqUA3jrbCkEyyVcxKoI"> - We might want to have the overview scrollbar in auto mode instead scroll <img alt="Screenshot 2024-06-25 at 19 50 38" width="415" src="https://private-user-images.githubusercontent.com/117287716/342851308-8972ff6d-4e40-4c77-9e70-8cea5858720e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNDE0ODIsIm5iZiI6MTcxOTM0MTE4MiwicGF0aCI6Ii8xMTcyODc3MTYvMzQyODUxMzA4LTg5NzJmZjZkLTRlNDAtNGM3Ny05ZTcwLThjZWE1ODU4NzIwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQxODQ2MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjcyODJmMWJmMmI0OWI2OGQxZDI3NGI5YTMyOTk0ZGQ5NGYxZGI1ZjhmYjU3ZDJkNzY5OTI1MWU5MTJlMGE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._i1jmWyQTlmBl2MbFpDoNwSNq1GoAorocVKOb5AK3qY">

Unfortunately we have to use scroll overview here. If we use "auto" the dropdown will grow indefinitely in size ignoring the max-height. The horizontal scroll in the content part is already documented in an issue and will be solved in a follow up PR.

2024-06-25 19:28 UTC, az108 commented
I like the changes, maybe in a future PR we could show somewhere which compentency one is at rn. Because right now I would have to click on the dropdown to see that i am in competency 2. 
![image](https://github.com/ls1intum/Artemis/assets/92953467/864e30a8-5d40-4719-a0c4-7b21d023073e)

2024-06-25 19:52 UTC, JohannesWt commented
> I like the changes, maybe in a future PR we could show somewhere which compentency one is at rn. Because right now I would have to click on the dropdown to see that i am in competency 2. 😄 ![image](https://private-user-images.githubusercontent.com/92953467/342898561-864e30a8-5d40-4719-a0c4-7b21d023073e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNDU0NDYsIm5iZiI6MTcxOTM0NTE0NiwicGF0aCI6Ii85Mjk1MzQ2Ny8zNDI4OTg1NjEtODY0ZTMwYTgtNWQ0MC00NzE5LWEwYzQtN2IyMWQwMjMwNzNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDE5NTIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMzkxOTg5NDQyOTM1MTdlYzVhYTdmYzA3ZDA4MWViNDEyY2MwYTQ2NDNiNmJhZDE5YTk1Yjk5ZmI3Zjc2YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1YyhQx7yvvf2omktkveBCFWf84rCGTl49zmAYv1AByM)

That's exactly the plan. In the future the current competency should be marked and opened, as soon as you open the drop down.

2024-06-26 08:51 UTC, MaximilianAnzinger approved these changes

2024-06-26 08:51 UTC, merged