Preliminary Feedback View
ls1intum/Artemis pull request #9310
Opened 2024-09-12 16:34 UTC by EneaGore

…, add text blocks

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [ ] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [ ] I **strictly** followed the principle of **data economy** for all database calls.
- [ ] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.

#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [ ] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [ ] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.

#### Changes affecting Programming Exercises
- [ ] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server configured with **Gitlab** and **Jenkins**.

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exam_mode/) as reference.
4. ...

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked
> Click on the badges to get to the test servers.

[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)](https://artemis-test1.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)](https://artemis-test2.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)](https://artemis-test3.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)](https://artemis-test4.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)](https://artemis-test5.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)](https://artemis-test6.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test9)](https://artemis-test9.artemis.cit.tum.de)

### Review Progress

#### Performance Review

- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2
#### Performance Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2024-09-15 15:49 UTC, eceeeren requested changes
Tested on TS1, I can ask for feedback in the code editor but I don't see the option on the Overview. See picture:

![Screenshot 2024-09-15 at 17 48 16](https://github.com/user-attachments/assets/2b206ca8-9d7b-4281-be8d-db519d721e85)

2024-09-15 17:58 UTC, coolchock submitted a review, later dismissed
tested on ts1, LGTM

2024-09-15 18:28 UTC, eceeeren requested changes
I am not sure if it is only me but I can not see the AI Feedback Analysis anymore:

![Screenshot 2024-09-15 at 20 19 36](https://github.com/user-attachments/assets/608ae582-461c-4f5c-a226-579d13f0ae79)

2024-09-16 08:26 UTC, BBesrour reviewed
Tested on TS1, works as expected if you set a due date. If due date is not set, you get this warning which I think is misleading. Is this wanted?
![image](https://github.com/user-attachments/assets/4a20fae5-4363-45a9-beb4-0cc132be4b81)

2024-09-17 07:40 UTC, coolchock approved these changes
re-approve

2024-09-17 14:54 UTC, SimonEntholzer requested changes
In the exercise creation/edit views, the buttons to enable the feedback are only shown after the change detection is triggered. I think they should be shown from the start, not only after some change is triggered.

![image](https://github.com/user-attachments/assets/a20b0fb0-729d-40cb-9b9d-95643ad3e93a)

Apart from that, generating the AI feedback works perfectly :+1:

2024-09-17 15:05 UTC, eceeeren submitted a review, later dismissed
Tested on a testing session, approved

2024-09-17 15:06 UTC, SimonEntholzer submitted a review, later dismissed

2024-09-17 16:27 UTC, edkaya approved these changes
Tested on ts1, works expected

2024-09-19 10:09 UTC, FelixTJDietrich requested changes

2024-09-19 10:09 UTC, FelixTJDietrich commented on src/main/webapp/app/exercises/text/participate/text-editor.component.ts
>          this.textExercise = this.participation.exercise as TextExercise;
"Cannot read properties of undefined (reading 'exercise')"

2024-09-19 10:09 UTC, FelixTJDietrich commented on src/main/webapp/app/exercises/text/participate/text-editor.component.ts
>          this.textExercise = this.participation.exercise as TextExercise;
I think this happens after I vote "How useful is this feedback to you?" and refresh on an older result

2024-09-19 10:20 UTC, FelixTJDietrich requested changes
There is a issue with the "How useful is this feedback to you?" prompt, it does not work for the older results when I refresh for example. I get an internal server error, you might need to provide also the submission id 🤔 

The rest of the functionality works as expected on TS1 :)

Code looks good except for some minor issues I found. You fixed a bunch of stuff on the server side but there are no new tests / test changes. Maybe we need some more server tests to cover those. 

Can you also fill out the "Test Coverage" section of the PR? There is a provided pythin script to automatically generate one.

2024-09-20 09:18 UTC, FelixTJDietrich reviewed
The rating works now :) and the rest too except for some internal server error in initial submit now, is this because of test server 1? 

![image (5)](https://github.com/user-attachments/assets/bf832440-da33-4b84-9d09-d557aca65cf8)
![image (4)](https://github.com/user-attachments/assets/7c93065a-a244-4055-8e3f-6070837b47bc)

```"detail": "could not execute batch [Cannot delete or update a parent row: a foreign key constraint fails (`artemis`.`participant_score`, CONSTRAINT `fk_participant_score_last_rated_result_id` FOREIGN KEY (`last_rated_result_id`) REFERENCES `result` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT)] [delete from result where id=?]; SQL [delete from result where id=?]; constraint [null]",
```

2024-09-21 01:16 UTC, EneaGore commented on src/main/webapp/app/exercises/text/participate/text-editor.component.ts
> +     * 1. They have a graded submission.
updated it

2024-09-21 19:18 UTC, eceeeren approved these changes
Tested on TS1, working as expected, reapprove

2024-09-23 01:44 UTC, BBesrour approved these changes
Tested on TS1, lgtm. thnx for adding the change requests

2024-09-27 07:34 UTC, FelixTJDietrich commented
Tested on TS1 and it does not work as expected 
<img width="752" alt="image" src="https://github.com/user-attachments/assets/d6a01065-ca46-44ca-bc15-2096fe6fc92a">

2024-09-27 07:38 UTC, FelixTJDietrich commented
This was after creating a new exercise

2024-09-30 07:40 UTC, FelixTJDietrich commented
The error happens when the submission is empty:
<img width="1335" alt="image" src="https://github.com/user-attachments/assets/4dea0a56-ec8a-47dd-b890-73ab32e0b3fe">

Also a gap between the buttons would be nice when the screen size is slightly smaller:
<img width="992" alt="image" src="https://github.com/user-attachments/assets/d032bf1d-5344-413d-b7d9-2467aba40564">

2024-10-13 05:07 UTC, closed without merging