`Development`: Upgrade markdown library to markdown-it
ls1intum/Artemis pull request #9354
Opened 2024-09-22 11:52 UTC by Strohgelaender

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [ ] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [ ] I **strictly** followed the principle of **data economy** for all database calls.
- [ ] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.

#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [ ] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [ ] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.

#### Changes affecting Programming Exercises
- [ ] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server configured with **Gitlab** and **Jenkins**.

### Motivation and Context
#9333

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exam_mode/) as reference.
4. ...

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked
> Click on the badges to get to the test servers.

[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)](https://artemis-test1.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)](https://artemis-test2.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)](https://artemis-test3.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)](https://artemis-test4.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)](https://artemis-test5.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)](https://artemis-test6.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test9)](https://artemis-test9.artemis.cit.tum.de)

### Review Progress

#### Performance Review

- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2
#### Performance Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2024-09-25 13:26 UTC, janthoXO requested changes
it would be good to adjust the documentation of the supported markdown syntax as well:
[https://docs.artemis.cit.tum.de/user/markdown-support.html](https://docs.artemis.cit.tum.de/user/markdown-support.html)

2024-09-26 08:32 UTC, SimonEntholzer submitted a review, later dismissed
Code looks good imo, and works on Ts2, Markdown/problem statements still render correctly.

2024-10-11 08:54 UTC, Strohgelaender commented
Formulas for short answer questions also don't work on develop / with showdown, there seems to be some styling issue in the quiz component. I looked at it but could not figure out the issue directly.
![grafik](https://github.com/user-attachments/assets/8c4eab40-4ca2-464b-89e8-4dad55bcd8c6)

2024-10-12 11:24 UTC, kaancayli approved these changes
Tested on TS5. Works as expected 👍 

- Tested with programming exercises with plant uml and tasks ✅ 
- Tested with multiple choice quizes ✅ 
- Tested short answer quizes ✅

2024-10-21 17:17 UTC, florian-glombik submitted a review, later dismissed
Tested on ts2, I did not find an issue with the new Markdown editor


### What I tested
* Submitting a programming exercise with inline linked tests marks the test properly as correct / incorrect
     <img width="498" alt="image" src="https://github.com/user-attachments/assets/8d8ead71-4f33-4427-a3ed-fb3415287bbc">

* The following problem statement was rendered as expected https://artemis-test2.artemis.cit.tum.de/course-management/12/programming-exercises/303/edit
```
# Markdown-It

## Text Styling
**Bold Text**  
*Italic Text*  
~~Strikethrough~~  
**_Bold and Italic_**  

---

## Code Blocks

### Inline Code
This is `inline code`.

### Block Code
```javascript
// JavaScript Example
function greet() {
  console.log("Hello, Markdown!");
}
```

### LaTeX Edge Cases:

1. **Unbalanced Braces:**
   $$ \frac{a + b}{c $$  (missing closing brace)
   **Expected behavior:** Should raise a formatting error or break the equation.

2. **Nested Fractions:**
   $$ \frac{\frac{a}{b}}{c} $$
   **Expected behavior:** Proper rendering of nested fractions.

3. **Escaping Special Characters:**
   $$ 3\% + 4\& = 7 $$
   **Expected behavior:** LaTeX should handle the escaped `%` and `&` properly without treating them as special characters.

4. **Unsupported LaTeX Commands:**
   $$ \textcolor{red}{x} = 5 $$  (testing unsupported LaTeX commands)
   **Expected behavior:** Markdown-It might fail to render unsupported commands or throw an error.

5. **Overlapping Symbols (Operator Alignment):**
   $$ \sum_{i=1}^{n} x_i = \prod_{i=1}^{n} y_i $$
   **Expected behavior:** Both summation and product symbols should be aligned and rendered correctly.

6. **Complex Matrix with Line Breaks:**
   $$ \begin{bmatrix} a_1 & a_2 & a_3 \\ b_1 & b_2 & b_3 \\ c_1 & c_2 & c_3 \end{bmatrix} $$
   **Expected behavior:** Proper formatting of the matrix, line breaks in rows, and alignment.

7. **Spacing Issues:**
   $$ a   \cdot  b = c $$   (testing multiple spaces)
   **Expected behavior:** LaTeX should ignore extra spaces and properly format the expression.

8. **Misuse of Text vs Math Mode:**
   $$ a^2 \text{plus} b^2 = c^2 $$  (text inside a math environment)
   **Expected behavior:** The word "plus" should be rendered in normal text mode inside the math expression.

9. **Superscript/Subscript without Delimiters:**
   $$ x^2y_3z $$  (no braces for superscript/subscript)
   **Expected behavior:** LaTeX might struggle to distinguish superscripts or subscripts without curly braces.

10. **Large Operators and Limits:**
    $$ \lim_{x \to 0} \frac{1}{x} $$
    **Expected behavior:** Proper rendering of the limit operator with subscript and superscript.

11. **Conditional Symbols:**
    $$ \begin{cases} x^2 & \text{if } x \geq 0 \\ -x^2 & \text{if } x < 0 \end{cases} $$
    **Expected behavior:** Proper handling of case statements with different conditions.

12. **Multiple Integrals:**
    $$ \int_0^1 \int_0^1 f(x, y) \, dx \, dy $$
    **Expected behavior:** Proper rendering of the multiple integrals, with limits and differentials aligned correctly.

13. **Uncommon Symbols:**
    $$ \hbar = 6.62607015 \times 10^{-34} \, \text{J} \cdot \text{s} $$
    **Expected behavior:** Proper rendering of uncommon symbols like `\hbar` (reduced Planck constant).

14. **Multiline Equations:**
    $$
    \begin{align}
    E &= mc^2 \\
    F &= ma
    \end{align}
    $$
    **Expected behavior:** Multiline equations should be aligned at the `=` sign.

15. **Overlines and Underlines:**
    $$ \overline{AB} = 5, \underline{CD} = 10 $$
    **Expected behavior:** LaTeX should render both overlined and underlined text correctly.

```

2024-10-27 12:46 UTC, JohannesStoehr approved these changes
Tested on ts2 and looked through the code. Looks good to me

2024-10-27 14:38 UTC, florian-glombik approved these changes
[Re-approve](https://github.com/ls1intum/Artemis/pull/9354#pullrequestreview-2382790274) after merging develop

2024-10-27 16:08 UTC, pzdr7 approved these changes
Code looks good. Works well on TS2 👍

2024-10-27 19:27 UTC, merged

2024-10-27 19:28 UTC, HawKhiem reviewed
Tested on TS2. Approve after the merge (Everything works as described)

![Screenshot 2024-10-27 202124](https://github.com/user-attachments/assets/bc38fa50-295a-460b-9336-b5d7797e7cda)
![Screenshot 2024-10-27 202151](https://github.com/user-attachments/assets/2464e3ec-3708-432c-a26d-b138f3c1ee07)
![Screenshot 2024-10-27 202211](https://github.com/user-attachments/assets/ddd46337-1e5d-4e79-a288-6de6c96fa659)