`Communication`: Refactor sidebar design
ls1intum/Artemis pull request #9356
Opened 2024-09-22 23:44 UTC by asliayk

### Checklist
#### General

- [X] This is an issue that I tested locally.
- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [X] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [X] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [X] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [X] I added multiple screenshots/screencasts of my UI changes.
- [X] I translated all newly inserted strings into English and German.

### Motivation and Context

**1st issue:** Next to each channel section header in sidebar, there was a "+" icon for channel creation. When this was clicked, the user first had to view the browse channel screen and then click the button in that dialog again to create a channel. Having too many icons and the need to open two dialogs one after the other was not user-friendly.

**2nd issue:**: As discussed in the communication subgroup, the section header should not be visible when there are no channels/conversations in that section.

**3rd issue:** Although the prefixes "exercise-", "lecture-", and "exam-" were included in the names of the exercise, lecture, and exam channels respectively, their presence was unnecessary since the channels were already grouped into their corresponding sections. This made the interface look complicated.

### Description

**1st issue:** Immediately above the sidebar, there are two primary buttons: "Create Chat" and "Add Channel," each featuring its own dropdown menu. The "Create Chat" dropdown offers two options: "Create Direct Chat" and "Create Group Chat." Similarly, the "Add Channel" dropdown provides "Create Chat" and "Browse Channels" options, mirroring the functionality found in Slack.

**2nd issue**: If a section is empty (i.e., there are no channels or conversations), the section header is no longer visible.

**3rd issue**: The channel prefixes ("exercise-" "lecture-" and "exam-") do not appear in their respective sections; they are only visible in the favorite and hidden sections.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Navigate to Communication section of a course
3. Notice that there are two new buttons above the sidebar. By clicking on these buttons and selecting respective options, create direct chat, group chat and new channel. Then click on browse channels to open the browse channels dialog.
4. Notice that in exercise, exam and lecture sections, the channels have no prefixes ("exercise-" "lecture-" and "exam-"), but they become visible if you hide/favorite them and they are in hidden/favorites section.
5. If there is no hidden channel, the hidden section should not be visible. If there exist hidden channels, make them visible by clicking on their 3-dot button to see the options and click on "Show". When there is no hidden channel anymore, notice that hidden section is not visible.

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked
> Click on the badges to get to the test servers.

[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)](https://artemis-test1.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)](https://artemis-test2.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)](https://artemis-test3.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)](https://artemis-test4.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)](https://artemis-test5.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)](https://artemis-test6.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test9)](https://artemis-test9.artemis.cit.tum.de)

### Review Progress

#### Performance Review

- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2
#### Performance Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

Updated Sidebar Design
<img src="https://github.com/user-attachments/assets/39350588-2755-4348-ba7c-b3e1cb119b46" width="400">
<img src="https://github.com/user-attachments/assets/920496ef-85e5-40c5-9767-18cd42820b3d" width="400">

2024-09-27 11:01 UTC, anian03 requested changes
Just tested it, looks good in terms of functionality!

Only suggestions for visual improvements:
- Can we left-align the contents of the dropdown menu? I think it looks a bit strange having centered text.
- Maybe consider adding icons to the items in the dropdown menu as well so that the user immediately finds the correct actions :)

2024-09-28 17:41 UTC, SimonEntholzer requested changes
Generally nice changes, but I think there are still some smaller UI issues that can be improved:

In dark mode the buttons aren't readable:
![image](https://github.com/user-attachments/assets/7934dfc1-5630-4f74-85a8-fb7e96d0bc63)

It would be nice if the "view" button shows up, when hovering anywhere within a box. Atm there is quite a margin, where the button does not show (that's rather a nitpick tbh.)
![image](https://github.com/user-attachments/assets/86048ce2-b233-49ec-8028-2c252a7ea4f9)

Here it seems like the highlight of the close button of the modals is on initially, until the user clicks somewhere else. 
![image](https://github.com/user-attachments/assets/df136756-8d8c-4120-86cd-e0946ad431f3)

2024-09-29 11:08 UTC, JohannesWt commented on src/main/webapp/app/overview/course-conversations/course-conversations.component.html
> +                    (onGroupChatPressed)="onCreateGroupChatPressed()"
why did you introduce extra methods for the consumption of OutputEvents it did not just call the already existing functions directly?

2024-09-29 11:26 UTC, JohannesWt requested changes
I have a few comments regarding the use of bootstrap rather than own css classes. If you have any questions, just hit me up anytime

2024-09-29 11:26 UTC, JohannesWt commented on src/main/webapp/app/overview/course-conversations/course-conversations.component.ts
> +
Could we also implement this by using the signal based output Event Emitter?

2024-09-29 11:26 UTC, JohannesWt commented on src/main/webapp/app/shared/sidebar/sidebar.component.scss
> +    display: block;
you can also do this with the bootstrap class attributes directly in the html template

2024-09-29 11:26 UTC, JohannesWt commented on src/main/webapp/app/shared/sidebar/sidebar.component.scss
> +    border: 1px solid #ccc;
You should use the color variables bg-secondary, etc. (or similar) to choose the right colors also when switching to darkmode. You can get the correct variable through the Chrome Dev tools by selection text for example or the background of e.g. the Sidebar itself. (I think the variables are at the bottom of the styles bar in the Dev tools)

2024-09-29 11:26 UTC, JohannesWt commented on src/main/webapp/app/shared/sidebar/sidebar.component.scss
> +    padding: 10px 10px;
we should also use the boostrap standards here e.g. `p-1` in the HTML template that we follow a similar look everywhere

2024-09-29 11:26 UTC, JohannesWt commented on src/main/webapp/app/shared/sidebar/sidebar.component.scss
> +    cursor: pointer;
there is a global class `.clickable` to achieve the same effect

2024-09-29 11:26 UTC, JohannesWt commented on src/main/webapp/app/shared/sidebar/sidebar.component.scss
> +    font-size: 14px;
we should not define specific font sizes to keep a consistent look throughout the App

2024-09-29 11:26 UTC, JohannesWt commented on src/main/webapp/app/shared/sidebar/sidebar.component.ts
> +    @Output() onCreateChannelPressed = new EventEmitter<void>();
same here could we also use the signal based output?

2024-09-29 11:26 UTC, JohannesWt commented on src/main/webapp/app/shared/sidebar/sidebar.component.ts
here same for the input

```suggestion
    inCommunication = input<boolean>(false);
```

2024-09-29 11:26 UTC, JohannesWt commented on src/test/javascript/spec/component/overview/course-conversations/course-conversations.component.spec.ts
> +                expect(spy).toHaveBeenCalledWith(GroupChatCreateDialogComponent, expect.anything());
Could we be more specific here?
```suggestion
                expect(spy).toHaveBeenCalledExactlyOnceWith(GroupChatCreateDialogComponent, expect.anything());
```

2024-09-29 11:26 UTC, JohannesWt commented on src/test/javascript/spec/component/overview/course-conversations/course-conversations.component.spec.ts
> +                expect(spy).toHaveBeenCalledWith(OneToOneChatCreateDialogComponent, expect.anything());
Same here and in the next occurrences (calledExactlyOnce)

2024-10-04 13:41 UTC, janthoXO requested changes
when searching for a person in the new chat pop up. and deleting the search text again, the suggestion still gets displayed. If the input field is empty the suggestion should disappear.
Not quite sure if its directly related to this PR, but otherwise please create a follow up issue

https://github.com/user-attachments/assets/26a78611-d1b2-45b8-9b33-0e28ebdae14f

2024-10-04 13:44 UTC, janthoXO requested changes
The selection for private or group chat should disappear when the user clicks somewhere else. Same applies for the channel selection

https://github.com/user-attachments/assets/2f83fafc-18c8-4df4-b109-13566a4129b6

2024-10-04 13:46 UTC, janthoXO commented
and for the future please keep in mind to write descriptive commit messages ;)

2024-10-06 10:50 UTC, asliayk commented
After the discussion in the communication subgroup, it was decided to use a single button with a dropdown containing four options. I have also updated the code based on your previous reviews and would appreciate your further reviews :)

2024-10-06 16:17 UTC, JohannesWt submitted a review, later dismissed
Thanks for the changes - Code looks good

2024-10-07 16:58 UTC, edkaya submitted a review, later dismissed
Tested on TS5, works as expected. Maybe one nitpick: If you click on 'create channel' or 'add channel', we see a dropdown menu, which can not be closed if you click outside of the dropdown. I think dropdown should be closed if you click anywhere on the page.

2024-10-07 19:14 UTC, anian03 requested changes
Thanks for the changes, it looks nicer now 👍🏻

One issue I noticed: If you disable DMs and Group chats in the course settings, the corresponding button in the sidebar for creating new chats is still there. Could you remove it when DMs are disabled? We can't create new DMs there

2024-10-14 12:52 UTC, rabeatwork requested changes

2024-10-14 12:52 UTC, rabeatwork commented on src/main/webapp/app/overview/course-conversations/dialogs/channels-overview-dialog/channel-item/channel-item.component.scss
> +    padding: 10px;
Could you use rem values? e.g. 0.5rem or 0.75rem.

2024-10-14 12:52 UTC, rabeatwork commented on src/main/webapp/app/shared/course-users-selector/course-users-selector.component.ts
> +        if (value.length < 3) {
Can you add a comment why `< 3`?

2024-10-14 12:52 UTC, rabeatwork commented on src/main/webapp/app/shared/sidebar/sidebar-card-item/sidebar-card-item.component.html
> +                    {{ removeChannelPrefix(sidebarItem.title) }}</span
Please avoid using function calls in the html template. `removeChannelPrefix` also sounds communication specific, which is why this should rather happen in the communication component beforehand and not within the generic `sidebar-card-item.component`.

2024-10-14 12:52 UTC, rabeatwork commented on src/main/webapp/app/shared/sidebar/sidebar-card-item/sidebar-card-item.component.ts
> +    removeChannelPrefix(name: string): string {
Could you adapt the communication data before passing it to the sidebar-card.component?

2024-10-14 12:52 UTC, rabeatwork commented on src/main/webapp/app/shared/sidebar/sidebar-card-item/sidebar-card-item.component.ts
> +            if (name && name.startsWith(prefix) && channelTypes.includes(<string>this.groupKey)) {
```suggestion
            if (name?.startsWith(prefix) && channelTypes.includes(<string>this.groupKey)) {
```

2024-10-14 12:52 UTC, rabeatwork commented on src/main/webapp/i18n/de/student-dashboard.json
> +                "addChannelChat": "Kanal/Chat hinzufügen",
I figure you don't need this anymore

2024-10-14 12:52 UTC, rabeatwork commented on src/main/webapp/i18n/en/student-dashboard.json
> +                "addChannelChat": "Add Channel/Chat",
I figure you don't need this anymore

2024-10-14 12:52 UTC, rabeatwork commented on src/main/webapp/i18n/en/student-dashboard.json
> +                "createChat": "Create Chat",
I figure you don't need this anymore

2024-10-14 12:52 UTC, rabeatwork commented on src/main/webapp/i18n/de/student-dashboard.json
> +                "createChat": "Chat erstellen",
I figure you don't need this anymore

2024-10-14 12:52 UTC, rabeatwork commented on src/main/webapp/app/shared/sidebar/sidebar-card-item/sidebar-card-item.component.ts
> +        for (const prefix of prefixes) {
personal preference: `prefixes.forEach((prefix) => { ... })`

2024-10-18 12:36 UTC, FelberMartin commented
Tested the functionality as described in the PR, all features work as expected 👍

2024-10-18 13:15 UTC, FelberMartin approved these changes
Tested the functionality as described in the PR, all features work as expected 👍

2024-10-18 13:16 UTC, sachmii approved these changes
Tested on TS4. Everything works just fine, I really like these changes! Gives you a better overview over each channel and the channel creation process itself.

2024-10-18 14:25 UTC, cremertim approved these changes
code lgtm, one minor thing can be adapted.We should prefer to use Input<>()

2024-10-18 14:27 UTC, cremertim commented on src/main/webapp/app/shared/sidebar/sidebar-card-item/sidebar-card-item.component.ts
> +    @Input() groupKey?: string;
New client guidelines want us to use of input <String>()
```suggestion
    groupKey = input<string>()
```

2024-10-18 14:30 UTC, cremertim commented on src/main/webapp/app/shared/sidebar/sidebar-card-large/sidebar-card-large.component.ts
> +    @Input() groupKey?: string;
see comment aboe
```suggestion
     groupKey = input<string>()
```

2024-10-18 14:30 UTC, cremertim commented on src/main/webapp/app/shared/sidebar/sidebar-card-medium/sidebar-card-medium.component.ts
> +    @Input() groupKey?: string;
see comment above

2024-10-18 14:30 UTC, cremertim commented on src/main/webapp/app/shared/sidebar/sidebar-card-large/sidebar-card-large.component.html
> +    <jhi-sidebar-card-item [groupKey]="groupKey" [sidebarType]="sidebarType" [sidebarItem]="sidebarItem" />
need to be accessed with groupKey() after implementing signals
```suggestion
    <jhi-sidebar-card-item [groupKey]="groupKey()" [sidebarType]="sidebarType" [sidebarItem]="sidebarItem" />
```

2024-10-18 14:30 UTC, cremertim commented on src/main/webapp/app/shared/sidebar/sidebar-card-small/sidebar-card-small.component.ts
> +    @Input() groupKey?: string;
comment above

2024-10-18 16:38 UTC, PaRangger approved these changes
Tested on TS3. Everything works and looks great. 👍

2024-10-18 17:02 UTC, HawKhiem approved these changes
Tested on TS3. Everything works as described! After unhide the announcement channel, the hidden section becomes invisible as described!
![Screenshot 2024-10-18 185836](https://github.com/user-attachments/assets/b1bd9109-7c76-40d7-92aa-066044e766bc)
![Screenshot 2024-10-18 185921](https://github.com/user-attachments/assets/76136af8-2643-4069-8d26-0fe148e66e14)
![Screenshot 2024-10-18 185930](https://github.com/user-attachments/assets/fa00c041-41fa-44f3-91ad-3547c0cf9798)

2024-10-19 11:55 UTC, anian03 approved these changes
Thanks for the quick fix, lgtm!

2024-10-19 11:57 UTC, krusche approved these changes

2024-10-19 11:57 UTC, merged