`Development`: Add action to validate pull request title
ls1intum/Artemis pull request #9449
Opened 2024-10-09 21:27 UTC by MaximilianAnzinger

### Checklist
#### General

- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

### Description

2024-10-10 07:24 UTC, bensofficial submitted a review, later dismissed
You might add a new line at the end of the file, but the workflow itself and the regex look reasonable 👍

2024-10-10 10:14 UTC, JohannesStoehr requested changes
Should we be this strict to only allow letters and numbers in the title?
E.g. these two PRs would not fit this criterion but have valid titles in my opinion:
https://github.com/ls1intum/Artemis/pull/8137
https://github.com/ls1intum/Artemis/pull/9261

2024-10-10 13:17 UTC, Hialus requested changes
I agree with Johannes.
The current Regex is too strict and does not allow for any special characters at all. It excludes basic characters like hyphens, apostrophes, and diacritics. All of which are used in the English language.
Imo we should just not limit the second part of the PR title through a Regex, as we can't really cover all legitimate cases.

2024-10-10 19:12 UTC, JohannesStoehr approved these changes

2024-10-10 21:49 UTC, Hialus approved these changes

2024-10-11 09:43 UTC, ole-ve approved these changes

2024-10-12 11:28 UTC, krusche approved these changes

2024-10-12 11:28 UTC, merged