`Integrated code lifecycle`: Add editing of auxiliary repositories for instructors
ls1intum/Artemis pull request #9585
Opened 2024-10-24 19:23 UTC by SimonEntholzer

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [ ] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [ ] I **strictly** followed the principle of **data economy** for all database calls.
- [ ] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.

#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [ ] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [ ] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.

#### Changes affecting Programming Exercises
- [ ] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server configured with **Gitlab** and **Jenkins**.

### Motivation and Context

Instructors can edit Template, Assignment, Solution and Test repositories in Artemis, by using the "edit in editor" view.
This is not yet possible for auxiliary repositories. 

### Description

This PR adds support for auxiliary repositories in the edit in editor view.
Also fixes a small UI bug, where the text on the drop-down button was not readable, when not hovering.

### Steps for Testing

1. Create a programming exercise with one or more auxiliary repositories
2. In the exercise details page, open the "edit in editor" view
3. In the drop-down, select the previously created auxiliary repositories.
4. Add/Delete/Change files and folders, and submit.
5. Go back to the details view, clone the auxiliary repositories and check that the created content is there.

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked
> Click on the badges to get to the test servers.

[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)](https://artemis-test1.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)](https://artemis-test2.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)](https://artemis-test3.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)](https://artemis-test4.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)](https://artemis-test5.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)](https://artemis-test6.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test9)](https://artemis-test9.artemis.cit.tum.de)

### Review Progress

#### Performance Review

- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2
#### Performance Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

![image](https://github.com/user-attachments/assets/ca3339fc-2a5b-4f4c-88fc-b0ae5b973bfe)
![image](https://github.com/user-attachments/assets/bba768b9-a03b-4636-8fc9-bac681414955)

small Bugfix:
![image](https://github.com/user-attachments/assets/93ef5545-0974-4c83-aabb-119626ee23f4)
vs. 
![image](https://github.com/user-attachments/assets/54f21244-4afb-4449-9ced-9623adc80ced)

2024-10-24 20:43 UTC, sachmii approved these changes
Tested on TS4, after adding files and folders to the auxiliary repository and cloning it, they also appeared locally. Worked just fine.

<img width="318" alt="Bildschirmfoto 2024-10-24 um 22 41 35" src="https://github.com/user-attachments/assets/de396343-53a2-476b-a566-dcafb9c59d6a">
<img width="301" alt="Bildschirmfoto 2024-10-24 um 22 41 41" src="https://github.com/user-attachments/assets/bdfa0e0e-3d79-4369-9a19-8c2f0a13577a">

2024-10-24 22:04 UTC, JohannesStoehr requested changes

2024-10-24 22:04 UTC, JohannesStoehr commented on src/main/java/de/tum/cit/aet/artemis/programming/repository/ProgrammingExerciseRepository.java
> +        programmingExerciseWithTemplate.setAuxiliaryRepositories(programmingExerciseWithAuxiliaryRepositories.getAuxiliaryRepositories());
Can you adapt the method name to reflect the new values as well?

2024-10-24 22:04 UTC, JohannesStoehr commented on src/main/webapp/app/exercises/programming/manage/code-editor/code-editor-instructor-and-editor-container.component.html
> +                                    selectedRepository === REPOSITORY.AUXILIARY && selectedRepositoryId === auxiliaryRepository.id ? '#3e8acc' : 'transparent'
Our documentation:
> Do not hard code any color values in your component stylesheets, templates or TypeScript files!

2024-10-25 10:09 UTC, HawKhiem reviewed
I'm sorry but how can I create an auxiliary repository? I can't seem to find anything in the edit view and then edit in editor view.

![image](https://github.com/user-attachments/assets/6bcf08ce-4f54-4cdd-a7a6-6cd1fa68c31b)
![image](https://github.com/user-attachments/assets/eb930036-fa09-4590-be07-57c310424f53)

2024-10-25 16:04 UTC, SimonEntholzer commented
> I'm sorry but how can I create an auxiliary repository? I can't seem to find anything in the edit view and then edit in editor view.

you can only create them when initially creating a programming exercise:
![image](https://github.com/user-attachments/assets/9de6d186-0c10-4d00-a4f4-18cd26366f96)

2024-10-25 16:15 UTC, SimonEntholzer commented on src/main/webapp/app/exercises/programming/manage/code-editor/code-editor-instructor-and-editor-container.component.html
> +                                    selectedRepository === REPOSITORY.AUXILIARY && selectedRepositoryId === auxiliaryRepository.id ? '#3e8acc' : 'transparent'
I replaced them with --link-color :+1:

2024-10-25 16:49 UTC, HawKhiem submitted a review, later dismissed
Tested on TS3. Works as described!

![Screenshot 2024-10-25 184722](https://github.com/user-attachments/assets/ecd9e7f8-6ab3-477d-be8a-dd88b0d7ad84)
![Screenshot 2024-10-25 184744](https://github.com/user-attachments/assets/d9645519-aab9-4ee9-ac9d-bdfbcb573f6c)
![Screenshot 2024-10-25 184801](https://github.com/user-attachments/assets/c411aa16-db47-4152-afca-d980a326c4ea)
![Screenshot 2024-10-25 184810](https://github.com/user-attachments/assets/6872b77b-186d-485c-9f32-b5c3cb9ee702)

2024-10-25 22:25 UTC, sachmii approved these changes
Tested on TS4, still works fine. Re-approve

2024-10-28 18:33 UTC, sarpsahinalp approved these changes
Code lgtm

2024-10-29 15:16 UTC, JohannesStoehr submitted a review, later dismissed
Code

2024-10-29 16:49 UTC, sachmii approved these changes

2024-10-29 16:50 UTC, HawKhiem approved these changes
LGTM

2024-10-29 16:52 UTC, JohannesStoehr approved these changes
New tests also look good

2024-11-02 06:45 UTC, merged