`Integrated code lifecycle`: Allow admins to set timeout options via application properties
ls1intum/Artemis pull request #9603
Opened 2024-10-26 20:23 UTC by BBesrour

### Require a config change

### Checklist
#### General

- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [ ] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [ ] I **strictly** followed the principle of **data economy** for all database calls.
- [ ] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.

#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [ ] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [ ] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.

#### Changes affecting Programming Exercises
- [ ] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).

### Motivation and Context

This PR allows admins to adjust the timeout options in the UI.
New properties are added:
- `artemis.continuous-integration.build-timeout-seconds.min`: Min timeout option
- `artemis.continuous-integration.build-timeout-seconds.max`: Max timeout option (if the user somehow sends a value higher than this, it will be checked and overridden)
- `artemis.continuous-integration.build-timeout-seconds.default`: default option

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Go to exercise creation, open dev tools
2. Check `Customize build script`
3. Make sure the default value of the timeout is 120 (default value), and that the max and min are respectively 360 and 10.
4. Save exercise
5. In the dev tools, check that the timeout was set correctly

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked
> Click on the badges to get to the test servers.

[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)](https://artemis-test1.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)](https://artemis-test2.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)](https://artemis-test3.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)](https://artemis-test4.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)](https://artemis-test5.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)](https://artemis-test6.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test9)](https://artemis-test9.artemis.cit.tum.de)

### Review Progress

#### Performance Review

- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Performance Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2024-10-26 22:42 UTC, HawKhiem reviewed
I tested on TS4. The min and default timeout is correct as described. The max timeout is however 240.

![Screenshot 2024-10-27 003548](https://github.com/user-attachments/assets/d8e1201c-d73c-4106-8a8b-6c129f1e8875)
![Screenshot 2024-10-27 003555](https://github.com/user-attachments/assets/79828a9f-382a-4d6d-a702-97f544601786)
![Screenshot 2024-10-27 003633](https://github.com/user-attachments/assets/7acc0efd-a0af-41aa-85d7-222aaf58aafb)

2024-10-26 22:48 UTC, Cathy0123456789 reviewed
Tested on TS4. Min and default timeout are set correctly, but max timeout is only 240s:
![image](https://github.com/user-attachments/assets/dff0c609-5830-470e-9808-d5198f14f4f4)

Not quite sure where to check step 5 of testing: "In the dev tools, check that the timeout was set correctly"?

2024-10-27 00:40 UTC, BBesrour commented
@Cathy0123456789 @HawKhiem 240 as max value is correct. I mistakenly put 360 in the description (fixed it)

@Cathy0123456789 Press F12 in your browser and go to the network tab. Look for the request responsible for creating the exercise (endpoint should end with `/setup`) and then check the body (under buildConfig -> timeout)

2024-10-27 09:21 UTC, SimonEntholzer submitted a review, later dismissed
Code

2024-10-27 23:39 UTC, Cathy0123456789 approved these changes
@BBesrour Thank you for the explanation!
I tested again on TS2, seems to be working good!

2024-10-28 11:33 UTC, flbrgit approved these changes
Tested on TS4, timout min max correct, timeout set correctly in responses, everything works as expected.
![Screenshot 2024-10-28 122913](https://github.com/user-attachments/assets/422f0ebf-54c5-4841-a9ae-04647746d1ca)

2024-10-28 14:59 UTC, zagemello approved these changes
![image](https://github.com/user-attachments/assets/15184eeb-cad4-47f0-8a3d-6b3fa6f28a5c)
All works as expected, tested on TS4, however on TS6 I was unable to find the option for the timeout :)

2024-10-28 18:26 UTC, sarpsahinalp submitted a review, later dismissed
Code lgtm

2024-10-28 22:24 UTC, Cathy0123456789 approved these changes
Tested on TS1. Works as expected and timeout set correctly 
![image](https://github.com/user-attachments/assets/f1bb971f-99c7-43fa-9ac9-bad687f96e9c)

2024-10-29 06:58 UTC, SimonEntholzer submitted a review, later dismissed
Re-approve after added docs

2024-10-29 11:32 UTC, HawKhiem approved these changes
Tested on TS3. Reapprove

![image](https://github.com/user-attachments/assets/cf5d36ca-604a-4fa8-b1e8-876034c6002a)

2024-10-29 12:17 UTC, JohannesStoehr requested changes

2024-10-29 12:17 UTC, JohannesStoehr commented on docs/admin/setup/distributed.rst
> +                    max: 2400                                      # (Optional, default 240) Maximum time in seconds a build job is allowed to run. If a build job exceeds this time, it will be cancel
Why does this value deviate from the default?

2024-10-29 12:17 UTC, JohannesStoehr commented on src/main/resources/config/application-buildagent.yml
> +          max: 240
These values do not align with the value mentioned in distributed.rst

2024-10-29 13:04 UTC, JohannesStoehr approved these changes
Code

2024-10-29 13:25 UTC, HawKhiem approved these changes
LGTM, reapprove

2024-10-29 13:26 UTC, SimonEntholzer approved these changes
reapprove

2024-10-29 17:27 UTC, Cathy0123456789 approved these changes
Reapprove

2024-10-30 20:13 UTC, SindiBuklaji approved these changes
Tested on Ts3 and everything worked as described 👍

2024-11-01 11:42 UTC, kevinfischer4 approved these changes
Tested on TS2. The timeout can be set to a value between 10 and 240. Works as expected.

2024-11-01 23:50 UTC, sawys777 approved these changes
Tested on TS1. Everything worked as expected and the range of timer was correct as well.

2024-11-02 06:48 UTC, merged