`Lectures`: Hide slide pages until a date
ls1intum/Artemis pull request #9868
Opened 2024-11-26 09:34 UTC by eceeeren

### Checklist
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the principle of **data economy** for all database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

The feature to hide slide pages (#9667) has been implemented, allowing instructors to hide pages indefinitely. However, a new feature is needed to enable instructors to hide specific pages with more flexibility to enhance functionality. This feature should provide the following options:

**1. Hide Indefinitely:** Maintain the current functionality to hide pages permanently until manually unhidden.
**2. Hide Until a Specific Date:** Allow instructors to set a manual date and time for the pages to be automatically unhidden.
**3. Hide Until an Exercise's Due Date:** Link the hidden pages to an exercise's due date, ensuring they are unhidden when it is due.

Additionally, a scheduled job should be implemented to automatically unhide pages once the specified conditions are met. This enhancement will improve usability and provide greater control for instructors.
### Description

To enable the functionality of hiding pages until a specific date, the following changes have been implemented:

**1. PDF Preview Date Box Component:** A new component named PDF Preview Date Box has been created.
Date Box Accessibility: The Date Box becomes accessible by clicking the "Hide" button when hovering over a page.
**2. Hide Options:** The Date Box allows instructors to configure hiding options for the selected page. It provides three choices:
- Hide the page indefinitely.
- Hide the page until a specific date and time.
- Hide the page until the selected exercise's due date.

**3. Configuration View:** Once the hiding configuration is saved, the current settings can be viewed by clicking the "View" button.
**4. Show Page Popover:** In the "Show Page" popover, the selected hiding date is displayed, along with an option to unhide the page.
**5. Database Integration:** The selected configurations are stored in the Slide table for persistence.
**6. Scheduled Job:** A scheduled job runs every minute, checking the Slide repository to automatically unhide slides that have reached their specified date.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student

1. Log in to Artemis
2. Navigate to Course Administration
3. Go to 'Lecture Units'
4. Create one Lecture Unit with a File
5. Click "View" button
6. Hover over one of the pages and click "Hide" button
7. Confirm that you can see a popover with different options
8. Click "Hide forever" and confirm that other options are disabled
9. Uncheck "Hide forever", click "Select Date" and confirm that you can choose a date and time in the calendar
10. Click "Select Exercise" and confirm that you see "No exercises available" text when there are no exercises with due date defined
11. Click "Cancel" and confirm that popover is closed with no side effect
12. Select one of the dates and click "Submit"
13. Confirm that the page is hidden and you can see "Show" button instead
14. Click "Show" button and confirm you can see "Show Page" popover
15. Click "Cancel" to test the button and then click "Show" to show the page again
16. Repeat from steps 5-15 with dark mode enabled, language is German and when some exercises are added to the course
17. Hide one of the page to a time in the future and one for a short time (e.g. 1 or 2 minutes)
18. Observe that the page hidden for a short time is visible after the specified time has passed
19. Test that "Download" button shows the student version and "Original Version" shows the version that pages are not hidden
20. Log in as a student and go to lecture's Communication part
21. Verify that you can not reference hidden slides in the forum, only the visible slides

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked
> Click on the badges to get to the test servers.

[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)](https://artemis-test1.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)](https://artemis-test2.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)](https://artemis-test3.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)](https://artemis-test4.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)](https://artemis-test5.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)](https://artemis-test6.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test9)](https://artemis-test9.artemis.cit.tum.de)

### Review Progress

#### Performance Review

- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| pdf-preview.component.ts  | 94% | ✅              |
| pdf-preview-thumbnail-grid.component.ts  | 92% | ✅              |
| pdf-preview-date-box.component.ts | 100% | ✅                           |

### Screenshots

 [...]

2025-01-04 23:44 UTC, Cathy0123456789 requested changes
Tested on TS3. Nice feature really, I ran into some problem / question marks though:

1. When setting a date from an exercise due in the past,
- it would hide the page (should it though?)
- and moving the exercise's due date to another date in the past or even the future, it doesn't show the page anymore as hidden (in View), however the download does not include that page -> nobody would notice it is missing until a change is made and then the slides update

2. When setting a date in the past,
- it would hide the page in the download (should it though?)
- and then again clicking on View, that page would not be marked as hidden even though the download does not include that page

3. When hiding a page, saving the slides and then wanting to unhide it
- the download would not change except in the same or next time you edit a _different_ page's visibility
- BUT when multiple pages are hidden and you unhide some (at least one page is still hidden though), then it works as expected

4. When setting a date from an exercise due in the future, then postponing the exercise's due date to another date in the future, the old date stays as release date on the slide -> potential problems if somebody forgets to edit that as well?

2025-01-05 23:06 UTC, HawKhiem reviewed
Tested on TS3. I had the same problems as Cathy mentioned

2025-01-06 12:48 UTC, zagemello reviewed
I also tested on TS3 and have no other issues apart from the above ones mentioned by Cathy.

2025-01-06 14:06 UTC, vinceclifford reviewed
Ran into the same issues as Cathy mentioned.

2025-03-15 11:23 UTC, krusche commented
This PR is open for a too long time ‼️ Please re-create the branch (to make sure build jobs are running on Bamboo appropriately) and re-open a new PR when you have finished the implementation. Thank you!

2025-03-15 11:23 UTC, closed without merging