DeLTI Client Migration
ls1intum/Artemis pull request #9908
Opened 2024-11-29 16:24 UTC by raffifasaro

### Checklist
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [ ] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [ ] I **strictly** followed the principle of **data economy** for all database calls.
- [ ] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.

#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [ ] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [ ] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.

#### Changes affecting Programming Exercises
- [ ] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server configured with **Gitlab** and **Jenkins**.

### Motivation and Context

### Description

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exam_mode/) as reference.
4. ...

### Testserver States
> [!NOTE]
> These badges show the state of the test servers.
> Green = Currently available, Red = Currently locked
> Click on the badges to get to the test servers.

[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test1)](https://artemis-test1.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test2)](https://artemis-test2.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test3)](https://artemis-test3.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test4)](https://artemis-test4.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test5)](https://artemis-test5.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test6)](https://artemis-test6.artemis.cit.tum.de)
[![](https://byob.yarr.is/ls1intum/Artemis/artemis-test9)](https://artemis-test9.artemis.cit.tum.de)

### Review Progress

#### Performance Review

- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2
#### Performance Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

### Screenshots

2024-12-05 13:49 UTC, HawKhiem approved these changes
Tested on TS1. Everthing mentioned works as described

![Screenshot 2024-12-05 143844](https://github.com/user-attachments/assets/6e5c3c27-1c9e-4954-b1a4-07195275f502)


However. Everytime I clicked on an exercise on Moodle, some settings on Artemis get reset to the default one (Light mode turned on). As can be seen here, I have Dark mode configured on Artemis

![image](https://github.com/user-attachments/assets/1c35c525-ec3a-46f0-a8e0-56f8387dac62)

After clicking onto an exercise on Moodle, the Iframe is opened as expected and it affects the settings on Artemis as well

![image](https://github.com/user-attachments/assets/976c7828-d002-4e84-9d35-8f85b8dec52f)
![image](https://github.com/user-attachments/assets/4e97cc9c-1c0a-4046-903f-34732b110bc9)

Language seems to work fine and didn't get reset to default!

2024-12-06 16:27 UTC, az108 requested changes
Overall Code LGTM 👍 would be good if we could implement this change tho

2024-12-06 16:27 UTC, az108 commented on src/main/webapp/app/lti/lti-course-card.component.ts
> +    course = input<Course>();
can we use input.required here? This would allow us to ignore the ? in the html

2024-12-06 16:27 UTC, az108 commented on src/main/webapp/app/lti/lti-course-card.component.html
> +        id="course-{{ course()?.id }}-header"
can we use input.required for course so that we can write `course().id`

2024-12-06 16:27 UTC, az108 commented on src/main/webapp/app/lti/lti-course-card.component.html
> +        [routerLink]="['/lti/exercises', course()?.id]"
same here

2024-12-06 16:27 UTC, az108 commented on src/main/webapp/app/lti/lti-course-card.component.html
> +                    @if (course()?.courseIcon) {
same here

2024-12-06 16:27 UTC, az108 commented on src/main/webapp/app/lti/lti-course-card.component.html
> +                        {{ course()?.title + ' (' + course()?.shortName + ')' }}
and same here

2024-12-06 17:17 UTC, az108 requested changes
can you check the client tests again please, i think you need to adapt smth small with input.required

2024-12-06 17:53 UTC, az108 requested changes
another thing i noticed

2024-12-06 17:53 UTC, az108 commented on src/test/javascript/spec/component/lti/lti13-deep-linking.component.spec.ts
> +                HttpClientTestingModule,
please use provideHttpClient() instead of the HttpClientModule

2024-12-06 17:53 UTC, az108 commented on src/test/javascript/spec/component/lti/lti13-select-content.component.spec.ts
> +                HttpClientTestingModule,
same here

2024-12-06 20:56 UTC, az108 approved these changes
Thanks for the quick changes, Code LGTM 👍

2024-12-06 23:27 UTC, Jan-Thurner approved these changes
code

2024-12-11 16:42 UTC, SimonEntholzer approved these changes
Works on Ts1+Moodle with test user 1

2024-12-11 18:45 UTC, HawKhiem approved these changes
Reapprove

2024-12-13 13:00 UTC, MaximilianAnzinger approved these changes

2024-12-14 11:37 UTC, merged